package com.lolfm.composition;
public enum CompositionCapability { ENGAGE,FOLLOW_UP,DISENGAGE,FRONTLINE,PEEL,PICK,POKE,SIEGE,WAVE_CLEAR,ZONE_CONTROL,SIDE_LANE_PRESSURE,OBJECTIVE_DAMAGE,SUSTAINED_DAMAGE,BURST_DAMAGE,BACKLINE_ACCESS }
