package com.lolfm.composition;
public enum CompositionDeficiency { NO_RELIABLE_ENGAGE, LOW_FRONTLINE, LOW_PEEL, LOW_WAVE_CLEAR, LOW_OBJECTIVE_DAMAGE, LOW_SUSTAINED_DAMAGE, NO_SIDE_LANE_ANSWER, DAMAGE_CHANNEL_SKEW }
