package com.lolfm.simulator;
import static org.assertj.core.api.Assertions.assertThat;
import com.lolfm.domain.PlayerAttributes;import com.lolfm.domain.Position;import java.util.List;import org.junit.jupiter.api.Test;
import com.lolfm.champion.ChampionCatalog;import com.lolfm.factory.DummyDataFactory;import com.fasterxml.jackson.databind.ObjectMapper;
class CombatOutcomeExecutionStatsTest{
 private PlayerState player(Position p){return new PlayerState("audit-"+p,p,new PlayerAttributes(14,14,14,14),500);}
 @Test void structuredWinnerAndParticipantAreRecordedOnce(){var stats=new CombatOutcomeExecutionStats();var mid=player(Position.MID);stats.record(ProgressionCombatContext.LANE_COMBAT,300,true,TeamSide.BLUE,List.of(mid),List.of(player(Position.MID)));var s=stats.snapshot();assertThat(s.wins(ProgressionCombatContext.LANE_COMBAT,TeamSide.BLUE)).isOne();assertThat(s.participantWins(ProgressionCombatContext.LANE_COMBAT,new PlayerKey(TeamSide.BLUE,Position.MID))).isOne();assertThat(s.participantWins(ProgressionCombatContext.LANE_COMBAT,new PlayerKey(TeamSide.BLUE,Position.TOP))).isZero();}
 @Test void duplicateStructuredIdentityIsRejected(){var stats=new CombatOutcomeExecutionStats();var blue=List.of(player(Position.MID));var red=List.of(player(Position.MID));stats.record(ProgressionCombatContext.LANE_COMBAT,300,true,TeamSide.BLUE,blue,red);stats.record(ProgressionCombatContext.LANE_COMBAT,300,true,TeamSide.BLUE,blue,red);assertThat(stats.snapshot().wins(ProgressionCombatContext.LANE_COMBAT,TeamSide.BLUE)).isOne();assertThat(stats.snapshot().duplicateOutcomeRecordErrors()).isOne();}
 @Test void evaluationWithoutActualAttemptDoesNotRecord(){var stats=new CombatOutcomeExecutionStats();stats.record(ProgressionCombatContext.TEAMFIGHT,900,false,TeamSide.BLUE,List.of(player(Position.TOP)),List.of(player(Position.TOP)));assertThat(stats.snapshot().outcomeWithoutAttemptErrors()).isOne();assertThat(stats.snapshot().wins(ProgressionCombatContext.TEAMFIGHT,TeamSide.BLUE)).isZero();}
 @Test void statsAreMatchScoped(){var first=new CombatOutcomeExecutionStats();first.record(ProgressionCombatContext.TEAMFIGHT,900,true,TeamSide.RED,List.of(player(Position.TOP)),List.of(player(Position.TOP)));assertThat(first.snapshot().wins(ProgressionCombatContext.TEAMFIGHT,TeamSide.RED)).isOne();assertThat(new CombatOutcomeExecutionStats().snapshot().wins(ProgressionCombatContext.TEAMFIGHT,TeamSide.RED)).isZero();}
 @Test void missingWinnerIsAnIntegrityError(){var stats=new CombatOutcomeExecutionStats();stats.record(ProgressionCombatContext.OBJECTIVE_FIGHT,1200,true,null,List.of(player(Position.TOP)),List.of(player(Position.TOP)));assertThat(stats.snapshot().outcomeWithoutWinnerErrors()).isOne();assertThat(stats.snapshot().wins(ProgressionCombatContext.OBJECTIVE_FIGHT,TeamSide.BLUE)).isZero();}
 @Test void participantMismatchDoesNotRecordOutcome(){var stats=new CombatOutcomeExecutionStats();stats.record(ProgressionCombatContext.OBJECTIVE_FIGHT,1200,true,TeamSide.BLUE,List.of(),List.of(player(Position.TOP)));assertThat(stats.snapshot().participantMismatchErrors()).isOne();assertThat(stats.snapshot().wins(ProgressionCombatContext.OBJECTIVE_FIGHT,TeamSide.BLUE)).isZero();}
 @Test void productionSimulationExposesOutcomes(){var c=new ChampionCatalog(new ObjectMapper());var sim=new MatchSimulator(new TeamfightResolver(),new EndGameEvaluator(),new SnapshotFactory(c),new ObjectiveResolver(),new PostFightResolver(),new ObjectiveAttemptResolver(),new StructureResolver(),new PushResolver(),SimulationOptions.productionDefaults());var f=new DummyDataFactory();var r=sim.simulateWithDiagnostics(f.createBlueTeam(),f.createRedTeam(),1);var s=r.combatOutcomeExecutionStats();int total=0;for(var x:List.of(ProgressionCombatContext.LANE_COMBAT,ProgressionCombatContext.TEAMFIGHT,ProgressionCombatContext.OBJECTIVE_FIGHT))for(var side:TeamSide.values())total+=s.wins(x,side);assertThat(total).isPositive();}
 @Test void sameSeedReplayProducesSameOutcomeStats()throws Exception{var c=new ChampionCatalog(new ObjectMapper());var sim=sim(c,SimulationOptions.productionDefaults());var f=new DummyDataFactory();var a=sim.simulateWithDiagnostics(f.createBlueTeam(),f.createRedTeam(),7);var b=sim.simulateWithDiagnostics(f.createBlueTeam(),f.createRedTeam(),7);assertThat(a.combatOutcomeExecutionStats()).isEqualTo(b.combatOutcomeExecutionStats());assertThat(new ObjectMapper().writeValueAsString(a.timeline())).isEqualTo(new ObjectMapper().writeValueAsString(b.timeline()));}
 @Test void diagnosticsCollectionDoesNotChangeTimeline()throws Exception{var c=new ChampionCatalog(new ObjectMapper());var f=new DummyDataFactory();var a=sim(c,SimulationOptions.productionDefaults().withDiagnosticsEnabled(false)).simulateWithDiagnostics(f.createBlueTeam(),f.createRedTeam(),11);var b=sim(c,SimulationOptions.productionDefaults().withDiagnosticsEnabled(true)).simulateWithDiagnostics(f.createBlueTeam(),f.createRedTeam(),11);assertThat(new ObjectMapper().writeValueAsString(a.timeline())).isEqualTo(new ObjectMapper().writeValueAsString(b.timeline()));}
 private MatchSimulator sim(ChampionCatalog c,SimulationOptions o){return new MatchSimulator(new TeamfightResolver(),new EndGameEvaluator(),new SnapshotFactory(c),new ObjectiveResolver(),new PostFightResolver(),new ObjectiveAttemptResolver(),new StructureResolver(),new PushResolver(),o);}
}
