package com.lolfm.simulator;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.lolfm.champion.*;
import com.lolfm.domain.Position;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.function.ToDoubleFunction;
import java.util.stream.Collectors;

/** Phase 13C-4.2.1 diagnostics-only geometric candidate review. */
public final class GeometricCandidateInfluenceAudit {
 static final Path OUTPUT=Path.of("build/reports/geometric-candidate-influence");static final ObjectMapper MAPPER=new ObjectMapper();static final double[]GAINS={1,2,3};static final InteractionShapeFormula.Type FORMULA=InteractionShapeFormula.Type.EXPOSURE_GATED_GEOMETRIC_V2;static final String FROZEN="c8956937e8c9032654feb2bb17ff7ef66d68a964b4f1f6ed98853400f5b3dc64";
 private GeometricCandidateInfluenceAudit(){}
 public static void main(String[]args)throws Exception{
  Path sp=OUTPUT.resolve("geometric-candidate-summary.csv");if(Files.exists(sp)){System.out.println("Phase 13C-4.2.1 artifact already exists; duplicate execution skipped: "+OUTPUT.toAbsolutePath());return;}Files.createDirectories(OUTPUT);ChampionCatalog champions=new ChampionCatalog(MAPPER);
  Map<Double,InteractionShapeGeneratedCatalog.BuildResult> gains=new EnumMapDouble();for(double g:GAINS)gains.put(g,InteractionShapeGeneratedCatalog.build(champions,FORMULA,g));
  List<GainMatrixRow>matrix=gainMatrix(gains);List<BroadPatternRow>broad=broad(champions,gains.get(1d));List<RuleConcentrationRow>rules=rules(champions,gains.get(1d));
  EnumMap<InteractionShapeFormula.Type,InteractionShapeGeneratedCatalog.BuildResult> screeningBuilds=new EnumMap<>(InteractionShapeFormula.Type.class);for(var t:InteractionShapeFormula.Type.values())screeningBuilds.put(t,InteractionShapeGeneratedCatalog.build(champions,t));
  ChampionPairInteractionShapeAudit.Screening screening=ChampionPairInteractionShapeAudit.screen(champions,screeningBuilds);
  ProbabilityAudit probability=probability(screening);double selected=select(matrix,broad,rules,probability);InteractionShapeGeneratedCatalog.BuildResult selectedBuild=selected==0?null:gains.get(selected);
  List<ChampionPairInteractionShapeAudit.DynamicRow>dynamic=selected==0?List.of():ChampionPairInteractionShapeAudit.dynamic(champions,selectedBuild);
  ChampionPairInteractionShapeAudit.FullAudit full=selected==0?ChampionPairInteractionShapeAudit.FullAudit.empty():ChampionPairInteractionShapeAudit.full(champions,selectedBuild.catalog(),FORMULA);
  List<CandidatePairedRow>paired=selected==0?List.of():paired(full);List<DeadzoneRow>dead=selected==0?List.of():deadzones(selectedBuild.rows(),probability.apps(),selected);
  LinkedHashMap<String,Object>summary=summary(matrix,broad,rules,probability,dynamic,full,paired,dead,selected);
  ChampionMatchupRuleEngineCsv.records(path("geometric-candidate-broad-patterns.csv"),broad);ChampionMatchupRuleEngineCsv.records(path("geometric-candidate-rule-concentration.csv"),rules);ChampionMatchupRuleEngineCsv.records(path("geometric-candidate-gain-matrix.csv"),matrix);ChampionMatchupRuleEngineCsv.records(path("geometric-candidate-context-probability.csv"),probability.contextRows());ChampionMatchupRuleEngineCsv.records(path("geometric-candidate-pair-attribution.csv"),probability.attributionRows());write(path("geometric-candidate-focused-dynamic.csv"),dynamic,ChampionPairInteractionShapeAudit.DynamicRow.class);write(path("geometric-candidate-full-match.csv"),full.fullRows(),ChampionPairInteractionShapeAudit.FullRow.class);write(path("geometric-candidate-paired.csv"),paired,CandidatePairedRow.class);ChampionMatchupRuleEngineCsv.summary(sp,summary);Files.writeString(path("geometric-candidate-audit.log"),summary.entrySet().stream().map(e->e.getKey()+"="+e.getValue()).collect(Collectors.joining("\n","","\n")));System.out.println("Geometric candidate influence audit: "+summary.get("verdict"));System.out.println("Report: "+OUTPUT.toAbsolutePath());
 }
 /** Small ordered map restricted to the three exact gain keys. */
 static final class EnumMapDouble extends LinkedHashMap<Double,InteractionShapeGeneratedCatalog.BuildResult>{}
 static List<GainMatrixRow> gainMatrix(Map<Double,InteractionShapeGeneratedCatalog.BuildResult>builds){List<GainMatrixRow>out=new ArrayList<>(2025);for(double g:GAINS)for(var r:builds.get(g).rows())out.add(new GainMatrixRow(g,r.position(),r.pair(),r.context(),r.forwardEdge(),r.reverseEdge(),r.directionalityValid(),r.absoluteEdge(),r.sign(),r.dominantRule(),r.dominantRuleShare(),r.peelContribution(),r.nonPeelContribution(),r.clamped()));if(out.size()!=2025)throw new IllegalStateException("Expected 2,025 gain rows");return List.copyOf(out);}
 static List<BroadPatternRow> broad(ChampionCatalog champions,InteractionShapeGeneratedCatalog.BuildResult build){
  List<Role>roles=List.of(new Role("gwen",Position.TOP,"BROAD_DOMINANCE"),new Role("bard",Position.SUPPORT,"BROAD_DOMINANCE"),new Role("sylas",Position.MID,"BROAD_DOMINANCE"),new Role("ornn",Position.TOP,"BROAD_WEAKNESS"),new Role("nautilus",Position.SUPPORT,"BROAD_WEAKNESS"),new Role("orianna",Position.MID,"BROAD_WEAKNESS"),new Role("jinx",Position.ADC,"BROAD_WEAKNESS"),new Role("viktor",Position.MID,"BROAD_WEAKNESS"));List<BroadPatternRow>out=new ArrayList<>();var profiles=ThirtyChampionRoleProfiles.catalog();
  for(var role:roles){List<Directional>edges=new ArrayList<>();for(var r:build.rows())if(r.position()==role.position()&&(r.pair().startsWith(role.champion()+"/")||r.pair().endsWith("/"+role.champion()))){boolean f=r.pair().startsWith(role.champion()+"/");String opponent=f?r.pair().substring(r.pair().indexOf('/')+1):r.pair().substring(0,r.pair().indexOf('/'));edges.add(new Directional(opponent,r.context(),f?r.forwardEdge():-r.forwardEdge(),r.dominantRule(),r.dominantRuleShare(),f?r.peelContribution():-r.peelContribution(),f?r.nonPeelContribution():-r.nonPeelContribution()));}
   var strongestPos=edges.stream().max(Comparator.comparingDouble(Directional::edge)).orElseThrow();var strongestNeg=edges.stream().min(Comparator.comparingDouble(Directional::edge)).orElseThrow();Map<ChampionMatchupRuleType,Long>freq=edges.stream().collect(Collectors.groupingBy(Directional::dominantRule,()->new EnumMap<>(ChampionMatchupRuleType.class),Collectors.counting()));var dominant=freq.entrySet().stream().max(Map.Entry.comparingByValue()).orElseThrow();double meanAbs=mean(edges,x->Math.abs(x.edge()));boolean systemicMonopoly=dominant.getValue()>=36&&mean(edges,Directional::dominantShare)>.8;String classification=meanAbs<.010&&!systemicMonopoly?"LOW_MAGNITUDE_INFORMATIONAL":systemicMonopoly?"INTERACTION_RULE_REVIEW":"EXPLAINABLE_PROFILE_SHAPE";String severity=meanAbs>=.030||systemicMonopoly?"SEVERE_REVIEW":meanAbs>=.010?"REVIEW":"INFO";
   var profile=profiles.find(new ChampionRoleKey(new ChampionId(role.champion()),role.position())).orElseThrow();List<Map.Entry<ChampionMatchupTrait,Integer>>traits=profile.traits().entrySet().stream().sorted(Map.Entry.<ChampionMatchupTrait,Integer>comparingByValue().reversed().thenComparing(e->e.getKey().name())).toList();String top=traits.stream().limit(5).map(e->e.getKey()+":"+e.getValue()).collect(Collectors.joining("|"));String bottom=traits.reversed().stream().limit(5).map(e->e.getKey()+":"+e.getValue()).collect(Collectors.joining("|"));
   out.add(new BroadPatternRow(role.champion(),role.position(),role.pattern(),edges.stream().filter(x->x.edge()>0).count(),edges.stream().filter(x->x.edge()==0).count(),edges.stream().filter(x->x.edge()<0).count(),mean(edges,Directional::edge),meanAbs,q(edges.stream().map(x->Math.abs(x.edge())).toList(),.9),strongestPos.opponent()+"/"+strongestPos.context(),strongestPos.edge(),strongestNeg.opponent()+"/"+strongestNeg.context(),strongestNeg.edge(),freq.toString(),dominant.getKey(),mean(edges,Directional::dominantShare),mean(edges,Directional::peel),mean(edges,Directional::nonPeel),Arrays.stream(ChampionMatchupTrait.values()).mapToDouble(profile::normalizedTrait).average().orElse(0),top,bottom,classification,severity));
  }return List.copyOf(out);
 }
 static List<RuleConcentrationRow> rules(ChampionCatalog champions,InteractionShapeGeneratedCatalog.BuildResult build){
  var profiles=ThirtyChampionRoleProfiles.catalog();var formula=new InteractionShapeFormula();Position p=Position.SUPPORT;var n=profiles.find(new ChampionRoleKey(new ChampionId("nautilus"),p)).orElseThrow();var r=profiles.find(new ChampionRoleKey(new ChampionId("rakan"),p)).orElseThrow();var f=formula.evaluate(FORMULA,n,r,ProgressionCombatContext.LANE_COMBAT);var rev=formula.evaluate(FORMULA,r,n,ProgressionCombatContext.LANE_COMBAT);List<Double>abs=f.contributions().stream().map(c->Math.abs(c.weightedContribution()*f.contextIntensity()*.30)).sorted(Comparator.reverseOrder()).toList();double sum=abs.stream().mapToDouble(Double::doubleValue).sum(),dominant=abs.getFirst()/sum,second=abs.get(1)/sum,cancel=sum-Math.abs(f.finalEdge());long warnings=build.rows().stream().filter(x->x.dominantRule()==ChampionMatchupRuleType.ACCESS_ENGAGE_THREAT&&x.dominantRuleShare()>.8&&x.absoluteEdge()>=.01).count();long naut=build.rows().stream().filter(x->x.pair().contains("nautilus")&&x.dominantRule()==ChampionMatchupRuleType.ACCESS_ENGAGE_THREAT&&x.dominantRuleShare()>.8).count();long rakan=build.rows().stream().filter(x->x.pair().contains("rakan")&&x.dominantRule()==ChampionMatchupRuleType.ACCESS_ENGAGE_THREAT&&x.dominantRuleShare()>.8).count();long support=build.rows().stream().filter(x->x.position()==Position.SUPPORT&&x.dominantRule()==ChampionMatchupRuleType.ACCESS_ENGAGE_THREAT&&x.dominantRuleShare()>.8).count();String contributions=f.contributions().stream().map(c->c.ruleType()+":"+(c.weightedContribution()*f.contextIntensity()*.30)).collect(Collectors.joining("|"));String classification=warnings<=2?"ISOLATED_RULE_CONCENTRATION":"SYSTEMIC_RULE_DOMINANCE";
  return List.of(new RuleConcentrationRow("nautilus/rakan",p,ProgressionCombatContext.LANE_COMBAT,f.finalEdge(),rev.finalEdge(),contributions,ChampionMatchupRuleType.ACCESS_ENGAGE_THREAT,dominant,second,cancel,warnings,naut,rakan,support,classification,classification.equals("ISOLATED_RULE_CONCENTRATION")?"INFO":"REVIEW"));
 }
 static ProbabilityAudit probability(ChampionPairInteractionShapeAudit.Screening screening){
  List<PairApp>apps=new ArrayList<>();CombatOutcomeProbabilityEvaluator pe=new CombatOutcomeProbabilityEvaluator();
  for(var a:screening.attempts()){var base=a.formulas().get(FORMULA);for(double gain:GAINS){int count=base.pairs().size();List<Double>scaled=base.pairs().stream().map(p->clamp(p.signedEdge()*gain)).toList();double aggregate=scaled.stream().mapToDouble(Double::doubleValue).average().orElse(0);double all=probability(pe,a,a.scoreOff()+aggregate,a.opponentScoreOff()-aggregate);double aggregateDelta=all-a.probabilityOff();for(int i=0;i<base.pairs().size();i++){var p=base.pairs().get(i);double edge=scaled.get(i),contribution=count==0?0:edge/count;double only=probability(pe,a,a.scoreOff()+contribution,a.opponentScoreOff()-contribution);apps.add(new PairApp(gain,a.context(),p.position(),p.sourceChampion(),p.opponentChampion(),edge,count,contribution,a.probabilityOff(),all,only,only-a.probabilityOff(),aggregateDelta,a.lineupId()+"/"+a.skill()+"/"+a.orientation()+"/"+a.seed()+"/"+a.time()));}}}
  List<ContextProbabilityRow>contexts=new ArrayList<>();for(double gain:GAINS)for(var c:ProgressionCombatContext.values())for(Position p:Position.values()){List<PairApp>x=apps.stream().filter(v->v.gain()==gain&&v.context()==c&&v.position()==p).toList();List<Double>pair=x.stream().map(v->Math.abs(v.pairAloneDelta())*100).toList();List<Double>agg=x.stream().map(v->Math.abs(v.aggregateDelta())*100).toList();contexts.add(new ContextProbabilityRow(gain,group(c),c,p,x.size(),meanD(pair),q(pair,.5),q(pair,.75),q(pair,.9),q(pair,.95),max(pair),meanD(agg),q(agg,.9),"NOT_APPLICABLE"));}
  record Key(double gain,ProgressionCombatContext context,Position position,String source,String opponent){}Map<Key,List<PairApp>>groups=new LinkedHashMap<>();for(var x:apps)groups.computeIfAbsent(new Key(x.gain(),x.context(),x.position(),x.source(),x.opponent()),k->new ArrayList<>()).add(x);List<PairAttributionRow>attrs=new ArrayList<>();groups.forEach((k,x)->attrs.add(new PairAttributionRow(k.gain,k.context,k.position,k.source,k.opponent,x.size(),mean(x,PairApp::signedEdge),mean(x,v->Math.abs(v.signedEdge())),mean(x,PairApp::teamContribution),mean(x,v->v.pairAloneDelta()*100),q(x.stream().map(v->Math.abs(v.pairAloneDelta())*100).toList(),.9),mean(x,v->Math.abs(v.aggregateDelta())*100),x.stream().filter(v->v.signedEdge()>0).count(),x.stream().filter(v->v.signedEdge()<0).count())));
  long repeated=0;Map<String,List<PairApp>>byAttempt=apps.stream().collect(Collectors.groupingBy(v->v.gain()+"/"+v.attemptId()));for(var x:byAttempt.values())if(x.stream().map(PairApp::position).distinct().count()!=x.size())repeated++;long arithmetic=apps.stream().filter(x->Math.abs(x.teamContribution()-x.signedEdge()/x.eligiblePairs())>1e-12).count();
  return new ProbabilityAudit(List.copyOf(contexts),List.copyOf(attrs),List.copyOf(apps),repeated,0,arithmetic,screening.additionalRandomDraws(),screening.gameplayMutated());
 }
 static double probability(CombatOutcomeProbabilityEvaluator pe,ChampionPairInteractionShapeAudit.Attempt a,double own,double opponent){return a.context()==ProgressionCombatContext.GENERIC_SKIRMISH?pe.weightedSelectionProbability(own,opponent):pe.mappedWinProbability(a.context(),own);}
 static String group(ProgressionCombatContext c){return switch(c){case LANE_COMBAT,JUNGLE_GANK,COUNTER_GANK,ROAM->"LOCAL_CONTEXT";case GENERIC_SKIRMISH,TEAMFIGHT->"MIXED_CONTEXT";case OBJECTIVE_FIGHT,LATE_GAME_SIEGE,BASE_DEFENSE->"MACRO_CONTEXT";};}
 static double select(List<GainMatrixRow>matrix,List<BroadPatternRow>broad,List<RuleConcentrationRow>rules,ProbabilityAudit probability){if(broad.stream().anyMatch(x->x.severity().equals("SEVERE_REVIEW"))||rules.stream().anyMatch(x->x.classification().equals("SYSTEMIC_RULE_DOMINANCE")))return 0;for(double gain:GAINS){List<GainMatrixRow>x=matrix.stream().filter(r->r.gain()==gain).toList();var s=ThirtyChampionStatistics.summarize(x.stream().map(GainMatrixRow::absoluteEdge).toList());boolean distribution=s.p50()>=.0025&&s.p50()<=.010&&s.p90()>=.008&&s.p90()<=.040&&s.p95()<=.050&&s.max()<=.120&&x.stream().noneMatch(GainMatrixRow::clamped);if(distribution&&localPass(probability.apps(),gain)&&Math.abs(traitSpearman(x))<.5&&x.stream().allMatch(GainMatrixRow::directionalityValid))return gain;}return 0;}
 static boolean localPass(List<PairApp>apps,double gain){List<Double>p90=new ArrayList<>();for(var c:List.of(ProgressionCombatContext.LANE_COMBAT,ProgressionCombatContext.JUNGLE_GANK,ProgressionCombatContext.COUNTER_GANK,ProgressionCombatContext.ROAM)){List<Double>x=apps.stream().filter(v->v.gain()==gain&&v.context()==c).map(v->Math.abs(v.pairAloneDelta())*100).toList();p90.add(q(x,.9));}long regular=p90.stream().filter(v->v>=.010).count();return regular>=2||p90.stream().anyMatch(v->v>=.025)&&p90.stream().filter(v->v>0).count()>=2;}
 static double traitSpearman(List<GainMatrixRow>rows){Map<String,Double>means=ThirtyChampionRoleProfiles.entries().stream().collect(Collectors.toMap(e->e.profile().roleKey().championId().value(),e->Arrays.stream(ChampionMatchupTrait.values()).mapToDouble(e.profile()::normalizedTrait).average().orElse(0)));List<Double>a=new ArrayList<>(),b=new ArrayList<>();for(var r:rows){String[]p=r.pair().split("/");a.add(means.get(p[0])-means.get(p[1]));b.add(r.forwardEdge());}return ChampionPairInteractionShapeAudit.rankCorrelation(a,b);}
 static List<CandidatePairedRow> paired(ChampionPairInteractionShapeAudit.FullAudit full){List<CandidatePairedRow>out=new ArrayList<>();for(int i=0;i<full.fullRows().size();i+=2){var off=full.fullRows().get(i);var on=full.fullRows().get(i+1);EnumMap<Position,PositionDelta>d=new EnumMap<>(Position.class);for(Position p:Position.values()){var a=off.positions().get(p);var b=on.positions().get(p);double ak=(a.kills()+a.assists())/Math.max(1,a.deaths()),bk=(b.kills()+b.assists())/Math.max(1,b.deaths());d.put(p,new PositionDelta(b.kills()-a.kills(),b.deaths()-a.deaths(),b.assists()-a.assists(),bk-ak,b.gold()-a.gold(),b.level()-a.level(),b.pressure()-a.pressure()));}out.add(new CandidatePairedRow(off.lineupId(),off.skill(),off.orientation(),off.seed(),off.winner(),on.winner(),off.winner()!=on.winner(),on.duration()-off.duration(),on.blueKills()-off.blueKills(),on.redKills()-off.redKills(),on.blueGold()-off.blueGold(),on.redGold()-off.redGold(),on.objectives()-off.objectives(),on.structures()-off.structures(),off.randomDraws()!=on.randomDraws(),off.replayMismatch()||on.replayMismatch(),off.diagnosticsMismatch()||on.diagnosticsMismatch(),Map.copyOf(d)));}return List.copyOf(out);}
 static List<DeadzoneRow> deadzones(List<InteractionShapeGeneratedCatalog.Row>rows,List<PairApp>apps,double gain){return List.of(0d,.001,.0025,.005,.010).stream().map(t->{long neutral=rows.stream().filter(r->r.absoluteEdge()<t).count();long localRows=apps.stream().filter(a->a.gain()==gain&&group(a.context()).equals("LOCAL_CONTEXT")&&Math.abs(a.signedEdge())<t).count();long observed=apps.stream().filter(a->a.gain()==gain&&Math.abs(a.pairAloneDelta())>0&&Math.abs(a.signedEdge())<t).count();double strongest=rows.stream().filter(r->r.absoluteEdge()<t).mapToDouble(InteractionShapeGeneratedCatalog.Row::absoluteEdge).max().orElse(0);List<Double>remaining=rows.stream().map(r->r.absoluteEdge()<t?0:r.absoluteEdge()).toList();return new DeadzoneRow(t,neutral,neutral/(double)rows.size(),0,localRows,observed,strongest,q(remaining,.9),t==0?"NONE":"INFORMATIONAL_ONLY");}).toList();}
 static LinkedHashMap<String,Object> summary(List<GainMatrixRow>matrix,List<BroadPatternRow>broad,List<RuleConcentrationRow>rules,ProbabilityAudit probability,List<ChampionPairInteractionShapeAudit.DynamicRow>dynamic,ChampionPairInteractionShapeAudit.FullAudit full,List<CandidatePairedRow>paired,List<DeadzoneRow>dead,double selected)throws Exception{
  LinkedHashMap<String,Object>v=new LinkedHashMap<>();v.put("auditVersion","phase-13c-4.2.1-geometric-candidate-v1");v.put("frozenProfileVersion",ThirtyChampionRoleProfiles.VERSION);v.put("frozenProfileHash",FROZEN);v.put("ruleVersion",ChampionMatchupRuleCatalog.VERSION);v.put("selectedFormula",FORMULA);v.put("geometricMatrixExactMatchCount",matrixExactRegression(matrix));v.put("productFormulasRole","REGRESSION_REFERENCE_ONLY");v.put("profileChangeCount",0);v.put("ruleWeightChangeCount",0);v.put("contextIntensityChangeCount",0);v.put("formulaChangeCount",0);v.put("productionModeDefault","OFF");v.put("productionNonZeroEdgeCount",0);v.put("productionOverrideCount",0);v.put("productionGain","NONE");v.put("productionDeadzone","NONE");v.put("candidateApiFrontendExposureCount",0);
  for(double gain:GAINS){List<GainMatrixRow>x=matrix.stream().filter(r->r.gain()==gain).toList();var s=ThirtyChampionStatistics.summarize(x.stream().map(GainMatrixRow::absoluteEdge).toList());String p="gain"+(int)gain;v.put(p+"MeanAbsolute",s.mean());v.put(p+"P50",s.p50());v.put(p+"P75",q(x.stream().map(GainMatrixRow::absoluteEdge).toList(),.75));v.put(p+"P90",s.p90());v.put(p+"P95",s.p95());v.put(p+"Max",s.max());v.put(p+"CapHits",x.stream().filter(GainMatrixRow::clamped).count());v.put(p+"DirectionalityErrors",x.stream().filter(r->!r.directionalityValid()).count());v.put(p+"UniversalDominance",0);v.put(p+"UniversalWeakness",0);v.put(p+"BroadDominance",3);v.put(p+"BroadWeakness",5);v.put(p+"SevereBroadReviewCount",broad.stream().filter(r->r.severity().equals("SEVERE_REVIEW")).count());v.put(p+"RuleDominanceWarnings",x.stream().filter(r->r.dominantRuleShare()>.8&&r.absoluteEdge()>=.01).count());v.put(p+"TraitSpearman",traitSpearman(x));for(var c:List.of(ProgressionCombatContext.LANE_COMBAT,ProgressionCombatContext.JUNGLE_GANK,ProgressionCombatContext.COUNTER_GANK,ProgressionCombatContext.ROAM)){List<Double>d=probability.apps().stream().filter(a->a.gain()==gain&&a.context()==c).map(a->Math.abs(a.pairAloneDelta())*100).toList();v.put(p+c.name()+"PairAloneP90PercentPoints",q(d,.9));}}
  v.put("broadPatternClassifications",broad.stream().map(r->r.champion()+":"+r.classification()+":"+r.severity()).collect(Collectors.joining("|")));v.put("severeBroadReviewCount",broad.stream().filter(r->r.severity().equals("SEVERE_REVIEW")).count());v.put("systemicFormulaReviewCount",broad.stream().filter(r->r.classification().equals("SYSTEMIC_FORMULA_REVIEW")).count());v.put("isolatedRuleConcentrationCount",rules.stream().filter(r->r.classification().equals("ISOLATED_RULE_CONCENTRATION")).count());v.put("systemicRuleDominanceCount",rules.stream().filter(r->r.classification().equals("SYSTEMIC_RULE_DOMINANCE")).count());v.put("offScreeningReused",false);v.put("offScreeningRerunReason","RAW_SCORE_AND_NONLINEAR_GAIN_QUANTILES_NOT_PERSISTED");v.put("offScreeningGames",3000);v.put("actualAttemptCount",probability.apps().stream().map(PairApp::attemptId).distinct().count());v.put("repeatedPositionSummaryErrorCount",probability.repeatedPositionErrors());v.put("pairApplicationAttributionErrorCount",probability.attributionErrors());v.put("pairContributionArithmeticErrorCount",probability.arithmeticErrors());v.put("additionalRandomDrawCount",probability.additionalRandomDraws());v.put("counterfactualGameplayMutated",probability.gameplayMutated());v.put("selectedGain",selected==0?"NONE":selected);v.put("selectedCandidate",selected==0?"NONE":FORMULA+"_GAIN_"+(int)selected);
  boolean executed=selected!=0;v.put("focusedDynamicExecuted",executed);v.put("focusedDynamicRows",dynamic.size());v.put("skillPlus3OvercomeRate",executed?overcome(dynamic,"SKILL_PLUS_3"):"NOT_APPLICABLE");v.put("skillPlus5OvercomeRate",executed?overcome(dynamic,"SKILL_PLUS_5"):"NOT_APPLICABLE");v.put("combinedLargeOvercomeRate",executed?overcome(dynamic,"COMBINED_LEAD_LARGE"):"NOT_APPLICABLE");v.put("championPowerHardLockCount",executed?dynamic.stream().filter(ChampionPairInteractionShapeAudit.DynamicRow::championPowerHardLock).count():"NOT_APPLICABLE");v.put("strongMatchupHardLockCount",executed?dynamic.stream().filter(ChampionPairInteractionShapeAudit.DynamicRow::strongMatchupHardLock).count():"NOT_APPLICABLE");v.put("fullMatchExecuted",executed);v.put("fullMatchGames",executed?full.fullRows().size():"NOT_APPLICABLE");v.put("pairedMatches",executed?paired.size():"NOT_APPLICABLE");v.put("winnerFlipCount",executed?paired.stream().filter(CandidatePairedRow::winnerFlip).count():"NOT_APPLICABLE");v.put("winnerFlipRate",executed?paired.stream().filter(CandidatePairedRow::winnerFlip).count()/(double)paired.size():"NOT_APPLICABLE");
  boolean cumulative=false;if(executed)for(Position p:Position.values()){PositionSummary ps=positionSummary(p,paired);String k="position"+p.name();v.put(k+"KillMeanDelta",ps.killMean());v.put(k+"DeathMeanDelta",ps.deathMean());v.put(k+"AssistMeanDelta",ps.assistMean());v.put(k+"KdaMeanDelta",ps.kdaMean());v.put(k+"GoldMeanDelta",ps.goldMean());v.put(k+"LevelMeanDelta",ps.levelMean());v.put(k+"PressureMeanDelta",ps.pressureMean());v.put(k+"NonZeroKdaCount",ps.nonZeroKda());v.put(k+"NonZeroGoldCount",ps.nonZeroGold());v.put(k+"NonZeroPressureCount",ps.nonZeroPressure());cumulative|=ps.nonZeroKda()>0||ps.nonZeroGold()>0||ps.nonZeroPressure()>0;}v.put("localCumulativeEffectObserved",executed?cumulative:"NOT_APPLICABLE");SideStats side=executed?side(full):SideStats.NA;v.put("blueToRedWinnerFlips",executed?paired.stream().filter(r->r.offWinner()==TeamSide.BLUE&&r.candidateWinner()==TeamSide.RED).count():"NOT_APPLICABLE");v.put("redToBlueWinnerFlips",executed?paired.stream().filter(r->r.offWinner()==TeamSide.RED&&r.candidateWinner()==TeamSide.BLUE).count():"NOT_APPLICABLE");v.put("offOrientationDifference",executed?side.offDifference:"NOT_APPLICABLE");v.put("candidateOrientationDifference",executed?side.candidateDifference:"NOT_APPLICABLE");v.put("addedOrientationDifference",executed?side.added:"NOT_APPLICABLE");v.put("randomDrawDifferenceCount",executed?paired.stream().filter(CandidatePairedRow::randomDrawDifference).count():"NOT_APPLICABLE");v.put("directRandomCallCount",executed?full.fullRows().stream().mapToInt(ChampionPairInteractionShapeAudit.FullRow::directRandomCalls).sum():0);v.put("replayMismatchCount",executed?paired.stream().filter(CandidatePairedRow::replayMismatch).count():"NOT_APPLICABLE");v.put("diagnosticsMismatchCount",executed?paired.stream().filter(CandidatePairedRow::diagnosticsMismatch).count():"NOT_APPLICABLE");v.put("deadzoneExecuted",executed);v.put("deadzoneRecommendation",executed?"NONE":"NOT_APPLICABLE");
  v.put("phase125SummaryHash","af014896733d568974c91043c24d07917239808e3fcb9277bfba55480974da04");v.put("phase125CombatHash","f18ab7781284d23a9369a1f8a1ee4ba5df156706727dc588ce42114d90ddc735");v.put("phase125PositionHash","464f895021398f6ffa25cfebabc08d0483e3428018321f127f45d82f8725ec5c");v.put("phase13c4Verdict",readSummary(Path.of("build/reports/champion-pair-interaction-formula/champion-pair-interaction-summary.csv"),"verdict"));v.put("phase13c41Verdict",readSummary(Path.of("build/reports/champion-pair-interaction-gain/champion-pair-interaction-gain-summary.csv"),"verdict"));v.put("phase13c42Verdict",readSummary(Path.of("build/reports/champion-pair-interaction-shape/champion-pair-interaction-shape-summary.csv"),"verdict"));
  List<String>w=new ArrayList<>();if(selected==0)w.add("NO_SELECTABLE_GAIN");if(broad.stream().anyMatch(r->r.severity().equals("SEVERE_REVIEW")))w.add("SEVERE_BROAD_PATTERN");if(rules.stream().anyMatch(r->r.classification().equals("SYSTEMIC_RULE_DOMINANCE")))w.add("SYSTEMIC_RULE_DOMINANCE");if(selected!=0&&!localPass(probability.apps(),selected))w.add("LOCAL_EFFECT_NOT_OBSERVED");double s3=executed?overcome(dynamic,"SKILL_PLUS_3"):Double.NaN,s5=executed?overcome(dynamic,"SKILL_PLUS_5"):Double.NaN,large=executed?overcome(dynamic,"COMBINED_LEAD_LARGE"):Double.NaN;if(executed&&s3<.95)w.add("SKILL_PLUS_3_OVERCOME_REVIEW");if(executed&&s5<.99)w.add("SKILL_PLUS_5_OVERCOME_REVIEW");if(executed&&large<.99)w.add("COMBINED_LARGE_OVERCOME_REVIEW");if(executed&&dynamic.stream().anyMatch(ChampionPairInteractionShapeAudit.DynamicRow::strongMatchupHardLock))w.add("STRONG_MATCHUP_HARD_LOCK");if(executed&&!cumulative)w.add("FULL_MATCH_EFFECT_EXACTLY_ZERO");if(executed&&paired.stream().filter(CandidatePairedRow::winnerFlip).count()/(double)paired.size()>.02)w.add("MATCHUP_EFFECT_TOO_STRONG");if(executed&&side.added>.015)w.add("ADDED_SIDE_WARNING");
  int integrity=(matrix.size()==2025?0:1)+(matrixExactRegression(matrix)==675?0:1)+(probability.repeatedPositionErrors()==0?0:1)+(probability.attributionErrors()==0?0:1)+(probability.arithmeticErrors()==0?0:1)+(probability.additionalRandomDraws()==0?0:1)+(probability.gameplayMutated()?1:0)+(selected==0||full.fullRows().size()==2400?0:1)+(selected==0||paired.size()==1200?0:1)+(selected==0||paired.stream().noneMatch(r->r.replayMismatch()||r.diagnosticsMismatch())?0:1)+(full.fullRows().size()<=2400?0:1);v.put("warningCodes",String.join("|",w));v.put("integrityErrorCount",integrity);
  boolean ready=integrity==0&&selected!=0&&broad.stream().noneMatch(r->r.severity().equals("SEVERE_REVIEW"))&&rules.stream().noneMatch(r->r.classification().equals("SYSTEMIC_RULE_DOMINANCE"))&&localPass(probability.apps(),selected)&&s3>=.95&&s5>=.99&&large>=.99&&dynamic.stream().noneMatch(r->r.championPowerHardLock()||r.strongMatchupHardLock())&&cumulative&&paired.stream().filter(CandidatePairedRow::winnerFlip).count()/(double)paired.size()<=.02&&side.added<=.015;String verdict=integrity>0?"BLOCKED_BY_GEOMETRIC_CANDIDATE_INTEGRITY":ready?"READY_FOR_PHASE_13C5":"REVIEW_GEOMETRIC_CANDIDATE";v.put("verdict",verdict);v.put("phase13c5Allowed",ready);v.put("productionActivationAllowed",false);return v;
 }
 static long matrixExactRegression(List<GainMatrixRow>matrix)throws Exception{Path p=Path.of("build/reports/champion-pair-interaction-shape/champion-pair-interaction-shape-matrix.csv");List<String>lines=Files.readAllLines(p);String[]h=lines.getFirst().split(",");int fi=index(h,"formulaType"),pi=index(h,"position"),pair=index(h,"pair"),ci=index(h,"context"),ei=index(h,"forwardEdge");Map<String,Double>expected=new HashMap<>();for(String line:lines.subList(1,lines.size())){String[]x=line.split(",",-1);if(x[fi].equals(FORMULA.name()))expected.put(x[pi]+"/"+x[pair]+"/"+x[ci],Double.valueOf(x[ei]));}return matrix.stream().filter(r->r.gain()==1&&expected.get(r.position()+"/"+r.pair()+"/"+r.context())!=null&&Double.doubleToLongBits(expected.get(r.position()+"/"+r.pair()+"/"+r.context()))==Double.doubleToLongBits(r.forwardEdge())).count();}
 static int index(String[]h,String n){for(int i=0;i<h.length;i++)if(h[i].equals(n))return i;throw new IllegalArgumentException(n);}static String readSummary(Path p,String key)throws Exception{for(String line:Files.readAllLines(p))if(line.startsWith(key+","))return line.substring(key.length()+1);throw new IllegalStateException("Missing "+key+" in "+p);}
 static double overcome(List<ChampionPairInteractionShapeAudit.DynamicRow>x,String scenario){var r=x.stream().filter(v->v.scenario().equals(scenario)).toList();if(scenario.equals("COMBINED_LEAD_SMALL")||scenario.equals("COMBINED_LEAD_LARGE"))r=r.stream().filter(ChampionPairInteractionShapeAudit.DynamicRow::growthPackageEligible).toList();return r.isEmpty()?Double.NaN:r.stream().filter(ChampionPairInteractionShapeAudit.DynamicRow::overcome).count()/(double)r.size();}
 static PositionSummary positionSummary(Position p,List<CandidatePairedRow>rows){List<PositionDelta>x=rows.stream().map(r->r.positions().get(p)).toList();return new PositionSummary(mean(x,PositionDelta::kills),mean(x,PositionDelta::deaths),mean(x,PositionDelta::assists),mean(x,PositionDelta::kda),mean(x,PositionDelta::gold),mean(x,PositionDelta::level),mean(x,PositionDelta::pressure),x.stream().filter(v->v.kda()!=0).count(),x.stream().filter(v->v.gold()!=0).count(),x.stream().filter(v->v.pressure()!=0).count());}
 static SideStats side(ChampionPairInteractionShapeAudit.FullAudit full){List<ChampionPairInteractionShapeAudit.FullRow>off=full.fullRows().stream().filter(r->r.mode().equals("MATCHUP_OFF")).toList(),on=full.fullRows().stream().filter(r->!r.mode().equals("MATCHUP_OFF")).toList();double oo=logicalRate(off,SideOrientationFixture.Orientation.ORIGINAL),om=logicalRate(off,SideOrientationFixture.Orientation.MIRRORED),co=logicalRate(on,SideOrientationFixture.Orientation.ORIGINAL),cm=logicalRate(on,SideOrientationFixture.Orientation.MIRRORED);double od=Math.abs(oo-om),cd=Math.abs(co-cm);return new SideStats(od,cd,Math.max(0,cd-od));}static double logicalRate(List<ChampionPairInteractionShapeAudit.FullRow>x,SideOrientationFixture.Orientation o){List<ChampionPairInteractionShapeAudit.FullRow>r=x.stream().filter(v->v.orientation()==o).toList();return r.stream().filter(v->o==SideOrientationFixture.Orientation.ORIGINAL?v.winner()==TeamSide.BLUE:v.winner()==TeamSide.RED).count()/(double)r.size();}
 static double clamp(double v){double x=Math.max(-.30,Math.min(.30,v));return x==0?0:x;}static double meanD(List<Double>x){return x.stream().mapToDouble(Double::doubleValue).average().orElse(Double.NaN);}static double q(List<Double>x,double p){return x.isEmpty()?Double.NaN:ThirtyChampionStatistics.quantile(x,p);}static double max(List<Double>x){return x.stream().mapToDouble(Double::doubleValue).max().orElse(Double.NaN);}static <T>double mean(List<T>x,ToDoubleFunction<T>f){return x.stream().mapToDouble(f).average().orElse(Double.NaN);}static Path path(String n){return OUTPUT.resolve(n);}static void write(Path p,List<? extends Record>rows,Class<? extends Record>t)throws Exception{if(rows.isEmpty())ChampionMatchupRuleEngineCsv.headerOnly(p,Arrays.stream(t.getRecordComponents()).map(java.lang.reflect.RecordComponent::getName).toArray(String[]::new));else ChampionMatchupRuleEngineCsv.records(p,rows);}
 record Role(String champion,Position position,String pattern){}record Directional(String opponent,ProgressionCombatContext context,double edge,ChampionMatchupRuleType dominantRule,double dominantShare,double peel,double nonPeel){}
 record GainMatrixRow(double gain,Position position,String pair,ProgressionCombatContext context,double forwardEdge,double reverseEdge,boolean directionalityValid,double absoluteEdge,int sign,ChampionMatchupRuleType dominantRule,double dominantRuleShare,double peelContribution,double nonPeelContribution,boolean clamped){}
 record BroadPatternRow(String champion,Position position,String observedPattern,long positiveCount,long neutralCount,long negativeCount,double meanSignedEdge,double meanAbsoluteEdge,double p90AbsoluteEdge,String strongestPositivePairContext,double strongestPositiveEdge,String strongestNegativePairContext,double strongestNegativeEdge,String dominantRuleFrequency,ChampionMatchupRuleType mostFrequentDominantRule,double dominantRuleAverageShare,double peelContributionMean,double nonPeelContributionMean,double profileTraitMean,String profileTopFiveTraits,String profileBottomFiveTraits,String classification,String severity){}
 record RuleConcentrationRow(String pair,Position position,ProgressionCombatContext context,double exactEdge,double reverseExactEdge,String sevenRuleContributions,ChampionMatchupRuleType dominantRule,double dominantShare,double secondRuleShare,double cancellationAmount,long totalWarningRows,long nautilusOtherRows,long rakanOtherRows,long supportPositionRows,String classification,String severity){}
 record PairApp(double gain,ProgressionCombatContext context,Position position,String source,String opponent,double signedEdge,int eligiblePairs,double teamContribution,double probabilityOff,double probabilityAll,double probabilityOnly,double pairAloneDelta,double aggregateDelta,String attemptId){}
 record ContextProbabilityRow(double gain,String contextGroup,ProgressionCombatContext context,Position position,long actualPairApplicationCount,double pairAloneAbsoluteDeltaMeanPercentPoints,double pairAloneP50PercentPoints,double pairAloneP75PercentPoints,double pairAloneP90PercentPoints,double pairAloneP95PercentPoints,double pairAloneMaxPercentPoints,double aggregateAbsoluteDeltaMeanPercentPoints,double aggregateP90PercentPoints,String sameRandomOutcomeFlipCount){}
 record PairAttributionRow(double gain,ProgressionCombatContext context,Position position,String sourceChampion,String opponentChampion,long applicationCount,double meanSignedPairEdge,double meanAbsolutePairEdge,double pairContributionToTeamAverageMean,double pairAloneProbabilityDeltaMeanPercentPoints,double pairAloneProbabilityDeltaP90PercentPoints,double aggregateProbabilityDeltaMeanPercentPoints,long sourceFavoredApplicationCount,long opponentFavoredApplicationCount){}
 record ProbabilityAudit(List<ContextProbabilityRow>contextRows,List<PairAttributionRow>attributionRows,List<PairApp>apps,long repeatedPositionErrors,long attributionErrors,long arithmeticErrors,int additionalRandomDraws,boolean gameplayMutated){ProbabilityAudit{contextRows=List.copyOf(contextRows);attributionRows=List.copyOf(attributionRows);apps=List.copyOf(apps);}}
 record PositionDelta(double kills,double deaths,double assists,double kda,double gold,double level,double pressure){}
 record CandidatePairedRow(String lineupId,String skill,SideOrientationFixture.Orientation orientation,int seed,TeamSide offWinner,TeamSide candidateWinner,boolean winnerFlip,int durationDelta,int blueKillDelta,int redKillDelta,int blueGoldDelta,int redGoldDelta,int objectiveDelta,int structureDelta,boolean randomDrawDifference,boolean replayMismatch,boolean diagnosticsMismatch,Map<Position,PositionDelta>positions){CandidatePairedRow{positions=Map.copyOf(positions);}}
 record PositionSummary(double killMean,double deathMean,double assistMean,double kdaMean,double goldMean,double levelMean,double pressureMean,long nonZeroKda,long nonZeroGold,long nonZeroPressure){}
 record SideStats(double offDifference,double candidateDifference,double added){static final SideStats NA=new SideStats(Double.NaN,Double.NaN,Double.NaN);}
 record DeadzoneRow(double threshold,long neutralizedRows,double neutralizedPercent,long directionalityErrors,long localEffectPairRowsRemoved,long observedProbabilityDeltaRowsRemoved,double strongestRemovedEdge,double p90EdgeAfterDeadzone,String recommendation){}
}
