package com.lolfm.simulator;
import static org.assertj.core.api.Assertions.assertThat;
import com.lolfm.domain.*;import java.util.*;import org.junit.jupiter.api.Test;
class LateGameStructureBranchTest{
 private final LateGameMacroResolver late=new LateGameMacroResolver();private final StructureResolver structures=new StructureResolver();private final TeamfightResolver fights=new TeamfightResolver();
 @Test void deterministicGiveStructureRecordsAttemptAndMutation(){Fixture f=fixture();var r=resolve(f,TeamSide.BLUE,LateGameAttackPlan.SIEGE_TOP,LateGameDefenseResponse.GIVE_STRUCTURE,new ZeroRandom());var x=f.state.getStructureActionExecutionStats().snapshot();assertThat(r.attackerStructure()).isTrue();assertThat(f.state.wasStructureActionAttemptedThisTick(TeamSide.BLUE)).isTrue();assertThat(f.state.wasStructureMutationPerformedThisTick(TeamSide.BLUE)).isTrue();assertThat(x.structureAttempted()).isOne();assertThat(x.structureMutationPerformed()).isOne();}
 @Test void siegeFightWinRecordsOneAttemptAndOneMutation(){Fixture f=fixture();f.state.getBlueTeamState().addGold(100000);var r=resolve(f,TeamSide.BLUE,LateGameAttackPlan.SIEGE_MID,LateGameDefenseResponse.DEFEND,new SequenceRandom(0,.5,0,0,0,0,0,0,0,0));var x=f.state.getStructureActionExecutionStats().snapshot();assertThat(r.fightWinner()).isEqualTo(TeamSide.BLUE);assertThat(r.attackerStructure()).isTrue();assertThat(x.structureAttempted()).isOne();assertThat(x.structureMutationPerformed()).isOne();assertThat(x.sameSideMultipleAttemptError()).isZero();assertThat(x.sameSideMultipleMutationError()).isZero();}
 @Test void siegeGiveMutatesExactlyOneStructure(){Fixture f=fixture();var r=resolve(f,TeamSide.BLUE,LateGameAttackPlan.SIEGE_TOP,LateGameDefenseResponse.GIVE_STRUCTURE,new ZeroRandom());assertThat(r.attackerStructure()).isTrue();assertThat(f.state.getMapState().getLaneState(TeamSide.RED,Lane.TOP).destroyedTowerCount()).isOne();assertThat(f.state.getStructureActionExecutionStats().snapshot().structureMutationPerformed()).isOne();}
 @Test void defendAttackerWinAndDefenderWinAreDeterministic(){Fixture a=fixture();a.state.getBlueTeamState().addGold(100000);var won=resolve(a,TeamSide.BLUE,LateGameAttackPlan.SIEGE_MID,LateGameDefenseResponse.DEFEND,new SequenceRandom(0,.5,0,0,0,0,0,0,0,0));assertThat(won.fightWinner()).isEqualTo(TeamSide.BLUE);assertThat(won.attackerStructure()).isTrue();Fixture d=fixture();d.state.getRedTeamState().addGold(100000);var lost=resolve(d,TeamSide.BLUE,LateGameAttackPlan.SIEGE_MID,LateGameDefenseResponse.DEFEND,new ZeroRandom());assertThat(lost.fightWinner()).isEqualTo(TeamSide.RED);assertThat(lost.attackerStructure()).isFalse();assertThat(d.state.wasStructureActionAttemptedThisTick(TeamSide.BLUE)).isTrue();}
 @Test void crossMapAllowsAtMostOneActionPerSide(){Fixture f=fixture();var r=resolve(f,TeamSide.BLUE,LateGameAttackPlan.SIEGE_TOP,LateGameDefenseResponse.CROSS_MAP_PUSH,new ZeroRandom());assertThat(r.attackerStructure()).isTrue();assertThat(r.defenderStructure()).isTrue();var x=f.state.getStructureActionExecutionStats().snapshot();assertThat(x.structureAttempted()).isEqualTo(2);assertThat(x.structureMutationPerformed()).isEqualTo(2);}
 @Test void nexusFinishDestroysExactlyOneTurret(){Fixture f=nexus(2);var r=resolve(f,TeamSide.BLUE,LateGameAttackPlan.NEXUS_FINISH,LateGameDefenseResponse.GIVE_STRUCTURE,new ZeroRandom());assertThat(r.result()).isEqualTo(LateGameActionResult.NEXUS_FINISH_ADVANCED);assertThat(f.state.getMapState().getBaseState(TeamSide.RED).getNexusTurretsRemaining()).isOne();assertThat(f.state.isFinished()).isFalse();}
 @Test void nexusFinishDestroysNexusAndGameEnds(){Fixture f=nexus(0);var r=resolve(f,TeamSide.BLUE,LateGameAttackPlan.NEXUS_FINISH,LateGameDefenseResponse.GIVE_STRUCTURE,new ZeroRandom());assertThat(r.result()).isEqualTo(LateGameActionResult.NEXUS_DESTROYED);assertThat(f.state.isFinished()).isTrue();assertThat(f.state.getEndReason()).isEqualTo(GameEndReason.NEXUS_DESTROYED);}
 @Test void seed7OrdersLaningMidGameLateGamePhaseEvents(){com.lolfm.factory.DummyDataFactory f=new com.lolfm.factory.DummyDataFactory();MatchSimulator s=new MatchSimulator(new TeamfightResolver(),new EndGameEvaluator(),new SnapshotFactory(),new ObjectiveResolver(),new PostFightResolver(),new ObjectiveAttemptResolver(),new StructureResolver(),new PushResolver(),SimulationOptions.productionDefaults());var phases=s.simulate(f.createBlueTeam(),f.createRedTeam(),7L).getEvents().stream().filter(e->e.getType()==MatchEventType.MATCH_PHASE_CHANGE).map(e->e.getMatchPhaseChange().newPhase()).toList();assertThat(phases).containsExactly(MatchPhase.MID_GAME,MatchPhase.LATE_GAME);}
 private LateGameMacroResolver.Resolution resolve(Fixture f,TeamSide a,LateGameAttackPlan p,LateGameDefenseResponse d,Random r){return late.resolveSelected(f.state,f.blue,f.red,r,new ArrayList<>(),structures,fights,a,p,d);}
 private Fixture nexus(int n){Fixture f=fixture();LateGameTestSupport.destroyThroughInhibitorTower(f.state,TeamSide.RED,Lane.MID);f.state.getMapState().getLaneState(TeamSide.RED,Lane.MID).destroyInhibitor(0);while(f.state.getMapState().getBaseState(TeamSide.RED).getNexusTurretsRemaining()>n)f.state.getMapState().getBaseState(TeamSide.RED).destroyOneNexusTurret();return f;}
 private Fixture fixture(){Team b=team("BLUE"),r=team("RED");GameState g=new GameState(state(b),state(r),true,true,true,true,true,true);g.advanceTimeSeconds(1800);return new Fixture(b,r,g);}
 private Team team(String n){List<Player>p=new ArrayList<>();for(Position x:Position.values())p.add(new Player(n+"-"+x,x,new PlayerAttributes(14,14,14,14)));return new Team(n,p);}
 private TeamState state(Team t){return new TeamState(t.getName(),t.getPlayers().stream().map(p->new PlayerState(p.getName(),p.getPosition(),p.getAttributes(),500)).toList());}
 private record Fixture(Team blue,Team red,GameState state){}private static final class ZeroRandom extends Random{@Override public double nextDouble(){return 0;}@Override public boolean nextBoolean(){return false;}@Override public int nextInt(int b){return 0;}}private static final class SequenceRandom extends Random{private final double[]values;private int index;private SequenceRandom(double...values){this.values=values;}@Override public double nextDouble(){return index<values.length?values[index++]:0;}@Override public boolean nextBoolean(){return nextDouble()<.5;}@Override public int nextInt(int bound){return 0;}}
}
