package com.lolfm.simulator;
import static org.junit.jupiter.api.Assertions.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.lolfm.domain.*;
import java.util.List;
import org.junit.jupiter.api.Test;
class ObjectivePrioritySnapshotTest {
 private static final double D=1e-6; private final SnapshotFactory snapshots=new SnapshotFactory(); private final ObjectivePriorityResolver priority=new ObjectivePriorityResolver();
 @Test void snapshotContainsExactDragonAndBaronPriorityFields(){GameState s=state(true);s.laneState(Lane.TOP).setPressure(-20);s.laneState(Lane.MID).setPressure(40);s.laneState(Lane.BOT).setPressure(20);priority.applyLaneCombatKill(s,100,Lane.MID,TeamSide.BLUE);var p=snapshots.create(s).getObjectivePriority();assertTrue(p.enabled());assertEquals(29,p.dragonLanePressureScore(),D);assertEquals(7,p.baronLanePressureScore(),D);assertEquals(6.4,p.dragonRecentControl(),D);assertEquals(6.4,p.baronRecentControl(),D);assertEquals(35.4,p.dragonSignedPriority(),D);assertEquals(13.4,p.baronSignedPriority(),D);assertEquals(100,p.blueDragonPriority()+p.redDragonPriority(),D);assertEquals(100,p.blueBaronPriority()+p.redBaronPriority(),D);}
 @Test void snapshotSignedPriorityAndDisplayPriorityClamp(){GameState s=state(true);s.laneState(Lane.TOP).setPressure(100);s.laneState(Lane.MID).setPressure(100);s.laneState(Lane.BOT).setPressure(100);for(int i=0;i<5;i++){priority.applyJungleGankKill(s,i,Lane.BOT,TeamSide.BLUE);priority.applyJungleGankKill(s,i,Lane.TOP,TeamSide.BLUE);}var p=snapshots.create(s).getObjectivePriority();assertEquals(100,p.dragonSignedPriority(),D);assertEquals(100,p.baronSignedPriority(),D);assertEquals(100,p.blueDragonPriority(),D);assertEquals(0,p.redDragonPriority(),D);}
 @Test void pastSnapshotIsImmutableAndCreationDoesNotDecayOrMutateState(){GameState s=state(true);priority.applyJungleGankKill(s,0,Lane.BOT,TeamSide.BLUE);var before=snapshots.create(s);int decay=s.getObjectivePriorityState().getLastDecayAppliedAtSeconds();s.laneState(Lane.BOT).setPressure(-100);priority.applyRoamKill(s,1,Lane.BOT,TeamSide.RED);assertEquals(10,before.getObjectivePriority().dragonRecentControl(),D);assertEquals(10,before.getObjectivePriority().dragonSignedPriority(),D);assertEquals(decay,s.getObjectivePriorityState().getLastDecayAppliedAtSeconds());}
 @Test void offSnapshotIsNeutralWithoutChangingUnderlyingLanePressure(){GameState s=state(false);s.laneState(Lane.MID).setPressure(80);s.laneState(Lane.BOT).setPressure(60);var p=snapshots.create(s).getObjectivePriority();assertFalse(p.enabled());assertEquals(0,p.dragonLanePressureScore(),D);assertEquals(0,p.dragonRecentControl(),D);assertEquals(0,p.dragonSignedPriority(),D);assertEquals(50,p.blueDragonPriority(),D);assertEquals(50,p.redDragonPriority(),D);assertEquals(80,s.laneState(Lane.MID).getPressure(),D);}
 @Test void jsonApiShapeIsAdditiveAndKeepsExistingSnapshotFields()throws Exception{String json=new ObjectMapper().writeValueAsString(snapshots.create(state(true)));assertTrue(json.contains("\"timeSeconds\""));assertTrue(json.contains("\"blueKills\""));assertTrue(json.contains("\"laneSnapshots\""));assertTrue(json.contains("\"objectivePriority\""));assertTrue(json.contains("\"dragonSignedPriority\""));assertTrue(json.contains("\"baronSignedPriority\""));}
 @Test void objectiveEventDecisionDataIsNullableAndAdditive(){MatchEvent ordinary=new MatchEvent(0,MatchEventType.GAME_START,"start",null,null,List.of());assertNull(ordinary.getObjectivePriorityDecision());GameState s=state(true);s.advanceTimeSeconds(300);s.getObjectiveState().updateSpawnState(300);s.advanceTimeSeconds(40);var dragon=new ObjectiveAttemptResolver().maybeAttemptObjective(s,new ZeroRandom(),new ObjectiveResolver()).orElseThrow();assertNotNull(dragon.getObjectivePriorityDecision());assertEquals(ObjectiveType.DRAGON,dragon.getObjectivePriorityDecision().objectiveType());}
 private GameState state(boolean e){return new GameState(team("BLUE"),team("RED"),true,e);}private TeamState team(String n){return new TeamState(n,List.of(p(n+"t",Position.TOP),p(n+"j",Position.JUNGLE),p(n+"m",Position.MID),p(n+"a",Position.ADC),p(n+"s",Position.SUPPORT)));}private PlayerState p(String n,Position pos){return new PlayerState(n,pos,new PlayerAttributes(14,14,14,14),500);}private static final class ZeroRandom extends java.util.Random{@Override public double nextDouble(){return 0;}@Override public boolean nextBoolean(){return false;}}
}
