package com.lolfm.simulator;

import com.lolfm.domain.*;
import java.util.*;

/** Large distribution diagnostics. Intentionally excluded from the normal test task. */
public final class ObjectivePriorityDiagnostics {
    private static final int FULL_SEEDS=1000, MIRROR_SEEDS=500;
    private static final List<Integer> TIMES=List.of(600,840,1200,1500);

    public static void main(String[] args){
        List<Scenario> base=scenarios(); Map<String,Report> reports=new LinkedHashMap<>();
        for(Scenario s:base){audit(s);runPair(s,FULL_SEEDS,reports);}
        for(Scenario s:base){if(s.key.equals("A"))continue;Scenario m=s.mirror();audit(m);runPair(m,MIRROR_SEEDS,reports);}
        for(Scenario s:base){printDelta(s.key,reports);if(!s.key.equals("A"))printDelta(s.key+"_MIRROR",reports);}
    }
    private static void runPair(Scenario s,int seeds,Map<String,Report> reports){for(boolean enabled:List.of(true,false)){Report r=run(s,seeds,enabled);reports.put(s.key+":"+enabled,r);System.out.println(r.line());}}
    private static Report run(Scenario scenario,int seeds,boolean enabled){
        Report report=new Report(scenario.key,enabled,seeds);
        SimulationOptions options=SimulationOptions.productionDefaults().withObjectivePriorityEnabled(enabled);
        MatchSimulator simulator=simulator(options);
        for(long seed=1;seed<=seeds;seed++)report.add(simulator.simulateWithDiagnostics(scenario.team(TeamSide.BLUE),scenario.team(TeamSide.RED),seed));
        report.replayMismatch=signature(simulator.simulate(scenario.team(TeamSide.BLUE),scenario.team(TeamSide.RED),1))
                .equals(signature(simulator.simulate(scenario.team(TeamSide.BLUE),scenario.team(TeamSide.RED),1)))?0:1;
        MatchTimeline diagnosticOn=simulator(SimulationOptions.productionDefaults().withObjectivePriorityEnabled(enabled).withDiagnosticsEnabled(true)).simulate(scenario.team(TeamSide.BLUE),scenario.team(TeamSide.RED),2);
        MatchTimeline diagnosticOff=simulator(SimulationOptions.productionDefaults().withObjectivePriorityEnabled(enabled).withDiagnosticsEnabled(false)).simulate(scenario.team(TeamSide.BLUE),scenario.team(TeamSide.RED),2);
        report.diagnosticsMismatch=signature(diagnosticOn).equals(signature(diagnosticOff))?0:1;
        return report;
    }
    private static MatchSimulator simulator(SimulationOptions o){return new MatchSimulator(new TeamfightResolver(),new EndGameEvaluator(),new SnapshotFactory(),new ObjectiveResolver(),new PostFightResolver(),new ObjectiveAttemptResolver(),new StructureResolver(),new PushResolver(),o);}
    private static String signature(MatchTimeline t){StringBuilder b=new StringBuilder().append(t.getDurationSeconds()).append('|');for(MatchEvent e:t.getEvents())b.append(e.getTimeSeconds()).append(':').append(e.getType()).append(':').append(e.getCombatSource()).append(':').append(e.getKiller()).append(':').append(e.getVictim()).append(':').append(e.getObjectivePriorityDecision()).append(';');for(MatchSnapshot s:t.getSnapshots())b.append(s.getTimeSeconds()).append(':').append(s.getBlueKills()).append(':').append(s.getRedKills()).append(':').append(s.getBlueGold()).append(':').append(s.getRedGold()).append(':').append(s.getObjectivePriority()).append(';');return b.toString();}

    private static void audit(Scenario s){Team b1=s.team(TeamSide.BLUE),b2=s.team(TeamSide.BLUE),r=s.team(TeamSide.RED);if(b1==b2||b1==r)throw new IllegalStateException("shared Team fixture "+s.key);for(Position pos:Position.values()){Player x=find(b1,pos),y=find(b2,pos);if(x.getAttributes()==y.getAttributes())throw new IllegalStateException("shared attributes "+s.key+" "+pos);}System.out.println("AUDIT key="+s.key+" blue="+profileLine(s.blue)+" red="+profileLine(s.red)+" freshTeams=true freshAttributes=true mirror="+s.key.endsWith("_MIRROR"));}
    private static Player find(Team t,Position p){return t.getPlayers().stream().filter(x->x.getPosition()==p).findFirst().orElseThrow();}
    private static String profileLine(Map<Position,Profile> ps){StringJoiner j=new StringJoiner(",");for(Position p:Position.values())j.add(p+"="+ps.get(p));return j.toString();}
    private static void printDelta(String key,Map<String,Report> rs){Report on=rs.get(key+":true"),off=rs.get(key+":false");System.out.println("DELTA key="+key+" dragonAttempts="+(on.dragonAttempts-off.dragonAttempts)+" baronAttempts="+(on.baronAttempts-off.baronAttempts)+" dragonBlueSelected="+(on.dragonBlueSelected-off.dragonBlueSelected)+" baronBlueSelected="+(on.baronBlueSelected-off.baronBlueSelected)+" soul="+(on.souls-off.souls)+" elder="+(on.elderCaptures-off.elderCaptures)+" kills="+(on.kills-off.kills)+" blueWins="+(on.blueWins-off.blueWins)+" avgDuration="+f(on.avgDuration()-off.avgDuration()));}

    private static List<Scenario> scenarios(){
        Map<Position,Profile> eq=all(Profile.equal());List<Scenario> s=new ArrayList<>();s.add(new Scenario("A",eq,eq));
        s.add(scenario("B",List.of(Position.MID,Position.ADC,Position.SUPPORT),Profile.laneStrong(),Profile.laneWeak()));
        s.add(scenario("C",List.of(Position.TOP,Position.MID),Profile.laneStrong(),Profile.laneWeak()));
        s.add(scenario("D",List.of(Position.JUNGLE,Position.MID,Position.ADC,Position.SUPPORT),Profile.actionStrong(),Profile.actionWeak()));
        s.add(scenario("E",List.of(Position.JUNGLE,Position.TOP,Position.MID),Profile.actionStrong(),Profile.actionWeak()));
        s.add(scenario("F",List.of(Position.MID,Position.ADC,Position.SUPPORT),Profile.farmingStrong(),Profile.farmingWeak()));
        s.add(new Scenario("G",all(Profile.teamfightStrong()),all(Profile.teamfightWeak())));return s;
    }
    private static Scenario scenario(String k,List<Position> positions,Profile blue,Profile red){Map<Position,Profile>b=all(Profile.equal()),r=all(Profile.equal());positions.forEach(p->{b.put(p,blue);r.put(p,red);});return new Scenario(k,b,r);}
    private static EnumMap<Position,Profile> all(Profile p){EnumMap<Position,Profile> m=new EnumMap<>(Position.class);for(Position x:Position.values())m.put(x,p);return m;}
    private record Profile(int mechanics,int aggression,int farming,int teamfighting){static Profile equal(){return new Profile(14,14,14,14);}static Profile laneStrong(){return new Profile(18,14,18,14);}static Profile laneWeak(){return new Profile(10,14,10,14);}static Profile actionStrong(){return new Profile(18,18,14,18);}static Profile actionWeak(){return new Profile(10,10,14,10);}static Profile farmingStrong(){return new Profile(14,14,18,14);}static Profile farmingWeak(){return new Profile(14,14,10,14);}static Profile teamfightStrong(){return new Profile(14,14,14,18);}static Profile teamfightWeak(){return new Profile(14,14,14,10);}public String toString(){return mechanics+"/"+aggression+"/"+farming+"/"+teamfighting;}}
    private record Scenario(String key,Map<Position,Profile> blue,Map<Position,Profile> red){Scenario mirror(){return new Scenario(key+"_MIRROR",new EnumMap<>(red),new EnumMap<>(blue));}Team team(TeamSide side){Map<Position,Profile> map=side==TeamSide.BLUE?blue:red;List<Player> players=new ArrayList<>();for(Position pos:Position.values()){Profile p=map.get(pos);players.add(new Player(key+"_"+side+"_"+pos,pos,new PlayerAttributes(p.mechanics,p.aggression,p.farming,p.teamfighting)));}return new Team(key+"_"+side,players);}}

    private static final class Report{
        final String key;final boolean enabled;final int games;final Map<Integer,PrioritySum> time=new LinkedHashMap<>();final PrioritySum end=new PrioritySum();final EnumMap<CombatSource,Long> sources=new EnumMap<>(CombatSource.class);final EnumMap<Lane,Long> lanes=new EnumMap<>(Lane.class);final EnumMap<TeamSide,Long>sides=new EnumMap<>(TeamSide.class);final EnumMap<ObjectiveType,AttemptSum> attempts=new EnumMap<>(ObjectiveType.class);final Map<String,Bucket> dragonBuckets=buckets(),baronBuckets=buckets();final List<Integer> durations=new ArrayList<>();
        long decayCalls,decaySeconds,dragonZero,baronZero,impacts,duplicates,noKill,disabledIgnored,dragonClamp,baronClamp,zeroDragon,zeroBaron;double dragonImpact,baronImpact;long dragonAttempts,dragonCaptures,postDragon,baronAttempts,baronCaptures,postBaron,elderAttempts,elderCaptures,dragonBlueSelected,baronBlueSelected,souls,soulTime,kills,totalGold,blueWins,redWins,timeouts,majorDup,objectiveDup,supportCsErrors,postFightPriorityErrors,elderPriorityErrors,offMutation,offBonus,offMultiplier,replayMismatch,diagnosticsMismatch;
        Report(String k,boolean e,int g){key=k;enabled=e;games=g;for(int t:TIMES)time.put(t,new PrioritySum());for(CombatSource x:CombatSource.values())sources.put(x,0L);for(Lane x:Lane.values())lanes.put(x,0L);for(TeamSide x:TeamSide.values())sides.put(x,0L);for(ObjectiveType x:ObjectiveType.values())attempts.put(x,new AttemptSum());}
        void add(MatchSimulator.SimulationResult r){MatchTimeline t=r.timeline();durations.add(t.getDurationSeconds());if(r.winnerSide()==TeamSide.BLUE)blueWins++;if(r.winnerSide()==TeamSide.RED)redWins++;if(r.endReason()==GameEndReason.SIMULATION_TIMEOUT)timeouts++;for(int target:TIMES)time.get(target).add(snapshotAt(t,target));for(MatchSnapshot sample:t.getSnapshots()){dragonBuckets.get(bucket(sample.getObjectivePriority().dragonSignedPriority())).snapshots++;baronBuckets.get(bucket(sample.getObjectivePriority().baronSignedPriority())).snapshots++;}MatchSnapshot last=t.getSnapshots().getLast();end.add(last);kills+=last.getBlueKills()+last.getRedKills();totalGold+=last.getBlueGold()+last.getRedGold();for(PlayerSnapshot p:last.getPlayerSnapshots())if(p.getPosition()==Position.SUPPORT&&p.getCs()!=0)supportCsErrors++;
            var st=r.objectivePriorityExecutionStats();decayCalls+=st.decayCalls();decaySeconds+=st.decayAppliedSeconds();dragonZero+=st.decayReturnedDragonToZero();baronZero+=st.decayReturnedBaronToZero();impacts+=st.impactsApplied();duplicates+=st.duplicateImpactsRejected();noKill+=st.noKillImpactsRejected();disabledIgnored+=st.disabledImpactsIgnored();dragonClamp+=st.dragonClampCount();baronClamp+=st.baronClampCount();dragonImpact+=st.dragonAppliedImpactTotal();baronImpact+=st.baronAppliedImpactTotal();zeroDragon+=st.zeroDragonMultiplierCount();zeroBaron+=st.zeroBaronMultiplierCount();st.impactsBySource().forEach((k,v)->sources.merge(k,v,Long::sum));st.impactsByLane().forEach((k,v)->lanes.merge(k,v,Long::sum));st.impactsBySide().forEach((k,v)->sides.merge(k,v,Long::sum));st.attempts().forEach((k,v)->attempts.get(k).add(v));postFightPriorityErrors+=st.priorityAppliedToPostFightError();elderPriorityErrors+=st.priorityAppliedToElderError();offBonus+=st.disabledBonusApplication();offMultiplier+=st.disabledMultiplierApplication();
            for(var d:st.decisions()){Bucket b=(d.objectiveType()==ObjectiveType.DRAGON?dragonBuckets:baronBuckets).get(bucket(d.signedPriority()));if(d.objectiveType()!=ObjectiveType.ELDER){b.evaluations++;if(d.attemptRollSucceeded())b.success++;if(d.selectedSide()==TeamSide.BLUE)b.blueSelected++;if(d.selectedSide()==TeamSide.RED)b.redSelected++;}}
            for(DragonCaptureRecord d:r.dragonCaptures()){if(d.source()==DragonCaptureSource.GENERAL)dragonCaptures++;else postDragon++;Bucket b=dragonBuckets.get(bucket(snapshotAt(t,d.captureTimeSeconds()).getObjectivePriority().dragonSignedPriority()));if(d.capturingSide()==TeamSide.BLUE)b.blueCapture++;else b.redCapture++;}
            if(r.soulOwner()!=null){souls++;soulTime+=r.soulClaimedAtSeconds();}
            Map<Integer,Integer> combatAt=new HashMap<>(),objectiveAt=new HashMap<>();for(MatchEvent e:t.getEvents()){if(Set.of(MatchEventType.JUNGLE_GANK,MatchEventType.COUNTER_GANK,MatchEventType.ROAM,MatchEventType.LANE_COMBAT,MatchEventType.TEAMFIGHT).contains(e.getType()))combatAt.merge(e.getTimeSeconds(),1,Integer::sum);if(Set.of(MatchEventType.DRAGON,MatchEventType.BARON,MatchEventType.ELDER).contains(e.getType()))objectiveAt.merge(e.getTimeSeconds(),1,Integer::sum);var d=e.getObjectivePriorityDecision();if(d==null)continue;if(d.objectiveType()==ObjectiveType.DRAGON&&d.generalAttempt()){dragonAttempts++;if(d.selectedSide()==TeamSide.BLUE)dragonBlueSelected++;}if(d.objectiveType()==ObjectiveType.BARON){if(d.generalAttempt()){baronAttempts++;baronCaptures++;if(d.selectedSide()==TeamSide.BLUE)baronBlueSelected++;}else postBaron++;}if(d.objectiveType()==ObjectiveType.ELDER){if(d.generalAttempt())elderAttempts++;elderCaptures++;}}
            majorDup+=combatAt.values().stream().filter(v->v>1).count();objectiveDup+=objectiveAt.values().stream().filter(v->v>1).count();if(!enabled&&(st.impactsApplied()!=0||last.getObjectivePriority().dragonRecentControl()!=0||last.getObjectivePriority().baronRecentControl()!=0))offMutation++;
        }
        String line(){return "REPORT key="+key+" mode="+(enabled?"ON":"OFF")+" seeds="+games+" snapshots="+time+" end="+end.avg(games)+" impacts={source="+sources+",lane="+lanes+",side="+sides+",dragonTotal="+f(dragonImpact)+",baronTotal="+f(baronImpact)+",dup="+duplicates+",noKill="+noKill+",disabled="+disabledIgnored+",clamp="+dragonClamp+"/"+baronClamp+",decay="+decayCalls+"/"+decaySeconds+",zero="+dragonZero+"/"+baronZero+",zeroMultiplier="+zeroDragon+"/"+zeroBaron+"} attempts="+attempts+" buckets={dragon="+dragonBuckets+",baron="+baronBuckets+"} objectives={generalDragon="+attempts.get(ObjectiveType.DRAGON).roll+"/"+dragonCaptures+",postDragon="+postDragon+",generalBaron="+attempts.get(ObjectiveType.BARON).roll+"/"+baronCaptures+",postBaron="+postBaron+",elder="+attempts.get(ObjectiveType.ELDER).roll+"/"+elderCaptures+",soulRate="+pct(souls,games)+",avgSoul="+(souls==0?0:soulTime/souls)+"} result={blueWin="+pct(blueWins,games)+",redWin="+pct(redWins,games)+",avg="+f(avgDuration())+",median="+percentile(.5)+",p90="+percentile(.9)+",p95="+percentile(.95)+",40m="+durations.stream().filter(x->x>=2400).count()+",60m="+durations.stream().filter(x->x>=3600).count()+",timeout="+timeouts+",kills="+kills+",gold="+totalGold+"} integrity={majorDup="+majorDup+",objectiveDup="+objectiveDup+",supportCs="+supportCsErrors+",postPriority="+postFightPriorityErrors+",elderPriority="+elderPriorityErrors+",offMutation="+offMutation+",offBonus="+offBonus+",offMultiplier="+offMultiplier+",replay="+replayMismatch+",diagnostics="+diagnosticsMismatch+"}";}
        double avgDuration(){return durations.stream().mapToInt(i->i).average().orElse(0);}int percentile(double p){List<Integer>x=new ArrayList<>(durations);Collections.sort(x);return x.get(Math.min(x.size()-1,(int)Math.ceil(p*x.size())-1));}
    }
    private static MatchSnapshot snapshotAt(MatchTimeline t,int time){MatchSnapshot found=t.getSnapshots().getFirst();for(MatchSnapshot s:t.getSnapshots()){if(s.getTimeSeconds()>time)break;found=s;}return found;}
    private static final class PrioritySum{double dl,dr,ds,bl,br,bs;long n;void add(MatchSnapshot s){var p=s.getObjectivePriority();dl+=p.dragonLanePressureScore();dr+=p.dragonRecentControl();ds+=p.dragonSignedPriority();bl+=p.baronLanePressureScore();br+=p.baronRecentControl();bs+=p.baronSignedPriority();n++;}String avg(long ignored){return "D("+f(dl/n)+","+f(dr/n)+","+f(ds/n)+") B("+f(bl/n)+","+f(br/n)+","+f(bs/n)+")";}public String toString(){return avg(n);}}
    private static final class AttemptSum{long eval,roll,success,fail,bOnly,rOnly,both,neither,weighted,blue,red;double base,bonus,fin,bw,rw,alive,gold,kills,big,ace,bm,rm,fb,fr;void add(ObjectivePriorityExecutionStatsSnapshot.ObjectiveAttemptStatsSnapshot s){eval+=s.evaluations();roll+=s.attemptRolls();success+=s.attemptSuccesses();fail+=s.attemptFailures();bOnly+=s.blueOnlyEligible();rOnly+=s.redOnlyEligible();both+=s.bothEligible();neither+=s.neitherEligible();weighted+=s.weightedSelectionRolls();blue+=s.blueSelected();red+=s.redSelected();base+=s.baseChanceTotal();bonus+=s.priorityBonusTotal();fin+=s.finalChanceTotal();bw+=s.existingBlueWeightTotal();rw+=s.existingRedWeightTotal();alive+=s.aliveContributionTotal();gold+=s.goldContributionTotal();kills+=s.killContributionTotal();big+=s.recentBigWinContributionTotal();ace+=s.recentAceContributionTotal();bm+=s.blueMultiplierTotal();rm+=s.redMultiplierTotal();fb+=s.finalBlueWeightTotal();fr+=s.finalRedWeightTotal();}public String toString(){return "eval="+eval+",roll="+roll+",ok="+success+",fail="+fail+",elig="+bOnly+"/"+rOnly+"/"+both+"/"+neither+",sel="+weighted+"/"+blue+"/"+red+",chance="+avg(base,eval)+"+"+avg(bonus,eval)+"="+avg(fin,eval)+",weight="+avg(bw,Math.max(1,success))+"/"+avg(rw,Math.max(1,success))+",parts="+avg(alive,Math.max(1,success))+"/"+avg(gold,Math.max(1,success))+"/"+avg(kills,Math.max(1,success))+"/"+avg(big,Math.max(1,success))+"/"+avg(ace,Math.max(1,success))+",mult="+avg(bm,Math.max(1,success))+"/"+avg(rm,Math.max(1,success))+",final="+avg(fb,Math.max(1,success))+"/"+avg(fr,Math.max(1,success));}}
    private static final class Bucket{long snapshots,evaluations,success,blueSelected,redSelected,blueCapture,redCapture;public String toString(){return snapshots+"/"+evaluations+"/"+success+"/"+blueSelected+"/"+redSelected+"/"+blueCapture+"/"+redCapture;}}
    private static Map<String,Bucket>buckets(){Map<String,Bucket>m=new LinkedHashMap<>();for(String k:List.of("-100~-61","-60~-21","-20~20","21~60","61~100"))m.put(k,new Bucket());return m;}
    private static String bucket(double v){return v<=-61?"-100~-61":v<=-21?"-60~-21":v<=20?"-20~20":v<=60?"21~60":"61~100";}
    private static String f(double v){return String.format(Locale.ROOT,"%.3f",v);}private static String avg(double v,long n){return f(n==0?0:v/n);}private static String pct(long n,long d){return f(d==0?0:n*100.0/d)+"%";}
}
