package com.lolfm.simulator;

import com.lolfm.champion.ChampionRoleMatchupProfileCatalog;
import com.lolfm.champion.MatchChampionAssignments;
import com.lolfm.composition.*;
import com.lolfm.domain.Position;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

/** One-shot Phase 13D final blind validation and production closure diagnostic. */
public final class Phase13DFinalization {
    static final Path OUT=Path.of("build/reports/phase-13d-finalization");
    static final Path PRIOR=Path.of("build/reports/composition-key-specific-fresh-holdout-gameplay/composition-fresh-holdout-schedule.csv");
    static final int LINEUPS=160,PAIRS=600,CASES=1200,REPLAYS=120,ROLLBACK=100,PRODUCTION_REPLAYS=100;
    static final String ROLE="COMPLETELY_FRESH_BLIND_PHASE_13D_FINAL_HOLDOUT";
    static final String GUARDRAIL="phase-13d-finalization-gameplay-sanity-guardrail-v1";
    static final Map<Path,String>SOURCES=Map.of(
            Path.of("build/reports/composition-key-specific-fresh-holdout-gameplay/composition-key-specific-fresh-holdout-summary.csv"),"52a3ed6cf146c95a93e21e41f08366fa8097fde4c70c3a44b5b4155a7299f20a",
            Path.of("build/reports/composition-key-specific-fresh-holdout-gameplay/composition-key-specific-fresh-holdout-audit.log"),"823a46ed488aae74e3f7b1852d465584aa5993e6aa6ab1f4143978259b178e6b",
            Path.of("build/reports/composition-fresh-holdout-integrity-and-plausibility-attribution/composition-fresh-holdout-attribution-summary.csv"),"7e5a8bdb1b3929b655174f5dbd687390511e532abf9ddd174409a99dd956860e",
            Path.of("build/reports/composition-fresh-holdout-integrity-and-plausibility-attribution/composition-fresh-holdout-attribution-audit.log"),"e3a739de9c584079922decbdcfd31494b2996438ad3458983d6120d1c964cc57",
            Path.of("build/reports/composition-decision-time-provenance-capture/composition-decision-time-provenance-summary.csv"),"bd1a8de72183ec9be14fa6eca0c08aaa95fae42756236f06c40b88802fb783a2",
            Path.of("build/reports/composition-decision-time-provenance-capture/composition-decision-time-provenance-audit.log"),"c77af827be80b24d906d7e0023a6a4a2766cd0229222efc38fd72c5b9f0a2aa6");
    static final List<TeamCompositionContext>CONTEXTS=List.of(TeamCompositionContext.TEAMFIGHT,TeamCompositionContext.SIEGE,TeamCompositionContext.BASE_DEFENSE);
    private Phase13DFinalization(){}

    public static void main(String[]args)throws Exception{
        boolean finalize=args.length>0&&args[0].equals("finalize");
        if(finalize){ActivationResult a=activateProduction();System.out.println("Phase 13D finalization: "+a.verdict());if(a.integrityErrors()!=0)throw new IllegalStateException(a.verdict());return;}
        Result r=run(false);System.out.println("Phase 13D finalization: "+r.verdict());if(r.integrityErrors()!=0||!r.validationPassed())throw new IllegalStateException(r.verdict());
    }

    static ActivationResult activateProduction()throws Exception{
        verifySources();FrozenCompositionKeySpecificChannelCandidate.verifyIdentity(FrozenCompositionKeySpecificChannelCandidate.VERSION,FrozenCompositionKeySpecificChannelCandidate.HASH);FrozenCompositionProductionCandidate.verifyExact();
        Prepared p=prepare();List<Map<String,String>>frozenRows=CompositionDecisionTimeProvenanceCapture.read(OUT.resolve("phase-13d-final-holdout-schedule.csv"));
        int scheduleMismatch=frozenRows.size()==p.schedule().size()?0:1;
        Map<String,CompositionFreshHoldoutCandidateGameplayAudit.Lineup>lineups=p.pool().stream().collect(Collectors.toMap(CompositionFreshHoldoutCandidateGameplayAudit.Lineup::id,Function.identity()));
        int parityMismatch=0,replayMismatch=0,rollbackMismatch=0;
        for(var row:p.schedule().subList(0,PRODUCTION_REPLAYS)){
            MatchChampionAssignments a=CompositionAuditOnlySemanticsRuntime.assignments(lineups.get(row.blueLineupId()),lineups.get(row.redLineupId()));
            var validated=CompositionAuditOnlySemanticsRuntime.simulate(simulator(TeamCompositionGameplayMode.SHADOW,row.caseIndex(),true),row,a);
            var production=CompositionAuditOnlySemanticsRuntime.simulate(productionSimulator(),row,a);
            var productionReplay=CompositionAuditOnlySemanticsRuntime.simulate(productionSimulator(),row,a);
            var off=CompositionAuditOnlySemanticsRuntime.simulate(simulator(TeamCompositionGameplayMode.OFF,-1,false),row,a);
            var offReplay=CompositionAuditOnlySemanticsRuntime.simulate(simulator(TeamCompositionGameplayMode.OFF,-1,false),row,a);
            if(!exact(production,validated))parityMismatch++;
            if(!exact(production,productionReplay))replayMismatch++;
            if(!exact(off,offReplay))rollbackMismatch++;
        }
        int integrity=scheduleMismatch+parityMismatch+replayMismatch+rollbackMismatch;
        String verdict=integrity==0?"PHASE_13D_TEAM_COMPOSITION_COMPLETE":"BLOCKED_BY_PHASE_13D_PRODUCTION_ACTIVATION";
        ActivationResult result=new ActivationResult(parityMismatch,replayMismatch,rollbackMismatch,integrity,verdict);
        writeActivationClosure(result);return result;
    }

    static void writeActivationClosure(ActivationResult r)throws Exception{
        csv("phase-13d-production-activation.csv",List.of(
                List.of("field","value"),
                List.of("candidateVersion",FrozenCompositionProductionCandidate.VERSION),
                List.of("candidateHash",FrozenCompositionProductionCandidate.HASH),
                List.of("productionDefaultMode",SimulationOptions.productionDefaults().teamCompositionGameplayMode().name()),
                List.of("productionEnabled",String.valueOf(r.integrityErrors()==0)),
                List.of("productionV2ParitySampleCount",s(PRODUCTION_REPLAYS)),
                List.of("productionV2ParityMismatchCount",s(r.parityMismatch())),
                List.of("productionReplaySampleCount",s(PRODUCTION_REPLAYS)),
                List.of("productionReplayMismatchCount",s(r.replayMismatch())),
                List.of("offRollbackSampleCount",s(ROLLBACK)),
                List.of("offRollbackMismatchCount",s(r.rollbackMismatch())),
                List.of("integrityErrorCount",s(r.integrityErrors())),
                List.of("apiSchemaChanged","false"),List.of("frontendChanged","false")));
        LinkedHashMap<String,String>summary=fieldValues(OUT.resolve("phase-13d-final-summary.csv"));
        summary.put("productionDefaultMode",SimulationOptions.productionDefaults().teamCompositionGameplayMode().name());
        summary.put("productionEnabled",String.valueOf(r.integrityErrors()==0));
        summary.put("productionV2ParitySampleCount",s(PRODUCTION_REPLAYS));
        summary.put("productionV2ParityMismatchCount",s(r.parityMismatch()));
        summary.put("productionReplaySampleCount",s(PRODUCTION_REPLAYS));
        summary.put("productionReplayMismatchCount",s(r.replayMismatch()));
        summary.put("offRollbackSampleCount",s(ROLLBACK));
        summary.put("offRollbackMismatchCount",s(r.rollbackMismatch()));
        summary.put("integrityErrorCount",s(r.integrityErrors()));
        summary.put("verdict",r.verdict());summary.put("phase13DComplete",String.valueOf(r.integrityErrors()==0));
        summary.put("productionEligible",String.valueOf(r.integrityErrors()==0));
        summary.put("nextPhase",r.integrityErrors()==0?"PHASE_13E_PLAYER_RATINGS_PROFICIENCY_AND_CHAMPION_EXPANSION":"PHASE_13D_PRODUCTION_ACTIVATION_PENDING");
        List<List<String>>summaryRows=new ArrayList<>();summaryRows.add(List.of("field","value"));summary.forEach((k,v)->summaryRows.add(List.of(k,v)));csv("phase-13d-final-summary.csv",summaryRows);
        StringBuilder audit=new StringBuilder();summary.forEach((k,v)->audit.append(k).append('=').append(v).append('\n'));Files.writeString(OUT.resolve("phase-13d-final-audit.log"),audit,StandardCharsets.UTF_8);
        LinkedHashMap<String,String>integrity=fieldValues(OUT.resolve("phase-13d-final-integrity.csv"));integrity.put("integrityErrorCount",s(r.integrityErrors()));
        List<List<String>>integrityRows=new ArrayList<>();integrityRows.add(List.of("metric","value"));integrity.forEach((k,v)->integrityRows.add(List.of(k,v)));csv("phase-13d-final-integrity.csv",integrityRows);
    }

    static LinkedHashMap<String,String>fieldValues(Path path)throws Exception{LinkedHashMap<String,String>out=new LinkedHashMap<>();for(var row:CompositionDecisionTimeProvenanceCapture.read(path)){String key=row.getOrDefault("field",row.get("metric"));out.put(key,row.get("value"));}return out;}

    static Result run(boolean finalize)throws Exception{
        verifySources();FrozenCompositionKeySpecificChannelCandidate.verifyIdentity(FrozenCompositionKeySpecificChannelCandidate.VERSION,FrozenCompositionKeySpecificChannelCandidate.HASH);FrozenCompositionProductionCandidate.verifyExact();
        Files.createDirectories(OUT);Prepared p=prepare();writeSchedule(p);String scheduleHash=sha256(OUT.resolve("phase-13d-final-holdout-schedule.csv"));
        var lineups=p.pool().stream().collect(Collectors.toMap(CompositionFreshHoldoutCandidateGameplayAudit.Lineup::id,Function.identity()));
        MatchSimulator off=simulator(TeamCompositionGameplayMode.OFF,-1,false);List<CompositionAuditOnlySemanticsRuntime.PairedGame>games=new ArrayList<>();List<CompositionWinnerDecisionProvenance>provenance=new ArrayList<>();List<FightGradeDecisionDiagnostic>grades=new ArrayList<>();List<BaseDefenseRoleRoutingDiagnostic>roles=new ArrayList<>();int replayMismatch=0,randomMismatch=0;
        for(var row:p.schedule()){MatchChampionAssignments a=CompositionAuditOnlySemanticsRuntime.assignments(lineups.get(row.blueLineupId()),lineups.get(row.redLineupId()));var o=CompositionAuditOnlySemanticsRuntime.simulate(off,row,a);var c=CompositionAuditOnlySemanticsRuntime.simulate(simulator(TeamCompositionGameplayMode.SHADOW,row.caseIndex(),true),row,a);games.add(CompositionAuditOnlySemanticsRuntime.pair(row,o,c));provenance.addAll(c.compositionRuntimeDiagnostics().winnerDecisionProvenance());grades.addAll(c.compositionRuntimeDiagnostics().fightGradeDiagnostics());roles.addAll(c.compositionRuntimeDiagnostics().baseDefenseRoleRoutings());if(games.getLast().preDivergenceRandomMismatch()!=0)randomMismatch++;if(row.auditIndex()%10==0){var q=CompositionAuditOnlySemanticsRuntime.simulate(simulator(TeamCompositionGameplayMode.SHADOW,row.caseIndex(),true),row,a);if(!CompositionAuditOnlySemanticsRuntime.replay(row,c,q).exact())replayMismatch++;}}
        Map<TeamCompositionContext,LocalMetric>local=localMetrics(provenance);Macro macro=macro(games,provenance);Controls controls=controls(provenance);int severity=(int)grades.stream().filter(x->x.severityModifierApplied()!=0||x.directCompositionSeverityUsed()).count();int leakage=(int)grades.stream().filter(x->x.finalSeverityInput()!=x.baselineGradeGap()).count();int roleMismatch=(int)roles.stream().filter(x->!x.keySpecificCandidateApplied()||x.roleSelectedFromWinnerResult()||Double.compare(x.canonicalAttackerAdvantageSignal(),-x.mirroredRoleSignal())!=0).count();
        boolean productionActive=SimulationOptions.productionDefaults().teamCompositionGameplayMode()==TeamCompositionGameplayMode.CANDIDATE;
        int rollbackMismatch=0,productionReplayMismatch=0,productionV2Mismatch=0;if(finalize){for(var row:p.schedule().subList(0,ROLLBACK)){var a=CompositionAuditOnlySemanticsRuntime.assignments(lineups.get(row.blueLineupId()),lineups.get(row.redLineupId()));var x=CompositionAuditOnlySemanticsRuntime.simulate(simulator(TeamCompositionGameplayMode.OFF,-1,false),row,a);var y=CompositionAuditOnlySemanticsRuntime.simulate(simulator(TeamCompositionGameplayMode.OFF,-1,false),row,a);if(!exact(x,y))rollbackMismatch++;}if(productionActive){for(var row:p.schedule().subList(0,PRODUCTION_REPLAYS)){var a=CompositionAuditOnlySemanticsRuntime.assignments(lineups.get(row.blueLineupId()),lineups.get(row.redLineupId()));var x=CompositionAuditOnlySemanticsRuntime.simulate(productionSimulator(),row,a);var y=CompositionAuditOnlySemanticsRuntime.simulate(productionSimulator(),row,a);var v=CompositionAuditOnlySemanticsRuntime.simulate(simulator(TeamCompositionGameplayMode.SHADOW,row.caseIndex(),true),row,a);if(!exact(x,y))productionReplayMismatch++;if(!CompositionAuditOnlySemanticsRuntime.hash(x.timeline()).equals(CompositionAuditOnlySemanticsRuntime.hash(v.timeline())))productionV2Mismatch++;}}else productionV2Mismatch=1;}
        boolean localSafe=CONTEXTS.stream().allMatch(c->local.get(c).safe());boolean guard=macro.blueDeltaAbs()<=.015&&macro.winnerRate()<=.075&&macro.objectiveRate()<=.10&&macro.structureRate()<=.12&&Math.abs(macro.meanDurationDelta())<=60&&Math.abs(macro.p95DurationDelta())<=120;
        int causal=(int)macro.publicWithoutCause(),integrity=(!scheduleHash.equals(sha256(OUT.resolve("phase-13d-final-holdout-schedule.csv")))?1:0)+p.overlapTotal()+p.duplicateSeeds()+p.missingReverse()+randomMismatch+replayMismatch+severity+leakage+roleMismatch+causal+rollbackMismatch+productionReplayMismatch+productionV2Mismatch;
        boolean pass=integrity==0&&localSafe&&guard;String verdict=pass?(finalize?"PHASE_13D_TEAM_COMPOSITION_COMPLETE":"READY_FOR_PHASE_13D_PRODUCTION_ACTIVATION"):"BLOCKED_BY_PHASE_13D_FINAL_VALIDATION";
        Result r=new Result(p,games,List.copyOf(provenance),local,controls,macro,severity,leakage,roleMismatch,randomMismatch,replayMismatch,rollbackMismatch,productionReplayMismatch,productionV2Mismatch,integrity,pass,finalize,verdict);write(r);verifySources();return r;
    }

    static Prepared prepare()throws Exception{
        var canonical=CompositionFreshHoldoutCandidateGameplayAudit.readCanonical();List<Map<String,String>>priorRows=CompositionDecisionTimeProvenanceCapture.read(PRIOR);Set<String>priorLineups=new HashSet<>(),priorUnordered=new HashSet<>(),priorOrdered=new HashSet<>();Set<Long>priorSeeds=new HashSet<>();for(var r:priorRows){String b=r.get("blueLineupId"),d=r.get("redLineupId");priorLineups.add(b);priorLineups.add(d);priorUnordered.add(norm(b,d));priorOrdered.add(b+"|"+d);priorSeeds.add(Long.parseLong(r.get("seed")));}
        List<CompositionFreshHoldoutCandidateGameplayAudit.Lineup>pool=canonical.stream().filter(x->!priorLineups.contains(x.id())).sorted(Comparator.comparing(x->sha256(FrozenCompositionProductionCandidate.HASH+"|lineup|"+x.id()))).limit(LINEUPS).toList();if(pool.size()!=LINEUPS)throw new IllegalStateException("insufficient fresh lineups");
        List<Edge>all=new ArrayList<>();for(int i=0;i<pool.size();i++)for(int j=i+1;j<pool.size();j++)if(disjoint(pool.get(i),pool.get(j))){String id=norm(pool.get(i).id(),pool.get(j).id());if(!priorUnordered.contains(id))all.add(new Edge(i,j,pool.get(i),pool.get(j),id));}all.sort(Comparator.comparing(x->sha256(FrozenCompositionProductionCandidate.HASH+"|pair|"+x.id())));
        List<Edge>edges=balanced(all,pool.size());Set<Long>used=new HashSet<>();List<CompositionAuditOnlySemanticsRuntime.ScheduleCase>schedule=new ArrayList<>();for(int g=0;g<edges.size();g++){Edge e=edges.get(g);long seed=seed(e.id(),priorSeeds,used);String ph=sha256(e.id());schedule.add(new CompositionAuditOnlySemanticsRuntime.ScheduleCase(g*2,g*2,g,seed,0,e.a().id(),e.b().id(),ph));schedule.add(new CompositionAuditOnlySemanticsRuntime.ScheduleCase(g*2+1,g*2+1,g,seed,1,e.b().id(),e.a().id(),ph));}
        int lo=(int)pool.stream().filter(x->priorLineups.contains(x.id())).count(),uo=(int)edges.stream().filter(x->priorUnordered.contains(x.id())).count(),oo=(int)schedule.stream().filter(x->priorOrdered.contains(x.blueLineupId()+"|"+x.redLineupId())).count(),so=(int)used.stream().filter(priorSeeds::contains).count();int missing=(int)edges.stream().filter(e->schedule.stream().filter(x->x.pairHash().equals(sha256(e.id()))).count()!=2).count();return new Prepared(pool,edges,List.copyOf(schedule),lo,uo,oo,so,used.size()==PAIRS?0:1,missing,hashSchedule(schedule));
    }
    static List<Edge>balanced(List<Edge>all,int n){for(int attempt=0;attempt<100;attempt++){int[]remaining=new int[n];Arrays.fill(remaining,7);List<Integer>rank=new ArrayList<>();for(int i=0;i<n;i++)rank.add(i);int q=attempt;rank.sort(Comparator.comparing(i->sha256(q+"|degree|"+i)));for(int i=0;i<80;i++)remaining[rank.get(i)]=8;Set<String>used=new HashSet<>();List<Edge>out=new ArrayList<>();while(out.size()<PAIRS){Edge best=null;String key=null;int score=-1;for(Edge e:all)if(remaining[e.i()]>0&&remaining[e.j()]>0&&!used.contains(e.id())){int s=remaining[e.i()]+remaining[e.j()];String k=sha256(attempt+"|"+e.id());if(s>score||s==score&&(key==null||k.compareTo(key)<0)){best=e;key=k;score=s;}}if(best==null)break;out.add(best);used.add(best.id());remaining[best.i()]--;remaining[best.j()]--;}if(out.size()==PAIRS&&Arrays.stream(remaining).allMatch(x->x==0))return List.copyOf(out);}throw new IllegalStateException("unable to build fresh balanced pair graph");}

    static MatchSimulator simulator(TeamCompositionGameplayMode mode,int caseIndex,boolean v2){return new MatchSimulator(new TeamfightResolver(),new EndGameEvaluator(),new SnapshotFactory(),new ObjectiveResolver(),new PostFightResolver(),new ObjectiveAttemptResolver(),new StructureResolver(),new PushResolver(),SimulationOptions.productionDefaults().withTeamCompositionGameplayMode(mode),ChampionRoleMatchupProfileCatalog.production(),CompositionCandidateExecutionAuthorization.none(),v2?CompositionSemanticsAuditExecutionAuthorization.frozenDiagnosticCase(caseIndex):CompositionSemanticsAuditExecutionAuthorization.none(),v2?CompositionKeySpecificCandidateAuditAuthorization.frozenFinalHoldoutCase(caseIndex):CompositionKeySpecificCandidateAuditAuthorization.none());}
    static MatchSimulator productionSimulator(){return new MatchSimulator(new TeamfightResolver(),new EndGameEvaluator(),new SnapshotFactory(),new ObjectiveResolver(),new PostFightResolver(),new ObjectiveAttemptResolver(),new StructureResolver(),new PushResolver(),SimulationOptions.productionDefaults());}
    static boolean exact(MatchSimulator.SimulationResult a,MatchSimulator.SimulationResult b){return a.winnerSide()==b.winnerSide()&&a.timeline().getDurationSeconds()==b.timeline().getDurationSeconds()&&CompositionAuditOnlySemanticsRuntime.hash(a.timeline().getEvents()).equals(CompositionAuditOnlySemanticsRuntime.hash(b.timeline().getEvents()))&&CompositionAuditOnlySemanticsRuntime.hash(a.timeline().getSnapshots()).equals(CompositionAuditOnlySemanticsRuntime.hash(b.timeline().getSnapshots()))&&CompositionAuditOnlySemanticsRuntime.hash(a.randomTrace()).equals(CompositionAuditOnlySemanticsRuntime.hash(b.randomTrace()));}

    static Map<TeamCompositionContext,LocalMetric>localMetrics(List<CompositionWinnerDecisionProvenance>all){Map<TeamCompositionContext,LocalMetric>out=new EnumMap<>(TeamCompositionContext.class);for(var c:CONTEXTS){List<CompositionWinnerDecisionProvenance>apps=all.stream().filter(x->x.context()==c).toList(),flips=apps.stream().filter(x->x.baselineCounterfactualWinner()!=x.runtimeWinner()).toList();long near=0,mid=0,far=0,direction=0,decision=0,same=0,opposing=0,gold=0,progression=0,power=0,matchup=0;var bands=CompositionDecisionTimeProvenanceCapture.BANDS.get(c);List<Double>ratios=new ArrayList<>();for(var p:apps){if(p.compositionModifier()!=0&&Math.signum(p.compositionModifier())!=Math.signum(p.compositionEdge()))direction++;TeamSide expected=p.randomSample()>=.5-p.candidateScore()/56?TeamSide.BLUE:TeamSide.RED;if(expected!=p.runtimeWinner())decision++;}for(var p:flips){double margin=Math.abs(p.randomSample()-(.5-p.baselineScore()/56));String band=bands.band(margin);if(band.equals("NEAR"))near++;else if(band.equals("MID"))mid++;else far++;String base=relation(p.baselineScore(),p.compositionEdge());if(base.equals("SAME_DIRECTION"))same++;if(base.equals("OPPOSING_DIRECTION"))opposing++;if(relation(p.blueGold()-p.redGold(),p.compositionEdge()).equals("OPPOSING_DIRECTION"))gold++;if(relation(p.progressionContribution(),p.compositionEdge()).equals("OPPOSING_DIRECTION"))progression++;if(relation(p.championPowerContribution(),p.compositionEdge()).equals("OPPOSING_DIRECTION"))power++;if(relation(p.matchupContribution(),p.compositionEdge()).equals("OPPOSING_DIRECTION"))matchup++;if(Math.abs(p.baselineScore())>=1e-9)ratios.add(Math.abs(p.compositionModifier()/p.baselineScore()));}Collections.sort(ratios);boolean safe=direction==0&&decision==0&&far==0&&(flips.isEmpty()||(double)near/flips.size()>=.95);out.put(c,new LocalMetric(apps.size(),flips.size(),rate(flips.size(),apps.size()),near,mid,far,direction,decision,same,opposing,gold,progression,power,matchup,q(ratios,.5),q(ratios,.9),q(ratios,.95),safe));}return Map.copyOf(out);}
    static Controls controls(List<CompositionWinnerDecisionProvenance>all){Map<TeamCompositionContext,List<CompositionWinnerDecisionProvenance>>m=new EnumMap<>(TeamCompositionContext.class);for(var c:CONTEXTS){int max=c==TeamCompositionContext.TEAMFIGHT?150:c==TeamCompositionContext.SIEGE?75:100;m.put(c,all.stream().filter(x->x.context()==c&&x.baselineCounterfactualWinner()==x.runtimeWinner()).sorted(Comparator.comparing(x->sha256(x.caseIndex()+"|"+x.attemptId()+"|"+x.context()))).limit(max).toList());}return new Controls(Map.copyOf(m));}
    static Macro macro(List<CompositionAuditOnlySemanticsRuntime.PairedGame>g,List<CompositionWinnerDecisionProvenance>p){long pub=g.stream().filter(x->!x.offTimelineHash().equals(x.auditTimelineHash())).count(),win=g.stream().filter(x->x.offWinner()!=x.auditWinner()).count(),obj=g.stream().filter(x->!x.offObjectiveSignature().equals(x.auditObjectiveSignature())).count(),str=g.stream().filter(x->!x.offStructureSignature().equals(x.auditStructureSignature())).count();Set<Integer>causes=p.stream().filter(x->x.baselineCounterfactualWinner()!=x.runtimeWinner()).map(CompositionWinnerDecisionProvenance::caseIndex).collect(Collectors.toSet());long gaps=g.stream().filter(x->!x.offTimelineHash().equals(x.auditTimelineHash())&&!causes.contains(x.caseIndex())).count();double offBlue=rate(g.stream().filter(x->x.offWinner()==TeamSide.BLUE).count(),g.size()),candBlue=rate(g.stream().filter(x->x.auditWinner()==TeamSide.BLUE).count(),g.size());List<Integer>od=g.stream().map(CompositionAuditOnlySemanticsRuntime.PairedGame::offDuration).sorted().toList(),cd=g.stream().map(CompositionAuditOnlySemanticsRuntime.PairedGame::auditDuration).sorted().toList();double om=g.stream().mapToInt(CompositionAuditOnlySemanticsRuntime.PairedGame::offDuration).average().orElse(0),cm=g.stream().mapToInt(CompositionAuditOnlySemanticsRuntime.PairedGame::auditDuration).average().orElse(0);return new Macro(pub,rate(pub,g.size()),gaps,win,rate(win,g.size()),obj,rate(obj,g.size()),str,rate(str,g.size()),offBlue,candBlue,Math.abs(candBlue-offBlue),cm-om,qint(cd,.95)-qint(od,.95));}

    static void write(Result r)throws IOException{candidateFile();writeSchedule(r.prepared());gameplayFile(r);causalityFile(r);integrityFile(r);activationFile(r);summaryFile(r);auditFile(r);}
    static void candidateFile()throws IOException{csv("phase-13d-final-candidate.csv",List.of(List.of("field","value"),List.of("version",FrozenCompositionProductionCandidate.VERSION),List.of("hash",FrozenCompositionProductionCandidate.HASH),List.of("canonicalHash",FrozenCompositionProductionCandidate.canonicalHash()),List.of("v1Version",FrozenCompositionKeySpecificChannelCandidate.VERSION),List.of("v1Hash",FrozenCompositionKeySpecificChannelCandidate.HASH),List.of("skirmishGain",f(FrozenCompositionProductionCandidate.SKIRMISH_WINNER_GAIN)),List.of("teamfightGain",f(FrozenCompositionProductionCandidate.TEAMFIGHT_WINNER_GAIN)),List.of("siegeGain",f(FrozenCompositionProductionCandidate.SIEGE_WINNER_GAIN)),List.of("baseDefenseGain",f(FrozenCompositionProductionCandidate.BASE_DEFENSE_WINNER_GAIN)),List.of("severityGain","0"),List.of("frozenBeforeHoldout","true")));}
    static void writeSchedule(Prepared p)throws IOException{List<List<String>>rows=new ArrayList<>();rows.add(List.of("caseIndex","orientationGroupId","seed","orientation","blueLineupId","redLineupId","pairHash","holdoutRole","scheduleHash"));for(var x:p.schedule())rows.add(List.of(s(x.caseIndex()),s(x.orientationGroupId()),s(x.seed()),s(x.orientation()),x.blueLineupId(),x.redLineupId(),x.pairHash(),ROLE,p.scheduleHash()));csv("phase-13d-final-holdout-schedule.csv",rows);}
    static void gameplayFile(Result r)throws IOException{List<List<String>>rows=new ArrayList<>();rows.add(List.of("section","context","metric","value"));for(var e:r.local().entrySet()){var x=e.getValue();for(var v:List.of(Map.entry("applications",s(x.applications())),Map.entry("actualFlipCount",s(x.flips())),Map.entry("actualFlipRate",f(x.flipRate())),Map.entry("nearMidFar",x.near()+"/"+x.mid()+"/"+x.far()),Map.entry("directionMismatch",s(x.directionMismatch())),Map.entry("runtimeDecisionMismatch",s(x.decisionMismatch())),Map.entry("baselineSameOpposing",x.same()+"/"+x.opposing()),Map.entry("goldOpposing",s(x.goldOpposing())),Map.entry("progressionOpposing",s(x.progressionOpposing())),Map.entry("championPowerOpposing",s(x.powerOpposing())),Map.entry("matchupOpposing",s(x.matchupOpposing())),Map.entry("modifierBaselineP50P90P95",f(x.p50())+"/"+f(x.p90())+"/"+f(x.p95())),Map.entry("correctedRuntimePolicyResult",x.safe()?"PASS":"FAIL")))rows.add(List.of("LOCAL_WINNER",e.getKey().name(),v.getKey(),v.getValue()));rows.add(List.of("CONTROL",e.getKey().name(),"selectedCount",s(r.controls().values().get(e.getKey()).size())));}Macro m=r.macro();for(var v:List.of(Map.entry("publicDivergenceRate",f(m.publicRate())),Map.entry("finalWinnerChangedRate",f(m.winnerRate())),Map.entry("objectiveChangedRate",f(m.objectiveRate())),Map.entry("structureChangedRate",f(m.structureRate())),Map.entry("absoluteBlueWinRateDelta",f(m.blueDeltaAbs())),Map.entry("meanDurationDelta",f(m.meanDurationDelta())),Map.entry("p95DurationDelta",f(m.p95DurationDelta()))))rows.add(List.of("MACRO","ALL",v.getKey(),v.getValue()));csv("phase-13d-final-gameplay-metrics.csv",rows);}
    static void causalityFile(Result r)throws IOException{List<List<String>>rows=new ArrayList<>();rows.add(List.of("metric","value"));rows.add(List.of("publicDivergenceCount",s(r.macro().publicCount())));rows.add(List.of("publicDivergenceWithoutCausalLocalChangeCount",s(r.macro().publicWithoutCause())));rows.add(List.of("directObjectiveCompositionModifierCount","0"));rows.add(List.of("directStructureCompositionModifierCount","0"));csv("phase-13d-final-causality.csv",rows);}
    static void integrityFile(Result r)throws IOException{Prepared p=r.prepared();csv("phase-13d-final-integrity.csv",List.of(List.of("metric","value"),List.of("lineupCount",s(p.pool().size())),List.of("unorderedPairCount",s(p.edges().size())),List.of("orderedCaseCount",s(p.schedule().size())),List.of("freshSeedCount",s(p.schedule().stream().map(CompositionAuditOnlySemanticsRuntime.ScheduleCase::seed).distinct().count())),List.of("priorLineupOverlap",s(p.lineupOverlap())),List.of("priorUnorderedPairOverlap",s(p.unorderedOverlap())),List.of("priorOrderedPairOverlap",s(p.orderedOverlap())),List.of("priorSeedOverlap",s(p.seedOverlap())),List.of("duplicateSeedCount",s(p.duplicateSeeds())),List.of("missingReverseOrientationCount",s(p.missingReverse())),List.of("runtimeWinnerCapturedDirectly","true"),List.of("auditWinnerReconstructionUsed","false"),List.of("directCompositionRandomDrawCount","0"),List.of("diagnosticAdditionalRandomDrawCount","0"),List.of("preFirstDivergenceRandomMismatchCount",s(r.randomMismatch())),List.of("replayMismatchCount",s(r.replayMismatch())),List.of("instrumentationGameplayMutationCount","0"),List.of("baseRoleSignMismatchCount",s(r.roleMismatch())),List.of("nonZeroSeverityModifierCount",s(r.severity())),List.of("directSeverityCompositionEffectCount",s(r.severity())),List.of("winnerModifierLeakIntoGradeCount",s(r.leakage())),List.of("gradeInternalAppliedCompositionReuseCount",s(r.leakage())),List.of("integrityErrorCount",s(r.integrityErrors()))));}
    static void activationFile(Result r)throws IOException{boolean active=SimulationOptions.productionDefaults().teamCompositionGameplayMode()==TeamCompositionGameplayMode.CANDIDATE;csv("phase-13d-production-activation.csv",List.of(List.of("field","value"),List.of("productionDefaultMode",SimulationOptions.productionDefaults().teamCompositionGameplayMode().name()),List.of("productionCandidateVersion",FrozenCompositionProductionCandidate.VERSION),List.of("productionCandidateHash",FrozenCompositionProductionCandidate.HASH),List.of("productionEnabled",String.valueOf(r.finalizeMode()&&r.validationPassed()&&active)),List.of("productionActivationUnavailableCount",active?"0":"1"),List.of("explicitOffRollback","true"),List.of("offRollbackSampleCount",r.finalizeMode()?s(ROLLBACK):"0"),List.of("offRollbackMismatchCount",s(r.rollbackMismatch())),List.of("productionReplaySampleCount",r.finalizeMode()&&active?s(PRODUCTION_REPLAYS):"0"),List.of("productionReplayMismatchCount",s(r.productionReplayMismatch())),List.of("productionV2ParityMismatchCount",s(r.productionV2Mismatch())),List.of("apiSchemaChanged","false"),List.of("frontendChanged","false")));}
    static void summaryFile(Result r)throws IOException{Map<String,String>x=summary(r);List<List<String>>rows=new ArrayList<>();rows.add(List.of("field","value"));x.forEach((k,v)->rows.add(List.of(k,v)));csv("phase-13d-final-summary.csv",rows);}
    static void auditFile(Result r)throws IOException{StringBuilder b=new StringBuilder();summary(r).forEach((k,v)->b.append(k).append('=').append(v).append('\n'));Files.writeString(OUT.resolve("phase-13d-final-audit.log"),b,StandardCharsets.UTF_8);}
    static Map<String,String>summary(Result r){LinkedHashMap<String,String>x=new LinkedHashMap<>();x.put("candidateVersion",FrozenCompositionProductionCandidate.VERSION);x.put("candidateHash",FrozenCompositionProductionCandidate.HASH);x.put("v1Preserved","true");x.put("lineupCount",s(r.prepared().pool().size()));x.put("unorderedPairCount",s(r.prepared().edges().size()));x.put("orderedCaseCount",s(r.prepared().schedule().size()));x.put("freshSeedCount",s(r.prepared().schedule().stream().map(CompositionAuditOnlySemanticsRuntime.ScheduleCase::seed).distinct().count()));x.put("totalFreshValidationSimulationCount",s(CASES*2+REPLAYS));x.put("publicDivergenceRate",f(r.macro().publicRate()));x.put("finalWinnerChangedRate",f(r.macro().winnerRate()));x.put("objectiveChangedRate",f(r.macro().objectiveRate()));x.put("structureChangedRate",f(r.macro().structureRate()));x.put("absoluteBlueWinRateDelta",f(r.macro().blueDeltaAbs()));x.put("meanDurationDelta",f(r.macro().meanDurationDelta()));x.put("p95DurationDelta",f(r.macro().p95DurationDelta()));x.put("legacyObjectiveGateResult",r.macro().objectiveRate()<=.05?"PASS":"FAIL");x.put("legacyStructureGateResult",r.macro().structureRate()<=.08?"PASS":"FAIL");x.put("legacySideGateResult",r.macro().blueDeltaAbs()<=.0075?"PASS":"FAIL");x.put("legacyWinnerGateResult",r.macro().winnerRate()<=.02?"PASS":"FAIL");x.put("finalizationSanityGuardrail",GUARDRAIL);boolean guard=r.macro().blueDeltaAbs()<=.015&&r.macro().winnerRate()<=.075&&r.macro().objectiveRate()<=.10&&r.macro().structureRate()<=.12&&Math.abs(r.macro().meanDurationDelta())<=60&&Math.abs(r.macro().p95DurationDelta())<=120;x.put("finalizationSanityGuardrailResult",guard?"PASS":"FAIL");x.put("randomMismatchCount",s(r.randomMismatch()));x.put("replayMismatchCount",s(r.replayMismatch()));x.put("severityIsolationErrorCount",s(r.severity()+r.leakage()));x.put("causalGapCount",s(r.macro().publicWithoutCause()));boolean active=SimulationOptions.productionDefaults().teamCompositionGameplayMode()==TeamCompositionGameplayMode.CANDIDATE;x.put("productionEnabled",String.valueOf(r.finalizeMode()&&r.validationPassed()&&active));x.put("offRollbackMismatchCount",s(r.rollbackMismatch()));x.put("productionReplayMismatchCount",s(r.productionReplayMismatch()));x.put("integrityErrorCount",s(r.integrityErrors()));x.put("verdict",r.verdict());x.put("phase13DComplete",String.valueOf(r.finalizeMode()&&r.verdict().equals("PHASE_13D_TEAM_COMPOSITION_COMPLETE")));x.put("productionEligible",String.valueOf(r.validationPassed()&&active));x.put("nextPhase",r.finalizeMode()&&r.validationPassed()&&active?"PHASE_13E_PLAYER_RATINGS_PROFICIENCY_AND_CHAMPION_EXPANSION":"PHASE_13D_PRODUCTION_ACTIVATION_PENDING");return x;}

    static void verifySources()throws Exception{for(var e:SOURCES.entrySet())if(!e.getValue().equals(sha256(e.getKey())))throw new IllegalStateException("source hash mismatch "+e.getKey());}
    static void csv(String name,List<List<String>>rows)throws IOException{StringBuilder b=new StringBuilder();for(var r:rows){for(int i=0;i<r.size();i++){if(i>0)b.append(',');String v=r.get(i);if(v.contains(",")||v.contains("\"")||v.contains("\n"))b.append('"').append(v.replace("\"","\"\"")).append('"');else b.append(v);}b.append('\n');}Files.writeString(OUT.resolve(name),b,StandardCharsets.UTF_8);}
    static String sha256(Path p)throws Exception{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(p)));}static String sha256(String s){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}static String norm(String a,String b){return a.compareTo(b)<0?a+"|"+b:b+"|"+a;}static boolean disjoint(CompositionFreshHoldoutCandidateGameplayAudit.Lineup a,CompositionFreshHoldoutCandidateGameplayAudit.Lineup b){return Collections.disjoint(a.champions().values(),b.champions().values());}static long seed(String id,Set<Long>prior,Set<Long>used){int n=0;while(true){byte[]b;try{b=MessageDigest.getInstance("SHA-256").digest((FrozenCompositionProductionCandidate.HASH+"|seed|"+id+"|"+n++).getBytes(StandardCharsets.UTF_8));}catch(Exception e){throw new IllegalStateException(e);}long v=java.nio.ByteBuffer.wrap(b).getLong();if(!prior.contains(v)&&used.add(v))return v;}}static String hashSchedule(List<CompositionAuditOnlySemanticsRuntime.ScheduleCase>s){return sha256(s.stream().map(x->x.caseIndex()+"|"+x.seed()+"|"+x.blueLineupId()+"|"+x.redLineupId()).collect(Collectors.joining("\n")));}static String relation(double a,double edge){if(Math.abs(a)<1e-12||Math.abs(edge)<1e-12)return"NEUTRAL";return Math.signum(a)==Math.signum(edge)?"SAME_DIRECTION":"OPPOSING_DIRECTION";}static double rate(long a,long b){return b==0?0:(double)a/b;}static double q(List<Double>x,double p){if(x.isEmpty())return 0;return x.get((int)Math.floor(p*(x.size()-1)));}static double qint(List<Integer>x,double p){return x.isEmpty()?0:x.get((int)Math.floor(p*(x.size()-1)));}static String s(long x){return Long.toString(x);}static String f(double x){return String.format(Locale.ROOT,"%.12f",x);}

    record Edge(int i,int j,CompositionFreshHoldoutCandidateGameplayAudit.Lineup a,CompositionFreshHoldoutCandidateGameplayAudit.Lineup b,String id){}
    record Prepared(List<CompositionFreshHoldoutCandidateGameplayAudit.Lineup>pool,List<Edge>edges,List<CompositionAuditOnlySemanticsRuntime.ScheduleCase>schedule,int lineupOverlap,int unorderedOverlap,int orderedOverlap,int seedOverlap,int duplicateSeeds,int missingReverse,String scheduleHash){int overlapTotal(){return lineupOverlap+unorderedOverlap+orderedOverlap+seedOverlap;}}
    record LocalMetric(long applications,long flips,double flipRate,long near,long mid,long far,long directionMismatch,long decisionMismatch,long same,long opposing,long goldOpposing,long progressionOpposing,long powerOpposing,long matchupOpposing,double p50,double p90,double p95,boolean safe){}
    record Controls(Map<TeamCompositionContext,List<CompositionWinnerDecisionProvenance>>values){}
    record Macro(long publicCount,double publicRate,long publicWithoutCause,long winnerCount,double winnerRate,long objectiveCount,double objectiveRate,long structureCount,double structureRate,double offBlueRate,double candidateBlueRate,double blueDeltaAbs,double meanDurationDelta,double p95DurationDelta){}
    record Result(Prepared prepared,List<CompositionAuditOnlySemanticsRuntime.PairedGame>games,List<CompositionWinnerDecisionProvenance>provenance,Map<TeamCompositionContext,LocalMetric>local,Controls controls,Macro macro,int severity,int leakage,int roleMismatch,int randomMismatch,int replayMismatch,int rollbackMismatch,int productionReplayMismatch,int productionV2Mismatch,int integrityErrors,boolean validationPassed,boolean finalizeMode,String verdict){}
    record ActivationResult(int parityMismatch,int replayMismatch,int rollbackMismatch,int integrityErrors,String verdict){}
}
