package com.lolfm.simulator;import static org.assertj.core.api.Assertions.*;import com.lolfm.domain.Position;import org.junit.jupiter.api.Test;
class PlayerProgressionStateTest{private PlayerState p(){PlayerState p=new PlayerState("p",Position.TOP,500);p.configureProgression(TeamSide.BLUE,true,new ProgressionExecutionStats());return p;}
@Test void freshStateIsLevelOneStarting(){var s=p().getProgressionState();assertThat(s.getLevel()).isOne();assertThat(s.getTotalExperience()).isZero();assertThat(s.getProgressionEarnedGold()).isZero();assertThat(s.getItemStage()).isEqualTo(ItemProgressStage.STARTING);}
@Test void exactLevelThresholdAndBefore(){var s=p().getProgressionState();s.awardExperience(ExperienceSource.LANE_ECONOMY,279,10);assertThat(s.getLevel()).isOne();s.awardExperience(ExperienceSource.LANE_ECONOMY,1,20);assertThat(s.getLevel()).isEqualTo(2);}
@Test void multiLevelRewardEmitsOrderedEvents(){var s=p().getProgressionState();s.awardExperience(ExperienceSource.KILL,2400,10);assertThat(s.getLevel()).isEqualTo(6);assertThat(s.drainEvents()).extracting(e->e.newLevel()).containsExactly(2,3,4,5,6);}
@Test void topQuestLevelTwentyClampsWithoutRollback(){var s=p().getProgressionState();s.awardExperience(ExperienceSource.KILL,50000,10);s.awardExperience(ExperienceSource.KILL,50000,20);assertThat(s.getLevel()).isEqualTo(20);assertThat(s.getTotalExperience()).isEqualTo(100000);}
@Test void itemThresholdsAreExact(){var s=p().getProgressionState();s.awardEarnedGold(1199,GoldSource.FARM,10);assertThat(s.getItemStage()).isEqualTo(ItemProgressStage.STARTING);s.awardEarnedGold(1,GoldSource.FARM,20);assertThat(s.getItemStage()).isEqualTo(ItemProgressStage.COMPONENT);s.awardEarnedGold(2300,GoldSource.FARM,30);assertThat(s.getItemStage()).isEqualTo(ItemProgressStage.FIRST_CORE);}
@Test void multiStageRewardIsOrdered(){var s=p().getProgressionState();s.awardEarnedGold(17500,GoldSource.KILL,10);assertThat(s.getItemStage()).isEqualTo(ItemProgressStage.FULL_BUILD);assertThat(s.drainEvents()).extracting(e->e.newItemStage()).containsExactly(ItemProgressStage.COMPONENT,ItemProgressStage.FIRST_CORE,ItemProgressStage.SECOND_CORE,ItemProgressStage.THIRD_CORE,ItemProgressStage.FOURTH_CORE,ItemProgressStage.FULL_BUILD);}
@Test void matchesDoNotShareProgression(){assertThat(p().getProgressionState()).isNotSameAs(p().getProgressionState());}
}
