package com.lolfm.simulator;
import static org.assertj.core.api.Assertions.*;
import com.lolfm.domain.*;
import java.util.*;
import org.junit.jupiter.api.Test;
class ProgressionRewardResolverTest {
 private GameState state(){return LateGameTestSupport.state();}
 @Test void killerReceivesConfiguredExperience(){GameState s=state();PlayerState k=s.getBlueTeamState().playerAt(Position.MID);new ProgressionRewardResolver().awardKillExperience(k,List.of(),100);assertThat(k.getProgressionState().getTotalExperience()).isEqualTo(180);}
 @Test void multipleAssistantsEachReceiveConfiguredExperience(){GameState s=state();PlayerState k=s.getBlueTeamState().playerAt(Position.MID),a=s.getBlueTeamState().playerAt(Position.JUNGLE),b=s.getBlueTeamState().playerAt(Position.SUPPORT);new ProgressionRewardResolver().awardKillExperience(k,List.of(a,b),100);assertThat(a.getProgressionState().getTotalExperience()).isEqualTo(90);assertThat(b.getProgressionState().getTotalExperience()).isEqualTo(90);}
 @Test void duplicateAssistantAndKillerAreExcluded(){GameState s=state();PlayerState k=s.getBlueTeamState().playerAt(Position.MID),a=s.getBlueTeamState().playerAt(Position.JUNGLE);new ProgressionRewardResolver().awardKillExperience(k,List.of(a,a,k),100);assertThat(k.getProgressionState().getTotalExperience()).isEqualTo(180);assertThat(a.getProgressionState().getTotalExperience()).isEqualTo(90);}
 @Test void deadAssistantReceivesNoExperience(){GameState s=state();PlayerState k=s.getBlueTeamState().playerAt(Position.MID),a=s.getBlueTeamState().playerAt(Position.JUNGLE);a.markDead(100,30);new ProgressionRewardResolver().awardKillExperience(k,List.of(a),100);assertThat(a.getProgressionState().getTotalExperience()).isZero();}
 @Test void duplicateActualKillDoesNotRewardTwice(){GameState s=state();PlayerState k=s.getBlueTeamState().playerAt(Position.MID),v=s.getRedTeamState().playerAt(Position.MID);KillRewardResolver r=new KillRewardResolver();List<MatchEvent> events=new ArrayList<>();r.award(100,s.getBlueTeamState(),k,s.getRedTeamState(),v,List.of(),20,false,0,events);r.award(100,s.getBlueTeamState(),k,s.getRedTeamState(),v,List.of(),20,false,0,events);assertThat(k.getProgressionState().getTotalExperience()).isEqualTo(180);assertThat(k.getProgressionState().getProgressionEarnedGold()).isEqualTo(400);assertThat(k.getKills()).isOne();}
 @Test void shutdownCreditsOnlyActualKillAndBountyGold(){GameState s=state();PlayerState k=s.getBlueTeamState().playerAt(Position.MID),v=s.getRedTeamState().playerAt(Position.MID);new KillRewardResolver().award(100,s.getBlueTeamState(),k,s.getRedTeamState(),v,List.of(),20,false,400,new ArrayList<>());assertThat(k.getProgressionState().getProgressionEarnedGold()).isEqualTo(800);assertThat(k.getProgressionState().getExperienceBySource()).containsEntry(ExperienceSource.KILL,180);}
 @Test void objectiveCaptureAwardsNoExperience(){GameState s=state();s.advanceTimeSeconds(300);ObjectiveResolver r=new ObjectiveResolver();r.updateSpawnState(s);r.captureDragon(s,TeamSide.BLUE,300,DragonCaptureSource.GENERAL,"x");assertThat(s.getBlueTeamState().getPlayers()).allMatch(p->p.getProgressionState().getTotalExperience()==0);}
 @Test void sameDisplayNameOnOppositeSidesRemainIndependent(){GameState s=state();PlayerState blue=s.getBlueTeamState().playerAt(Position.TOP),red=s.getRedTeamState().playerAt(Position.TOP);new ProgressionRewardResolver().awardExperience(blue,ExperienceSource.KILL,180,1);assertThat(blue.getProgressionState().getTotalExperience()).isEqualTo(180);assertThat(red.getProgressionState().getTotalExperience()).isZero();assertThat(blue.getProgressionState().getExperienceBySource()).containsEntry(ExperienceSource.KILL,180);}
}
