package com.lolfm.simulator;
import static org.assertj.core.api.Assertions.*;import com.lolfm.domain.Position;import java.util.List;import org.junit.jupiter.api.Test;
class ProgressionBaselineInstrumentationTest{private GameState s(){return LateGameTestSupport.state();}private PlayerState b(GameState s){return s.getBlueTeamState().playerAt(Position.TOP);}private PlayerState r(GameState s){return s.getRedTeamState().playerAt(Position.TOP);}
@Test void combatSampleSeparatesLevelAndItemContribution(){GameState s=s();b(s).getProgressionState().awardExperience(ExperienceSource.KILL,2400,1);b(s).getProgressionState().awardEarnedGold(3500,GoldSource.KILL,1);new CombatProgressionEvaluator().contribution(s,ProgressionCombatContext.TEAMFIGHT,List.of(b(s)),List.of(r(s)),10,2);var x=s.getProgressionExecutionStats().snapshot().combatSamples().getLast();assertThat(x.totalContribution()).isCloseTo(x.levelContribution()+x.itemContribution(),within(1e-9));}
@Test void combatSampleKeepsExistingAndGoldBreakdownDistinct(){GameState s=s();new CombatProgressionEvaluator().contribution(s,ProgressionCombatContext.LANE_COMBAT,List.of(b(s)),List.of(r(s)),4.5,1.25);var x=s.getProgressionExecutionStats().snapshot().combatSamples().getLast();assertThat(x.existingScoreBeforeProgression()).isEqualTo(4.5);assertThat(x.goldContribution()).isEqualTo(1.25);}
@Test void powerOffRecordsZeroContributionWithoutChangingState(){GameState s=s();b(s).getProgressionState().awardExperience(ExperienceSource.KILL,2400,1);int xp=b(s).getProgressionState().getTotalExperience();s.configureProgression(true,false);double v=new CombatProgressionEvaluator().contribution(s,ProgressionCombatContext.TEAMFIGHT,List.of(b(s)),List.of(r(s)),10,2);assertThat(v).isZero();assertThat(b(s).getProgressionState().getTotalExperience()).isEqualTo(xp);}
@Test void duplicateParticipantIsSampledOnce(){GameState s=s();new CombatProgressionEvaluator().contribution(s,ProgressionCombatContext.TEAMFIGHT,List.of(b(s),b(s)),List.of(r(s)),1,0);assertThat(s.getProgressionExecutionStats().snapshot().combatSamples().getLast().ownParticipantCount()).isOne();}
@Test void deadParticipantIsAbsentFromSample(){GameState s=s();b(s).markDead(0,30);new CombatProgressionEvaluator().contribution(s,ProgressionCombatContext.TEAMFIGHT,List.of(b(s)),List.of(r(s)),1,0);assertThat(s.getProgressionExecutionStats().snapshot().combatSamples().getLast().ownParticipantCount()).isZero();}
@Test void perPlayerExperienceBreakdownUsesStructuredIdentity(){GameState s=s();b(s).getProgressionState().awardExperience(ExperienceSource.KILL,180,1);var x=s.getProgressionExecutionStats().snapshot().experienceByPlayer();assertThat(x.get(new PlayerKey(TeamSide.BLUE,Position.TOP))).containsEntry(ExperienceSource.KILL,180);assertThat(x).doesNotContainKey(new PlayerKey(TeamSide.RED,Position.TOP));}
}
