package com.lolfm.simulator;
import static org.assertj.core.api.Assertions.*;
import com.lolfm.domain.*;
import java.util.*;
import org.junit.jupiter.api.Test;
class ProgressionBoundaryTest {
 private GameState state(){return LateGameTestSupport.state();}
 @Test void everyTopQuestLevelThresholdHasExactBoundary(){for(int level=2;level<=20;level++){PlayerState p=new PlayerState("p",Position.TOP,500);p.configureProgression(TeamSide.BLUE,true,new ProgressionExecutionStats());int threshold=ProgressionRuleConfig.xpForLevel(level);p.getProgressionState().awardExperience(ExperienceSource.LANE_ECONOMY,threshold-1,1);assertThat(p.getProgressionState().getLevel()).isEqualTo(level-1);p.getProgressionState().awardExperience(ExperienceSource.LANE_ECONOMY,1,2);assertThat(p.getProgressionState().getLevel()).isEqualTo(level);}}
 @Test void everyItemThresholdHasExactBoundary(){for(ItemProgressStage stage:ItemProgressStage.values()){if(stage==ItemProgressStage.STARTING)continue;PlayerState p=new PlayerState("p",Position.TOP,500);p.configureProgression(TeamSide.BLUE,true,new ProgressionExecutionStats());int threshold=ProgressionRuleConfig.itemThreshold(stage);p.getProgressionState().awardEarnedGold(threshold-1,GoldSource.FARM,1);assertThat(p.getProgressionState().getItemStage().ordinal()).isEqualTo(stage.ordinal()-1);p.getProgressionState().awardEarnedGold(1,GoldSource.FARM,2);assertThat(p.getProgressionState().getItemStage()).isEqualTo(stage);}}
 @Test void everyItemStageUsesConfiguredPower(){GameState s=state();PlayerState p=s.getBlueTeamState().playerAt(Position.TOP);int previous=0;for(ItemProgressStage stage:ItemProgressStage.values()){int threshold=ProgressionRuleConfig.itemThreshold(stage);p.getProgressionState().awardEarnedGold(threshold-previous,GoldSource.FARM,stage.ordinal());previous=threshold;assertThat(new PlayerProgressionPowerEvaluator().evaluate(p,ProgressionCombatContext.TEAMFIGHT,true).itemPower()).isEqualTo(ProgressionRuleConfig.itemPower(stage));}}
 @Test void counterGankBlockStopsAndRestoresJungleExperience(){GameState s=state();s.advanceTimeSeconds(300);PlayerState j=s.getBlueTeamState().playerAt(Position.JUNGLE);s.jungleActionState(TeamSide.BLUE).recordCounterGankAttempt(300,Lane.TOP);new ProgressionEconomyResolver().resolve(s,300);assertThat(j.getProgressionState().getTotalExperience()).isZero();int end=s.jungleActionState(TeamSide.BLUE).getJungleFarmBlockedUntilSeconds();s.advanceTimeSeconds(end-300);new ProgressionEconomyResolver().resolve(s,end);assertThat(j.getProgressionState().getTotalExperience()).isEqualTo(60);}
 @Test void topQuestLevelTwentySnapshotUsesTerminalThresholdAndRatio(){GameState s=state();PlayerState p=s.getBlueTeamState().playerAt(Position.TOP);p.getProgressionState().awardExperience(ExperienceSource.KILL,50000,1);PlayerSnapshot x=new SnapshotFactory().create(s).getPlayerSnapshots().stream().filter(q->q.getTeamSide()==TeamSide.BLUE&&q.getPosition()==Position.TOP).findFirst().orElseThrow();assertThat(x.getLevel()).isEqualTo(20);assertThat(x.getNextLevelTotalExperience()).isEqualTo(22360);assertThat(x.getLevelProgressRatio()).isOne();}
 @Test void fullBuildSnapshotUsesTerminalThresholdAndRatio(){GameState s=state();PlayerState p=s.getBlueTeamState().playerAt(Position.TOP);p.getProgressionState().awardEarnedGold(20000,GoldSource.FARM,1);PlayerSnapshot x=new SnapshotFactory().create(s).getPlayerSnapshots().stream().filter(q->q.getTeamSide()==TeamSide.BLUE&&q.getPosition()==Position.TOP).findFirst().orElseThrow();assertThat(x.getItemStage()).isEqualTo(ItemProgressStage.FULL_BUILD);assertThat(x.getNextItemStageGold()).isEqualTo(17500);assertThat(x.getItemProgressRatio()).isOne();}
 @Test void featureOffIgnoresRewardsWithoutMutationError(){GameState s=state();s.configureProgression(false,false);PlayerState p=s.getBlueTeamState().playerAt(Position.TOP);p.getProgressionState().awardExperience(ExperienceSource.KILL,180,1);p.addGold(300,GoldSource.KILL,1);assertThat(p.getProgressionState().getTotalExperience()).isZero();assertThat(p.getProgressionState().getProgressionEarnedGold()).isZero();assertThat(s.getProgressionExecutionStats().snapshot().featureOffMutation()).isZero();}
 @Test void drainingProgressionEventsIsIdempotent(){GameState s=state();PlayerState p=s.getBlueTeamState().playerAt(Position.TOP);p.getProgressionState().awardExperience(ExperienceSource.KILL,2400,1);p.getProgressionState().awardEarnedGold(3500,GoldSource.KILL,1);List<MatchEvent> events=new ArrayList<>();s.drainProgressionEvents(events);int count=events.size();s.drainProgressionEvents(events);assertThat(events).hasSize(count);assertThat(events).filteredOn(e->e.getType()==MatchEventType.LEVEL_UP).hasSize(5);assertThat(events).filteredOn(e->e.getType()==MatchEventType.ITEM_STAGE_REACHED).hasSize(2);}
}
