import './career.css';
import { SKILL_LABELS } from '../player-data/playerAbility';
import { useEffect, useRef, useState } from 'react';
import { acceptRecordView, recordRequest, recordsSelectionKey, restoreRecordSelection } from './api/careerRecords';
import type { Award, RecordDirectory, RecordSelection, RecordSeries, RecordsView } from './api/careerRecords';
const number = (v: unknown, digits = 1) => typeof v === 'number' ? v.toLocaleString('ko-KR', { maximumFractionDigits: digits }) : '미수집';
const coverage: Record<string, string> = { COMPLETE: '수집 완료', IN_PROGRESS: '시즌 진행 중 · 현재까지 수집', OBSERVED: '관측된 성적', PARTIAL: '일부 수집', NOT_COLLECTED: '미수집', INPUT_INCOMPLETE: '심사 자료 부족', FINALIZED: '수상 확정', ACTIVE_GAME_POLICY: '게임 정책 채택', SOURCE_REVIEW: '출처 추가 확인 필요', MODEL_UNSUPPORTED: '이번 버전 미지원', NOT_ACTIVE: '현재 운영하지 않음', DO_NOT_CREATE: '미시상' };
export function CareerRecordsPanel({ careerId, year, revision, busy }: { careerId: string; year: number; revision: number; busy: boolean }) {
  const [open, setOpen] = useState(false), [directory, setDirectory] = useState<RecordDirectory | null>(null), [view, setView] = useState<RecordsView | null>(null);
  const [selection, setSelection] = useState<RecordSelection>(() => restoreRecordSelection(sessionStorage.getItem(recordsSelectionKey(careerId)), year));
  const [search, setSearch] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(false), [refresh, setRefresh] = useState(0), [page, setPage] = useState({ cursor: 0, asOf: null as number | null });
  const [award, setAward] = useState<Award | null>(null), [match, setMatch] = useState<RecordSeries | null>(null), [matchAwards, setMatchAwards] = useState<Award[]>([]), [awardCursor, setAwardCursor] = useState(0), [tab, setTab] = useState('성적'), [back, setBack] = useState<RecordSelection[]>([]);
  const generation = useRef(0), restoring = useRef(false);
  useEffect(() => {
    if (!open) return; const controller = new AbortController();
    void recordRequest<RecordDirectory>(careerId, '', controller.signal).then(d => { if (!controller.signal.aborted && d.careerId === careerId) setDirectory(d); }).catch(e => { if (!controller.signal.aborted) setError(String(e)); });
    return () => controller.abort();
  }, [careerId, open, refresh, year]);
  useEffect(() => {
    if (!open) return; const token = ++generation.current, controller = new AbortController(); setLoading(true); setError(''); setView(null); setAward(null); setMatch(null);
    sessionStorage.setItem(recordsSelectionKey(careerId), JSON.stringify(selection));
    const params = new URLSearchParams({ kind: selection.kind, entity: selection.entity, cursor: String(page.cursor), organization: String(!!selection.organization), awardCursor: String(awardCursor) });
    if (selection.year !== null) params.set('year', String(selection.year)); if (selection.competition) params.set('competition', selection.competition); if (page.asOf !== null) params.set('asOf', String(page.asOf));
    void recordRequest<RecordsView>(careerId, `/view?${params}`, controller.signal).then(v => { if (!controller.signal.aborted && token === generation.current) setView(acceptRecordView(v, careerId, selection)); }).catch(e => { if (!controller.signal.aborted && token === generation.current) setError(String(e)); }).finally(() => { if (!controller.signal.aborted && token === generation.current) setLoading(false); });
    return () => { ++generation.current; controller.abort(); };
  }, [careerId, open, selection, page, refresh, revision, awardCursor]);
  useEffect(() => {
    setMatchAwards([]); if (!match) return; const controller = new AbortController();
    void recordRequest<Award[]>(careerId, `/matches/${encodeURIComponent(match.recordId)}/awards`, controller.signal).then(a => { if (!controller.signal.aborted) setMatchAwards(a); }).catch(e => { if (!controller.signal.aborted) setError(String(e)); });
    return () => controller.abort();
  }, [careerId, match]);
  function select(next: RecordSelection) { setAwardCursor(0); setBack(v => [...v, selection]); setSelection(next); setPage({ cursor: 0, asOf: null }); }
  function player(id: string) { select({ ...selection, kind: 'PLAYER', entity: id, organization: false }); }
  function team(id: string) { select({ ...selection, kind: 'TEAM', entity: id }); }
  async function restore() {
    if (busy || restoring.current) return; restoring.current = true; const token = generation.current; const controller = new AbortController();
    try { const r = await recordRequest<{ restored: number; remaining: boolean; note: string }>(careerId, '/restore', controller.signal, 'POST'); if (token === generation.current) { setRefresh(v => v + 1); setError(`${r.restored}경기 복원. ${r.remaining ? '남은 기록은 다시 복원할 수 있습니다.' : ''} ${r.note}`); } } catch (e) { if (token === generation.current) setError(String(e)); } finally { restoring.current = false; }
  }
  const entities = selection.kind === 'TEAM' ? directory?.teams : directory?.players;
  return <section className="ca-calendar ca-records" aria-label="Career 경기 성적과 수상 기록">
    <header><div><span>CAREER RECORDS</span><strong>경기 성적 · 개인상 · 커리어</strong></div><button className="lm-secondary-button" onClick={() => setOpen(!open)}>{open ? '기록 닫기' : '기록 열기'}</button></header>
    {open ? <>
      <div className="ca-calendar__controls"><label>기록 종류 <select value={selection.kind} onChange={e => select({ ...selection, kind: e.target.value as RecordSelection['kind'], entity: '' })}><option value="ALL">전체 경기</option><option value="PLAYER">선수</option><option value="TEAM">구단</option></select></label><label>시즌 <select value={selection.year ?? 'ALL'} onChange={e => select({ ...selection, year: e.target.value === 'ALL' ? null : Number(e.target.value) })}><option value="ALL">통산</option>{(directory?.seasons ?? [year]).map(y => <option key={y} value={y}>{y}</option>)}</select></label>
      {selection.kind !== 'ALL' ? <><label>검색 <input value={search} onChange={e => setSearch(e.target.value)} placeholder="선수 또는 구단 이름" /></label><label>대상 <select value={selection.entity} onChange={e => select({ ...selection, entity: e.target.value })}><option value="">대상 선택</option>{entities?.filter(p => `${p.name} ${p.id}`.toLowerCase().includes(search.toLowerCase())).map(p => <option key={p.id} value={p.id}>{p.name} · {p.team ?? p.status}</option>)}</select></label></> : null}
      {selection.kind === 'TEAM' ? <label><input type="checkbox" checked={!!selection.organization} onChange={e => select({ ...selection, organization: e.target.checked })} />구단 전체 합산 (1군·CL / KC·KCB)</label> : null}<label>대회 <select value={selection.competition} onChange={e => select({ ...selection, competition: e.target.value })}><option value="">모든 대회</option>{[...new Set(directory?.definitions.map(d => d.scope) ?? [])].filter(v => v !== 'LCK_REGULAR').concat(['LCK_REGULAR_R1_R2', 'LCK_REGULAR_R3_R4']).map(v => <option key={v}>{v}</option>)}</select></label><button onClick={() => { setPage({ cursor: 0, asOf: null }); setRefresh(v => v + 1); }}>새로고침</button>{back.length ? <button onClick={() => { setSelection(back[back.length - 1]); setBack(v => v.slice(0, -1)); setPage({ cursor: 0, asOf: null }); }}>이전 기록으로</button> : null}</div>
      <p>관리 구단 외 해외·CL·FA·은퇴 선수까지 조회합니다. 구단 전체 합산을 선택하면 연계 팀을 함께 조회하며 당시 경기 팀별 행은 보존합니다.</p>
      <nav aria-label="기록 탭">{['성적', '챔피언', '수상', '성장·이력', '현실 참고', '시상 정책'].map(v => <button key={v} aria-current={tab === v ? 'page' : undefined} onClick={() => setTab(v)}>{v}</button>)}</nav>
      {loading ? <p role="status">선택한 범위의 기록을 읽고 있습니다.</p> : null}{error ? <p role="alert">{error}</p> : null}
      {view ? <><p>{view.collectionNote} · {coverage[view.statisticsCoverage] ?? view.statisticsCoverage} · 경기 사실 {coverage[view.factsCoverage]} · 수상 {coverage[view.awardsCoverage]} · 이력 {coverage[view.historyCoverage]}</p>{view.organization ? <p>구단 전체: 중복을 제외한 {view.organizationTotals.series} Series · {view.organizationTotals.sets}세트 · Series {view.organizationTotals.serieswins}승</p> : null}
        {tab === '성적' ? <><div className="ca-records-scroll"><table><thead><tr>{['시즌 / 대회', '당시 팀', 'Series 승/출전', '세트 승/출전', 'K / D / A', 'KDA', 'CSPM', '평점'].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{view.totals.map((r, i) => <tr key={i}><td>{r.seasonyear} / <button onClick={() => select({ ...selection, competition: String(r.competition) })}>{r.competition}</button></td><td><button onClick={() => team(String(r.team))}>{r.team}</button></td><td>{r.serieswins} / {r.series}</td><td>{r.setwins} / {r.sets}</td><td>{r.kills ?? '미수집'} / {r.deaths ?? '미수집'} / {r.assists ?? '미수집'}</td><td>{r.deaths === null ? '미수집' : Number(r.deaths) === 0 ? '무사망' : number((Number(r.kills) + Number(r.assists)) / Number(r.deaths), 2)}</td><td>{r.cs != null && Number(r.seconds) > 0 ? number(Number(r.cs) * 60 / Number(r.seconds), 2) : '미수집'}</td><td>{number(r.rating)}</td></tr>)}</tbody></table></div>
        <h4>승인된 경기 결과</h4>{view.matches.map(m => <p key={m.recordId}><button onClick={() => setMatch(m)}>{m.date} · {m.competition} · {m.firstTeam} vs {m.secondTeam}</button> · 승리 {m.winner} · {coverage[m.coverage]}</p>)}{view.matches.length === 0 ? <p>이 범위에서 수집된 출전 기록이 없습니다. 과거 미수집 여부를 함께 확인하세요.</p> : null}{view.nextCursor >= 0 ? <button onClick={() => setPage({ cursor: view.nextCursor, asOf: view.asOf })}>다음 경기 목록</button> : null}</> : null}
        {tab === '챔피언' ? <table><thead><tr><th>챔피언 / 역할</th><th>사용 / 승리</th><th>마지막 사용</th></tr></thead><tbody>{view.champions.map((c, i) => <tr key={i}><td>{c.champion} / {c.position}</td><td>{c.sets} / {c.wins}</td><td>{String(c.lastused)}</td></tr>)}</tbody></table> : null}
        {tab === '수상' ? <><p>수상 횟수: {Object.entries(view.awardCounts).map(([id, count]) => `${directory?.definitions.find(d => d.id === id)?.name ?? id}: ${count}`).join(' · ') || '확인된 수상 없음'} · 팀 수훈선수는 분석 배지로 별도 집계합니다.</p>{view.awards.map(a => <p key={a.instanceId}><button onClick={() => setAward(a)}>{a.gameYear} · {a.name} · {a.scope}</button> · {coverage[a.status]}{a.analysisBadge ? ' · 분석 배지' : ''} · {a.slots.filter(s => s.playerId).map(s => a.candidates.find(c => c.playerId === s.playerId)?.name).join(', ')}</p>)}{view.awards.length === 0 ? <p>이 범위에서 확인할 수 있는 게임 시상 기록이 없습니다.</p> : null}{view.nextAwardCursor >= 0 ? <button onClick={() => { setPage(p => ({ ...p, asOf: view.asOf })); setAwardCursor(view.nextAwardCursor); }}>다음 시상 목록</button> : null}</> : null}
        {tab === '성장·이력' ? <><GrowthChange observations={view.observations} />{view.historicalRoster.length ? <><h4>당시 실제 출전 선수</h4>{view.historicalRoster.map(p => <p key={`${p.playerid}:${p.team}`}><button onClick={() => player(p.playerid)}>{p.name}</button> · {p.team} · {p.series} Series / {p.sets}세트</p>)}</> : null}{view.observations.map((o, i) => <History key={i} observation={o} onTeam={team} onPlayer={player} />)}{!view.observations.length ? <p>관측된 성장·운영 이력이 없습니다. 과거 상태를 현재 능력치로 추정하지 않습니다.</p> : null}<p>경기 성장 보상과 시즌 총변화는 다릅니다. 시즌 총변화는 시작과 최종 마감의 내부 능력치 차이이며, 임시 시즌 마감 이후 스토브·노쇠 결과까지 포함합니다.</p></> : null}
      </> : null}
      {tab === '현실 참고' ? <Reference career={careerId} player={selection.kind === 'PLAYER' ? selection.entity : ''} /> : null}
      {tab === '시상 정책' ? <><p>2026년 조사 자료를 채택한 게임 정책입니다. 성적 점수는 실제 심사위원·팬 투표가 아닙니다. FST/EWC는 전체 대회, 결승 MVP는 실제 최종 결승만 평가합니다.</p><table><thead><tr><th>대회 / 상</th><th>적용</th><th>범위 / 자격</th></tr></thead><tbody>{directory?.definitions.map(d => <tr key={d.id}><td>{d.scope} · {d.name}</td><td>{coverage[d.status]}</td><td>{d.period} · {d.eligibility}{d.tiers.length ? ` · ${d.tiers.length * 5}슬롯` : ''}</td></tr>)}</tbody></table></> : null}
      {match ? <section aria-label="경기 성적 상세"><h4>{match.date} · {match.firstTeam} vs {match.secondTeam}</h4><p>승인된 Series 결과 · {match.games.length}세트. 이 기록에는 전체 타임라인이 보존되지 않아 여기에서 리플레이를 제공하지 않습니다.</p>{match.games.map(g => <div key={g.gameNumber}><h4>{g.gameNumber}세트 · {Math.floor(g.seconds / 60)}:{String(g.seconds % 60).padStart(2, '0')} · 승리 {g.winner}</h4><div className="ca-records-scroll"><table><thead><tr><th>선수 / 당시 팀</th><th>역할 / 챔피언</th><th>K/D/A</th><th>CS / 골드</th><th>전투 / 경제 / 사망</th><th>평점</th></tr></thead><tbody>{g.players.map(p => <tr key={p.playerId}><td><button onClick={() => player(p.playerId)}>{p.name}</button> / <button onClick={() => team(p.team)}>{p.team}</button>{p.employer && p.employer !== p.team ? <small> 원계약 {p.employer}</small> : null}</td><td>{p.statistics?.position ?? '과거 배정'} / {p.statistics?.championId ?? '성적 미수집'}</td><td>{p.statistics ? `${p.statistics.kills}/${p.statistics.deaths}/${p.statistics.assists}` : '미수집'}</td><td>{p.statistics?.cs ?? '미수집'} / {number(p.statistics?.gold, 0)}</td><td>{number(p.evaluation.combat)} / {number(p.evaluation.economy)} / {number(p.evaluation.survival)}</td><td>{number(p.evaluation.rating)}</td></tr>)}</tbody></table></div></div>)}{matchAwards.map(a => <button key={a.instanceId} onClick={() => setAward(a)}>{a.name} 선정 근거</button>)}</section> : null}
      {award ? <section aria-label="개인상 선정 근거"><h4>{award.name} · {coverage[award.status]}</h4><p>{award.reason} 평가 마감: {award.cutoffDate} · 발표: {award.publishedOn ?? '시점 미수집 또는 보류'} · 입력 {award.inputRecords.length} Series · {award.aliases.join(' / ')}</p><p>{award.tiePolicy}</p><table><thead><tr><th>후보 / 당시 팀</th><th>자격</th><th>출전 세트 / 유효 Series</th><th>선정 점수</th><th>보정 평균 / 꾸준함 / 팀 성과</th><th>수상 슬롯</th></tr></thead><tbody>{award.candidates.map(c => <tr key={c.playerId}><td><button onClick={() => player(c.playerId)}>{c.name}</button> / <button onClick={() => team(c.team)}>{c.team}</button></td><td>{c.eligibilityReason}</td><td>{c.sets} / {number(c.participation, 2)}</td><td>{number(c.score, 4)}</td><td>{c.period ? `${number(c.period.adjustedMean)} / ${number(c.period.consistency)} / ${number(c.period.teamPerformance)}` : '단일 경기 범위'}</td><td>{award.slots.filter(s => s.playerId === c.playerId).map(s => `${s.position ? ['', '퍼스트', '세컨드', '서드'][s.tier] : '수상자'} ${s.position ?? ''} · ${s.reason}`).join(', ') || '후보'}</td></tr>)}</tbody></table>{award.slots.filter(s => !s.playerId).map((s, i) => <p key={i}>{s.tier}팀 {s.position}: {s.reason}</p>)}{award.entitlements.map(e => <p key={e.playerId}>개인 포상금 권리: {number(e.amount, 0)} {e.currency} · 원화 참고 {number(e.krw, 0)}원 · 미지급{e.minimumDelayDays ? ` · 최소 ${e.minimumDelayDays}일 지연, 정확한 지급일 미확정` : ''}. 구단 예산에는 반영하지 않습니다.</p>)}</section> : null}
      <p><button className="lm-secondary-button" disabled={busy} onClick={() => { void restore(); }}>보존된 과거 경기 기록 복원</button> · 한 번에 최대 20경기. 누락된 성적을 새 경기로 만들어 채우지 않습니다.</p>
    </> : null}
  </section>;
}
function History({ observation: o, onTeam, onPlayer }: { observation: RecordsView['observations'][number]; onTeam: (id: string) => void; onPlayer: (id: string) => void }) {
  const v = o.value;
  if (o.kind.startsWith('EVENT:')) return <p>{String(v.date)} · {String(v.kind)} · {v.playerId ? <button onClick={() => onPlayer(String(v.playerId))}>{String(v.name)}</button> : null} · <button onClick={() => onTeam(String(v.team))}>{String(v.team)}</button> · {String(v.reason ?? '')}</p>;
  if (o.kind.startsWith('PLACEMENT:')) return <p>{o.seasonYear} · {String(v.competition)} · <button onClick={() => onTeam(String(v.team))}>{String(v.team)}</button> · {String(v.kind).startsWith('REGULAR_GROUP_RANK:') ? `정규 조별 순위 (${String(v.kind).split(':')[1]})` : v.kind === 'REGULAR_RANK' ? '정규 순위' : v.kind === 'QUALIFICATION_RESULT' ? '진출 단계 결과' : '최종 순위'} {String(v.from)}{v.from !== v.through ? `~${String(v.through)}` : ''}위</p>;
  if (o.kind.startsWith('TITLE:')) return <div><p>{o.seasonYear} · {String(v.competition)} 우승 · <button onClick={() => onTeam(String(v.winner))}>{String(v.winner)}</button> · 실제 기여 선수 {Array.isArray(v.contributors) ? v.contributors.length : '미수집'}명 · {coverage[String(v.coverage)]}</p><p>우승 기여: {Array.isArray(v.contributors) ? v.contributors.map(id => <button key={String(id)} onClick={() => onPlayer(String(id))}>{String(id)}</button>) : '미수집'}</p><p>등록 후보: {Array.isArray(v.bench) ? v.bench.map(id => <button key={String(id)} onClick={() => onPlayer(String(id))}>{String(id)}</button>) : '미수집'}</p></div>;
  const ratings = v.internalRatings as Record<string, number> | undefined;
  return <details><summary>{o.seasonYear} · {o.kind === 'OPENING' ? '시즌 시작 관측' : o.kind === 'CLOSING_FINAL' ? '시즌 최종 마감' : o.kind.replace('MONTH:', '월말 관측 ')}{ratings ? ` · 능력치 합계 ${number(Object.values(ratings).reduce((a, b) => a + b, 0) / 1000, 3)}` : ''}</summary>{ratings ? <><p>관측 당시의 소수 진행을 포함합니다. CA 수치와는 구분합니다.</p><table><thead><tr><th>능력치</th><th>관측값 / 20</th></tr></thead><tbody>{Object.entries(ratings).map(([key, value]) => <tr key={key}><td>{SKILL_LABELS[key] ?? key}</td><td>{number(value / 1000, 3)}</td></tr>)}</tbody></table><p>피로 {number(Number(v.fatigue) / 10)} / 100</p><details><summary>당시 챔피언 숙련도</summary>{Object.entries((v.internalProficiencies ?? {}) as Record<string, number>).map(([key, value]) => <p key={key}>{key.replace('|', ' · ')}: {number(value / 1000, 3)} / 20</p>)}</details></> : <p>선수별 성장 관측을 선택해 주세요.</p>}</details>;
}

function Reference({ career, player }: { career: string; player: string }) {
  const [value, setValue] = useState<Record<string, unknown> | null>(null);
  useEffect(() => { setValue(null); if (!player) return; const controller = new AbortController(); void recordRequest<Record<string, unknown>>(career, `/players/${encodeURIComponent(player)}/reference`, controller.signal).then(v => { if (!controller.signal.aborted) setValue(v); }).catch(() => {}); return () => controller.abort(); }, [career, player]);
  const honors = value?.honors as Record<string, unknown> | undefined, history = value?.career as Record<string, unknown> | undefined;
  const render = (v: unknown): string => v == null ? '미확인' : typeof v === 'object' ? Array.isArray(v) ? v.map(render).join(' · ') : Object.entries(v).map(([key, x]) => `${key}: ${render(x)}`).join(' / ') : String(v);
  return <section><h4>원본 현실 참고 이력</h4><p>조사 당시의 작성 자료입니다. 이 Career에서 발생한 경기·수상과 합산하지 않습니다.</p>{player ? <><p>팀 경력: {render(history?.teamHistory)}</p><p>팀 수상: {render(honors?.teamAchievements)}</p><p>개인 수상: {render(honors?.individualAwards)}</p></> : <p>선수를 선택하면 원본 참고 이력을 확인할 수 있습니다.</p>}</section>;
}

function GrowthChange({ observations }: { observations: RecordsView['observations'] }) {
  const sum = (v: unknown) => v && typeof v === 'object' ? Object.values(v).reduce<number>((a, x) => a + (typeof x === 'number' ? x : 0), 0) : null;
  return <>{observations.filter(o => o.kind === 'OPENING').map(open => {
    const close = observations.find(o => o.seasonYear === open.seasonYear && o.kind === 'CLOSING_FINAL');
    const before = sum(open.value.internalRatings), after = sum(close?.value.internalRatings);
    return <p key={open.seasonYear}>{open.seasonYear} 시즌 총변화: {before !== null && after !== null ? `능력치 합계 ${after - before >= 0 ? '+' : ''}${number((after - before) / 1000, 3)}` : '최종 마감 관측 전 · 아직 확정하지 않음'}. 경기 성장 보상 합계와 구분합니다.</p>;
  })}</>;
}
