import { PlayerPortrait } from '../team-player/components/PlayerPortrait';
import { useEffect,useRef,useState } from 'react';
import { PlayerDetails } from './CareerRosterPanel';
import { CareerRecordsPanel } from './CareerRecordsPanel';
import { SKILL_LABELS,currentAbility } from '../player-data/playerAbility';
import { careerMoney } from './careerMoney';
import { comparisonSkills,restoreScouting,scoutLink,scoutingRequest,type Candidate,type Comparison,type ScoutFinance,type ScoutPage,type Opponent } from './api/careerScouting';
import type { InboxLink } from './api/careerInbox';
const money=(v:number|null|undefined)=>v==null?'미확인':careerMoney(v);
const stateName=(s:string)=>({CONTRACTED:'계약 중',FREE_AGENT:'FA',UNAVAILABLE:'소속·자격 미확인',RETIRED:'은퇴',FIRST_TEAM:'1군',DEVELOPMENT:'육성',UNCONFIRMED:'소속 미확인',UNAFFILIATED:'무소속'}[s]??s);
const commonSkills=new Set(['MECHANICS','DECISION_MAKING','MAP_AWARENESS','POSITIONING','COMBAT_EXECUTION','CONSISTENCY']);
const roles=['TOP','JUNGLE','MID','ADC','SUPPORT'];
export function CareerScoutingPanel({careerId,year,revision,busy,onNavigate,showOpponent=0}:{careerId:string;year:number;revision:number;busy:boolean;onNavigate:(link:InboxLink)=>void;showOpponent?:number}){
 const key=`lolfm.scouting.v1.${careerId}`,initial=useRef(restoreScouting(sessionStorage.getItem(key)));
 const [filters,setFilters]=useState(initial.current.filters),[chosen,setChosen]=useState(initial.current.chosen),[page,setPage]=useState<ScoutPage|null>(null),[comparison,setComparison]=useState<Comparison|null>(null),[detail,setDetail]=useState<Candidate|null>(null),[error,setError]=useState(''),[pending,setPending]=useState(false),[request,setRequest]=useState({cursor:0,asOf:'',refresh:0}),[statYear,setStatYear]=useState(year),[competition,setCompetition]=useState(''),[opponentOpen,setOpponentOpen]=useState(false);
 useEffect(()=>{if(showOpponent>0)setOpponentOpen(true);},[showOpponent]);
 const generation=useRef(0),action=useRef<AbortController|null>(null);
 useEffect(()=>{sessionStorage.setItem(key,JSON.stringify({filters,chosen}));},[key,filters,chosen]);
 useEffect(()=>{const c=new AbortController(),token=++generation.current;setPage(null);setError('');const q=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==''));q.set('cursor',String(request.cursor));if(request.asOf)q.set('asOf',request.asOf);void scoutingRequest<ScoutPage>(careerId,`?${q}`,c.signal).then(v=>{if(!c.signal.aborted&&token===generation.current){if(v.careerId!==careerId)throw new Error('Career 범위 불일치');setPage(v);}}).catch(e=>{if(!c.signal.aborted)setError(String(e));});return()=>{++generation.current;c.abort();action.current?.abort();setPending(false);};},[careerId,revision,filters,request]);
 useEffect(()=>()=>action.current?.abort(),[]);
 useEffect(()=>{setComparison(null);setDetail(null);},[careerId,revision]);
 const reset=()=>setRequest(r=>({cursor:0,asOf:'',refresh:r.refresh+1}));
 const filter=(k:string,v:string)=>{setFilters(f=>({...f,[k]:v}));reset();};
 const cancelComparison=()=>{action.current?.abort();setPending(false);};
 const select=(id:string)=>{setComparison(null);setChosen(old=>old.includes(id)?old.filter(p=>p!==id):old.length<4?[...old,id]:old);cancelComparison();};
 async function interest(p:Candidate){if(pending)return;const c=new AbortController();action.current=c;setPending(true);try{await scoutingRequest(careerId,'/interest',c.signal,{playerId:p.player.playerId,expectedRevision:p.interest.revision,selected:!p.interest.selected});if(!c.signal.aborted)reset();}catch(e){if(!c.signal.aborted)setError(String(e));}finally{if(!c.signal.aborted)setPending(false);}}
 async function compare(){const c=new AbortController(),token=generation.current;action.current?.abort();action.current=c;setPending(true);setError('');setComparison(null);try{const v=await scoutingRequest<Comparison>(careerId,`/compare?${new URLSearchParams({players:chosen.join(','),year:String(statYear),competition})}`,c.signal);if(!c.signal.aborted&&token===generation.current&&v.careerId===careerId)setComparison(v);}catch(e){if(!c.signal.aborted)setError(String(e));}finally{if(!c.signal.aborted)setPending(false);}}
 const chosenPosition=page?.players.find(p=>chosen.includes(p.player.playerId))?.player.position??comparison?.players[0]?.player.position??filters.position;
 const field=(key:string,label:string,type='number')=><label>{label}<input type={type} value={filters[key]??''} onChange={e=>filter(key,e.target.value)}/></label>;
 return <section className="ca-calendar ca-scouting" aria-label="Career 스카우팅"><header><div><span>SCOUTING</span><strong>선수 검색 · 관심 목록 · 후보 비교</strong></div><button onClick={reset}>검색 새로고침</button><button onClick={()=>setOpponentOpen(v=>!v)}>다음 상대 분석</button></header><p>현재 Career에 공개된 기량과 기존 견적입니다. PA는 성장 천장 참고이며 자동 영입 점수에 사용하지 않습니다. 조회·관심 등록은 게임 진행을 변경하지 않습니다.</p>
 {error?<p role="alert">{error}</p>:null}<div className="ca-scouting__filters">{field('search','이름 검색','search')}<label>포지션<select value={filters.position??''} onChange={e=>filter('position',e.target.value)}><option value="">전체</option>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>소속·배치<select value={filters.status??''} onChange={e=>filter('status',e.target.value)}><option value="">활동 선수 전체</option>{['STARTER','BENCH','FIRST_TEAM','DEVELOPMENT','FREE_AGENT','UNCONFIRMED','UNAVAILABLE','RETIRED'].map(s=><option key={s} value={s}>{s==='STARTER'?'현재 선발':s==='BENCH'?'1군 후보':stateName(s)}</option>)}</select></label><label>구단<select value={filters.team??''} onChange={e=>filter('team',e.target.value)}><option value="">전체 구단</option>{Object.entries(page?.teams??{}).map(([id,name])=><option key={id} value={id}>{id} · {name}</option>)}</select></label>{field('region','지역 코드','text')}{field('ageMin','게임 나이 최소')}{field('ageMax','게임 나이 최대')}{field('caMin','CA 최소')}{field('caMax','CA 최대')}<label>능력치<select value={filters.skill??''} onChange={e=>filter('skill',e.target.value)}><option value="">선택 안 함</option>{Object.entries(SKILL_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{field('skillMin','능력치 최소')}{field('champion','챔피언 ID','text')}{field('proficiencyMin','숙련도 최소')}{field('expiryFrom','만료 시작','date')}{field('expiryThrough','만료 끝','date')}{field('salaryMax','요구 연봉 상한(원)')}{field('feeMax','제안용 이적료 상한(원)')}<label>정렬<select value={filters.sort??'ca'} onChange={e=>filter('sort',e.target.value)}>{[['ca','CA'],['age','게임 나이'],['expiry','만료일'],['salary','요구 연봉'],['fee','제안용 이적료']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>순서<select value={filters.direction??'desc'} onChange={e=>filter('direction',e.target.value)}><option value="desc">높은 값 먼저</option><option value="asc">낮은 값 먼저</option></select></label>{[['watch','관심 선수만'],['negotiable','현재 협상 경로 있음'],['unknown','조건의 미확인 값 포함']].map(([k,label])=><label key={k}><input type="checkbox" checked={filters[k]==='true'} onChange={e=>filter(k,String(e.target.checked))}/>{label}</label>)}</div>
 <p>{page?`${page.date} 현재 · 전체 ${page.population}명 중 조건 ${page.total}명 · 미확인 값은 정렬 마지막`:'현재 선수 조회 중…'}</p><Finance finance={page?.finance}/><div className="ca-scouting__table"><table><thead><tr><th>관심</th><th>비교</th><th>선수</th><th>역할</th><th>CA / PA</th><th>게임 나이</th><th>소속 · 상태</th><th>요구 연봉</th><th>계약 만료</th></tr></thead><tbody>{page?.players.map(p=><tr key={p.player.playerId}><td><button disabled={pending} onClick={()=>void interest(p)}>{p.interest.selected?'관심 해제':'관심 등록'}</button></td><td><input aria-label={`${p.player.nickname} 비교`} type="checkbox" checked={chosen.includes(p.player.playerId)} disabled={!chosen.includes(p.player.playerId)&&chosen.length===4} onChange={()=>select(p.player.playerId)}/></td><td><PlayerPortrait playerId={p.player.playerId} nickname={p.player.nickname} size="thumbnail"/><button onClick={()=>setDetail(p)}>{p.player.nickname}</button>{p.source==='GENERATED'?' · 생성 신인':''}</td><td>{p.player.position}</td><td>{p.ca} / {p.pa??'미입력'}</td><td>{p.age??'미확인'} · {p.ageBasis}</td><td>{p.membership?.ownerTeam??'소속 미확인'} · {stateName(p.status)} · {p.starter?'선발':stateName(p.membership?.squad??'UNCONFIRMED')}</td><td>{money(p.market?.askingSalary)}</td><td>{p.expires??'미확인·현재 계약 없음'}</td></tr>)}</tbody></table></div>{page&&page.nextCursor>=0?<button onClick={()=>setRequest(r=>({...r,cursor:page.nextCursor,asOf:page.asOf}))}>다음 선수 페이지</button>:null}
 <div className="ca-calendar__controls"><strong>비교 {chosen.length}/4명</strong><button disabled={!chosenPosition||!page?.starterByPosition[chosenPosition]} onClick={()=>{const id=page?.starterByPosition[chosenPosition];if(id&&!chosen.includes(id))select(id);}}>우리 팀 같은 포지션 선발 추가</button><button onClick={()=>{setChosen([]);setComparison(null);cancelComparison();}}>비교 비우기</button><label>성적 시즌<input type="number" value={statYear} onChange={e=>{setStatYear(Number(e.target.value));setComparison(null);cancelComparison();}}/></label><label>대회 코드<input value={competition} placeholder="전체 대회 · 당시 팀별 구분" onChange={e=>{setCompetition(e.target.value);setComparison(null);cancelComparison();}}/></label><button disabled={pending||chosen.length<2} onClick={()=>void compare()}>선택 선수 비교</button></div>
 {detail?<><PlayerDetails player={detail.player}/><button onClick={()=>setDetail(null)}>선수 상세 닫기</button></>:null}
 {comparison?<ComparisonView value={comparison} busy={busy} onNavigate={onNavigate}/>:null}
 {opponentOpen?<OpponentPanel careerId={careerId} year={year} busy={busy} onNavigate={onNavigate}/>:null}
 </section>;
}
function Finance({finance}:{finance:ScoutFinance|null|undefined}){return finance?<p>우리 구단 현금 {money(finance.cash)} · 지급 여유 {money(finance.paymentHeadroom)} · 연봉 예산 잔여 {money(finance.annualBudget-finance.committedPeakSalary)} · 미지급 급여 {money(finance.salaryArrears)}</p>:null;}
function ComparisonView({value:v,busy,onNavigate}:{value:Comparison;busy:boolean;onNavigate:(link:InboxLink)=>void}){
 const [record,setRecord]=useState<InboxLink|null>(null),[champion,setChampion]=useState('');const names=v.players.map(p=>p.player.nickname);const row=(label:string,values:React.ReactNode[])=><tr key={label}><th>{label}</th>{values.map((x,i)=><td key={i}>{x}</td>)}</tr>;
 return <section aria-label="영입 후보 비교"><h3>{names.join(' · ')} 비교</h3><p>기량·가격 {v.date} 현재 / 성적 {v.statisticsYear} · {v.competition||'전체 대회, 당시 팀별 구분'}. 견적은 영입 확정 가능 여부가 아닙니다.</p><Finance finance={v.finance}/><label>비교 챔피언 ID<input value={champion} onChange={e=>setChampion(e.target.value)}/></label><div className="ca-scouting__table"><table><thead><tr><th>항목</th>{names.map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{row('CA / PA',v.players.map(p=>`${p.ca} / ${p.pa??'미입력'}`))}{row('게임 나이 · 기준',v.players.map(p=>`${p.age??'미확인'} · ${p.ageBasis}`))}{comparisonSkills(v.players).map(skill=>row(`${commonSkills.has(skill)?'공통':'역할'} · ${SKILL_LABELS[skill]??skill}`,v.players.map(p=>{const value=p.player.gameplay.ratings[skill],delta=value-v.players[0].player.gameplay.ratings[skill];return `${value} (${delta>=0?'+':''}${delta})`;})))}{champion?row(`${champion} 숙련도`,v.players.map(p=>p.player.gameplay.proficiencies.find(c=>c.championId===champion&&c.position===p.player.position)?.value??'미수집')):null}{row('선택 가능 챔피언 숙련도',v.players.map(p=><details><summary>역할·챔피언 ID 기준</summary>{p.player.gameplay.proficiencies.map(c=><span key={c.championId}>{c.championId} {c.value} · </span>)}</details>))}{row('현재 연봉',v.players.map(p=>money(p.salary)))}{row('새 계약 요구 연봉',v.players.map(p=>money(p.market?.askingSalary)))}{row('기준 연봉 / 추정 가치',v.players.map(p=>`${money(p.quote?.referenceSalary)} / ${money(p.quote?.estimatedValue)}`))}{row('제안용 이적료',v.players.map(p=>p.status==='CONTRACTED'?money(p.quote?.suggestedTransferFee):'현재 계약 없음 · 이적료 견적 해당 없음'))}{row('실제 합의 금액',v.players.map(()=> '이 화면은 공개 견적 · 실제 합의는 협상 원본 확인'))}{row('계약 만료 / 협상 시작 가능일',v.players.map(p=>`${p.expires??'미확인'} / ${p.market?.availableStart??p.quote?.earliestStart??'미확인'}`))}{row('현재 자격',v.players.map(p=>p.quote?.unavailableReason??p.market?.eligibilityReason??'협상에서 상대·선수 동의와 예산·등록 재검사'))}{row('기존 협상',v.players.map(p=><button disabled={busy||p.status==='RETIRED'||p.status==='UNAVAILABLE'} onClick={()=>onNavigate(scoutLink(p,v.activeYear,v.finance?.team??''))}>{p.membership?.ownerTeam===v.finance?.team?'재계약 확인':p.status==='FREE_AGENT'?'FA 계약 확인':'이적·임대 확인'}</button>))}</tbody></table></div>
 <p>능력치 차이는 첫 후보 기준이며 CA가 높아도 모든 능력치가 우위라는 뜻은 아닙니다. 공통·포지션 능력치는 실제 이름으로 대응합니다. 선발 교체·제안 제출·비용 예약은 실행하지 않습니다.</p>
 {v.players.map(p=>{const stats=v.statistics.filter(r=>r.playerid===p.player.playerId);return <article key={p.player.playerId}><h4>{p.player.nickname} 관측 성적</h4>{stats.length?stats.map((r,i)=><p key={i}>{String(r.competition)} · 당시 {String(r.team)} · {String(r.series)} Series / {String(r.sets)}세트 / {String(r.wins)}승 · K/D/A {r.kills==null?'미수집':`${r.kills}/${r.deaths}/${r.assists}`} ({String(r.kdaobservedunits)} 관측) · CSPM {r.observedcspm==null?'미수집':Number(r.observedcspm).toFixed(2)} ({String(r.csobservedunits)}/{String(r.sets)}세트) · 평점 {Array.isArray(r.ratings)&&r.ratings.length?r.ratings.map((x:{mean:number;count:number;version:string})=>`${x.mean.toFixed(2)} (${x.count} 관측 · ${x.version})`).join(' / '):'미수집'}</p>):<p>선택 범위 성적 미수집</p>}<p>{v.champions.filter(r=>r.playerid===p.player.playerId).map(r=>`${r.competition}/${r.team}: ${r.champion} ${r.wins}/${r.sets}승`).join(' · ')}</p><p>{growthChange(v.growth[p.player.playerId]??[])} · 성장 관측 {(v.growth[p.player.playerId]??[]).length}개 · {(v.growth[p.player.playerId]??[]).some(o=>o.kind==='CLOSING_FINAL')?'최종 마감 포함':'최종 마감 관측 전 또는 미수집'}</p><button onClick={()=>setRecord({panel:'RECORDS',playerId:p.player.playerId,sourceId:null,competition:v.competition,seasonYear:v.statisticsYear,seriesId:null,positions:[]})}>성장·경기 근거 보기</button>{v.awards.filter(a=>a.playerId===p.player.playerId).map(a=><button key={a.instanceId} onClick={()=>setRecord({panel:'AWARDS',playerId:p.player.playerId,sourceId:a.instanceId,competition:null,seasonYear:v.statisticsYear,seriesId:null,positions:[]})}>{a.name}</button>)}</article>;})}{record?<CareerRecordsPanel careerId={v.careerId} year={v.statisticsYear} revision={0} busy={busy} focus={record}/>:null}
 </section>;
}
function growthChange(observations:Comparison['growth'][string]){
 const ca=(observation:Comparison['growth'][string][number]|undefined)=>{const value=observation?.value as {internalRatings?:Record<string,number>}|undefined;if(!value?.internalRatings)return null;try{return currentAbility(Object.fromEntries(Object.entries(value.internalRatings).map(([k,n])=>[k,Math.trunc(n/1000)])));}catch{return null;}};
 const opening=ca(observations.find(o=>o.kind==='OPENING')),closing=ca(observations.find(o=>o.kind==='CLOSING_FINAL'));
 return opening==null?'시작 기량 미수집':closing==null?`시작 CA ${opening} · 최종 기량 미수집`:`보존 시작/최종 CA ${opening} → ${closing} (${closing-opening>=0?'+':''}${closing-opening})`;
}
function OpponentPanel({careerId,year,busy,onNavigate}:{careerId:string;year:number;busy:boolean;onNavigate:(link:InboxLink)=>void}){
 const [view,setView]=useState<Opponent|null>(null),[q,setQ]=useState({year:String(year),team:'',competition:'',limit:'5'}),[error,setError]=useState(''),[record,setRecord]=useState<InboxLink|null>(null);const generation=useRef(0);
 useEffect(()=>{const c=new AbortController(),token=++generation.current;setView(null);setError('');const params=new URLSearchParams(Object.entries(q).filter(([,v])=>v!==''));void scoutingRequest<Opponent>(careerId,`/opponent?${params}`,c.signal).then(v=>{if(!c.signal.aborted&&token===generation.current&&v.careerId===careerId)setView(v);}).catch(e=>{if(!c.signal.aborted)setError(String(e));});return()=>{++generation.current;c.abort();};},[careerId,q]);
 async function prepare(){const c=new AbortController(),token=generation.current;try{const fresh=await scoutingRequest<Opponent>(careerId,'/opponent',c.signal);if(token!==generation.current)return;if(!fresh.next||fresh.next.fixtureId!==view?.next?.fixtureId){setError('다음 경기가 변경됐습니다. 분석을 새로 확인하세요.');setView(fresh);return;}onNavigate({...fresh.next.link,current:true});}catch(e){if(token===generation.current)setError(String(e));}}
 const frequency=(label:string,items:Record<string,number>,denominator:number)=><p>{label}: {Object.entries(items).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).map(([id,count])=>`${id} ${count}/${denominator}세트`).join(' · ')||'미수집'}</p>;
 return <section aria-label="다음 상대 분석"><h3>다음 상대 · 승인 경기 분석</h3><div className="ca-calendar__controls">{[['year','기록 시즌'],['team','팀 코드(빈칸은 다음 상대)'],['competition','대회 코드(빈칸은 다음 경기 대회)']].map(([key,label])=><label key={key}>{label}<input value={q[key as keyof typeof q]} onChange={e=>setQ(old=>({...old,[key]:e.target.value}))}/></label>)}<label>최근 Series<select value={q.limit} onChange={e=>setQ(old=>({...old,limit:e.target.value}))}><option>5</option><option>10</option></select></label></div>{error?<p role="alert">{error}</p>:null}{view?<><p>{view.next?`${view.next.date} · ${view.next.first??'미확정'} vs ${view.next.second??'미확정'} · ${view.next.state}`:'다음 관리 대진 미확정 또는 일정 완료'}</p><button disabled={busy||!view.next} onClick={()=>void prepare()}>기존 경기 준비 화면으로</button><p>{view.currentDate} 현재 선발: {view.currentStarters.map(id=>view.names[id]??id).join(', ')||'미확인'}</p><p>선택 대회 등록 후보: {view.registered.map(id=>view.names[id]??id).join(', ')||'보존 등록 자료 미수집'}</p><p>시작된 Series 고정 선수: {view.frozen.map(id=>view.names[id]??id).join(', ')||'시작 전 또는 고정 자료 미수집'}</p><p>{view.year} · {view.competition||'전체 대회'} · {view.team??'상대 미확정'} · 최근 {view.series} Series({view.seriesWins}승), {view.sets}세트({view.wins}승). 밴픽 {view.draftSets}/{view.sets}세트 관측 · BLUE {view.blueSets}, RED {view.draftSets-view.blueSets}.</p>{frequency('최종 포지션별 픽',view.picks,view.draftSets)}{frequency('직접 한 밴',view.bansBy,view.draftSets)}{frequency('상대를 대상으로 한 밴',view.bansAgainst,view.draftSets)}<details><summary>반복 조합</summary>{frequency('관측 조합',view.combinations,view.draftSets)}</details><p>Hard Fearless의 앞 세트 픽은 이후 사용 불가입니다. 빈도는 관측 사실이며 선택 기회 보정 선호도나 다음 경기 확률이 아닙니다. 현재 숙련도와 과거 구단 기록은 별도입니다.</p>{view.games.map(g=><article key={`${g.recordId}:${g.gameNumber}`}><button onClick={()=>setRecord({panel:'RECORDS',playerId:null,sourceId:g.recordId,competition:g.competition,seasonYear:view.year,seriesId:null,positions:[],teamId:view.team})}>{g.date} · vs {g.against} · {g.gameNumber}세트 · {g.won?'승':'패'} · {g.seconds}초</button><p>{g.draft?`${g.draft.blue===view.team?'BLUE':'RED'} · 첫 픽 ${g.draft.firstPickTeam}/${g.draft.firstPick} · ${g.draft.rule} · 이전 사용 불가 ${g.draft.unavailableBefore.join(', ')||'없음'} · 엔진 ${g.draft.engine}`:'밴픽 미수집 · 0회로 집계하지 않음'}</p><p>{g.performances.map(p=>`${view.names[p.playerId]??p.playerId}: ${p.statistics?`${p.statistics.kills}/${p.statistics.deaths}/${p.statistics.assists}`:'KDA 미수집'} · 평점 ${p.evaluation.rating??'미수집'} (${p.evaluation.version})`).join(' · ')}</p>{g.draft?.picks.filter(p=>p.team===view.team).map(p=><button key={p.playerId} onClick={()=>setRecord({panel:'RECORDS',playerId:p.playerId,sourceId:null,competition:g.competition,seasonYear:view.year,seriesId:null,positions:[]})}>{view.names[p.playerId]??p.playerId} {p.position} · {p.championId}</button>)}</article>)}{record?<CareerRecordsPanel careerId={careerId} year={view.year} revision={0} busy={busy} focus={record}/>:null}</>:<p>승인 기록 확인 중…</p>}</section>;
}
