import { useEffect, useRef, useState } from 'react';
import { CareerApiFailure, getCareerLifecycle } from './api/careerApi.client';
import { filterLifecycle, lifecycleStatusName } from './api/careerLifecycle.contract';
import type { CareerLifecycle } from './api/careerLifecycle.contract';
const positionNames: Record<string, string> = { TOP: '탑', JUNGLE: '정글', MID: '미드', ADC: '원딜', SUPPORT: '서포터' };
const supplyText = (v: Record<string, number>) => Object.entries(v).map(([p, n]) => `${positionNames[p] ?? p} ${n}`).join(' · ');
export function CareerLifecyclePanel({ careerId, year, revision, historical, busy, onMarket }: { careerId: string; year: number; revision: number; historical: boolean; busy: boolean; onMarket: (id: string) => void }) {
  const [view, setView] = useState<CareerLifecycle | null>(null), [error, setError] = useState(''), [filter, setFilter] = useState('announced'), [search, setSearch] = useState(''), [selected, setSelected] = useState('');
  const generation = useRef(0);
  useEffect(() => { setView(null); setSelected(''); setFilter('announced'); setSearch(''); }, [careerId, year]);
  useEffect(() => { const controller = new AbortController(), token = ++generation.current; setError(''); void getCareerLifecycle(careerId, year, controller.signal).then(v => { if (!controller.signal.aborted && token === generation.current) { if (v.careerId !== careerId || v.seasonYear !== year) throw new Error('생애주기 조회 범위가 다릅니다.'); setView(v); } }).catch(e => { if (!controller.signal.aborted && token === generation.current) setError(e instanceof CareerApiFailure ? e.userMessage : String(e)); }); return () => { controller.abort(); ++generation.current; }; }, [careerId, year, revision]);
  const visible = filterLifecycle(view?.players ?? [], filter).filter(p => `${p.nickname} ${p.playerId}`.toLowerCase().includes(search.toLowerCase()));
  const player = view?.players.find(p => p.playerId === selected), life = player?.lifecycle;
  return <details className="ca-training" id="career-lifecycle"><summary>시즌 성장·은퇴·신인</summary>
    {error ? <p role="alert">{error}</p> : null}{!view ? <p>시즌 선수 변화 확인 중…</p> : <>
      <p>{view.date} 기준 · 현역 {view.activeCount}명 · 은퇴 기록 {view.archivedCount}명{historical ? ' · 과거 마감 기록 (읽기 전용)' : ''}</p>
      {view.reviews.length === 0 ? <p>아직 시즌 심사를 하지 않았습니다. 필수 대회 결과가 모두 반영된 뒤 계약 시장의 ‘스토브 진입’에서 심사합니다.</p> : view.reviews.map(r => <section key={r.seasonYear} aria-label="시즌 심사 요약"><h4>{r.seasonYear} 시즌 심사 · {r.reviewedOn}</h4>{r.kind === 'LEGACY_STOVE_NO_RETROACTIVE_REVIEW' ? <p>이미 열린 스토브에 기능이 도입되어 이 시즌은 소급 심사하지 않았습니다.</p> : <><p>은퇴 발표 {r.changes.filter(c => c.outcome === 'RETIREMENT_ANNOUNCED').length}명 · 신인 {r.rookieIds.length}명 · 해외·육성팀 및 충분히 관측되지 않은 기간은 미출전 불이익을 적용하지 않습니다.</p>{r.supply ? <><p>예상 현역 {r.supply.projectedActive}명 · 정상 공급 {r.supply.normalCount}명 · 부족 대응 {r.supply.emergencyCount}명</p><p>다음 계약 기준 구단 공백: {supplyText(r.supply.missingByPosition)}</p><p>신인 배분: {supplyText(r.supply.generatedByPosition)}</p><p>공급 후 미해결: {supplyText(r.supply.unresolvedByPosition)}. 공급 인원은 계약 성사를 보장하지 않습니다.</p></> : null}<p>우리 팀 선수가 은퇴하면 명부에서 대체 주전을 직접 지정하세요. <a href="#career-contract-market">계약 시장</a> · <a href="#career-roster">선수 명부</a></p></>}</section>)}
      <label>선수 구분 <select value={filter} onChange={e => { setFilter(e.target.value); setSelected(''); }}><option value="announced">은퇴 발표</option><option value="rookies">생성 신인</option><option value="retired">은퇴 선수</option><option value="all">전체 선수</option></select></label>
      <label>선수 검색 <input value={search} onChange={e => setSearch(e.target.value)} /></label>
      <label>선수 변화 <select value={selected} onChange={e => setSelected(e.target.value)}><option value="">{visible.length ? `${visible.length}명 · 선수 선택` : '해당 선수 없음'}</option>{visible.map(p => <option key={p.playerId} value={p.playerId}>{p.nickname} · {positionNames[p.position]} · {p.gameAge}세 · CA {p.currentCA} / PA {p.potentialAbility ?? '미입력'} · {lifecycleStatusName[p.lifecycle.status]}</option>)}</select></label>
      {player && life ? <section aria-label="생애주기 선수 상세"><h4>{player.nickname} · {positionNames[player.position]}</h4><p>{player.playerId}</p><p>{life.source === 'GENERATED' ? `게임 생성 신인 · ${life.intakeYear} 클래스` : '작성 선수'} · {player.gameAge}세 ({life.age.publicBirthDate ? '공개 생일' : life.source === 'GENERATED' ? '게임 생성 생일' : '게임 추정 생일'}) · {life.age.simulationBirthDate}</p><p>현재 CA {player.currentCA} / PA {player.potentialAbility ?? '미입력'} · 관측 최고 CA {life.peakCA} ({life.peakObservedSince}부터 관측)</p><p>시즌 능력치 총량: 성장 +{(player.seasonGrowth / 1000).toFixed(3)} · 노쇠화 −{(player.seasonDecline / 1000).toFixed(3)} · 순변화 {player.seasonNet >= 0 ? '+' : ''}{(player.seasonNet / 1000).toFixed(3)}. 12개 능력치 합계 기준이며 표시 CA 변화와 다릅니다.</p><p>{lifecycleStatusName[life.status]}{life.effectiveOn ? ` · 효력일 ${life.effectiveOn}` : ''} · {life.reason}</p><p>다음 심사로 넘기는 노쇠화 소수 예산 {(life.declineRemainder / 1000).toFixed(3)} · 연속 관측 미출전 {life.noAppearanceSeasons}시즌</p>{!historical && life.status !== 'RETIRED' ? <button disabled={busy} onClick={() => onMarket(player.playerId)}>이 선수 계약 시장에서 보기</button> : null}</section> : null}
    </>}
  </details>;
}
