-- Verified compact adjuncts; old Match/receipt canonical forms remain unchanged.
CREATE TABLE career_game_statistics (
 series_id VARCHAR(80) NOT NULL, game_number INTEGER NOT NULL,
 output_hash CHAR(64) NOT NULL, statistics_json CLOB NOT NULL, statistics_hash CHAR(64) NOT NULL,
 PRIMARY KEY(series_id,game_number)
);
CREATE TABLE career_record_series (
 record_id CHAR(64) PRIMARY KEY, career_id VARCHAR(80) NOT NULL, season_year INTEGER NOT NULL,
 origin_identity VARCHAR(256) NOT NULL, competition_id VARCHAR(64) NOT NULL, stage_id VARCHAR(64) NOT NULL,
 fixture_id VARCHAR(96) NOT NULL, series_id VARCHAR(80) NOT NULL, played_date DATE NOT NULL,
 receipt_hash CHAR(64) NOT NULL, winner_team VARCHAR(32) NOT NULL, first_team VARCHAR(32) NOT NULL, second_team VARCHAR(32) NOT NULL,
 game_count INTEGER NOT NULL, coverage VARCHAR(32) NOT NULL, record_json CLOB NOT NULL, record_hash CHAR(64) NOT NULL,
 record_revision BIGINT GENERATED BY DEFAULT AS IDENTITY,
 UNIQUE(career_id,season_year,origin_identity)
);
CREATE INDEX idx_career_record_period ON career_record_series(career_id,season_year,competition_id,record_revision);
CREATE TABLE career_record_player (
 record_id CHAR(64) NOT NULL, game_number INTEGER NOT NULL, player_id VARCHAR(128) NOT NULL,
 career_id VARCHAR(80) NOT NULL, season_year INTEGER NOT NULL, team_id VARCHAR(32) NOT NULL,
 player_name VARCHAR(256) NOT NULL, player_json CLOB NOT NULL,
 champion_id VARCHAR(128) NOT NULL, position VARCHAR(16) NOT NULL,
 kills INTEGER, deaths INTEGER, assists INTEGER, cs INTEGER,
 gold BIGINT, experience BIGINT, seconds INTEGER NOT NULL, won BOOLEAN NOT NULL,
 rating DECIMAL(18,12),
 PRIMARY KEY(record_id,game_number,player_id)
);
CREATE INDEX idx_career_record_player_query ON career_record_player(career_id,player_id,season_year,record_id);
CREATE INDEX idx_career_record_team_query ON career_record_player(career_id,team_id,season_year,record_id);
CREATE TABLE career_record_award (
 instance_id CHAR(64) PRIMARY KEY, career_id VARCHAR(80) NOT NULL, season_year INTEGER NOT NULL,
 definition_id VARCHAR(96) NOT NULL, scope_id VARCHAR(96) NOT NULL, occurrence_key VARCHAR(256) NOT NULL,
 cutoff_revision BIGINT NOT NULL, status VARCHAR(32) NOT NULL, award_json CLOB NOT NULL, award_hash CHAR(64) NOT NULL,
 UNIQUE(career_id,season_year,definition_id,scope_id,occurrence_key)
);
CREATE INDEX idx_career_award_period ON career_record_award(career_id,season_year,cutoff_revision,instance_id);
CREATE TABLE career_record_observation (
 career_id VARCHAR(80) NOT NULL, season_year INTEGER NOT NULL, observation_key VARCHAR(256) NOT NULL,
 observed_date DATE NOT NULL, observation_json CLOB NOT NULL, observation_hash CHAR(64) NOT NULL,
 PRIMARY KEY(career_id,season_year,observation_key)
);
CREATE TABLE career_record_restore (
 career_id VARCHAR(80) PRIMARY KEY, cursor_key VARCHAR(256), completed BOOLEAN NOT NULL
);

-- Bounded personal/team award pages filter before loading candidate JSON.
CREATE TABLE career_record_award_candidate (
 instance_id CHAR(64) NOT NULL REFERENCES career_record_award(instance_id),
 player_id VARCHAR(128) NOT NULL, team_id VARCHAR(32) NOT NULL, winner BOOLEAN NOT NULL,
 PRIMARY KEY(instance_id,player_id)
);
CREATE INDEX idx_career_award_player ON career_record_award_candidate(player_id,instance_id);
CREATE INDEX idx_career_award_team ON career_record_award_candidate(team_id,instance_id);
CREATE TABLE career_record_award_input (
 instance_id CHAR(64) NOT NULL REFERENCES career_record_award(instance_id), record_id CHAR(64) NOT NULL,
 PRIMARY KEY(instance_id,record_id)
);
CREATE INDEX idx_career_award_record ON career_record_award_input(record_id,instance_id);
