-- Search projections and inbox metadata; preserved canonical observations/receipts are untouched.
CREATE TABLE career_observation_index (
 sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 career_id VARCHAR(80) NOT NULL, season_year INTEGER NOT NULL, observation_key VARCHAR(256) NOT NULL,
 category VARCHAR(16) NOT NULL, fact_revision BIGINT NOT NULL,
 UNIQUE(career_id,season_year,observation_key)
);
CREATE TABLE career_observation_subject (
 sequence BIGINT NOT NULL REFERENCES career_observation_index(sequence),
 kind VARCHAR(16) NOT NULL, entity VARCHAR(128) NOT NULL,
 PRIMARY KEY(kind,entity,sequence)
);
CREATE INDEX idx_observation_page ON career_observation_index(career_id,season_year,category,sequence);
CREATE TABLE career_inbox_item (
 sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 career_id VARCHAR(80) NOT NULL, season_year INTEGER NOT NULL, source_key VARCHAR(512) NOT NULL,
 kind VARCHAR(48) NOT NULL, game_date DATE NOT NULL, development BOOLEAN NOT NULL,
 item_json CLOB NOT NULL, read_flag BOOLEAN NOT NULL DEFAULT FALSE,
 UNIQUE(career_id,source_key)
);
CREATE INDEX idx_inbox_page ON career_inbox_item(career_id,season_year,kind,development,sequence);
