package com.lolfm.simulator;
import java.util.List;
public final class CombatProgressionEvaluator {
 public CombatProgressionBreakdown evaluate(GameState state,ProgressionCombatContext context,List<PlayerState> own,List<PlayerState> enemy){return evaluate(state,context,own,enemy,Double.NaN,Double.NaN,ProgressionApplicationStage.COMBAT_SCORE);}
 public CombatProgressionBreakdown evaluate(GameState state,ProgressionCombatContext context,List<PlayerState> own,List<PlayerState> enemy,double existingScoreBeforeProgression,double goldContribution){return evaluate(state,context,own,enemy,existingScoreBeforeProgression,goldContribution,ProgressionApplicationStage.COMBAT_SCORE);}
 public CombatProgressionBreakdown evaluate(GameState state,ProgressionCombatContext context,List<PlayerState> own,List<PlayerState> enemy,double existingScoreBeforeProgression,double goldContribution,ProgressionApplicationStage stage){
  int time=state.getCurrentTimeSeconds();List<PlayerState>a=eligible(own,time),b=eligible(enemy,time);boolean on=state.isProgressionPowerEnabled();Averages ap=averages(a,context,on),bp=averages(b,context,on);double levelEdge=ap.level-bp.level,itemEdge=ap.item-bp.item,edge=ap.total-bp.total,multiplier=ProgressionRuleConfig.contextMultiplier(context),levelContribution=levelEdge*multiplier,itemContribution=itemEdge*multiplier,value=edge*multiplier;TeamSide ownSide=sideOf(state,a,own);
  state.getProgressionExecutionStats().combatSample(new ProgressionCombatSample(time,context,stage,ownSide,a.size(),b.size(),ap.level,bp.level,ap.item,bp.item,ap.total,bp.total,ap.clamped+bp.clamped,levelEdge,itemEdge,edge,multiplier,levelContribution,itemContribution,value,existingScoreBeforeProgression,goldContribution));
  if(on)state.getProgressionExecutionStats().power(context,edge,value);
  return new CombatProgressionBreakdown(context,a.size(),b.size(),ap.total,bp.total,edge,multiplier,value);
 }
 public double contribution(GameState state,ProgressionCombatContext context,List<PlayerState> own,List<PlayerState> enemy){return evaluate(state,context,own,enemy).finalContribution();}
 public double contribution(GameState state,ProgressionCombatContext context,List<PlayerState> own,List<PlayerState> enemy,double existingScoreBeforeProgression,double goldContribution){return evaluate(state,context,own,enemy,existingScoreBeforeProgression,goldContribution).finalContribution();}
 public double contribution(GameState state,ProgressionCombatContext context,List<PlayerState> own,List<PlayerState> enemy,double existingScoreBeforeProgression,double goldContribution,ProgressionApplicationStage stage){return evaluate(state,context,own,enemy,existingScoreBeforeProgression,goldContribution,stage).finalContribution();}
 private List<PlayerState> eligible(List<PlayerState> players,int time){return players.stream().filter(p->p.isAlive(time)).distinct().toList();}
 private Averages averages(List<PlayerState> players,ProgressionCombatContext context,boolean on){if(players.isEmpty())return new Averages(0,0,0,0);double level=0,item=0,total=0;int clamped=0;PlayerProgressionPowerEvaluator evaluator=new PlayerProgressionPowerEvaluator();for(PlayerState player:players){ProgressionPowerBreakdown p=evaluator.evaluate(player,context,on);level+=p.levelPower();item+=p.itemPower();total+=p.clampedTotalPower();if(p.clampedTotalPower()>=ProgressionRuleConfig.MAX_PLAYER_PROGRESSION_POWER)clamped++;}return new Averages(level/players.size(),item/players.size(),total/players.size(),clamped);}
 private TeamSide sideOf(GameState state,List<PlayerState> eligible,List<PlayerState> original){PlayerState sample=!eligible.isEmpty()?eligible.getFirst():original.stream().findFirst().orElse(null);if(sample==null)return null;if(state.getBlueTeamState().getPlayers().contains(sample))return TeamSide.BLUE;if(state.getRedTeamState().getPlayers().contains(sample))return TeamSide.RED;return null;}
 private record Averages(double level,double item,double total,int clamped){}
}
