package com.lolfm.simulator;

public final class CounterGankRuleConfig {
    public static final int COUNTER_GANK_START_SECONDS=180, COUNTER_GANK_END_SECONDS=840;
    public static final double BASE_RESPONSE_CHANCE=.10, MIN_RESPONSE_CHANCE=.03, MAX_RESPONSE_CHANCE=.35;
    public static final double DEFENDER_INITIAL_TRIGGER_BONUS=.12;
    public static final double DEFENDER_AGGRESSION_RESPONSE_FACTOR=.01, DEFENDER_AGGRESSION_RESPONSE_MIN=-.04, DEFENDER_AGGRESSION_RESPONSE_MAX=.06;
    public static final double OVEREXTENSION_RESPONSE_MAX_BONUS=.08;
    public static final int COUNTER_GANK_ACTION_COOLDOWN_SECONDS=120, COUNTER_GANK_FARM_BLOCK_SECONDS=30;
    public static final double JUNGLER_MECHANICS_CONTRIBUTION=.50, LANE_MECHANICS_CONTRIBUTION=.50;
    public static final double JUNGLER_AGGRESSION_CONTRIBUTION=.40, LANE_AGGRESSION_CONTRIBUTION=.60;
    public static final double JUNGLER_TEAMFIGHTING_CONTRIBUTION=.35, LANE_TEAMFIGHTING_CONTRIBUTION=.65;
    public static final double BOT_ADC_MECHANICS_CONTRIBUTION=.60, BOT_SUPPORT_MECHANICS_CONTRIBUTION=.40;
    public static final double BOT_ADC_AGGRESSION_CONTRIBUTION=.35, BOT_SUPPORT_AGGRESSION_CONTRIBUTION=.65;
    public static final double BOT_ADC_TEAMFIGHTING_CONTRIBUTION=.45, BOT_SUPPORT_TEAMFIGHTING_CONTRIBUTION=.55;
    public static final double MECHANICS_EDGE_FACTOR=.65, AGGRESSION_EDGE_FACTOR=.10, TEAMFIGHTING_EDGE_FACTOR=.25;
    public static final double COUNTER_GANK_GOLD_DIVISOR=400.0, COUNTER_GANK_GOLD_EDGE_MIN=-4.0, COUNTER_GANK_GOLD_EDGE_MAX=4.0;
    public static final double OVEREXTENSION_EDGE_DIVISOR=20.0, OVEREXTENSION_EDGE_MAX=4.0, COUNTER_PREPARATION_EDGE=1.50;
    public static final double BASE_DECISIVE_CHANCE=.45, AVERAGE_AGGRESSION_DECISIVE_FACTOR=.012, DECISIVE_EDGE_FACTOR=.015, BOT_DECISIVE_BONUS=.05;
    public static final double MIN_DECISIVE_CHANCE=.30, MAX_DECISIVE_CHANCE=.80;
    public static final double BASE_ATTACKING_SIDE_WIN_CHANCE=.50, ATTACKING_SIDE_WIN_EDGE_FACTOR=.03;
    public static final double MIN_ATTACKING_SIDE_WIN_CHANCE=.20, MAX_ATTACKING_SIDE_WIN_CHANCE=.80;
    public static final double SOLO_COUNTER_GANK_PRESSURE_SHOCK=18.0, BOT_COUNTER_GANK_PRESSURE_SHOCK=15.0;
    public static final double SOLO_WINNER_JUNGLER_KILLER_WEIGHT=.55, SOLO_WINNER_LANER_KILLER_WEIGHT=.45;
    public static final double SOLO_LOSER_JUNGLER_VICTIM_WEIGHT=.55, SOLO_LOSER_LANER_VICTIM_WEIGHT=.45;
    public static final double BOT_WINNER_JUNGLER_KILLER_WEIGHT=.35, BOT_WINNER_ADC_KILLER_WEIGHT=.50, BOT_WINNER_SUPPORT_KILLER_WEIGHT=.15;
    public static final double BOT_LOSER_JUNGLER_VICTIM_WEIGHT=.40, BOT_LOSER_ADC_VICTIM_WEIGHT=.40, BOT_LOSER_SUPPORT_VICTIM_WEIGHT=.20;
    private CounterGankRuleConfig() { }
}
