package com.lolfm.simulator;

public final class LateGameRuleConfig {
 public static final int POST_REPEL_MACRO_PUSH_BLOCK_SECONDS=30;
    public static final int LATE_GAME_START_SECONDS=1800,FIRST_EVALUATION_DELAY_SECONDS=30,EVALUATION_INTERVAL_SECONDS=60,PLAN_DURATION_SECONDS=60,BASE_DEFENSE_COMBAT_COOLDOWN_SECONDS=240;
    public static final double MIN_PLAN_WEIGHT=.10,MAX_PLAN_WEIGHT=3.00,GOLD_EDGE_NORMALIZER=5000.0,ATTRIBUTE_EDGE_NORMALIZER=8.0,ALIVE_EDGE_NORMALIZER=3.0;
    public static final int RESPAWN_SOON_SECONDS=15,RESPAWN_LONG_SECONDS=35;
    public static final double INITIATIVE_BASE_WEIGHT=.80,INITIATIVE_GOLD_EDGE_WEIGHT=.30,INITIATIVE_ALIVE_EDGE_WEIGHT=.35,INITIATIVE_TEAMFIGHT_EDGE_WEIGHT=.25,INITIATIVE_BARON_BONUS=.35,INITIATIVE_ELDER_BONUS=.50,INITIATIVE_RECENT_BIG_WIN_BONUS=.20,INITIATIVE_RECENT_ACE_BONUS=.40,INITIATIVE_BASE_EXPOSURE_WEIGHT=.25;
    public static final double SIEGE_BASE_WEIGHT=.85,SIEGE_GOLD_EDGE_WEIGHT=.25,SIEGE_ALIVE_EDGE_WEIGHT=.35,SIEGE_TEAMFIGHT_EDGE_WEIGHT=.30,SIEGE_BARON_BONUS=.35,SIEGE_ELDER_BONUS=.45,SIEGE_INHIBITOR_PRESSURE_BONUS=.25;
    public static final double OUTER_TARGET_DEPTH_BONUS=0,INNER_TARGET_DEPTH_BONUS=.10,INHIBITOR_TOWER_TARGET_DEPTH_BONUS=.25,INHIBITOR_TARGET_DEPTH_BONUS=.40;
    public static final double NEXUS_FINISH_BASE_WEIGHT=.65,NEXUS_TURRET_EXPOSED_BONUS=.45,NEXUS_EXPOSED_BONUS=.75,NEXUS_FINISH_GOLD_EDGE_WEIGHT=.25,NEXUS_FINISH_ALIVE_EDGE_WEIGHT=.40,NEXUS_FINISH_DEAD_DEFENDER_BONUS_PER_PLAYER=.15,NEXUS_FINISH_LONG_RESPAWN_BONUS_PER_PLAYER=.10,NEXUS_FINISH_RECENT_ACE_BONUS=.45,NEXUS_FINISH_BARON_BONUS=.25,NEXUS_FINISH_ELDER_BONUS=.50;
    public static final double RESET_AND_REGROUP_BASE_WEIGHT=.50,RESET_BEHIND_GOLD_WEIGHT=.35,RESET_BEHIND_ALIVE_WEIGHT=.45,RESET_MISSING_ATTACKER_WEIGHT=.15,RESET_ENEMY_RESPAWN_SOON_WEIGHT=.25;
    public static final double DEFEND_BASE_WEIGHT=.95,DEFEND_THREAT_LEVEL_WEIGHT=.20,DEFEND_ALIVE_EDGE_WEIGHT=.35,DEFEND_TEAMFIGHT_EDGE_WEIGHT=.35,DEFEND_RESPAWN_SOON_BONUS=.25,DEFEND_NEXUS_URGENCY_BONUS=.60;
    public static final double GIVE_STRUCTURE_BASE_WEIGHT=.55,GIVE_BEHIND_GOLD_WEIGHT=.35,GIVE_BEHIND_ALIVE_WEIGHT=.45,GIVE_MISSING_PLAYER_WEIGHT=.15;
    public static final double CROSS_MAP_BASE_WEIGHT=.45,CROSS_MAP_TARGET_AVAILABLE_BONUS=.35,CROSS_MAP_FARMING_EDGE_WEIGHT=.35,CROSS_MAP_BARON_BONUS=.15;
    public static final double SIEGE_FIGHT_TRIGGER_BASE_CHANCE=.30,SIEGE_FIGHT_AGGRESSION_EDGE_BONUS_MAX=.15,SIEGE_FIGHT_THREAT_LEVEL_BONUS_MAX=.15,MIN_SIEGE_FIGHT_TRIGGER_CHANCE=.10,MAX_SIEGE_FIGHT_TRIGGER_CHANCE=.65;
    public static final double NON_COMBAT_SIEGE_BASE_CHANCE=.35,NON_COMBAT_SIEGE_GOLD_BONUS_MAX=.08,NON_COMBAT_SIEGE_ALIVE_BONUS_PER_PLAYER=.03,NON_COMBAT_SIEGE_TEAMFIGHT_BONUS_MAX=.08,NON_COMBAT_SIEGE_BARON_BONUS=.20,NON_COMBAT_SIEGE_ELDER_BONUS=.25;
    public static final double NEXUS_FINISH_BASE_CHANCE=.60,NEXUS_FINISH_GOLD_BONUS_MAX=.08,NEXUS_FINISH_ALIVE_BONUS_PER_PLAYER=.05,NEXUS_FINISH_DEAD_DEFENDER_CHANCE_PER_PLAYER=.05,NEXUS_FINISH_LONG_RESPAWN_CHANCE_PER_PLAYER=.08,NEXUS_FINISH_BARON_CHANCE_BONUS=.15,NEXUS_FINISH_ELDER_CHANCE_BONUS=.25,NEXUS_FINISH_RECENT_ACE_CHANCE_BONUS=.20;
    public static final double CROSS_MAP_PUSH_BASE_CHANCE=.35,CROSS_MAP_GOLD_BONUS_MAX=.08,CROSS_MAP_ALIVE_BONUS_PER_PLAYER=.03,CROSS_MAP_FARMING_BONUS_MAX=.10,CROSS_MAP_BARON_CHANCE_BONUS=.15,MIN_STRUCTURE_ACTION_CHANCE=.10,MAX_STRUCTURE_ACTION_CHANCE=.90;
    public static final int MIN_SIEGE_ATTACKERS=3,MIN_STANDARD_DEFENDERS=2,MIN_NEXUS_DEFENDERS=1;
    private LateGameRuleConfig(){}
}
