package com.lolfm.simulator;

import com.lolfm.domain.*;import java.util.*;
/** Stateless late-game evaluator/executor. Random order: initiative, plan, response, fight trigger, fight, structure, cross-map. */
public final class LateGameMacroResolver{
 private final BaseThreatEvaluator threats=new BaseThreatEvaluator();
 public void expirePlans(GameState s){s.getLateGameState().expire(s.getCurrentTimeSeconds());}
 public Optional<MatchEvent> transitionIfDue(GameState s,MidGameMacroResolver mid){Optional<MatchEvent> event=new LanePhaseResolver().transitionToLateGameIfDue(s);if(event.isPresent()){LateGameTransitionReason r=s.getLanePhaseState().getLateGameTransitionReason();s.getLateGameState().start(s.getCurrentTimeSeconds(),r);mid.onLateGameTransition(s);}return event;}
 public void onMatchFinished(GameState s){s.getLateGameState().finish();}
 public void resolveDue(GameState s,Team blue,Team red,Random random,List<MatchEvent> events,StructureResolver structures,TeamfightResolver fights){
  LateGameState state=s.getLateGameState();int time=s.getCurrentTimeSeconds();if(!state.isEnabled()||s.isFinished()||s.getLanePhaseState().getMatchPhase()!=MatchPhase.LATE_GAME||!state.due(time))return;
  int due=state.beginEvaluation(time);Context c=context(s,time);List<LateGameInitiativeCandidate> initiatives=new ArrayList<>();for(TeamSide side:TeamSide.values())initiatives.add(initiative(c,side));List<LateGameInitiativeCandidate> eligible=initiatives.stream().filter(LateGameInitiativeCandidate::eligible).toList();
  if(eligible.isEmpty()){state.getStats().noInitiative();LateGameDecisionData d=emptyDecision(state,due,time,initiatives,c,LateGameActionResult.NO_INITIATIVE);state.record(d);return;}
  boolean initiativeRoll=eligible.size()>1;TeamSide attacker=initiativeRoll?weightedInitiative(eligible,random):eligible.getFirst().side();if(initiativeRoll)state.getStats().initiativeRoll();TeamSide defender=attacker.opposite();
  List<PlanCandidate> planCandidates=new ArrayList<>();for(LateGameAttackPlan plan:LateGameAttackPlan.values())planCandidates.add(plan(c,attacker,plan));List<PlanCandidate> eligiblePlans=planCandidates.stream().filter(x->x.weight.eligible()).toList();boolean planRoll=eligiblePlans.size()>1;PlanCandidate selected=planRoll?weightedPlan(eligiblePlans,random):eligiblePlans.getFirst();if(planRoll)state.getStats().planRoll();
  if(selected.plan==LateGameAttackPlan.RESET_AND_REGROUP){state.teamPlan(attacker).beginAttack(selected.plan,null,null,Set.of(),time);state.teamPlan(attacker).setResult(LateGameActionResult.ATTACKER_RESET);LateGameDecisionData d=decision(state,due,time,initiatives,attacker,initiativeRoll,planCandidates,selected,planRoll,List.of(),null,false,c,null,0,false,null,null,0,false,false,null,null,0,false,false,LateGameActionResult.ATTACKER_RESET,false,false,false);state.record(d);return;}
  Set<Position> assigned=assign(s,attacker,selected.plan);if(assigned.size()<LateGameRuleConfig.MIN_SIEGE_ATTACKERS){LateGameDecisionData d=decision(state,due,time,initiatives,attacker,initiativeRoll,planCandidates,selected,planRoll,List.of(),null,false,c,respawn(c,defender),0,false,null,null,0,false,false,null,null,0,false,false,LateGameActionResult.INELIGIBLE,false,false,false);state.record(d);return;}
  CrossTarget cross=crossTarget(c,defender,selected.lane);List<ResponseCandidate> responses=new ArrayList<>();for(LateGameDefenseResponse r:LateGameDefenseResponse.values())responses.add(response(c,attacker,selected,r,cross));List<ResponseCandidate> eligibleResponses=responses.stream().filter(x->x.weight.eligible()).toList();boolean responseRoll=eligibleResponses.size()>1;ResponseCandidate response=responseRoll?weightedResponse(eligibleResponses,random):eligibleResponses.getFirst();if(responseRoll)state.getStats().responseRoll();
  state.teamPlan(attacker).beginAttack(selected.plan,selected.lane,selected.target,assigned,time);Set<Position> defenders=availablePositions(s,defender,List.of(Position.TOP,Position.JUNGLE,Position.MID,Position.ADC,Position.SUPPORT));state.teamPlan(defender).beginDefense(response.response,selected.lane,selected.target,defenders,time);
  Resolution resolution=resolve(s,blue,red,random,events,structures,fights,c,attacker,selected,response,cross);state.teamPlan(attacker).setResult(resolution.result);state.teamPlan(defender).setResult(resolution.result);
  LateGameDecisionData d=decision(state,due,time,initiatives,attacker,initiativeRoll,planCandidates,selected,planRoll,responses,response,responseRoll,c,respawn(c,defender),resolution.fightChance,resolution.fightTriggered,resolution.grade,resolution.fightWinner,resolution.structureChance,resolution.structureRoll,resolution.structureSuccess,resolution.crossLane,resolution.crossTarget,resolution.crossChance,resolution.crossRoll,resolution.crossSuccess,resolution.result,resolution.majorCombat,resolution.attackerStructure,resolution.defenderStructure);state.record(d);
  if(resolution.attempted){MatchEvent event=new MatchEvent(time,MatchEventType.LATE_GAME_ACTION,"Late game action",null,null,List.of());event.setLateGameDecision(d);events.add(event);}
 }
 Resolution resolveSelected(GameState s,Team blue,Team red,Random random,List<MatchEvent> events,StructureResolver structures,TeamfightResolver fights,TeamSide attacker,LateGameAttackPlan attackPlan,LateGameDefenseResponse defenseResponse){Context c=context(s,s.getCurrentTimeSeconds());PlanCandidate selected=plan(c,attacker,attackPlan);CrossTarget cross=crossTarget(c,attacker.opposite(),selected.lane);ResponseCandidate response=response(c,attacker,selected,defenseResponse,cross);return resolve(s,blue,red,random,events,structures,fights,c,attacker,selected,response,cross);}
 private Resolution resolve(GameState s,Team blue,Team red,Random random,List<MatchEvent> events,StructureResolver structures,TeamfightResolver fights,Context c,TeamSide attacker,PlanCandidate plan,ResponseCandidate response,CrossTarget cross){
  if(s.wasStructureActionPerformedThisTick(attacker)||threats.nextTarget(s,attacker,plan.lane)!=plan.target)return Resolution.ineligible();s.getCompositionRuntimeState().recordActualAttempt(com.lolfm.composition.CompositionActionType.SIEGE,attacker,attacker,attacker.opposite(),com.lolfm.composition.FightScale.NONE,null,false,null,plan.lane,s.getCurrentTimeSeconds(),com.lolfm.composition.CompositionBaselineScoreDomain.NOT_AVAILABLE,null,null);s.markStructureActionAttempted(attacker);s.getLateGameState().getStats().attempt();boolean nexus=plan.plan==LateGameAttackPlan.NEXUS_FINISH;double fightChance=0;boolean fightTriggered=false;TeamfightOutcome fight=null;
  if(response.response==LateGameDefenseResponse.DEFEND&&!s.wasMajorCombatAttemptedThisTick()
          &&(!nexus||s.getLateGameState().canAttemptBaseDefenseCombat(attacker,s.getCurrentTimeSeconds()))){
   if(nexus)fightTriggered=true;else{fightChance=clamp(LateGameRuleConfig.SIEGE_FIGHT_TRIGGER_BASE_CHANCE+edge(c.avgAggression.get(attacker),c.avgAggression.get(attacker.opposite()),LateGameRuleConfig.ATTRIBUTE_EDGE_NORMALIZER)*LateGameRuleConfig.SIEGE_FIGHT_AGGRESSION_EDGE_BONUS_MAX+threatValue(c.threat(attacker.opposite()).overallLevel())/4.0*LateGameRuleConfig.SIEGE_FIGHT_THREAT_LEVEL_BONUS_MAX,LateGameRuleConfig.MIN_SIEGE_FIGHT_TRIGGER_CHANCE,LateGameRuleConfig.MAX_SIEGE_FIGHT_TRIGGER_CHANCE);fightTriggered=random.nextDouble()<fightChance;}
   if(fightTriggered){s.getLateGameState().getStats().fight();fight=fights.resolveForcedTeamfight(s,blue,red,random,events,nexus?CombatSource.BASE_DEFENSE:CombatSource.LATE_GAME_SIEGE,attacker).orElse(null);if(fight!=null&&nexus)s.getLateGameState().recordBaseDefenseCombat(attacker,s.getCurrentTimeSeconds());if(fight!=null&&fight.winningSide()!=attacker)return new Resolution(true,Latest(false,false),fightChance,true,fight.grade(),fight.winningSide(),0,false,false,null,null,0,false,false,LateGameActionResult.SIEGE_FIGHT_DEFENDER_WIN,true,false,false);}
  }
  if(nexus){s.getLateGameState().getStats().finishAttempt();double chance=finishChance(c,attacker);boolean success=random.nextDouble()<chance;StructureOutcome out=success?structures.destroyTarget(s,attacker,null,plan.target,PushReason.NEXUS_FINISH).orElse(null):null;if(out!=null){events.add(structures.createStructureEvent(s,out));s.getLateGameState().getStats().structure();if(out.structureKind()==StructureKind.NEXUS)s.getLateGameState().getStats().nexusDestroyed();}LateGameActionResult result=out==null?LateGameActionResult.SIEGE_REPELLED:out.gameEnded()?LateGameActionResult.NEXUS_DESTROYED:LateGameActionResult.NEXUS_FINISH_ADVANCED;return new Resolution(true,Latest(out!=null,false),fightChance,fightTriggered,fight==null?null:fight.grade(),fight==null?null:fight.winningSide(),chance,true,out!=null,null,null,0,false,false,result,fight!=null,out!=null,false);}
  StructureOutcome attackOut=null;double structureChance=1;boolean structureRoll=false;
  if(response.response==LateGameDefenseResponse.DEFEND&&!fightTriggered){structureChance=nonCombatChance(c,attacker);structureRoll=true;if(random.nextDouble()<structureChance)attackOut=structures.destroyTarget(s,attacker,plan.lane,plan.target,PushReason.LATE_GAME_SIEGE).orElse(null);}else attackOut=structures.destroyTarget(s,attacker,plan.lane,plan.target,PushReason.LATE_GAME_SIEGE).orElse(null);
  if(attackOut!=null){events.add(structures.createStructureEvent(s,attackOut));s.getLateGameState().getStats().structure();}
  Lane crossLane=null;LateGameStructureTarget crossTarget=null;double crossChance=0;boolean crossRoll=false,crossSuccess=false;
  if(response.response==LateGameDefenseResponse.CROSS_MAP_PUSH&&cross!=null){crossLane=cross.lane;crossTarget=cross.target;crossChance=crossMapChance(c,attacker.opposite(),cross.lane);crossRoll=true;s.getCompositionRuntimeState().recordActualAttempt(com.lolfm.composition.CompositionActionType.SIEGE,attacker.opposite(),attacker.opposite(),attacker,com.lolfm.composition.FightScale.NONE,null,false,null,cross.lane,s.getCurrentTimeSeconds(),com.lolfm.composition.CompositionBaselineScoreDomain.NOT_AVAILABLE,null,null);s.markStructureActionAttempted(attacker.opposite());crossSuccess=random.nextDouble()<crossChance;StructureOutcome out=crossSuccess?structures.destroyTarget(s,attacker.opposite(),cross.lane,cross.target,PushReason.LATE_GAME_CROSS_MAP).orElse(null):null;crossSuccess=out!=null;if(out!=null){events.add(structures.createStructureEvent(s,out));s.getLateGameState().getStats().structure();}s.getLateGameState().getStats().crossMap(crossSuccess);}
  LateGameActionResult result=attackOut==null?LateGameActionResult.SIEGE_REPELLED:fight!=null?LateGameActionResult.SIEGE_FIGHT_ATTACKER_WIN:crossSuccess?LateGameActionResult.CROSS_MAP_SUCCEEDED:LateGameActionResult.STRUCTURE_DESTROYED;return new Resolution(true,Latest(attackOut!=null,crossSuccess),fightChance,fightTriggered,fight==null?null:fight.grade(),fight==null?null:fight.winningSide(),structureChance,structureRoll,attackOut!=null,crossLane,crossTarget,crossChance,crossRoll,crossSuccess,result,fight!=null,attackOut!=null,crossSuccess);
 }
 private Context context(GameState s,int time){EnumMap<TeamSide,Integer>gold=new EnumMap<>(TeamSide.class),alive=new EnumMap<>(TeamSide.class);EnumMap<TeamSide,Double>tf=new EnumMap<>(TeamSide.class),agg=new EnumMap<>(TeamSide.class);EnumMap<TeamSide,Boolean>baron=new EnumMap<>(TeamSide.class),elder=new EnumMap<>(TeamSide.class),big=new EnumMap<>(TeamSide.class),ace=new EnumMap<>(TeamSide.class);EnumMap<TeamSide,BaseThreatSnapshot>threat=new EnumMap<>(TeamSide.class);for(TeamSide side:TeamSide.values()){TeamState t=s.getTeamState(side);gold.put(side,t.getGold());alive.put(side,countAlive(t,time));tf.put(side,average(t,PlayerState::getTeamfighting));agg.put(side,average(t,PlayerState::getAggression));baron.put(side,t.hasActiveBaronBuff(time));elder.put(side,t.getPlayers().stream().anyMatch(p->p.hasActiveElderBuff(time)));big.put(side,s.hasRecentBigWin(side,120));ace.put(side,s.hasRecentAce(side,120));threat.put(side,threats.evaluate(s,side));}return new Context(s,time,gold,alive,tf,agg,baron,elder,big,ace,threat);}
 private LateGameInitiativeCandidate initiative(Context c,TeamSide side){if(c.s.wasStructureActionAttemptedThisTick(side))c.s.recordLaterStructureResolverBlockedByAttempt();boolean eligible=c.alive.get(side)>=3&&!c.s.wasStructureActionPerformedThisTick(side)&&hasTarget(c.s,side);String reason=eligible?null:c.alive.get(side)<3?"INSUFFICIENT_ATTACKERS":c.s.wasStructureActionPerformedThisTick(side)?"STRUCTURE_SLOT_USED":"NO_TARGET";double g=edge(c.gold.get(side),c.gold.get(side.opposite()),LateGameRuleConfig.GOLD_EDGE_NORMALIZER),a=edge(c.alive.get(side),c.alive.get(side.opposite()),LateGameRuleConfig.ALIVE_EDGE_NORMALIZER),t=edge(c.avgTeamfight.get(side),c.avgTeamfight.get(side.opposite()),LateGameRuleConfig.ATTRIBUTE_EDGE_NORMALIZER);double gc=Math.max(0,g)*LateGameRuleConfig.INITIATIVE_GOLD_EDGE_WEIGHT,ac=Math.max(0,a)*LateGameRuleConfig.INITIATIVE_ALIVE_EDGE_WEIGHT,tc=Math.max(0,t)*LateGameRuleConfig.INITIATIVE_TEAMFIGHT_EDGE_WEIGHT,b=c.baron.get(side)?LateGameRuleConfig.INITIATIVE_BARON_BONUS:0,e=c.elder.get(side)?LateGameRuleConfig.INITIATIVE_ELDER_BONUS:0,r=c.ace.get(side)?LateGameRuleConfig.INITIATIVE_RECENT_ACE_BONUS:c.big.get(side)?LateGameRuleConfig.INITIATIVE_RECENT_BIG_WIN_BONUS:0,x=threatValue(c.threat(side.opposite()).overallLevel())/4.0*LateGameRuleConfig.INITIATIVE_BASE_EXPOSURE_WEIGHT;return new LateGameInitiativeCandidate(side,eligible,reason,g,a,t,gc,ac,tc,b,e,r,x,eligible?clamp(LateGameRuleConfig.INITIATIVE_BASE_WEIGHT+gc+ac+tc+b+e+r+x,.1,3):0);}
 private PlanCandidate plan(Context c,TeamSide side,LateGameAttackPlan plan){Lane lane=switch(plan){case SIEGE_TOP->Lane.TOP;case SIEGE_MID->Lane.MID;case SIEGE_BOT->Lane.BOT;default->null;};LateGameStructureTarget target=threats.nextTarget(c.s,side,lane);boolean reset=plan==LateGameAttackPlan.RESET_AND_REGROUP,nexus=plan==LateGameAttackPlan.NEXUS_FINISH;boolean eligible=reset||c.alive.get(side)>=3&&!c.s.wasStructureActionPerformedThisTick(side)&&(nexus?((target==LateGameStructureTarget.NEXUS||target==LateGameStructureTarget.NEXUS_TURRET)&&!c.s.wasMajorCombatAttemptedThisTick()):target!=null&&target.ordinal()<=LateGameStructureTarget.INHIBITOR.ordinal());String reason=eligible?null:"TARGET_OR_PARTICIPANT_INELIGIBLE";double g=edge(c.gold.get(side),c.gold.get(side.opposite()),5000),a=edge(c.alive.get(side),c.alive.get(side.opposite()),3),t=edge(c.avgTeamfight.get(side),c.avgTeamfight.get(side.opposite()),8);double base,gc,ac,tc,depth=0,b=0,e=0,recent=0,resp=0;if(reset){base=.5;gc=Math.max(0,-g)*.35;ac=Math.max(0,-a)*.45;tc=0;resp=(5-c.alive.get(side))*.15+respawn(c,side.opposite()).respawningSoonCount()*.25;}else if(nexus){base=.65;gc=g*.25;ac=a*.40;tc=0;depth=c.threat(side.opposite()).remainingNexusTurrets()>0?.45:.75;resp=respawn(c,side.opposite()).deadCount()*.15+respawn(c,side.opposite()).longRespawnCount()*.10;recent=c.ace.get(side)?.45:0;b=c.baron.get(side)?.25:0;e=c.elder.get(side)?.50:0;}else{base=.85;gc=g*.25;ac=a*.35;tc=t*.30;depth=depth(target);b=c.baron.get(side)?.35:0;e=c.elder.get(side)?.45:0;if(!c.s.getMapState().getLaneState(side.opposite(),lane).isInhibitorAlive())recent=.25;}double total=eligible?clamp(base+gc+ac+tc+depth+b+e+recent+resp,.1,3):0;return new PlanCandidate(plan,lane,nexus?threats.nextTarget(c.s,side,null):target,new LateGamePlanWeightBreakdown(plan,eligible,reason,base,g,gc,a,ac,t,tc,depth,b,e,recent,0,resp,total));}
 private ResponseCandidate response(Context c,TeamSide attacker,PlanCandidate plan,LateGameDefenseResponse r,CrossTarget cross){TeamSide side=attacker.opposite();int min=plan.plan==LateGameAttackPlan.NEXUS_FINISH?1:2;boolean eligible=switch(r){case DEFEND->c.alive.get(side)>=min;case GIVE_STRUCTURE->true;case CROSS_MAP_PUSH->plan.plan!=LateGameAttackPlan.NEXUS_FINISH&&c.threat(side).overallLevel().ordinal()<BaseThreatLevel.NEXUS_TURRET_THREAT.ordinal()&&cross!=null&&!c.s.wasStructureActionPerformedThisTick(side);};String reason=eligible?null:"INELIGIBLE";double a=edge(c.alive.get(side),c.alive.get(attacker),3),t=edge(c.avgTeamfight.get(side),c.avgTeamfight.get(attacker),8),g=edge(c.gold.get(side),c.gold.get(attacker),5000);double base,th=0,ac=0,tc=0,missing=0,target=0,farm=0,baron=0;if(r==LateGameDefenseResponse.DEFEND){base=.95;th=threatValue(c.threat(side).overallLevel())/4.0*.20;ac=a*.35;tc=t*.35;if(respawn(c,side).respawningSoonCount()>0)missing=.25;if(plan.plan==LateGameAttackPlan.NEXUS_FINISH)th+=.60;}else if(r==LateGameDefenseResponse.GIVE_STRUCTURE){base=.55;missing=(5-c.alive.get(side))*.15;ac=Math.max(0,-a)*.45;th=Math.max(0,-g)*.35;}else{base=.45;target=.35;farm=cross==null?0:farmingEdge(c.s,side,cross.lane)*.35;baron=c.baron.get(side)?.15:0;}double total=eligible?clamp(base+th+ac+tc+missing+target+farm+baron,.1,3):0;return new ResponseCandidate(r,new LateGameDefenseWeightBreakdown(r,eligible,reason,base,th,ac,tc,missing,target,farm,baron,total));}
 private CrossTarget crossTarget(Context c,TeamSide side,Lane attacked){if(attacked==null)return null;List<Lane> order=switch(attacked){case TOP->List.of(Lane.BOT,Lane.MID,Lane.TOP);case MID->List.of(Lane.TOP,Lane.BOT,Lane.MID);case BOT->List.of(Lane.TOP,Lane.MID,Lane.BOT);};for(Lane lane:order){LateGameStructureTarget target=threats.nextTarget(c.s,side,lane);Position p=primary(lane);PlayerState player=c.s.getTeamState(side).playerAt(p);if(target!=null&&target.ordinal()<=LateGameStructureTarget.INHIBITOR_TOWER.ordinal()&&player.canParticipateInMajorCombatAt(c.time)&&!c.s.wasMajorCombatParticipantThisTick(player))return new CrossTarget(lane,target,p);}return null;}
 private Set<Position> assign(GameState s,TeamSide side,LateGameAttackPlan p){List<Position> order=switch(p){case SIEGE_TOP->List.of(Position.TOP,Position.JUNGLE,Position.SUPPORT,Position.MID,Position.ADC);case SIEGE_MID->List.of(Position.JUNGLE,Position.MID,Position.ADC,Position.SUPPORT);case SIEGE_BOT->List.of(Position.JUNGLE,Position.ADC,Position.SUPPORT,Position.TOP,Position.MID);case NEXUS_FINISH->List.of(Position.TOP,Position.JUNGLE,Position.MID,Position.ADC,Position.SUPPORT);default->List.of();};EnumSet<Position> result=EnumSet.noneOf(Position.class);for(Position pos:order){PlayerState x=s.getTeamState(side).playerAt(pos);if(x.canParticipateInMajorCombatAt(s.getCurrentTimeSeconds())&&!s.wasMajorCombatParticipantThisTick(x))result.add(pos);if((p==LateGameAttackPlan.SIEGE_TOP||p==LateGameAttackPlan.SIEGE_BOT)&&result.size()==4)break;}return result;}
 private Set<Position> availablePositions(GameState s,TeamSide side,List<Position> order){EnumSet<Position> r=EnumSet.noneOf(Position.class);for(Position p:order){PlayerState x=s.getTeamState(side).playerAt(p);if(x.canParticipateInMajorCombatAt(s.getCurrentTimeSeconds())&&!s.wasMajorCombatParticipantThisTick(x))r.add(p);}return r;}
 private double finishChance(Context c,TeamSide side){LateGameRespawnSummary r=respawn(c,side.opposite());return clamp(LateGameRuleConfig.NEXUS_FINISH_BASE_CHANCE+edge(c.gold.get(side),c.gold.get(side.opposite()),LateGameRuleConfig.GOLD_EDGE_NORMALIZER)*LateGameRuleConfig.NEXUS_FINISH_GOLD_BONUS_MAX+(c.alive.get(side)-c.alive.get(side.opposite()))*LateGameRuleConfig.NEXUS_FINISH_ALIVE_BONUS_PER_PLAYER+r.deadCount()*LateGameRuleConfig.NEXUS_FINISH_DEAD_DEFENDER_CHANCE_PER_PLAYER+r.longRespawnCount()*LateGameRuleConfig.NEXUS_FINISH_LONG_RESPAWN_CHANCE_PER_PLAYER+(c.baron.get(side)?LateGameRuleConfig.NEXUS_FINISH_BARON_CHANCE_BONUS:0)+(c.elder.get(side)?LateGameRuleConfig.NEXUS_FINISH_ELDER_CHANCE_BONUS:0)+(c.ace.get(side)?LateGameRuleConfig.NEXUS_FINISH_RECENT_ACE_CHANCE_BONUS:0),LateGameRuleConfig.MIN_STRUCTURE_ACTION_CHANCE,LateGameRuleConfig.MAX_STRUCTURE_ACTION_CHANCE);}
 private double nonCombatChance(Context c,TeamSide side){return clamp(.35+edge(c.gold.get(side),c.gold.get(side.opposite()),5000)*.08+(c.alive.get(side)-c.alive.get(side.opposite()))*.03+edge(c.avgTeamfight.get(side),c.avgTeamfight.get(side.opposite()),8)*.08+(c.baron.get(side)?.20:0)+(c.elder.get(side)?.25:0),.1,.8);}
 private double crossMapChance(Context c,TeamSide side,Lane lane){return clamp(.35+edge(c.gold.get(side),c.gold.get(side.opposite()),5000)*.08+(c.alive.get(side)-c.alive.get(side.opposite()))*.03+farmingEdge(c.s,side,lane)*.10+(c.baron.get(side)?.15:0),.1,.8);}
 private boolean hasTarget(GameState s,TeamSide side){if(threats.nextTarget(s,side,null)!=null)return true;for(Lane lane:Lane.values())if(threats.nextTarget(s,side,lane)!=null)return true;return false;}
 private LateGameRespawnSummary respawn(Context c,TeamSide side){int dead=0,soon=0,longCount=0,longest=0;for(PlayerState p:c.s.getTeamState(side).getPlayers())if(!p.isAlive(c.time)){dead++;int seconds=Math.max(0,p.getRespawnAtSeconds()-c.time);if(seconds<=15)soon++;if(seconds>=35)longCount++;longest=Math.max(longest,seconds);}return new LateGameRespawnSummary(dead,soon,longCount,longest);}
 private TeamSide weightedInitiative(List<LateGameInitiativeCandidate>x,Random r){double total=x.stream().mapToDouble(LateGameInitiativeCandidate::finalWeight).sum(),roll=r.nextDouble()*total;for(var c:x){roll-=c.finalWeight();if(roll<0)return c.side();}return x.getLast().side();}private PlanCandidate weightedPlan(List<PlanCandidate>x,Random r){double total=x.stream().mapToDouble(c->c.weight.finalWeight()).sum(),roll=r.nextDouble()*total;for(var c:x){roll-=c.weight.finalWeight();if(roll<0)return c;}return x.getLast();}private ResponseCandidate weightedResponse(List<ResponseCandidate>x,Random r){double total=x.stream().mapToDouble(c->c.weight.finalWeight()).sum(),roll=r.nextDouble()*total;for(var c:x){roll-=c.weight.finalWeight();if(roll<0)return c;}return x.getLast();}
 private LateGameDecisionData emptyDecision(LateGameState s,int due,int time,List<LateGameInitiativeCandidate>i,Context c,LateGameActionResult result){return new LateGameDecisionData(s.getEvaluationSequence(),due,time,i,null,false,List.of(),null,false,null,null,Set.of(),List.of(),null,false,c.threat(TeamSide.BLUE),c.threat(TeamSide.RED),0,0,new LateGameRespawnSummary(0,0,0,0),0,false,null,null,0,false,false,null,null,0,false,false,result,false,false,false,s.getNextEvaluationAtSeconds());}
 private LateGameDecisionData decision(LateGameState s,int due,int time,List<LateGameInitiativeCandidate>i,TeamSide attacker,boolean ir,List<PlanCandidate>p,PlanCandidate selected,boolean pr,List<ResponseCandidate>d,ResponseCandidate response,boolean dr,Context c,LateGameRespawnSummary resp,double fc,boolean ft,FightGrade grade,TeamSide winner,double sc,boolean sr,boolean ss,Lane cl,LateGameStructureTarget ct,double cc,boolean cr,boolean cs,LateGameActionResult result,boolean major,boolean as,boolean ds){return new LateGameDecisionData(s.getEvaluationSequence(),due,time,i,attacker,ir,p.stream().map(x->x.weight).toList(),selected.plan,pr,selected.lane,selected.target,(s.teamPlan(attacker).snapshot("ATTACK").assignedPositions().isEmpty()?assign(c.s,attacker,selected.plan):s.teamPlan(attacker).snapshot("ATTACK").assignedPositions()),d.stream().map(x->x.weight).toList(),response==null?null:response.response,dr,c.threat(TeamSide.BLUE),c.threat(TeamSide.RED),c.alive.get(attacker),c.alive.get(attacker.opposite()),resp,fc,ft,grade,winner,sc,sr,ss,cl,ct,cc,cr,cs,result,major,as,ds,s.getNextEvaluationAtSeconds());}
 private int threatValue(BaseThreatLevel l){return switch(l){case NONE->0;case INHIBITOR_TOWER_THREAT->1;case INHIBITOR_THREAT->2;case NEXUS_TURRET_THREAT->3;case NEXUS_THREAT,MATCH_ENDED->4;};}private double depth(LateGameStructureTarget t){return switch(t){case OUTER->0;case INNER->.10;case INHIBITOR_TOWER->.25;case INHIBITOR->.40;default->0;};}private double farmingEdge(GameState s,TeamSide side,Lane lane){Position p=primary(lane);return edge(s.getTeamState(side).playerAt(p).getFarming(),s.getTeamState(side.opposite()).playerAt(p).getFarming(),8);}private Position primary(Lane lane){return switch(lane){case TOP->Position.TOP;case MID->Position.MID;case BOT->Position.ADC;};}private int countAlive(TeamState t,int time){return(int)t.getPlayers().stream().filter(p->p.isAlive(time)).count();}private double average(TeamState t,java.util.function.ToIntFunction<PlayerState> f){return t.getPlayers().stream().mapToInt(f).average().orElse(14);}private double edge(double a,double b,double n){return clamp((a-b)/n,-1,1);}private double clamp(double v,double min,double max){return Math.max(min,Math.min(max,v));}private static boolean Latest(boolean a,boolean b){return a||b;}
 private record Context(GameState s,int time,EnumMap<TeamSide,Integer>gold,EnumMap<TeamSide,Integer>alive,EnumMap<TeamSide,Double>avgTeamfight,EnumMap<TeamSide,Double>avgAggression,EnumMap<TeamSide,Boolean>baron,EnumMap<TeamSide,Boolean>elder,EnumMap<TeamSide,Boolean>big,EnumMap<TeamSide,Boolean>ace,EnumMap<TeamSide,BaseThreatSnapshot>threats){BaseThreatSnapshot threat(TeamSide side){return threats.get(side);}}
 private record PlanCandidate(LateGameAttackPlan plan,Lane lane,LateGameStructureTarget target,LateGamePlanWeightBreakdown weight){}private record ResponseCandidate(LateGameDefenseResponse response,LateGameDefenseWeightBreakdown weight){}private record CrossTarget(Lane lane,LateGameStructureTarget target,Position pusher){}
 record Resolution(boolean attempted,boolean anySuccess,double fightChance,boolean fightTriggered,FightGrade grade,TeamSide fightWinner,double structureChance,boolean structureRoll,boolean structureSuccess,Lane crossLane,LateGameStructureTarget crossTarget,double crossChance,boolean crossRoll,boolean crossSuccess,LateGameActionResult result,boolean majorCombat,boolean attackerStructure,boolean defenderStructure){static Resolution ineligible(){return new Resolution(false,false,0,false,null,null,0,false,false,null,null,0,false,false,LateGameActionResult.INELIGIBLE,false,false,false);}}
}
