package com.lolfm.simulator;
public enum LateGameActionResult {
    NOT_EVALUATED, NO_INITIATIVE, ATTACKER_RESET, SIEGE_REPELLED, STRUCTURE_DESTROYED,
    SIEGE_FIGHT_ATTACKER_WIN, SIEGE_FIGHT_DEFENDER_WIN, CROSS_MAP_SUCCEEDED, CROSS_MAP_FAILED,
    NEXUS_FINISH_ADVANCED, NEXUS_DESTROYED, STALE_TARGET, INELIGIBLE, GAME_FINISHED
}
