package com.lolfm.simulator;

public enum ObjectiveSecureIneligibleReason {
    OBJECTIVE_UNAVAILABLE,
    WINNING_JUNGLER_PROFILE_UNAVAILABLE,
    CHALLENGING_JUNGLER_PROFILE_UNAVAILABLE,
    WINNING_JUNGLER_UNAVAILABLE,
    CHALLENGING_JUNGLER_UNAVAILABLE
}
