package com.lolfm.simulator;
public final class ObjectiveDecisionRuleConfig {
 private ObjectiveDecisionRuleConfig() {}
 public static final double MIN_DECISION_WEIGHT=.10, MAX_DECISION_WEIGHT=3.00;
 public static final double GOLD_EDGE_NORMALIZER=5000.0, ATTRIBUTE_EDGE_NORMALIZER=8.0, ALIVE_EDGE_NORMALIZER=3.0;
 public static final double TAKE_BASE_WEIGHT=1.00, RESET_BASE_WEIGHT=.45;
 public static final double CONTEST_BASE_WEIGHT=.90, GIVE_BASE_WEIGHT=.70, TRADE_STRUCTURE_BASE_WEIGHT=.55;
 public static final double TAKE_PRIORITY_EDGE_WEIGHT=.55, TAKE_ALIVE_EDGE_WEIGHT=.35, TAKE_GOLD_EDGE_WEIGHT=.25, TAKE_TEAMFIGHT_EDGE_WEIGHT=.30;
 public static final double RESET_BEHIND_PRIORITY_WEIGHT=.35, RESET_BEHIND_ALIVE_WEIGHT=.45, RESET_BEHIND_GOLD_WEIGHT=.35, RESET_MISSING_PLAYER_WEIGHT=.15;
 public static final double CONTEST_PRIORITY_EDGE_WEIGHT=.45, CONTEST_ALIVE_EDGE_WEIGHT=.45, CONTEST_GOLD_EDGE_WEIGHT=.25, CONTEST_TEAMFIGHT_EDGE_WEIGHT=.45;
 public static final double GIVE_BEHIND_PRIORITY_WEIGHT=.45, GIVE_BEHIND_ALIVE_WEIGHT=.55, GIVE_BEHIND_GOLD_WEIGHT=.35, GIVE_MISSING_PLAYER_WEIGHT=.15;
 public static final double TRADE_STRUCTURE_AVAILABLE_BONUS=.35, TRADE_FARMING_EDGE_WEIGHT=.35, TRADE_BEHIND_PRIORITY_WEIGHT=.15;
 public static final double OWN_SOUL_POINT_URGENCY_BONUS=.50, ENEMY_SOUL_POINT_DENIAL_BONUS=.35, BARON_LATE_GAME_URGENCY_BONUS=.20, ELDER_URGENCY_BONUS=.75;
 public static final int BARON_LATE_GAME_START_SECONDS=1800;
 public static final double TRADE_STRUCTURE_PUSH_BASE_CHANCE=.40, TRADE_GOLD_EDGE_BONUS_MAX=.08, TRADE_ALIVE_EDGE_BONUS_PER_PLAYER=.03, TRADE_FARMING_EDGE_BONUS_MAX=.10, TRADE_BARON_BUFF_BONUS=.15;
 public static final double MIN_TRADE_STRUCTURE_CHANCE=.10, MAX_TRADE_STRUCTURE_CHANCE=.70;
}
