package com.lolfm.simulator;
public enum ObjectiveDecisionResult { NOT_EVALUATED, INITIATOR_RESET, UNCONTESTED_CAPTURE, CONTEST_FIGHT, TRADE_ATTEMPTED, TRADE_SUCCEEDED, TRADE_FAILED, STALE_OBJECTIVE, INELIGIBLE }
