package com.lolfm.simulator;
import com.lolfm.domain.*;import java.util.*;
public final class PlayerProgressionState {
 private final Position position;private boolean enabled=true;private TeamSide side;private ProgressionExecutionStats stats;private int xp,level=1,earnedGold;private ItemProgressStage stage=ItemProgressStage.STARTING;private final EnumMap<ExperienceSource,Integer>xpBySource=new EnumMap<>(ExperienceSource.class);private final EnumSet<ItemProgressStage>emittedStages=EnumSet.noneOf(ItemProgressStage.class);private final Set<Integer>emittedLevels=new HashSet<>();private final List<ProgressionEventData>pending=new ArrayList<>();
 PlayerProgressionState(Position p){position=p;for(var s:ExperienceSource.values())xpBySource.put(s,0);}
 void configure(TeamSide s,boolean on,ProgressionExecutionStats st){side=s;enabled=on;stats=st;if(!on){xp=0;level=1;earnedGold=0;stage=ItemProgressStage.STARTING;xpBySource.replaceAll((k,v)->0);pending.clear();emittedLevels.clear();emittedStages.clear();}}
 public boolean isEnabled(){return enabled;}public int getTotalExperience(){return xp;}public int getLevel(){return level;}public int getProgressionEarnedGold(){return earnedGold;}public ItemProgressStage getItemStage(){return stage;}public int getNextLevelTotalExperience(){int max=ProgressionRuleConfig.maxLevel(position);return level>=max?ProgressionRuleConfig.xpForLevel(max):ProgressionRuleConfig.xpForLevel(level+1);}public int getNextItemStageGold(){return stage==ItemProgressStage.FULL_BUILD?ProgressionRuleConfig.FULL_BUILD_GOLD_THRESHOLD:ProgressionRuleConfig.itemThreshold(ItemProgressStage.values()[stage.ordinal()+1]);}public Map<ExperienceSource,Integer>getExperienceBySource(){return Map.copyOf(xpBySource);}
 public void awardExperience(ExperienceSource source,int amount,int time){if(amount<=0||!enabled)return;int before=xp,previousLevel=level,max=ProgressionRuleConfig.maxLevel(position);xp+=amount;xpBySource.merge(source,amount,Integer::sum);if(stats!=null)stats.xp(side,position,source,amount);while(level<max&&xp>=ProgressionRuleConfig.xpForLevel(level+1)){int old=level;level++;if(emittedLevels.add(level) && side != null)pending.add(new ProgressionEventData(side,new PlayerKey(side,position),position,ProgressionEventType.LEVEL_UP,source,before,xp,amount,old,level,stage,stage,earnedGold,ProgressionRuleConfig.xpForLevel(level),time));}if(stats!=null)stats.levelUps(level-previousLevel);}
 public void awardEarnedGold(int amount,GoldSource source,int time){if(amount<=0||!enabled)return;earnedGold+=amount;if(stats!=null)stats.gold(side,position,source,amount);int reached=0;while(stage!=ItemProgressStage.FULL_BUILD){ItemProgressStage next=ItemProgressStage.values()[stage.ordinal()+1];int threshold=ProgressionRuleConfig.itemThreshold(next);if(earnedGold<threshold)break;ItemProgressStage old=stage;stage=next;reached++;if(emittedStages.add(stage) && side != null)pending.add(new ProgressionEventData(side,new PlayerKey(side,position),position,ProgressionEventType.ITEM_STAGE_REACHED,null,xp,xp,0,level,level,old,stage,earnedGold,threshold,time));}if(stats!=null)stats.stages(reached);}
 public List<ProgressionEventData>drainEvents(){List<ProgressionEventData>x=List.copyOf(pending);pending.clear();return x;}
 public PlayerProgressionSnapshot snapshot(boolean powerEnabled){int start=ProgressionRuleConfig.xpForLevel(level),next=getNextLevelTotalExperience();double lr=level>=ProgressionRuleConfig.maxLevel(position)?1:ratio(xp-start,next-start);int currentGold=ProgressionRuleConfig.itemThreshold(stage),nextGold=getNextItemStageGold();double ir=stage==ItemProgressStage.FULL_BUILD?1:ratio(earnedGold-currentGold,nextGold-currentGold);ProgressionPowerBreakdown p=new PlayerProgressionPowerEvaluator().evaluate(this,ProgressionCombatContext.TEAMFIGHT,powerEnabled);return new PlayerProgressionSnapshot(enabled,level,xp,start,next,lr,stage,earnedGold,nextGold,ir,new ProgressionPowerSnapshot(p.levelPower(),p.itemPower(),p.championMultiplier(),p.championSpikeBonus(),p.clampedTotalPower()));}
 private double ratio(double n,double d){return d<=0?1:Math.max(0,Math.min(1,n/d));}
}
