package com.lolfm.simulator;
import com.lolfm.domain.Position;
public final class ProgressionRuleConfig {
 private ProgressionRuleConfig(){}
 public static final int MAX_LEVEL=18,TOP_QUEST_MAX_LEVEL=20;
 public static final int[] TOTAL_XP_BY_LEVEL={0,0,280,660,1140,1720,2400,3180,4060,5040,6120,7300,8580,9960,11440,13020,14700,16480,18360,20320,22360};
 public static final int SOLO_LANE_XP_PER_TICK=70,TOP_QUEST_XP_PER_TICK=79,JUNGLE_XP_PER_TICK=60,BOT_SHARED_XP_PER_PLAYER_PER_TICK=56,BOT_SOLO_XP_PER_TICK=70,KILL_XP=180,ASSIST_XP=90;
 public static final int COMPONENT_GOLD_THRESHOLD=1200,FIRST_CORE_GOLD_THRESHOLD=3500,SECOND_CORE_GOLD_THRESHOLD=7000,THIRD_CORE_GOLD_THRESHOLD=10500,FOURTH_CORE_GOLD_THRESHOLD=14000,FULL_BUILD_GOLD_THRESHOLD=17500;
 public static final double LEVEL_POWER_PER_LEVEL_ABOVE_ONE=.12,ITEM_POWER_STARTING=0,ITEM_POWER_COMPONENT=.25,ITEM_POWER_FIRST_CORE=.85,ITEM_POWER_SECOND_CORE=1.65,ITEM_POWER_THIRD_CORE=2.55,ITEM_POWER_FOURTH_CORE=3.45,ITEM_POWER_FULL_BUILD=4.50,MAX_PLAYER_PROGRESSION_POWER=7.0;
 public static final double LANE_COMBAT_MULTIPLIER=.60,JUNGLE_GANK_MULTIPLIER=.65,COUNTER_GANK_MULTIPLIER=.75,ROAM_MULTIPLIER=.70,GENERIC_SKIRMISH_MULTIPLIER=.85,TEAMFIGHT_MULTIPLIER=1,OBJECTIVE_FIGHT_MULTIPLIER=1,LATE_GAME_SIEGE_MULTIPLIER=1,BASE_DEFENSE_MULTIPLIER=1;
 public static int maxLevel(Position position){return position==Position.TOP?TOP_QUEST_MAX_LEVEL:MAX_LEVEL;}
 public static int xpForLevel(int level){return TOTAL_XP_BY_LEVEL[Math.max(1,Math.min(TOP_QUEST_MAX_LEVEL,level))];}
 public static int itemThreshold(ItemProgressStage s){return switch(s){case STARTING->0;case COMPONENT->COMPONENT_GOLD_THRESHOLD;case FIRST_CORE->FIRST_CORE_GOLD_THRESHOLD;case SECOND_CORE->SECOND_CORE_GOLD_THRESHOLD;case THIRD_CORE->THIRD_CORE_GOLD_THRESHOLD;case FOURTH_CORE->FOURTH_CORE_GOLD_THRESHOLD;case FULL_BUILD->FULL_BUILD_GOLD_THRESHOLD;};}
 public static double itemPower(ItemProgressStage s){return switch(s){case STARTING->ITEM_POWER_STARTING;case COMPONENT->ITEM_POWER_COMPONENT;case FIRST_CORE->ITEM_POWER_FIRST_CORE;case SECOND_CORE->ITEM_POWER_SECOND_CORE;case THIRD_CORE->ITEM_POWER_THIRD_CORE;case FOURTH_CORE->ITEM_POWER_FOURTH_CORE;case FULL_BUILD->ITEM_POWER_FULL_BUILD;};}
 public static double contextMultiplier(ProgressionCombatContext c){return switch(c){case LANE_COMBAT->LANE_COMBAT_MULTIPLIER;case JUNGLE_GANK->JUNGLE_GANK_MULTIPLIER;case COUNTER_GANK->COUNTER_GANK_MULTIPLIER;case ROAM->ROAM_MULTIPLIER;case GENERIC_SKIRMISH->GENERIC_SKIRMISH_MULTIPLIER;case TEAMFIGHT->TEAMFIGHT_MULTIPLIER;case OBJECTIVE_FIGHT->OBJECTIVE_FIGHT_MULTIPLIER;case LATE_GAME_SIEGE->LATE_GAME_SIEGE_MULTIPLIER;case BASE_DEFENSE->BASE_DEFENSE_MULTIPLIER;};}
}
