package com.lolfm.simulator;
import com.lolfm.domain.Position;import java.util.*;
public final class ProgressionExecutionStats {
 private final EnumMap<ExperienceSource,Integer>a=new EnumMap<>(ExperienceSource.class),xp=new EnumMap<>(ExperienceSource.class);private final EnumMap<GoldSource,Integer>gold=new EnumMap<>(GoldSource.class);private final Map<PlayerKey,EnumMap<ExperienceSource,Integer>>playerXp=new HashMap<>();private final Map<PlayerKey,EnumMap<GoldSource,Integer>>playerGold=new HashMap<>();private final EnumMap<TeamSide,Integer>sideXp=new EnumMap<>(TeamSide.class);private final EnumMap<Position,Integer>posXp=new EnumMap<>(Position.class);private final EnumMap<ProgressionCombatContext,Double>edges=new EnumMap<>(ProgressionCombatContext.class),contrib=new EnumMap<>(ProgressionCombatContext.class);private int dead,activity,recovery,shared,adcSolo,supportSolo,absent,jungle,dupXp,invalid,offMutation,levelUps,multiLevel,stages,multiStage,dupLevel,dupStage,levelRollback,itemRollback,over18,powerApps,powerOff,champMult,champSpike,posMult,levelSpike;private final List<ProgressionCombatSample> combatSamples=new ArrayList<>();
 public ProgressionExecutionStats(){for(var x:ExperienceSource.values()){a.put(x,0);xp.put(x,0);}for(var x:GoldSource.values())gold.put(x,0);for(var x:TeamSide.values())sideXp.put(x,0);for(var x:Position.values())posXp.put(x,0);for(var x:ProgressionCombatContext.values()){edges.put(x,0d);contrib.put(x,0d);}}
 void xp(TeamSide s,Position p,ExperienceSource src,int amount){a.merge(src,1,Integer::sum);xp.merge(src,amount,Integer::sum);sideXp.merge(s,amount,Integer::sum);posXp.merge(p,amount,Integer::sum);playerXp.computeIfAbsent(new PlayerKey(s,p),k->new EnumMap<>(ExperienceSource.class)).merge(src,amount,Integer::sum);}void gold(TeamSide side,Position position,GoldSource s,int n){gold.merge(s,n,Integer::sum);playerGold.computeIfAbsent(new PlayerKey(side,position),k->new EnumMap<>(GoldSource.class)).merge(s,n,Integer::sum);}void dead(){dead++;}void activity(){activity++;}void recovery(){recovery++;}void shared(){shared++;}void adcSolo(){adcSolo++;}void supportSolo(){supportSolo++;}void absent(){absent++;}void jungle(){jungle++;}void off(){offMutation++;}void levelUps(int n){levelUps+=n;if(n>1)multiLevel++;}void stages(int n){stages+=n;if(n>1)multiStage++;}void power(ProgressionCombatContext c,double edge,double value){powerApps++;edges.merge(c,edge,Double::sum);contrib.merge(c,value,Double::sum);}void combatSample(ProgressionCombatSample sample){combatSamples.add(sample);}
 private Map<PlayerKey,Map<ExperienceSource,Integer>> deepXp(){Map<PlayerKey,Map<ExperienceSource,Integer>>r=new HashMap<>();playerXp.forEach((k,v)->r.put(k,Map.copyOf(v)));return r;}private Map<PlayerKey,Map<GoldSource,Integer>> deepGold(){Map<PlayerKey,Map<GoldSource,Integer>>r=new HashMap<>();playerGold.forEach((k,v)->r.put(k,Map.copyOf(v)));return r;}
 public ProgressionExecutionStatsSnapshot snapshot(){return new ProgressionExecutionStatsSnapshot(a,xp,gold,deepXp(),deepGold(),sideXp,posXp,dead,activity,recovery,shared,adcSolo,supportSolo,absent,jungle,dupXp,invalid,offMutation,levelUps,multiLevel,stages,multiStage,dupLevel,dupStage,levelRollback,itemRollback,over18,powerApps,powerOff,champMult,champSpike,posMult,levelSpike,edges,contrib,combatSamples);}
}
