package com.lolfm.simulator;

public record RoamExecutionStatsSnapshot(
        int roamResolverEvaluations,
        int midCandidateEvaluationsBlue,
        int midCandidateEvaluationsRed,
        int supportCandidateEvaluationsBlue,
        int supportCandidateEvaluationsRed,
        int roamIneligibleDead,
        int roamIneligibleCooldown,
        int roamIneligibleActivity,
        int roamIneligibleNoTarget,
        int roamSkippedByHigherPriorityActualCombat,
        int roamTriggerRolls,
        int roamTriggersBlue,
        int roamTriggersRed,
        int multipleRoamTriggers,
        int actualRoamAttempts,
        int actualMidRoams,
        int actualSupportRoams,
        int unselectedTriggeredCandidates,
        int midToTopAttempts,
        int midToBotAttempts,
        int supportToMidAttempts,
        int roamNoKill,
        int roamingSideKills,
        int defendingSideKills,
        int roamBlockedLaneCombat,
        int roamEvaluationFallthroughToLaneCombat,
        int roamBlockedGeneric,
        int activityCreated,
        int activityReturned,
        int activityClearedByDeath
) { }
