package com.lolfm.simulator;

/** Production tuning values for the initial MID and SUPPORT roam model. */
public final class RoamRuleConfig {
    private RoamRuleConfig() { }
    public static final int MID_ROAM_START_SECONDS = 240, SUPPORT_ROAM_START_SECONDS = 300, ROAM_END_SECONDS = 840, ROAM_EVALUATION_INTERVAL_SECONDS = 60;
    public static final int ROAM_ACTION_COOLDOWN_SECONDS = 180, SAME_TARGET_REPEAT_WINDOW_SECONDS = 240, ROAM_ACTIVITY_SECONDS = 30;
    public static final int MID_ROAM_FARM_BLOCK_SECONDS = 30, SUPPORT_ROAM_FARM_BLOCK_SECONDS = 0;
    public static final double BASE_MID_ROAM_ATTEMPT_CHANCE = .05, BASE_SUPPORT_ROAM_ATTEMPT_CHANCE = .04, MIN_ROAM_ATTEMPT_CHANCE = .02, MAX_ROAM_ATTEMPT_CHANCE = .20;
    public static final double ROAMER_AGGRESSION_ATTEMPT_FACTOR = .01, ROAMER_AGGRESSION_ATTEMPT_MIN = -.04, ROAMER_AGGRESSION_ATTEMPT_MAX = .06, ORIGIN_PRIORITY_ATTEMPT_MAX_BONUS = .08, TARGET_OVEREXTENSION_ATTEMPT_MAX_BONUS = .06;
    public static final double BASE_TARGET_WEIGHT = 1, MIN_TARGET_WEIGHT = .10, TARGET_OVEREXTENSION_WEIGHT_MAX_BONUS = 2, FOLLOWUP_TARGET_FACTOR = .06, FOLLOWUP_TARGET_MIN = -.24, FOLLOWUP_TARGET_MAX = .36, TARGET_GOLD_DIVISOR = 600, TARGET_GOLD_MIN = -.50, TARGET_GOLD_MAX = 1;
    public static final double BOT_TARGET_WEIGHT_MULTIPLIER = 1.05, REPEAT_TARGET_WEIGHT_MULTIPLIER = .35;
    public static final double MID_ORIGIN_PRESSURE_COST = 8, SUPPORT_ORIGIN_PRESSURE_COST = 10;
    public static final double ROAMER_MECHANICS_CONTRIBUTION = .45, TARGET_GROUP_MECHANICS_CONTRIBUTION = .55, ROAMER_AGGRESSION_CONTRIBUTION = .55, TARGET_GROUP_AGGRESSION_CONTRIBUTION = .45, ROAMER_TEAMFIGHTING_CONTRIBUTION = .40, TARGET_GROUP_TEAMFIGHTING_CONTRIBUTION = .60;
    public static final double BOT_ADC_MECHANICS_CONTRIBUTION = .60, BOT_SUPPORT_MECHANICS_CONTRIBUTION = .40, BOT_ADC_AGGRESSION_CONTRIBUTION = .35, BOT_SUPPORT_AGGRESSION_CONTRIBUTION = .65, BOT_ADC_TEAMFIGHTING_CONTRIBUTION = .45, BOT_SUPPORT_TEAMFIGHTING_CONTRIBUTION = .55;
    public static final double SOLO_ROAM_NUMBERS_EDGE = 2, BOT_ROAM_NUMBERS_EDGE = 1.5, ROAM_MECHANICS_EDGE_FACTOR = .70, ROAM_AGGRESSION_EDGE_FACTOR = .10, ROAM_TEAMFIGHTING_EDGE_FACTOR = .20, ROAM_GOLD_DIVISOR = 400, ROAM_GOLD_EDGE_MIN = -4, ROAM_GOLD_EDGE_MAX = 4, ROAM_VULNERABILITY_DIVISOR = 15, ROAM_VULNERABILITY_EDGE_MAX = 4;
    public static final double BASE_ROAM_DECISIVE_CHANCE = .35, ROAMER_AGGRESSION_DECISIVE_FACTOR = .015, ROAM_DECISIVE_EDGE_FACTOR = .015, ROAM_DECISIVE_OVEREXTENSION_MAX_BONUS = .10, MIN_ROAM_DECISIVE_CHANCE = .25, MAX_ROAM_DECISIVE_CHANCE = .70;
    public static final double BASE_ROAM_SUCCESS_CHANCE = .58, ROAM_SUCCESS_EDGE_FACTOR = .03, MIN_ROAM_SUCCESS_CHANCE = .25, MAX_ROAM_SUCCESS_CHANCE = .88;
    public static final double SOLO_TARGET_PRESSURE_SHOCK = 15, BOT_TARGET_PRESSURE_SHOCK = 12;
    public static final double MID_TO_TOP_ROAMER_KILLER_WEIGHT = .50, MID_TO_TOP_LANER_KILLER_WEIGHT = .50, MID_TO_BOT_ROAMER_KILLER_WEIGHT = .35, MID_TO_BOT_ADC_KILLER_WEIGHT = .45, MID_TO_BOT_SUPPORT_KILLER_WEIGHT = .20, SUPPORT_TO_MID_ROAMER_KILLER_WEIGHT = .25, SUPPORT_TO_MID_MID_KILLER_WEIGHT = .75;
    public static final double BOT_SUCCESS_ADC_VICTIM_WEIGHT = .65, BOT_SUCCESS_SUPPORT_VICTIM_WEIGHT = .35;
    public static final double SOLO_REVERSE_ROAMER_VICTIM_WEIGHT = .60, SOLO_REVERSE_TARGET_LANER_VICTIM_WEIGHT = .40, BOT_REVERSE_ROAMER_VICTIM_WEIGHT = .45, BOT_REVERSE_ADC_VICTIM_WEIGHT = .35, BOT_REVERSE_SUPPORT_VICTIM_WEIGHT = .20, BOT_REVERSE_ADC_KILLER_WEIGHT = .75, BOT_REVERSE_SUPPORT_KILLER_WEIGHT = .25;
}
