package com.lolfm.simulator;
/** Per-simulator feature and observational-instrumentation options. */
public record SimulationOptions(boolean laneCombatEnabled,boolean farmRecoveryEnabled,boolean jungleGankEnabled,boolean counterGankEnabled,boolean roamEnabled,boolean diagnosticsEnabled,boolean objectivePriorityEnabled,boolean lanePhaseEnabled,boolean midGameMacroEnabled,boolean objectiveDecisionEnabled,boolean lateGameMacroEnabled,boolean progressionEnabled,boolean progressionPowerEnabled){
 public SimulationOptions{if(!progressionEnabled)progressionPowerEnabled=false;}
 public SimulationOptions(boolean a,boolean b,boolean c,boolean d,boolean e,boolean f,boolean g,boolean h){this(a,b,c,d,e,f,g,h,true,true,true,true,true);}
 public SimulationOptions(boolean a,boolean b,boolean c,boolean d,boolean e,boolean f,boolean g,boolean h,boolean i){this(a,b,c,d,e,f,g,h,i,true,true,true,true);}
 public SimulationOptions(boolean a,boolean b,boolean c,boolean d,boolean e,boolean f,boolean g,boolean h,boolean i,boolean j){this(a,b,c,d,e,f,g,h,i,j,true,true,true);}
 public SimulationOptions(boolean a,boolean b,boolean c,boolean d,boolean e,boolean f,boolean g,boolean h,boolean i,boolean j,boolean k){this(a,b,c,d,e,f,g,h,i,j,k,true,true);}
 public static SimulationOptions productionDefaults(){return new SimulationOptions(true,true,true,true,true,true,true,true,true,true,true,true,true);}
 private SimulationOptions copy(Boolean roam,Boolean diagnostics,Boolean priority,Boolean lane,Boolean macro,Boolean decision,Boolean late,Boolean progression,Boolean power){return new SimulationOptions(laneCombatEnabled,farmRecoveryEnabled,jungleGankEnabled,counterGankEnabled,roam==null?roamEnabled:roam,diagnostics==null?diagnosticsEnabled:diagnostics,priority==null?objectivePriorityEnabled:priority,lane==null?lanePhaseEnabled:lane,macro==null?midGameMacroEnabled:macro,decision==null?objectiveDecisionEnabled:decision,late==null?lateGameMacroEnabled:late,progression==null?progressionEnabled:progression,power==null?progressionPowerEnabled:power);}
 public SimulationOptions withRoamEnabled(boolean v){return copy(v,null,null,null,null,null,null,null,null);}public SimulationOptions withDiagnosticsEnabled(boolean v){return copy(null,v,null,null,null,null,null,null,null);}public SimulationOptions withObjectivePriorityEnabled(boolean v){return copy(null,null,v,null,null,null,null,null,null);}public SimulationOptions withLanePhaseEnabled(boolean v){return copy(null,null,null,v,null,null,null,null,null);}public SimulationOptions withMidGameMacroEnabled(boolean v){return copy(null,null,null,null,v,null,null,null,null);}public SimulationOptions withObjectiveDecisionEnabled(boolean v){return copy(null,null,null,null,null,v,null,null,null);}public SimulationOptions withLateGameMacroEnabled(boolean v){return copy(null,null,null,null,null,null,v,null,null);}public SimulationOptions withProgressionEnabled(boolean v){return copy(null,null,null,null,null,null,null,v,v?progressionPowerEnabled:false);}public SimulationOptions withProgressionPowerEnabled(boolean v){return copy(null,null,null,null,null,null,null,null,v);}
}
