import type {
  LeagueApiErrorDto, LeagueCompletionStatusResponseDto, LeagueCompletionStatusViewDto,
  LeagueFixtureCommand, LeagueFixtureListDto, LeagueFixtureResponseDto, LeagueFixtureStatus,
  LeagueFixtureViewDto, LeagueJobResponseDto, LeagueJobStatus, LeagueJobViewDto,
  LeaguePlayerCommand, LeaguePlayerSeriesResponseDto, LeaguePlayerSeriesViewDto,
  LeagueRunResponseDto, LeagueSeasonCommand, LeagueSeasonResponseDto, LeagueSeasonStatus,
  LeagueSeasonViewDto, LeagueStandingRowDto, LeagueStandingsDto,
} from './leagueApi.types';

export class LeagueContractError extends Error {
  readonly path: string;
  constructor(path: string, message: string) { super(`${path}: ${message}`); this.path = path; this.name = 'LeagueContractError'; }
}

type JsonObject = Record<string, unknown>;
const SEASON_STATUSES = ['DRAFT', 'FROZEN', 'READY', 'RUNNING', 'PAUSED', 'WAITING_FOR_PLAYER', 'COMPLETED', 'BLOCKED', 'CANCELLED'] as const;
const FIXTURE_STATUSES = ['SCHEDULED', 'QUEUED', 'LEASED', 'RUNNING', 'AWAITING_PLAYER', 'PLAYER_SERIES_RESERVED', 'PLAYER_SERIES_ACTIVE', 'COMPLETION_PENDING_VERIFICATION', 'RETRY_PENDING', 'PLAYER_SERIES_RESTART_REQUIRED', 'COMPLETED', 'BLOCKED', 'CANCELLED'] as const;
const JOB_STATUSES = ['QUEUED', 'LEASED', 'RUNNING', 'RETRY_PENDING', 'COMPLETION_PENDING_VERIFICATION', 'COMPLETED', 'BLOCKED', 'CANCELLED'] as const;
const PLAYER_COMMANDS = ['START_PLAYER_SERIES', 'RESUME_PLAYER_SERIES', 'RECONCILE_PLAYER_SERIES_COMPLETION'] as const;
const FIXTURE_COMMANDS = ['VIEW_FIXTURE', ...PLAYER_COMMANDS] as const;
const SEASON_COMMANDS = ['VIEW_STANDINGS', 'VIEW_FIXTURE', 'RUN_CURRENT_ROUND_AUTO_FIXTURES', 'PAUSE_SEASON', 'RESUME_SEASON', 'CANCEL_SEASON', ...PLAYER_COMMANDS] as const;
const BINDING_STATUSES = ['CREATED', 'ACTIVE', 'COMPLETION_PENDING_VERIFICATION', 'VERIFIED', 'PLAYER_SERIES_RESTART_REQUIRED', 'BLOCKED'] as const;
const HASH = /^[0-9a-f]{64}$/; const TEAM = /^[A-Z0-9]{2,8}$/;
const IDS = { league: /^league_[0-9a-f]{64}$/, season: /^season_[0-9a-f]{64}$/, fixture: /^fixture_[0-9a-f]{64}$/, job: /^job_[0-9a-f]{64}$/, series: /^series_[0-9a-f]{64}$/ };

function fail(path: string, message: string): never { throw new LeagueContractError(path, message); }
function object(value: unknown, path: string): JsonObject { if (typeof value !== 'object' || value === null || Array.isArray(value)) fail(path, '객체가 필요합니다.'); return value as JsonObject; }
function exact(value: JsonObject, fields: readonly string[], path: string): void {
  const expected = new Set(fields); const actual = Object.keys(value);
  const unknown = actual.find((key) => !expected.has(key)); if (unknown) fail(`${path}.${unknown}`, '지원하지 않는 필드입니다.');
  const missing = fields.find((key) => !Object.prototype.hasOwnProperty.call(value, key)); if (missing) fail(`${path}.${missing}`, '필드가 필요합니다.');
}
function string(value: unknown, path: string, pattern?: RegExp): string { if (typeof value !== 'string' || value.length === 0 || (pattern && !pattern.test(value))) fail(path, '문자열 형식이 올바르지 않습니다.'); return value; }
function nullableString(value: unknown, path: string, pattern?: RegExp): string | null { return value === null ? null : string(value, path, pattern); }
function bool(value: unknown, path: string): boolean { if (typeof value !== 'boolean') fail(path, 'boolean 값이 필요합니다.'); return value; }
function integer(value: unknown, path: string, minimum = 0): number { if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < minimum) fail(path, `${minimum} 이상의 안전한 정수가 필요합니다.`); return value; }
function enumeration<T extends string>(value: unknown, values: readonly T[], path: string): T { if (typeof value !== 'string' || !values.includes(value as T)) fail(path, `허용되지 않은 값 ${String(value)}입니다.`); return value as T; }
function nullableEnum<T extends string>(value: unknown, values: readonly T[], path: string): T | null { return value === null ? null : enumeration(value, values, path); }
function array(value: unknown, path: string): unknown[] { if (!Array.isArray(value)) fail(path, '배열이 필요합니다.'); return value; }
function canonicalLong(value: unknown, path: string): string { const text = string(value, path, /^-?(0|[1-9][0-9]*)$/); try { const parsed = BigInt(text); if (parsed < -9223372036854775808n || parsed > 9223372036854775807n) fail(path, 'signed-long 범위를 벗어났습니다.'); } catch { fail(path, 'signed-long 문자열이 필요합니다.'); } return text; }
function iso(value: unknown, path: string): string { const text = string(value, path); if (!Number.isFinite(Date.parse(text))) fail(path, 'ISO 날짜/시간이 필요합니다.'); return text; }
function unique<T>(values: readonly T[], path: string): void { if (new Set(values).size !== values.length) fail(path, '중복 값은 허용되지 않습니다.'); }
function commands<T extends string>(value: unknown, values: readonly T[], path: string): readonly T[] { const result = array(value, path).map((item, index) => enumeration(item, values, `${path}[${index}]`)); unique(result, path); return result; }

function standing(value: unknown, path: string): LeagueStandingRowDto {
  const root = object(value, path); exact(root, ['position', 'teamCode', 'seriesWins', 'seriesLosses', 'gameWins', 'gameLosses', 'gameDifferential', 'deterministicDrawHash'], path);
  const row = { position: integer(root.position, `${path}.position`, 1), teamCode: string(root.teamCode, `${path}.teamCode`, TEAM), seriesWins: integer(root.seriesWins, `${path}.seriesWins`), seriesLosses: integer(root.seriesLosses, `${path}.seriesLosses`), gameWins: integer(root.gameWins, `${path}.gameWins`), gameLosses: integer(root.gameLosses, `${path}.gameLosses`), gameDifferential: integer(root.gameDifferential, `${path}.gameDifferential`, -99), deterministicDrawHash: nullableString(root.deterministicDrawHash, `${path}.deterministicDrawHash`, HASH) };
  if (row.gameDifferential !== row.gameWins - row.gameLosses) fail(`${path}.gameDifferential`, '승패 차이와 일치하지 않습니다.');
  return row;
}

function standings(value: unknown, path: string): readonly LeagueStandingRowDto[] {
  const rows = array(value, path).map((item, index) => standing(item, `${path}[${index}]`));
  if (rows.length !== 10) fail(path, '정확히 10팀이어야 합니다.'); unique(rows.map((row) => row.teamCode), `${path}.teamCode`); unique(rows.map((row) => row.position), `${path}.position`);
  if (rows.some((row, index) => row.position !== index + 1)) fail(path, '순위가 1위부터 정렬되어야 합니다.'); return rows;
}

function fixture(value: unknown, path: string): LeagueFixtureViewDto {
  const root = object(value, path); exact(root, ['fixtureId', 'roundNumber', 'lifecycleStatus', 'revision', 'executionMode', 'firstTeamCode', 'secondTeamCode', 'game1BlueTeamCode', 'game1RedTeamCode', 'seriesFormat', 'fixtureRootSeed', 'boundSeriesId', 'bindingHash', 'playerSeriesStatus', 'completionStatus', 'jobId', 'jobStatus', 'allowedCommands'], path);
  const result: LeagueFixtureViewDto = {
    fixtureId: string(root.fixtureId, `${path}.fixtureId`, IDS.fixture), roundNumber: integer(root.roundNumber, `${path}.roundNumber`, 1), lifecycleStatus: enumeration(root.lifecycleStatus, FIXTURE_STATUSES, `${path}.lifecycleStatus`) as LeagueFixtureStatus, revision: integer(root.revision, `${path}.revision`), executionMode: enumeration(root.executionMode, ['FULL_AUTO', 'PLAYER_CONTROLLED'] as const, `${path}.executionMode`), firstTeamCode: string(root.firstTeamCode, `${path}.firstTeamCode`, TEAM), secondTeamCode: string(root.secondTeamCode, `${path}.secondTeamCode`, TEAM), game1BlueTeamCode: string(root.game1BlueTeamCode, `${path}.game1BlueTeamCode`, TEAM), game1RedTeamCode: string(root.game1RedTeamCode, `${path}.game1RedTeamCode`, TEAM), seriesFormat: enumeration(root.seriesFormat, ['BO3'] as const, `${path}.seriesFormat`), fixtureRootSeed: canonicalLong(root.fixtureRootSeed, `${path}.fixtureRootSeed`), boundSeriesId: string(root.boundSeriesId, `${path}.boundSeriesId`, IDS.series), bindingHash: nullableString(root.bindingHash, `${path}.bindingHash`, HASH), playerSeriesStatus: nullableEnum(root.playerSeriesStatus, BINDING_STATUSES, `${path}.playerSeriesStatus`), completionStatus: enumeration(root.completionStatus, ['NOT_CREATED', 'PENDING_RECONCILIATION', 'APPLIED'] as const, `${path}.completionStatus`), jobId: nullableString(root.jobId, `${path}.jobId`, IDS.job), jobStatus: nullableEnum(root.jobStatus, JOB_STATUSES, `${path}.jobStatus`) as LeagueJobStatus | null, allowedCommands: commands(root.allowedCommands, FIXTURE_COMMANDS, `${path}.allowedCommands`) as readonly LeagueFixtureCommand[],
  };
  if (result.roundNumber > 18 || result.firstTeamCode === result.secondTeamCode || new Set([result.game1BlueTeamCode, result.game1RedTeamCode]).size !== 2 || ![result.firstTeamCode, result.secondTeamCode].includes(result.game1BlueTeamCode) || ![result.firstTeamCode, result.secondTeamCode].includes(result.game1RedTeamCode)) fail(path, 'fixture 팀/라운드 identity가 올바르지 않습니다.');
  if ((result.jobId === null) !== (result.jobStatus === null)) fail(path, 'job ID와 상태는 함께 존재해야 합니다.');
  if (result.executionMode === 'FULL_AUTO' && result.allowedCommands.some((item) => PLAYER_COMMANDS.includes(item as LeaguePlayerCommand))) fail(`${path}.allowedCommands`, '자동 fixture는 Player 명령을 허용할 수 없습니다.');
  if (result.lifecycleStatus === 'COMPLETED' && result.completionStatus !== 'APPLIED') fail(`${path}.completionStatus`, '완료 fixture는 standings 반영 상태여야 합니다.');
  return result;
}

function counters(value: unknown, path: string) {
  const root = object(value, path); exact(root, ['total', 'completed', 'inProgress', 'waiting', 'blocked', 'cancelled'], path);
  const result = { total: integer(root.total, `${path}.total`), completed: integer(root.completed, `${path}.completed`), inProgress: integer(root.inProgress, `${path}.inProgress`), waiting: integer(root.waiting, `${path}.waiting`), blocked: integer(root.blocked, `${path}.blocked`), cancelled: integer(root.cancelled, `${path}.cancelled`) };
  if (result.total !== 90 || result.completed + result.inProgress + result.waiting + result.blocked + result.cancelled !== result.total) fail(path, '90개 fixture 카운터 합계가 일치하지 않습니다.'); return result;
}

function season(value: unknown, path: string): LeagueSeasonViewDto {
  const root = object(value, path); exact(root, ['leagueId', 'seasonId', 'lifecycleStatus', 'lifecycleRevision', 'standingsRevision', 'seasonMode', 'managedTeamCode', 'seasonRootSeed', 'scheduleIdentity', 'frozenSnapshotIdentity', 'productDecisionHash', 'productionRuntimeIdentity', 'currentRound', 'fixtureCounters', 'standings', 'playableManagedFixture', 'allowedCommands', 'updatedAt'], path);
  const mode = enumeration(root.seasonMode, ['HYBRID_MANAGER', 'SPECTATOR_FULL_AUTO'] as const, `${path}.seasonMode`); const managed = nullableString(root.managedTeamCode, `${path}.managedTeamCode`, TEAM);
  if ((mode === 'HYBRID_MANAGER') !== (managed !== null)) fail(`${path}.managedTeamCode`, 'Season mode의 관리 팀 규칙과 일치하지 않습니다.');
  const playable = root.playableManagedFixture === null ? null : fixture(root.playableManagedFixture, `${path}.playableManagedFixture`);
  if ((mode === 'SPECTATOR_FULL_AUTO' && playable !== null) || (playable && (playable.executionMode !== 'PLAYER_CONTROLLED' || ![playable.firstTeamCode, playable.secondTeamCode].includes(managed ?? '')))) fail(`${path}.playableManagedFixture`, '관리 팀 Player fixture가 아닙니다.');
  const currentRound = integer(root.currentRound, `${path}.currentRound`, 1); if (currentRound > 18) fail(`${path}.currentRound`, '18 이하여야 합니다.');
  const lifecycleStatus = enumeration(root.lifecycleStatus, SEASON_STATUSES, `${path}.lifecycleStatus`) as LeagueSeasonStatus; const allowedCommands = commands(root.allowedCommands, SEASON_COMMANDS, `${path}.allowedCommands`) as readonly LeagueSeasonCommand[]; const mutationCommands = allowedCommands.filter((command) => !['VIEW_STANDINGS', 'VIEW_FIXTURE'].includes(command));
  if (lifecycleStatus === 'READY' && allowedCommands.some((command) => ['PAUSE_SEASON', 'RESUME_SEASON'].includes(command))) fail(`${path}.allowedCommands`, 'READY에서는 pause/resume을 노출할 수 없습니다.');
  if (['RUNNING', 'WAITING_FOR_PLAYER'].includes(lifecycleStatus) && allowedCommands.includes('RESUME_SEASON')) fail(`${path}.allowedCommands`, '진행 중 Season은 resume을 노출할 수 없습니다.');
  if (lifecycleStatus === 'PAUSED' && allowedCommands.some((command) => command !== 'VIEW_STANDINGS' && command !== 'VIEW_FIXTURE' && command !== 'RESUME_SEASON' && command !== 'CANCEL_SEASON')) fail(`${path}.allowedCommands`, 'PAUSED에서는 resume/cancel만 변경 명령으로 허용됩니다.');
  if (['DRAFT', 'FROZEN', 'COMPLETED', 'BLOCKED', 'CANCELLED'].includes(lifecycleStatus) && mutationCommands.length > 0) fail(`${path}.allowedCommands`, '비활성/terminal Season은 변경 명령을 노출할 수 없습니다.');
  return { leagueId: string(root.leagueId, `${path}.leagueId`, IDS.league), seasonId: string(root.seasonId, `${path}.seasonId`, IDS.season), lifecycleStatus, lifecycleRevision: integer(root.lifecycleRevision, `${path}.lifecycleRevision`), standingsRevision: integer(root.standingsRevision, `${path}.standingsRevision`), seasonMode: mode, managedTeamCode: managed, seasonRootSeed: canonicalLong(root.seasonRootSeed, `${path}.seasonRootSeed`), scheduleIdentity: string(root.scheduleIdentity, `${path}.scheduleIdentity`, HASH), frozenSnapshotIdentity: string(root.frozenSnapshotIdentity, `${path}.frozenSnapshotIdentity`, HASH), productDecisionHash: string(root.productDecisionHash, `${path}.productDecisionHash`, HASH), productionRuntimeIdentity: string(root.productionRuntimeIdentity, `${path}.productionRuntimeIdentity`, HASH), currentRound, fixtureCounters: counters(root.fixtureCounters, `${path}.fixtureCounters`), standings: standings(root.standings, `${path}.standings`), playableManagedFixture: playable, allowedCommands, updatedAt: iso(root.updatedAt, `${path}.updatedAt`) };
}

function job(value: unknown, path: string): LeagueJobViewDto {
  const root = object(value, path); exact(root, ['jobId', 'fixtureId', 'lifecycleStatus', 'revision', 'attemptNumber', 'failureClass', 'failureCode', 'retryable', 'updatedAt'], path);
  const status = enumeration(root.lifecycleStatus, JOB_STATUSES, `${path}.lifecycleStatus`) as LeagueJobStatus; const failureClass = nullableEnum(root.failureClass, ['TRANSIENT', 'DETERMINISTIC'] as const, `${path}.failureClass`); const failureCode = nullableString(root.failureCode, `${path}.failureCode`, /^[A-Z][A-Z0-9_]{2,159}$/); const retryable = bool(root.retryable, `${path}.retryable`);
  if (retryable !== ['QUEUED', 'RETRY_PENDING'].includes(status)) fail(`${path}.retryable`, 'job 상태와 재시도 가능 여부가 일치하지 않습니다.');
  if (status === 'COMPLETED' && (failureClass !== null || failureCode !== null)) fail(path, '완료 job에 failure가 남아 있습니다.');
  return { jobId: string(root.jobId, `${path}.jobId`, IDS.job), fixtureId: string(root.fixtureId, `${path}.fixtureId`, IDS.fixture), lifecycleStatus: status, revision: integer(root.revision, `${path}.revision`), attemptNumber: integer(root.attemptNumber, `${path}.attemptNumber`), failureClass, failureCode, retryable, updatedAt: iso(root.updatedAt, `${path}.updatedAt`) };
}

function wrapper(value: unknown, schema: string, fields: readonly string[], path = '$'): JsonObject { const root = object(value, path); exact(root, fields, path); if (root.schemaVersion !== schema) fail(`${path}.schemaVersion`, `${schema}가 필요합니다.`); return root; }
function requireScope(actualLeague: string, actualSeason: string, leagueId: string, seasonId: string, path: string) { if (actualLeague !== leagueId || actualSeason !== seasonId) fail(path, '요청한 League/Season scope와 다릅니다.'); }

export function validateLeagueSeasonResponse(value: unknown, scope?: { leagueId: string; seasonId: string }): LeagueSeasonResponseDto { const root = wrapper(value, 'AI_LEAGUE_SEASON_VIEW_V1', ['schemaVersion', 'replayed', 'season']); const result = { schemaVersion: 'AI_LEAGUE_SEASON_VIEW_V1' as const, replayed: bool(root.replayed, '$.replayed'), season: season(root.season, '$.season') }; if (scope) requireScope(result.season.leagueId, result.season.seasonId, scope.leagueId, scope.seasonId, '$.season'); return result; }
export function validateLeagueFixtureList(value: unknown, scope: { leagueId: string; seasonId: string }): LeagueFixtureListDto {
  const root = wrapper(value, 'AI_LEAGUE_FIXTURE_LIST_V1', ['schemaVersion', 'leagueId', 'seasonId', 'lifecycleRevision', 'standingsRevision', 'fixtures']); const leagueId = string(root.leagueId, '$.leagueId', IDS.league); const seasonId = string(root.seasonId, '$.seasonId', IDS.season); requireScope(leagueId, seasonId, scope.leagueId, scope.seasonId, '$'); const fixtures = array(root.fixtures, '$.fixtures').map((item, index) => fixture(item, `$.fixtures[${index}]`));
  if (fixtures.length !== 90) fail('$.fixtures', '정확히 90개 fixture여야 합니다.'); unique(fixtures.map((item) => item.fixtureId), '$.fixtures.fixtureId'); for (let round = 1; round <= 18; round += 1) if (fixtures.filter((item) => item.roundNumber === round).length !== 5) fail('$.fixtures', `Round ${round}은 5경기여야 합니다.`); const playerCount = fixtures.filter((item) => item.executionMode === 'PLAYER_CONTROLLED').length; if (playerCount !== 0 && playerCount !== 18) fail('$.fixtures', 'Hybrid는 Player 18개, Spectator는 0개여야 합니다.');
  const teams = new Set(fixtures.flatMap((item) => [item.firstTeamCode, item.secondTeamCode])); if (teams.size !== 10 || [...teams].some((team) => fixtures.filter((item) => item.firstTeamCode === team || item.secondTeamCode === team).length !== 18)) fail('$.fixtures', '10팀 double round-robin 구조가 아닙니다.');
  return { schemaVersion: 'AI_LEAGUE_FIXTURE_LIST_V1', leagueId, seasonId, lifecycleRevision: integer(root.lifecycleRevision, '$.lifecycleRevision'), standingsRevision: integer(root.standingsRevision, '$.standingsRevision'), fixtures };
}
export function validateLeagueFixtureResponse(value: unknown): LeagueFixtureResponseDto { const root = wrapper(value, 'AI_LEAGUE_FIXTURE_VIEW_V1', ['schemaVersion', 'fixture']); return { schemaVersion: 'AI_LEAGUE_FIXTURE_VIEW_V1', fixture: fixture(root.fixture, '$.fixture') }; }
export function validateLeagueStandings(value: unknown, scope: { leagueId: string; seasonId: string }): LeagueStandingsDto { const root = wrapper(value, 'AI_LEAGUE_STANDINGS_VIEW_V1', ['schemaVersion', 'leagueId', 'seasonId', 'standingsRevision', 'standingsPolicyId', 'rows']); const leagueId = string(root.leagueId, '$.leagueId', IDS.league); const seasonId = string(root.seasonId, '$.seasonId', IDS.season); requireScope(leagueId, seasonId, scope.leagueId, scope.seasonId, '$'); return { schemaVersion: 'AI_LEAGUE_STANDINGS_VIEW_V1', leagueId, seasonId, standingsRevision: integer(root.standingsRevision, '$.standingsRevision'), standingsPolicyId: string(root.standingsPolicyId, '$.standingsPolicyId'), rows: standings(root.rows, '$.rows') }; }
export function validateLeagueJobResponse(value: unknown, fixtureId?: string): LeagueJobResponseDto { const root = wrapper(value, 'AI_LEAGUE_JOB_VIEW_V1', ['schemaVersion', 'job']); const result = { schemaVersion: 'AI_LEAGUE_JOB_VIEW_V1' as const, job: job(root.job, '$.job') }; if (fixtureId && result.job.fixtureId !== fixtureId) fail('$.job.fixtureId', '요청 fixture scope와 다릅니다.'); return result; }
export function validateLeagueRunResponse(value: unknown, scope: { leagueId: string; seasonId: string }): LeagueRunResponseDto { const root = wrapper(value, 'AI_LEAGUE_RUN_RESPONSE_V1', ['schemaVersion', 'replayed', 'queued', 'existing', 'playerFixturesExcluded', 'season', 'jobs']); const seasonValue = season(root.season, '$.season'); requireScope(seasonValue.leagueId, seasonValue.seasonId, scope.leagueId, scope.seasonId, '$.season'); const jobs = array(root.jobs, '$.jobs').map((item, index) => job(item, `$.jobs[${index}]`)); unique(jobs.map((item) => item.jobId), '$.jobs.jobId'); const queued = integer(root.queued, '$.queued'); const existing = integer(root.existing, '$.existing'); if (queued + existing !== jobs.length) fail('$.jobs', 'queued/existing 합계와 일치하지 않습니다.'); return { schemaVersion: 'AI_LEAGUE_RUN_RESPONSE_V1', replayed: bool(root.replayed, '$.replayed'), queued, existing, playerFixturesExcluded: integer(root.playerFixturesExcluded, '$.playerFixturesExcluded'), season: seasonValue, jobs };
}

function playerSeries(value: unknown, path: string): LeaguePlayerSeriesViewDto { const root = object(value, path); exact(root, ['leagueId', 'seasonId', 'fixtureId', 'bindingHash', 'bindingRevision', 'lifecycleStatus', 'boundSeriesId', 'completionReceiptHash', 'allowedCommands'], path); const status = enumeration(root.lifecycleStatus, BINDING_STATUSES, `${path}.lifecycleStatus`); const allowed = commands(root.allowedCommands, PLAYER_COMMANDS, `${path}.allowedCommands`) as readonly LeaguePlayerCommand[]; if (['VERIFIED', 'BLOCKED', 'PLAYER_SERIES_RESTART_REQUIRED'].includes(status) && allowed.length > 0) fail(`${path}.allowedCommands`, 'terminal/blocked binding은 명령을 허용할 수 없습니다.'); return { leagueId: string(root.leagueId, `${path}.leagueId`, IDS.league), seasonId: string(root.seasonId, `${path}.seasonId`, IDS.season), fixtureId: string(root.fixtureId, `${path}.fixtureId`, IDS.fixture), bindingHash: string(root.bindingHash, `${path}.bindingHash`, HASH), bindingRevision: integer(root.bindingRevision, `${path}.bindingRevision`), lifecycleStatus: status, boundSeriesId: string(root.boundSeriesId, `${path}.boundSeriesId`, IDS.series), completionReceiptHash: nullableString(root.completionReceiptHash, `${path}.completionReceiptHash`, HASH), allowedCommands: allowed }; }
export function validateLeaguePlayerSeriesResponse(value: unknown, scope: { leagueId: string; seasonId: string; fixtureId: string }): LeaguePlayerSeriesResponseDto { const root = wrapper(value, 'AI_LEAGUE_PLAYER_SERIES_VIEW_V1', ['schemaVersion', 'replayed', 'playerSeries']); const result = { schemaVersion: 'AI_LEAGUE_PLAYER_SERIES_VIEW_V1' as const, replayed: bool(root.replayed, '$.replayed'), playerSeries: playerSeries(root.playerSeries, '$.playerSeries') }; requireScope(result.playerSeries.leagueId, result.playerSeries.seasonId, scope.leagueId, scope.seasonId, '$.playerSeries'); if (result.playerSeries.fixtureId !== scope.fixtureId) fail('$.playerSeries.fixtureId', '요청 fixture scope와 다릅니다.'); return result; }
function completion(value: unknown, path: string): LeagueCompletionStatusViewDto { const root = object(value, path); exact(root, ['leagueId', 'seasonId', 'fixtureId', 'fixtureStatus', 'bindingStatus', 'receiptHash', 'outboxStatus', 'standingsApplied', 'standingsRevision', 'allowedCommands'], path); const applied = bool(root.standingsApplied, `${path}.standingsApplied`); const outbox = enumeration(root.outboxStatus, ['NOT_CREATED', 'PENDING', 'DELIVERED'] as const, `${path}.outboxStatus`); if (applied && outbox !== 'DELIVERED') fail(path, 'standings 반영은 delivered outbox가 필요합니다.'); return { leagueId: string(root.leagueId, `${path}.leagueId`, IDS.league), seasonId: string(root.seasonId, `${path}.seasonId`, IDS.season), fixtureId: string(root.fixtureId, `${path}.fixtureId`, IDS.fixture), fixtureStatus: enumeration(root.fixtureStatus, FIXTURE_STATUSES, `${path}.fixtureStatus`) as LeagueFixtureStatus, bindingStatus: nullableEnum(root.bindingStatus, BINDING_STATUSES, `${path}.bindingStatus`), receiptHash: nullableString(root.receiptHash, `${path}.receiptHash`, HASH), outboxStatus: outbox, standingsApplied: applied, standingsRevision: integer(root.standingsRevision, `${path}.standingsRevision`), allowedCommands: commands(root.allowedCommands, FIXTURE_COMMANDS, `${path}.allowedCommands`) as readonly LeagueFixtureCommand[] }; }
export function validateLeagueCompletionStatusResponse(value: unknown, scope: { leagueId: string; seasonId: string; fixtureId: string }): LeagueCompletionStatusResponseDto { const root = wrapper(value, 'AI_LEAGUE_COMPLETION_STATUS_VIEW_V1', ['schemaVersion', 'replayed', 'completion']); const result = { schemaVersion: 'AI_LEAGUE_COMPLETION_STATUS_VIEW_V1' as const, replayed: bool(root.replayed, '$.replayed'), completion: completion(root.completion, '$.completion') }; requireScope(result.completion.leagueId, result.completion.seasonId, scope.leagueId, scope.seasonId, '$.completion'); if (result.completion.fixtureId !== scope.fixtureId) fail('$.completion.fixtureId', '요청 fixture scope와 다릅니다.'); return result; }
export function validateLeagueApiError(value: unknown): LeagueApiErrorDto { const root = wrapper(value, 'AI_LEAGUE_API_ERROR_V1', ['schemaVersion', 'code', 'field', 'message', 'retryable', 'currentLifecycleRevision', 'currentLifecycleStatus']); return { schemaVersion: 'AI_LEAGUE_API_ERROR_V1', code: string(root.code, '$.code', /^[A-Z][A-Z0-9_]{2,159}$/), field: nullableString(root.field, '$.field'), message: string(root.message, '$.message'), retryable: bool(root.retryable, '$.retryable'), currentLifecycleRevision: root.currentLifecycleRevision === null ? null : integer(root.currentLifecycleRevision, '$.currentLifecycleRevision'), currentLifecycleStatus: nullableString(root.currentLifecycleStatus, '$.currentLifecycleStatus') }; }
