import { validateClubFinance } from './careerFinance.contract.ts';
import type { ClubFinance } from './careerFinance.contract';
import { validateManagement } from './careerManagement.contract.ts';
import type { CareerManagement } from './careerManagement.contract';
import { CareerContractError } from './careerApi.validation.ts';
export type MarketRole = 'STARTER' | 'RESERVE' | 'DEVELOPMENT';
export interface MarketTerms { startDate: string; endDate: string; annualSalary: number; signingBonus: number; role: MarketRole }
export interface GameContract { contractId: string; careerId: string; playerId: string; team: string | null; organizationId: string; signedDate: string; terms: MarketTerms; status: 'ACTIVE' | 'SCHEDULED' | 'EXPIRED' | 'RELEASED' | 'TRANSFERRED' | 'RETIRED' | 'CANCELLED_RETIREMENT'; revision: number; policyVersion: string; origin: string; terminationPolicy: string; endedDate: string | null; paidThrough: string }
export interface MarketOffer { offerId: string; playerId: string; team: string; terms: MarketTerms; submittedDate: string; responseDate: string; decisionDate: string; expiresDate: string; revision: number; status: 'SUBMITTED' | 'COUNTER' | 'ACCEPTED' | 'REJECTED' | 'WITHDRAWN' | 'EXPIRED' | 'SUPERSEDED'; previousOfferId: string | null; round: number; requestedSalary: number | null; reason: string }
export interface MarketPreference { compensation: number; opportunity: number; strength: number; stability: number; familiarity: number; relocationPenalty: number; inclination: string; homeRegion: string | null }
export interface MarketPlayer { playerId: string; status: 'CONTRACTED' | 'FREE_AGENT' | 'UNAVAILABLE' | 'RETIRED'; currentContractId: string | null; scheduledContractId: string | null; availableStart: string | null; askingSalary: number; releaseCost: number; eligibilityReason: string | null; preference: MarketPreference }
export interface MarketFinance { team: string; annualBudget: number; cash: number; reservedCash: number; currentAnnualSalary: number; committedPeakSalary: number; rosterLimit: number; fundingPolicy?: string; salaryArrears?: number; paymentHeadroom?: number }
export interface MarketEvent { eventId: string; date: string; kind: string; playerId: string | null; team: string | null; referenceId: string; reason: string }
export interface MarketEvaluation { offerId: string; team: string; compensation: number; opportunity: number; strength: number; stability: number; familiarity: number; relocation: number; score: number; tieBreak: number; reason: string; promiseTrust?: number; satisfaction?: number; relationshipAdjustment?: number }
export interface MarketDecision { eventId: string; playerId: string; date: string; winningOfferId: string | null; evaluations: MarketEvaluation[]; reason: string; policyVersion: string }
export interface MarketLedger { entryId: string; date: string; team: string; contractId: string | null; kind: string; amount: number }
export interface MarketSupplement { competitionId: string; team: string; playerId: string; position: string; date: string; revision: number; reason: string }
export interface SquadOperation { id: string; seasonYear: number; date: string; team: string; position: string; squad: string; action: string; status: string; playerId: string | null; previousPlayerId: string | null; effectiveDate: string | null; referenceId: null; reason: string }
export interface CareerMarket { schemaVersion: 'CAREER_MARKET_VIEW_V1'; policyVersion: string; currency: string; careerId: string; seasonYear: number; currentDate: string; revision: number; readOnly: boolean; managedTeam: string; offseason: boolean; nextMarketEvent: string | null; players: MarketPlayer[]; contracts: GameContract[]; offers: MarketOffer[]; finances: MarketFinance[]; decisions: MarketDecision[]; events: MarketEvent[]; ledger: MarketLedger[]; missingPositions: Record<string, string[]>; supplements: MarketSupplement[]; allowedCommands: string[]; registrationPolicy: string; management?: CareerManagement | null; squadOperations?: SquadOperation[]; clubFinance?: ClubFinance | null }
export interface MarketCommand { schemaVersion: 'CAREER_MARKET_COMMAND_V1' | 'CAREER_MARKET_COMMAND_KRW_V1'; sourceYear: number; expectedRevision: number; action: 'SUBMIT' | 'REVISE' | 'WITHDRAW' | 'RELEASE' | 'SUPPLEMENT' | 'OPEN_STOVE'; playerId: string | null; offerId: string | null; terms: MarketTerms | null; replacementPlayerId: string | null; competitionId: string | null; clientCommandId: string }
export interface MarketChange { replayed: boolean; receipt: { clientCommandId: string; careerId: string; sourceYear: number; resultingRevision: number; action: string; referenceId: string | null; appliedDate: string; reason: string }; market: CareerMarket }
type Obj = Record<string, unknown>;
function check(ok: unknown, path: string): asserts ok { if (!ok) throw new CareerContractError(`market.${path}`); }
function exact(value: unknown, fields: string, path: string): Obj { check(value !== null && typeof value === 'object' && !Array.isArray(value), path); const v = value as Obj; check(Object.keys(v).sort().join() === fields.split(' ').sort().join(), path); return v; }
const str = (v: unknown): v is string => typeof v === 'string' && v.length > 0;
const nullable = (v: unknown) => v === null || str(v);
const integer = (v: unknown): v is number => Number.isSafeInteger(v) && (v as number) >= 0;
const date = (v: unknown): v is string => typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) && new Date(`${v}T00:00:00Z`).toISOString().slice(0, 10) === v;
const uuid = (v: unknown) => typeof v === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(v);
const roles = ['STARTER', 'RESERVE', 'DEVELOPMENT'];
const actions = ['SUBMIT', 'REVISE', 'WITHDRAW', 'RELEASE', 'SUPPLEMENT', 'OPEN_STOVE'];
export function validateMarketTerms(value: unknown): MarketTerms { const v = exact(value, 'startDate endDate annualSalary signingBonus role', 'terms'); check(date(v.startDate) && date(v.endDate) && v.startDate <= v.endDate && integer(v.annualSalary) && v.annualSalary > 0 && integer(v.signingBonus) && roles.includes(v.role as string), 'terms.values'); return v as unknown as MarketTerms; }
export function validateMarketCommand(value: unknown): MarketCommand {
  const v = exact(value, 'schemaVersion sourceYear expectedRevision action playerId offerId terms replacementPlayerId competitionId clientCommandId', 'command');
  check(['CAREER_MARKET_COMMAND_V1', 'CAREER_MARKET_COMMAND_KRW_V1'].includes(v.schemaVersion as string) && integer(v.sourceYear) && v.sourceYear >= 2026 && integer(v.expectedRevision) && actions.includes(v.action as string) && uuid(v.clientCommandId), 'command.scope');
  check(nullable(v.playerId) && nullable(v.offerId) && nullable(v.replacementPlayerId) && nullable(v.competitionId), 'command.ids');
  if (v.action === 'SUBMIT' || v.action === 'REVISE') { validateMarketTerms(v.terms); check(str(v.playerId) && (v.action === 'REVISE' ? str(v.offerId) : v.offerId === null) && v.competitionId === null && v.replacementPlayerId === null, 'command.offer'); }
  else { check(v.terms === null, 'command.unusedTerms'); if (v.action === 'WITHDRAW') check(str(v.offerId), 'command.withdraw'); if (v.action === 'RELEASE' || v.action === 'SUPPLEMENT') check(str(v.playerId), 'command.player'); if (v.action === 'SUPPLEMENT') check(str(v.competitionId), 'command.competition'); }
  return v as unknown as MarketCommand;
}
export function validateCareerMarket(value: unknown): CareerMarket {
  const v = exact(value, 'schemaVersion policyVersion currency careerId seasonYear currentDate revision readOnly managedTeam offseason nextMarketEvent players contracts offers finances decisions events ledger missingPositions supplements allowedCommands registrationPolicy' + (value && typeof value === 'object' && 'management' in value ? ' management' : '') + (value && typeof value === 'object' && 'squadOperations' in value ? ' squadOperations' : '') + (value && typeof value === 'object' && 'clubFinance' in value ? ' clubFinance' : ''), 'view');
  if (v.squadOperations !== undefined) {
    check(Array.isArray(v.squadOperations), 'squadOperations');
    const seen = new Set<string>();
    for (const raw of v.squadOperations as unknown[]) {
      const o = exact(raw, 'id seasonYear date team position squad action status playerId previousPlayerId effectiveDate referenceId reason', 'squadOperation');
      check(str(o.id) && !seen.has(o.id) && integer(o.seasonYear) && date(o.date) && str(o.team) && ['TOP', 'JUNGLE', 'MID', 'ADC', 'SUPPORT'].includes(o.position as string) && ['FIRST_TEAM', 'DEVELOPMENT'].includes(o.squad as string) && str(o.action) && ['APPLIED', 'RETAINED', 'DEFERRED', 'PLANNED', 'PROPOSED', 'AWAITING_CONSENT', 'AGREED', 'CLOSED'].includes(o.status as string) && nullable(o.playerId) && nullable(o.previousPlayerId) && (o.effectiveDate === null || date(o.effectiveDate)) && o.referenceId === null && str(o.reason), 'squadOperation.values');
      seen.add(o.id as string);
    }
  }
  if (v.management !== undefined && v.management !== null) validateManagement(v.management);
  check(v.schemaVersion === 'CAREER_MARKET_VIEW_V1' && v.policyVersion === 'CAREER_CONTRACT_MARKET_GAME_POLICY_V1' && ['GAME_CREDITS', 'KRW'].includes(v.currency as string) && str(v.careerId) && /^career_[0-9a-f]{64}$/.test(v.careerId) && integer(v.seasonYear) && date(v.currentDate) && integer(v.revision) && typeof v.readOnly === 'boolean' && typeof v.offseason === 'boolean' && str(v.managedTeam) && (v.nextMarketEvent === null || date(v.nextMarketEvent)) && str(v.registrationPolicy), 'view.scope');
  for (const name of ['players', 'contracts', 'offers', 'finances', 'decisions', 'events', 'ledger', 'supplements', 'allowedCommands']) check(Array.isArray(v[name]), name);
  if (v.currency === 'KRW') validateClubFinance(v.clubFinance, v.managedTeam as string);
  else check(v.clubFinance == null, 'legacy.finance');
  const contracts = new Map<string, Obj>(), players = new Set<string>(), offers = new Set<string>();
  for (const raw of v.contracts as unknown[]) { const c = exact(raw, 'contractId careerId playerId team organizationId signedDate terms status revision policyVersion origin terminationPolicy endedDate paidThrough', 'contract'); check(str(c.contractId) && !contracts.has(c.contractId) && c.careerId === v.careerId && str(c.playerId) && nullable(c.team) && str(c.organizationId) && date(c.signedDate) && date(c.paidThrough) && (c.endedDate === null || date(c.endedDate)) && integer(c.revision) && ['ACTIVE', 'SCHEDULED', 'EXPIRED', 'RELEASED', 'TRANSFERRED', 'RETIRED', 'CANCELLED_RETIREMENT'].includes(c.status as string) && c.policyVersion === v.policyVersion && str(c.origin) && str(c.terminationPolicy), 'contract.values'); validateMarketTerms(c.terms); contracts.set(c.contractId, c); }
  for (const raw of v.players as unknown[]) { const p = exact(raw, 'playerId status currentContractId scheduledContractId availableStart askingSalary releaseCost eligibilityReason preference', 'player'); check(str(p.playerId) && !players.has(p.playerId) && ['CONTRACTED', 'FREE_AGENT', 'UNAVAILABLE', 'RETIRED'].includes(p.status as string) && (p.availableStart === null || date(p.availableStart)) && integer(p.askingSalary) && integer(p.releaseCost) && nullable(p.eligibilityReason), 'player.values'); for (const key of ['currentContractId', 'scheduledContractId']) check(p[key] === null || str(p[key]) && contracts.get(p[key])?.playerId === p.playerId, 'player.contract'); const f = exact(p.preference, 'compensation opportunity strength stability familiarity relocationPenalty inclination homeRegion', 'preference'); check(['compensation', 'opportunity', 'strength', 'stability', 'familiarity', 'relocationPenalty'].every(k => integer(f[k])) && str(f.inclination) && nullable(f.homeRegion), 'preference.values'); players.add(p.playerId); }
  for (const raw of v.offers as unknown[]) { const o = exact(raw, 'offerId playerId team terms submittedDate responseDate decisionDate expiresDate revision status previousOfferId round requestedSalary reason', 'offer'); check(str(o.offerId) && !offers.has(o.offerId) && players.has(o.playerId as string) && str(o.team) && [o.submittedDate, o.responseDate, o.decisionDate, o.expiresDate].every(date) && integer(o.revision) && integer(o.round) && nullable(o.previousOfferId) && (o.requestedSalary === null || integer(o.requestedSalary)) && ['SUBMITTED', 'COUNTER', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', 'SUPERSEDED'].includes(o.status as string) && str(o.reason), 'offer.values'); validateMarketTerms(o.terms); offers.add(o.offerId); }
  for (const raw of v.finances as unknown[]) { const extended = raw !== null && typeof raw === 'object' && 'fundingPolicy' in raw; const a = exact(raw, 'team annualBudget cash reservedCash currentAnnualSalary committedPeakSalary rosterLimit' + (extended ? ' fundingPolicy salaryArrears paymentHeadroom' : ''), 'finance'); if (extended) check(['PAYROLL_CASH_FLOW_AND_ARREARS_RECOVERY_V2','GAME_RECURRING_FINANCE_V1','LEGACY_FUNDING_UNTIL_NEXT_SEASON'].includes(a.fundingPolicy as string) && integer(a.salaryArrears) && integer(a.paymentHeadroom), 'finance.recovery'); check(str(a.team) && ['annualBudget', 'cash', 'reservedCash', 'currentAnnualSalary', 'committedPeakSalary', 'rosterLimit'].every(k => integer(a[k])) && (extended || (a.reservedCash as number) <= (a.cash as number) && (a.committedPeakSalary as number) <= (a.annualBudget as number)), 'finance.budget'); }
  for (const raw of v.events as unknown[]) { const e = exact(raw, 'eventId date kind playerId team referenceId reason', 'event'); check(str(e.eventId) && date(e.date) && str(e.kind) && nullable(e.playerId) && nullable(e.team) && str(e.referenceId) && str(e.reason), 'event.values'); }
  for (const raw of v.ledger as unknown[]) { const l = exact(raw, 'entryId date team contractId kind amount', 'ledger'); check(str(l.entryId) && date(l.date) && str(l.team) && nullable(l.contractId) && str(l.kind) && Number.isSafeInteger(l.amount), 'ledger.values'); }
  for (const raw of v.decisions as unknown[]) { const d = exact(raw, 'eventId playerId date winningOfferId evaluations reason policyVersion', 'decision'); check(str(d.eventId) && players.has(d.playerId as string) && date(d.date) && (d.winningOfferId === null || offers.has(d.winningOfferId as string)) && Array.isArray(d.evaluations) && str(d.reason) && d.policyVersion === v.policyVersion, 'decision.values'); for (const rawE of d.evaluations as unknown[]) { const e = exact(rawE, 'offerId team compensation opportunity strength stability familiarity relocation score tieBreak reason' + (rawE && typeof rawE === 'object' && 'promiseTrust' in rawE ? ' promiseTrust satisfaction relationshipAdjustment' : ''), 'evaluation'); if (e.promiseTrust !== undefined) check(integer(e.promiseTrust) && e.promiseTrust <= 100 && integer(e.satisfaction) && e.satisfaction <= 100 && Number.isSafeInteger(e.relationshipAdjustment), 'evaluation.relationship'); check(offers.has(e.offerId as string) && str(e.team) && str(e.reason) && ['compensation', 'opportunity', 'strength', 'stability', 'familiarity', 'relocation', 'score', 'tieBreak'].every(k => Number.isSafeInteger(e[k])), 'evaluation.values'); } }
  check(v.missingPositions !== null && typeof v.missingPositions === 'object' && !Array.isArray(v.missingPositions), 'gaps'); for (const ids of Object.values(v.missingPositions as Obj)) check(Array.isArray(ids) && new Set(ids).size === ids.length && ids.every(x => ['TOP', 'JUNGLE', 'MID', 'ADC', 'SUPPORT'].includes(x)), 'gaps.roles');
  for (const raw of v.supplements as unknown[]) { const s = exact(raw, 'competitionId team playerId position date revision reason', 'supplement'); check(str(s.competitionId) && str(s.team) && players.has(s.playerId as string) && ['TOP', 'JUNGLE', 'MID', 'ADC', 'SUPPORT'].includes(s.position as string) && date(s.date) && integer(s.revision) && str(s.reason), 'supplement.values'); }
  check((v.allowedCommands as unknown[]).every(c => actions.includes(c as string)) && (!v.readOnly || (v.allowedCommands as unknown[]).length === 0), 'commands');
  return v as unknown as CareerMarket;
}
export function validateMarketChange(value: unknown): MarketChange { const v = exact(value, 'replayed receipt market', 'change'); check(typeof v.replayed === 'boolean', 'replayed'); const market = validateCareerMarket(v.market), r = exact(v.receipt, 'clientCommandId careerId sourceYear resultingRevision action referenceId appliedDate reason', 'receipt'); check(uuid(r.clientCommandId) && r.careerId === market.careerId && integer(r.sourceYear) && integer(r.resultingRevision) && r.resultingRevision <= market.revision && [...actions, 'TRADE_SUBMIT', 'TRADE_COUNTER', 'TRADE_ACCEPT', 'TRADE_REJECT', 'TRADE_WITHDRAW'].includes(r.action as string) && nullable(r.referenceId) && date(r.appliedDate) && str(r.reason), 'receipt.values'); return v as unknown as MarketChange; }
export const marketOperationKey = (career: string) => `lolfm.career.market-command.v1.${career}`;
export function readMarketOperation(storage: Pick<Storage, 'getItem'>, career: string): MarketCommand | null { const raw = storage.getItem(marketOperationKey(career)); return raw ? validateMarketCommand(JSON.parse(raw)) : null; }

/** A delayed legacy response cannot replace an already accepted KRW projection of the same season. */
export function newerMarket(previous: CareerMarket | null, next: CareerMarket): CareerMarket {
  if (previous?.careerId === next.careerId && previous.seasonYear === next.seasonYear && (previous.revision > next.revision || previous.currency === 'KRW' && next.currency !== 'KRW')) return previous;
  return next;
}
