export type LifecycleStatus = 'ACTIVE' | 'CONSIDERING_RETIREMENT' | 'RETIREMENT_ANNOUNCED' | 'RETIRED';
export interface CareerLifeProfile {
  playerId: string; nickname: string; position: string; currentCA: number; potentialAbility: number | null; gameAge: number;
  seasonGrowth: number; seasonDecline: number; seasonNet: number;
  lifecycle: { age: { publicBirthDate: string | null; simulationBirthDate: string; basis: string; referenceDate: string; appliedOn: string }; source: string; intakeYear: number | null; introducedOn: string; peakCA: number; peakObservedSince: string; status: LifecycleStatus; announcedOn: string | null; effectiveOn: string | null; reason: string; declineRemainder: number; noAppearanceSeasons: number; lastCoverage: string; freeAgentSince: string | null };
}
export interface LifeReview { seasonYear: number; reviewedOn: string; kind: string; rookieIds: string[]; changes: { playerId: string; outcome: LifecycleStatus; retirementProbability: number; retirementRoll: number; appliedDecline: number; carriedDecline: number; limitedDecline: number; observation: { coverage: string; opportunities: number; starts: number; sets: number } }[]; supply: { projectedActive: number; normalCount: number; emergencyCount: number; availableByPosition: Record<string, number>; missingByPosition: Record<string, number>; generatedByPosition: Record<string, number>; unresolvedByPosition: Record<string, number> } | null }
export interface CareerLifecycle { schemaVersion: 'CAREER_LIFECYCLE_VIEW_V1'; careerId: string; seasonYear: number; date: string; readOnly: boolean; activeCount: number; archivedCount: number; players: CareerLifeProfile[]; reviews: LifeReview[]; policyVersion: string }
const statuses = ['ACTIVE', 'CONSIDERING_RETIREMENT', 'RETIREMENT_ANNOUNCED', 'RETIRED'];
const obj = (v: unknown): Record<string, unknown> => { if (!v || typeof v !== 'object' || Array.isArray(v)) throw new Error('생애주기 데이터 형식 오류'); return v as Record<string, unknown>; };
const check: (v: unknown) => asserts v = v => { if (!v) throw new Error('생애주기 데이터 계약 오류'); };
const integer = (v: unknown, min = 0, max = Number.MAX_SAFE_INTEGER) => Number.isSafeInteger(v) && Number(v) >= min && Number(v) <= max;
const date = (v: unknown) => typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v);
export function validateCareerLifecycle(value: unknown): CareerLifecycle {
  const v = obj(value); check(v.schemaVersion === 'CAREER_LIFECYCLE_VIEW_V1' && typeof v.careerId === 'string' && integer(v.seasonYear, 2026) && date(v.date) && typeof v.readOnly === 'boolean' && integer(v.activeCount) && integer(v.archivedCount) && Array.isArray(v.players) && Array.isArray(v.reviews));
  const ids = new Set<string>(); let retired = 0;
  for (const raw of v.players) { const p = obj(raw), l = obj(p.lifecycle), a = obj(l.age); check(typeof p.playerId === 'string' && !ids.has(p.playerId)); ids.add(p.playerId); check(typeof p.nickname === 'string' && ['TOP', 'JUNGLE', 'MID', 'ADC', 'SUPPORT'].includes(String(p.position)) && integer(p.currentCA, 1, 200) && (p.potentialAbility === null || integer(p.potentialAbility, 1, 200)) && integer(p.gameAge, 0, 120)); check(integer(p.seasonGrowth) && integer(p.seasonDecline) && p.seasonNet === Number(p.seasonGrowth) - Number(p.seasonDecline)); check(statuses.includes(String(l.status)) && integer(l.peakCA, 1, 200) && date(l.peakObservedSince) && date(a.simulationBirthDate) && (a.publicBirthDate === null || date(a.publicBirthDate)) && integer(l.declineRemainder, 0, 999)); if (l.status === 'RETIRED') retired++; if (l.status === 'RETIRED' || l.status === 'RETIREMENT_ANNOUNCED') check(date(l.announcedOn) && date(l.effectiveOn) && String(l.effectiveOn) > String(l.announcedOn)); }
  check(retired === v.archivedCount && ids.size === Number(v.activeCount) + retired);
  for (const raw of v.reviews) { const r = obj(raw); check(r.seasonYear === v.seasonYear && date(r.reviewedOn) && Array.isArray(r.rookieIds) && new Set(r.rookieIds).size === r.rookieIds.length && Array.isArray(r.changes)); for (const rawChange of r.changes) { const c = obj(rawChange), o = obj(c.observation); check(ids.has(String(c.playerId)) && statuses.includes(String(c.outcome)) && integer(c.retirementProbability, 0, 95) && integer(c.retirementRoll, 0, 9999) && integer(o.opportunities) && integer(o.starts, 0, Number(o.opportunities)) && integer(o.sets)); } if (r.supply !== null) { const s = obj(r.supply); check(integer(s.normalCount, 0, 36) && integer(s.emergencyCount, 0, 60) && r.rookieIds.length === Number(s.normalCount) + Number(s.emergencyCount)); check(r.rookieIds.every(id => ids.has(String(id)))); for (const key of ['availableByPosition', 'missingByPosition', 'generatedByPosition', 'unresolvedByPosition']) check(Object.values(obj(s[key])).every(n => integer(n))); } }
  return v as unknown as CareerLifecycle;
}
export const lifecycleStatusName: Record<LifecycleStatus, string> = { ACTIVE: '현역', CONSIDERING_RETIREMENT: '은퇴 고민 · 활동 가능', RETIREMENT_ANNOUNCED: '은퇴 발표', RETIRED: '은퇴' };
export function filterLifecycle(players: CareerLifeProfile[], filter: string) { return players.filter(p => filter === 'all' || filter === 'rookies' && p.lifecycle.source === 'GENERATED' || filter === 'retired' && p.lifecycle.status === 'RETIRED' || filter === 'announced' && p.lifecycle.status === 'RETIREMENT_ANNOUNCED'); }
