import { realMatchConfig } from '../../real-match/realMatch.config';
import type { RosterPlayer, RosterMember } from './careerRoster.contract';
import type { InboxLink } from './careerInbox';
export interface Interest { playerId: string; revision: number; selected: boolean }
export interface Candidate { player: RosterPlayer; membership: RosterMember | null; ca: number; pa: number | null; age: number | null; ageBasis: string; source: string; status: string; starter: boolean; salary: number | null; expires: string | null; market: { availableStart: string | null; askingSalary: number; eligibilityReason: string | null } | null; quote: { referenceSalary: number; estimatedValue: number; suggestedTransferFee: number; earliestStart: string | null; unavailableReason: string | null } | null; interest: Interest }
export interface ScoutFinance { team: string; cash: number; annualBudget: number; committedPeakSalary: number; paymentHeadroom: number; salaryArrears: number }
export interface ScoutPage { careerId: string; activeYear: number; date: string; asOf: string; population: number; total: number; nextCursor: number; players: Candidate[]; teams: Record<string,string>; starters: string[]; starterByPosition: Record<string,string>; finance: ScoutFinance | null }
export interface Comparison { careerId: string; activeYear: number; date: string; asOf: string; statisticsYear: number; competition: string; players: Candidate[]; statistics: Record<string,unknown>[]; champions: Record<string,unknown>[]; awards: { playerId: string; instanceId: string; name: string; scope: string }[]; growth: Record<string, {kind:string;value:unknown}[]>; finance: ScoutFinance | null }
export interface Opponent { careerId:string; activeYear:number; currentDate:string; year:number; competition:string; team:string|null; asOf:number; next:{fixtureId:string; date:string; first:string; second:string; opponent:string|null; state:string; link:InboxLink}|null; currentStarters:string[]; registered:string[]; frozen:string[]; names:Record<string,string>; series:number; seriesWins:number; sets:number; wins:number; draftSets:number; blueSets:number; picks:Record<string,number>; bansBy:Record<string,number>; bansAgainst:Record<string,number>; combinations:Record<string,number>; games:{recordId:string;date:string;competition:string;against:string;gameNumber:number;seconds:number;won:boolean;draft:{blue:string;red:string;firstPickTeam:string|null;firstPick:string|null;rule:string;unavailableBefore:string[];engine:string;picks:{playerId:string;position:string;championId:string;team:string}[]}|null;performances:{playerId:string;statistics:{kills:number;deaths:number;assists:number;cs:number}|null;evaluation:{rating:number|null;version:string}}[]}[] }
export async function scoutingRequest<T>(career:string,path:string,signal:AbortSignal,body?:unknown):Promise<T>{const r=await fetch(`${realMatchConfig.apiBaseUrl}/api/v1/careers/${encodeURIComponent(career)}/scouting${path}`,{signal,method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error(r.status===409?'조회 기준이 변경됐습니다. 검색을 새로고침하세요.':`스카우팅 요청 실패 (${r.status})`);return r.json() as Promise<T>;}
export function scoutLink(c:Candidate,year:number,managed:string):InboxLink {return {panel:c.status==='CONTRACTED'&&c.membership?.ownerTeam!==managed?'TRADE':'MARKET',playerId:c.player.playerId,sourceId:null,competition:null,seasonYear:year,seriesId:null,positions:[],current:true};}
export function comparisonSkills(players:Candidate[]){return [...new Set(players.flatMap(p=>Object.keys(p.player.gameplay.ratings)))].filter(skill=>players.every(p=>Object.prototype.hasOwnProperty.call(p.player.gameplay.ratings,skill)));}
export function restoreScouting(raw:string|null):{filters:Record<string,string>;chosen:string[]}{try{const v=JSON.parse(raw??'{}');return {filters:v.filters&&typeof v.filters==='object'?Object.fromEntries(Object.entries(v.filters).filter((e):e is [string,string]=>typeof e[1]==='string')):{},chosen:Array.isArray(v.chosen)?[...new Set(v.chosen.filter((s:unknown):s is string=>typeof s==='string'))].slice(0,4) as string[]:[]};}catch{return {filters:{},chosen:[]};}}
