export interface ClClub { team: string; candidates: string[]; registered: string[]; lineup: string[]; blockers: string[] }
export interface ClFixture { competitionId: string; matchId: string; seriesId: string; date: string; stageId: string; seriesFormat: string; firstTeamCode: string; secondTeamCode: string; lifecycleStatus: string; executionMode: string; winnerTeamCode: string | null }
export interface CareerCl { careerId: string; seasonYear: number; activationYear: number | null; active: boolean; readOnly: boolean; revision: number; rosterRevision: number; managedTeam: string; clubs: ClClub[]; fixtures: ClFixture[]; standings: { team: string; wins: number; losses: number; gameWins: number; gameLosses: number }[]; ranking: string[] }
export interface ClCommand { sourceYear: number; expectedRevision: number; expectedRosterRevision: number; action: 'CONFIRM_LINEUP' | 'SELECT_AUTO'; players: string[] | null; matchId: string | null; clientCommandId: string }
export interface ClChange { replayed: boolean; receipt: { clientCommandId: string; careerId: string; seasonYear: number; revision: number; payloadHash: string }; cl: CareerCl }
export const clOperationKey = (career: string) => `lolfm.career.cl-command.v1.${career}`;
const object = (v: unknown): Record<string, unknown> => { if (!v || typeof v !== 'object' || Array.isArray(v)) throw new Error('CL 응답 형식 오류'); return v as Record<string, unknown>; };
function check(v: unknown): asserts v { if (!v) throw new Error('CL 데이터 계약 오류'); }
const ids = (v: unknown): v is string[] => Array.isArray(v) && v.every(x => typeof x === 'string' && !!x) && new Set(v).size === v.length;
export function validateClCommand(raw: unknown): ClCommand {
  const v = object(raw); check(Object.keys(v).sort().join() === 'sourceYear expectedRevision expectedRosterRevision action players matchId clientCommandId'.split(' ').sort().join());
  check(Number.isSafeInteger(v.sourceYear) && Number(v.sourceYear) >= 2026 && Number.isSafeInteger(v.expectedRevision) && Number(v.expectedRevision) >= 0 && Number.isSafeInteger(v.expectedRosterRevision) && Number(v.expectedRosterRevision) >= 0);
  check(typeof v.clientCommandId === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v.clientCommandId));
  check(v.action === 'CONFIRM_LINEUP' ? ids(v.players) && v.players.length === 5 && v.matchId === null : v.action === 'SELECT_AUTO' && v.players === null && typeof v.matchId === 'string'); return v as unknown as ClCommand;
}
export function validateCareerCl(raw: unknown): CareerCl {
  const v = object(raw); check(typeof v.careerId === 'string' && Number.isSafeInteger(v.seasonYear) && typeof v.active === 'boolean' && typeof v.readOnly === 'boolean' && typeof v.managedTeam === 'string');
  check(Number.isSafeInteger(v.revision) && Number.isSafeInteger(v.rosterRevision) && (v.activationYear === null || Number.isSafeInteger(v.activationYear)));
  check(Array.isArray(v.clubs) && v.clubs.length === (v.active ? 10 : 0));
  for (const rawClub of v.clubs) { const c = object(rawClub); check(typeof c.team === 'string' && ids(c.candidates) && ids(c.registered) && ids(c.lineup) && c.lineup.length <= 5 && Array.isArray(c.blockers)); }
  check(Array.isArray(v.fixtures) && v.fixtures.length <= 160 && Array.isArray(v.standings) && ids(v.ranking));
  for (const rawFixture of v.fixtures) { const f = object(rawFixture); check(f.competitionId === 'LCK_CL' && typeof f.matchId === 'string' && typeof f.seriesId === 'string' && typeof f.date === 'string' && typeof f.firstTeamCode === 'string' && typeof f.secondTeamCode === 'string' && ['BO1', 'BO3', 'BO5'].includes(String(f.seriesFormat))); }
  return v as unknown as CareerCl;
}
export function validateClChange(raw: unknown): ClChange { const v = object(raw), cl = validateCareerCl(v.cl), r = object(v.receipt); check(typeof v.replayed === 'boolean' && r.careerId === cl.careerId && typeof r.clientCommandId === 'string' && Number.isSafeInteger(r.seasonYear) && Number.isSafeInteger(r.revision)); return v as unknown as ClChange; }
export interface AppearancePerformance { seasonYear: number; date: string; seriesId: string; playerId: string; team: string; squad: string; competitionId: string | null; sets: number; champions: Record<string, number>; internalGain: number; proficiencyGain: number }
export function validatePerformances(raw: unknown): AppearancePerformance[] { check(Array.isArray(raw)); for (const value of raw) { const p = object(value); check(typeof p.playerId === 'string' && typeof p.seriesId === 'string' && typeof p.team === 'string' && typeof p.date === 'string' && ['FIRST_TEAM', 'DEVELOPMENT'].includes(String(p.squad)) && Number.isSafeInteger(p.seasonYear) && Number.isSafeInteger(p.sets) && Number(p.sets) > 0 && Number.isSafeInteger(p.internalGain) && Number.isSafeInteger(p.proficiencyGain)); check(Object.values(object(p.champions)).every(n => Number.isSafeInteger(n) && Number(n) > 0)); } return raw as AppearancePerformance[]; }
export interface ClResult { careerId: string; seasonYear: number; matchId: string; seriesId: string; firstTeam: string; secondTeam: string; firstScore: number; secondScore: number; replayAvailable: boolean; games: { game: number; blueTeam: string; redTeam: string; winner: string; durationSeconds: number; picks: { playerId: string; nickname: string; position: string; team: string; champion: string }[] }[] }
export function validateClResult(raw: unknown): ClResult { const v = object(raw); check(typeof v.careerId === 'string' && Number.isSafeInteger(v.seasonYear) && typeof v.matchId === 'string' && typeof v.seriesId === 'string' && typeof v.replayAvailable === 'boolean' && Number.isSafeInteger(v.firstScore) && Number.isSafeInteger(v.secondScore) && Array.isArray(v.games) && v.games.length === Number(v.firstScore) + Number(v.secondScore)); for (const game of v.games) { const g = object(game); check(Number.isSafeInteger(g.game) && typeof g.winner === 'string' && Number.isSafeInteger(g.durationSeconds) && Array.isArray(g.picks) && g.picks.length === 10); } return v as unknown as ClResult; }
