import type { MarketRole, MarketTerms } from './careerMarket.contract';
import { CareerContractError } from './careerApi.validation.ts';
export interface RolePromise { promiseId: string; playerId: string; team: string; contractId: string; loanId: string | null; role: MarketRole; startDate: string; endDate: string; observationStart: string; lastEvaluation: string; opportunities: number; starts: number; sets: number; satisfaction: number; trust: number; status: string; reason: string; policyVersion: string }
export interface TradeTerms { kind: 'TRANSFER' | 'LOAN'; playerId: string; seller: string; buyer: string; startDate: string; endDate: string; fee: number; borrowerSalaryPercent: number; playerTerms: MarketTerms; replacementPlayerId: string | null }
export interface Negotiation { tradeId: string; contractId: string; proposer: string; terms: TradeTerms; submittedDate: string; responseDate: string; decisionDate: string; expiresDate: string; round: number; previousTradeId: string | null; status: 'CLUB_PENDING' | 'CLUB_COUNTER' | 'PLAYER_PENDING' | 'AGREED' | 'COMPLETED' | 'REJECTED' | 'WITHDRAWN' | 'EXPIRED' | 'SUPERSEDED' | 'CANCELLED_RETIREMENT'; sellerAgreed: boolean; buyerAgreed: boolean; referenceValue: number; sellerDemand: number; reason: string; policyVersion: string }
export interface Loan { loanId: string; tradeId: string; contractId: string; playerId: string; parentTeam: string; borrowingTeam: string; startDate: string; endDate: string; fee: number; borrowerSalaryPercent: number; role: MarketRole; returnOrganization: string; returnSquad: string; status: string; policyVersion: string }
export interface Appearance { completionId: string; fixtureId: string; seriesId: string; seasonYear: number; date: string; completedSets: number; opportunities: { playerId: string; team: string; position: string; promiseId: string; eligible: boolean; selected: boolean; reason: string }[] }
export interface TradeQuote { playerId: string; referenceSalary: number; estimatedValue: number; suggestedTransferFee: number; earliestStart: string; unavailableReason: string | null }
export interface CareerManagement { policyVersion: string; observationStarted: string; promises: RolePromise[]; trades: Negotiation[]; loans: Loan[]; appearances: Appearance[]; quotes: TradeQuote[] }
export interface TradeCommand { schemaVersion: 'CAREER_TRADE_COMMAND_V1'; sourceYear: number; expectedRevision: number; action: 'SUBMIT' | 'COUNTER' | 'ACCEPT' | 'REJECT' | 'WITHDRAW'; tradeId: string | null; terms: TradeTerms | null; replacementPlayerId: string | null; clientCommandId: string }
function require(ok: unknown): asserts ok { if (!ok) throw new CareerContractError('management'); }
const object = (v: unknown): Record<string, unknown> => { require(v && typeof v === 'object' && !Array.isArray(v)); return v as Record<string, unknown>; };
const nonnegative = (v: unknown): v is number => Number.isSafeInteger(v) && (v as number) >= 0;
function terms(v: unknown) { const t = object(v), p = object(t.playerTerms); require(['TRANSFER', 'LOAN'].includes(t.kind as string) && typeof t.playerId === 'string' && typeof t.seller === 'string' && typeof t.buyer === 'string' && t.seller !== t.buyer && nonnegative(t.fee) && nonnegative(t.borrowerSalaryPercent) && t.borrowerSalaryPercent <= 100 && t.startDate === p.startDate && t.endDate === p.endDate && nonnegative(p.annualSalary) && p.annualSalary > 0 && nonnegative(p.signingBonus) && ['STARTER', 'RESERVE', 'DEVELOPMENT'].includes(p.role as string)); require(t.kind === 'LOAN' ? p.signingBonus === 0 : t.borrowerSalaryPercent === 0); }
export function validateManagement(value: unknown): CareerManagement {
  const v = object(value); require(v.policyVersion === 'CAREER_PROMISE_TRANSFER_LOAN_V1' && typeof v.observationStarted === 'string');
  for (const key of ['promises', 'trades', 'loans', 'appearances', 'quotes']) require(Array.isArray(v[key]));
  for (const raw of v.promises as unknown[]) { const p = object(raw); require(['satisfaction', 'trust', 'opportunities', 'starts', 'sets'].every(k => nonnegative(p[k])) && (p.satisfaction as number) <= 100 && (p.trust as number) <= 100 && (p.starts as number) <= (p.opportunities as number) && typeof p.reason === 'string' && ['STARTER', 'RESERVE', 'DEVELOPMENT'].includes(p.role as string)); }
  for (const raw of v.trades as unknown[]) { const t = object(raw); terms(t.terms); require(typeof t.tradeId === 'string' && typeof t.sellerAgreed === 'boolean' && typeof t.buyerAgreed === 'boolean' && ['CLUB_PENDING', 'CLUB_COUNTER', 'PLAYER_PENDING', 'AGREED', 'COMPLETED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', 'SUPERSEDED', 'CANCELLED_RETIREMENT'].includes(t.status as string)); if (t.status === 'COMPLETED' || t.status === 'AGREED') require(t.sellerAgreed && t.buyerAgreed); }
  for (const raw of v.loans as unknown[]) { const l = object(raw); require(l.parentTeam !== l.borrowingTeam && nonnegative(l.borrowerSalaryPercent) && l.borrowerSalaryPercent <= 100 && ['ACTIVE', 'RETURNED', 'RETIRED'].includes(l.status as string)); }
  for (const raw of v.appearances as unknown[]) { const a = object(raw); require(nonnegative(a.completedSets) && a.completedSets > 0 && Array.isArray(a.opportunities)); }
  for (const raw of v.quotes as unknown[]) { const q = object(raw); require(nonnegative(q.referenceSalary) && nonnegative(q.estimatedValue) && nonnegative(q.suggestedTransferFee)); }
  return v as unknown as CareerManagement;
}
export function validateTradeCommand(value: unknown): TradeCommand {
  const v = object(value); require(Object.keys(v).sort().join() === 'schemaVersion sourceYear expectedRevision action tradeId terms replacementPlayerId clientCommandId'.split(' ').sort().join());
  require(v.schemaVersion === 'CAREER_TRADE_COMMAND_V1' && nonnegative(v.sourceYear) && nonnegative(v.expectedRevision) && ['SUBMIT', 'COUNTER', 'ACCEPT', 'REJECT', 'WITHDRAW'].includes(v.action as string) && typeof v.clientCommandId === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(v.clientCommandId));
  if (v.action === 'SUBMIT' || v.action === 'COUNTER') { terms(v.terms); require(v.action === 'SUBMIT' ? v.tradeId === null : typeof v.tradeId === 'string'); require(v.replacementPlayerId === null); } else require(v.terms === null && typeof v.tradeId === 'string');
  return v as unknown as TradeCommand;
}
export const tradeOperationKey = (career: string) => `lolfm.career.trade-command.v1.${career}`;
export function readTradeOperation(storage: Pick<Storage, 'getItem'>, career: string): TradeCommand | null { const raw = storage.getItem(tradeOperationKey(career)); return raw ? validateTradeCommand(JSON.parse(raw)) : null; }
