package com.lolfm.composition;
import static org.assertj.core.api.Assertions.*;
import com.lolfm.champion.*;import com.lolfm.domain.Position;import com.lolfm.simulator.SimulationOptions;import java.nio.file.*;import java.security.MessageDigest;import java.util.*;import org.junit.jupiter.api.Test;
class CompositionProfileWarningReviewerTest{
 static final Path SOURCE=Path.of("build/reports/thirty-champion-composition-profiles");static final CompositionProfileWarningReviewer.ReviewResult REVIEW=load();
 @Test void trueDamageReviewEnumeratesAllNonZeroProfiles(){assertThat(REVIEW.trueDamage()).hasSize(5).extracting(CompositionProfileWarningReviewer.TrueDamageReview::championId).containsExactlyInAnyOrder("gwen","ksante","ahri","jax","kaisa");}
 @Test void trueDamageZeroSparsityIsNotAutomaticallyAnError(){assertThat(REVIEW.infoCodes()).contains("EXPECTED_SPARSE_DAMAGE_CHANNEL");}
 @Test void trueDamageNonZeroRequiresExplicitRationale(){assertThat(REVIEW.trueDamage()).allMatch(x->!x.rationale().isBlank()&&!x.sourceType().equals("UNKNOWN"));}
 @Test void incidentalDamageDoesNotCreateTrueDamageThreat(){assertThat(CompositionProfileWarningReviewer.classifyTrueDamage("INCIDENTAL",true)).isEqualTo("PROFILE_DATA_ERROR");}
 @Test void invalidTrueDamageProfileIsClassifiedAsDataError(){assertThat(CompositionProfileWarningReviewer.classifyTrueDamage("NONE",true)).isEqualTo("PROFILE_DATA_ERROR");}
 @Test void broadPatternWithMeaningfulSpreadIsInformational(){assertThat(REVIEW.patterns()).allMatch(x->x.classification().equals("BROAD_BUT_VARIABLE_INFO"));}
 @Test void saturatedPatternRemainsReview(){assertThat(CompositionProfileWarningReviewer.classifyPattern(.01,.01,10,.02,.001,0,0,true)).isEqualTo("PATTERN_SATURATION_REVIEW");}
 @Test void patternReviewUsesExistingLineupArtifact()throws Exception{String before=hash(SOURCE.resolve("thirty-champion-composition-lineups.csv"));CompositionProfileWarningReviewer.review(SOURCE);assertThat(hash(SOURCE.resolve("thirty-champion-composition-lineups.csv"))).isEqualTo(before);}
 @Test void patternReviewRecordsTopBottomSeparation(){assertThat(REVIEW.patterns()).allMatch(x->x.topOnePercentMean()>x.bottomTenPercentMean());}
 @Test void patternClassificationIsDeterministic()throws Exception{assertThat(CompositionProfileWarningReviewer.review(SOURCE).patterns()).isEqualTo(REVIEW.patterns());}
 @Test void zeroRateDeficiencyCanBeCurrentCatalogUnreachable(){assertThat(REVIEW.deficiencies()).allMatch(x->x.classification().equals("CURRENT_CATALOG_UNREACHABLE_INFO"));}
 @Test void unreachableDeficiencyRequiresSyntheticDetectability(){assertThat(REVIEW.deficiencies()).allMatch(CompositionProfileWarningReviewer.DeficiencyReachability::syntheticDetectable);}
 @Test void foundationPolicyFailureRemainsReview(){assertThat(CompositionProfileWarningReviewer.classifyDeficiency(false,true,false,true)).isEqualTo("FOUNDATION_POLICY_REVIEW");}
 @Test void sideLaneAnswerChecksBothConditions(){var x=REVIEW.deficiencies().stream().filter(d->d.deficiency().equals("NO_SIDE_LANE_ANSWER")).findFirst().orElseThrow();assertThat(x.relevantCapability()).contains("SIDE_LANE_PRESSURE","WAVE_CLEAR");assertThat(x.actualMinimum()).contains("side=","wave=");}
 @Test void deficiencyReachabilityIsDeterministic()throws Exception{assertThat(CompositionProfileWarningReviewer.review(SOURCE).deficiencies()).isEqualTo(REVIEW.deficiencies());}
 @Test void specialistConcentrationIsInformational(){assertThat(REVIEW.concentrations()).hasSize(7).allMatch(x->x.classification().equals("SPECIALIST_CONCENTRATION_INFO"));}
 @Test void systemicMultiPatternConcentrationRemainsReview(){assertThat(CompositionProfileWarningReviewer.classifyConcentration(3,false,false,false,"A=1|B=2|C=3",true)).isEqualTo("SYSTEMIC_CONCENTRATION_REVIEW");}
 @Test void concentrationRecordsPatternAndRate(){assertThat(REVIEW.concentrations()).allMatch(x->!x.pattern().isBlank()&&x.concentrationRate()>=.80);}
 @Test void universalProviderCannotBeClassifiedAsSpecialist(){assertThat(CompositionProfileWarningReviewer.classifyConcentration(1,true,false,false,"A=1",true)).isEqualTo("SYSTEMIC_CONCENTRATION_REVIEW");}
 @Test void broadDeficiencyRemoverCannotBeClassifiedAsSpecialist(){assertThat(CompositionProfileWarningReviewer.classifyConcentration(1,false,true,false,"A=1",true)).isEqualTo("SYSTEMIC_CONCENTRATION_REVIEW");}
 @Test void noProfileChangePreservesVersionAndHash(){assertThat(CompositionProfileWarningReviewer.SOURCE_VERSION).isEqualTo("thirty-champion-composition-profile-candidate-v1");assertThat(CompositionProfileWarningReviewer.SOURCE_HASH).isEqualTo("b6324c6e5bdeddb142159fe0dac9af9224033b6421d389c2f519ea4ed050b676");}
 @Test void noProfileChangeDoesNotRerunExhaustiveAnalysis(){assertThat(CompositionProfileWarningReviewer.shouldRerunExhaustive("PATH_A_NO_PROFILE_CHANGE")).isFalse();}
 @Test void profileCorrectionBumpsCandidateVersion(){assertThat(REVIEW.finalVersion()).isEqualTo("thirty-champion-composition-profile-candidate-v2");}
 @Test void profileCorrectionChangesCanonicalHash(){assertThat(REVIEW.finalHash()).isNotEqualTo(REVIEW.sourceHash()).isEqualTo(ThirtyChampionCompositionProfiles.profileHash());}
 @Test void profileCorrectionRerunsPureAuditOnly()throws Exception{assertThat(CompositionProfileWarningReviewer.shouldRerunExhaustive(REVIEW.executionPath())).isTrue();assertThat(reviewerSource()).doesNotContain("MatchSimulator",".simulate(");}
 @Test void infoCodesDoNotBlockReadyVerdict(){assertThat(CompositionProfileWarningReviewer.freezeVerdict(List.of(),List.of(),List.of())).isEqualTo("READY_FOR_PHASE_13D3");}
 @Test void reviewCodesBlockPhase13D3(){assertThat(CompositionProfileWarningReviewer.freezeVerdict(List.of("review"),List.of(),List.of())).isEqualTo("REVIEW_COMPOSITION_PROFILE_FREEZE");}
 @Test void correctionCodesRequireReaudit(){assertThat(CompositionProfileWarningReviewer.freezeVerdict(List.of(),List.of("correction"),List.of())).isEqualTo("REVIEW_COMPOSITION_PROFILE_FREEZE");}
 @Test void verdictIsComputedNotHardcoded()throws Exception{assertThat(reviewerSource()).contains("String verdict=!integrity.isEmpty()?").doesNotContain("String verdict=\"READY_FOR_PHASE_13D3\"");}
 @Test void profileFreezeRequiresNoUnresolvedReview(){assertThat(REVIEW.profileFrozen()).isTrue();assertThat(REVIEW.reviewCodes()).isEmpty();assertThat(REVIEW.correctionCodes()).isEmpty();}
 @Test void reviewerRunsNoMatchSimulation()throws Exception{assertThat(reviewerSource()).doesNotContain("MatchSimulator",".simulate(");}
 @Test void reviewerConsumesNoRandom()throws Exception{assertThat(reviewerSource()).doesNotContain("Math.random","new Random","java.util.Random");}
 @Test void gameplayApplicationRemainsZero(){assertThat(REVIEW.integrityErrorCount()).isZero();}
 @Test void productionGameplayRemainsUnchanged()throws Exception{assertThat(Files.readString(Path.of("src/main/java/com/lolfm/simulator/MatchSimulator.java"))).doesNotContain("ThirtyChampionCompositionProfiles");}
 @Test void productionMatchupDefaultRemainsGeometricV2(){assertThat(SimulationOptions.productionDefaults().championMatchupMode()).isEqualTo(ChampionMatchupMode.GEOMETRIC_V2);}
 @Test void explicitMatchupOffRollbackStillWorks(){var e=new ChampionMatchupEvaluator(ChampionRoleMatchupProfileCatalog.production());var k=new ChampionRoleKey(new ChampionId("unsupported"),Position.TOP);assertThat(e.evaluate(k,k,com.lolfm.simulator.ProgressionCombatContext.LANE_COMBAT,ChampionMatchupMode.OFF).finalEdge()).isZero();}
 @Test void apiSchemaIsUnchanged()throws Exception{for(var p:Files.walk(Path.of("src/main/java/com/lolfm/dto")).filter(Files::isRegularFile).toList())assertThat(Files.readString(p)).doesNotContain("CompositionProfileWarningReviewer");}
 @Test void frontendFilesAreUnchanged()throws Exception{for(var p:Files.walk(Path.of("../frontend/src")).filter(Files::isRegularFile).toList())assertThat(Files.readString(p)).doesNotContain("CompositionProfileWarningReviewer");}
 @Test void sourceArtifactsRemainUnchangedOnPathA()throws Exception{String summary=hash(SOURCE.resolve("thirty-champion-composition-profile-summary.csv")),audit=hash(SOURCE.resolve("thirty-champion-composition-profile-audit.log"));CompositionProfileWarningReviewer.review(SOURCE);assertThat(hash(SOURCE.resolve("thirty-champion-composition-profile-summary.csv"))).isEqualTo(summary);assertThat(hash(SOURCE.resolve("thirty-champion-composition-profile-audit.log"))).isEqualTo(audit);}
 @Test void priorHashesRemainExact()throws Exception{assertHash("baseline/phase12_5/progression-baseline-summary.csv","af014896733d568974c91043c24d07917239808e3fcb9277bfba55480974da04");assertHash("baseline/phase12_5/progression-combat-contribution.csv","f18ab7781284d23a9369a1f8a1ee4ba5df156706727dc588ce42114d90ddc735");assertHash("baseline/phase12_5/progression-position-timings.csv","464f895021398f6ffa25cfebabc08d0483e3428018321f127f45d82f8725ec5c");assertHash("build/reports/champion-matchup-production-activation/champion-matchup-production-activation-summary.csv","d6eab10c88e5cc36ecd5d2e71b916e26703f83cddce1a792ba6cad7a2adf8cb1");assertHash("build/reports/team-composition-foundation/team-composition-foundation-summary.csv","98c896c81e3b432c095b74b3693c3491f3d9cac7c941d98b9c34ea658b33afa1");}
 static CompositionProfileWarningReviewer.ReviewResult load(){try{return CompositionProfileWarningReviewer.review(SOURCE);}catch(Exception e){throw new ExceptionInInitializerError(e);}}static String reviewerSource()throws Exception{return Files.readString(Path.of("src/test/java/com/lolfm/composition/CompositionProfileWarningReviewer.java"));}static String hash(Path p)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(p)));}static void assertHash(String p,String h)throws Exception{assertThat(hash(Path.of(p))).isEqualTo(h);}
}
