package com.lolfm.composition;
import static org.assertj.core.api.Assertions.*;
import com.lolfm.simulator.CombatOutcomeProbabilityEvaluator;import java.util.*;import org.junit.jupiter.api.*;
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@Tag("diagnostic")
@Tag("historical-artifact")
class CompositionApplicationSemanticsReviewTest{
 CompositionApplicationSemanticsReview.Result r;@BeforeAll void load()throws Exception{r=CompositionApplicationSemanticsReview.analyze();}
 @Test void marginRepairHashesAreExact(){assertThat(CompositionApplicationSemanticsReview.RSH).isEqualTo("07594a77ccea8746fc26203b77eb84753d2443719d96515beddc0f1e443aef20");assertThat(CompositionApplicationSemanticsReview.RAH).isEqualTo("273a269f5ca477d6afd2b36726ec4b4496f9b674f6daa4a223849ac02a494b09");}
 @Test void historicalCandidateIdentityRemainsExact(){assertThat(FrozenCompositionGameplayGainPolicy.CANDIDATE_HASH).isEqualTo("ec99828c0f04a00cc644f4d0446d851543a46a530c9bc561408af9cf704da32d");FrozenCompositionInteractionRuntimePolicy.current().verifyExactIdentity();}
 @Test void sourceArtifactsRemainReadOnly(){assertThat(r.before()).isEqualTo(r.after());}
 @Test void reviewRunsNoGameplaySimulation(){assertThat(metric("matchSimulationCount")).isEqualTo("0");assertThat(metric("gameplayApplicationExecutionCount")).isEqualTo("0");}
 @Test void reviewDoesNotChangeGain(){assertThat(metric("gainChanged")).isEqualTo("false");assertThat(List.of(FrozenCompositionGameplayGainPolicy.SKIRMISH_GAIN,FrozenCompositionGameplayGainPolicy.TEAMFIGHT_GAIN,FrozenCompositionGameplayGainPolicy.SIEGE_GAIN,FrozenCompositionGameplayGainPolicy.BASE_DEFENSE_GAIN)).containsExactly(24.509721397259,11.595061941148,6.805985567298,10.837956658606);}
 @Test void reviewDoesNotCreateCandidate(){assertThat(metric("newCandidateCreated")).isEqualTo("false");}
 @Test void everyApplicationKeyHasStructuredScoreProvenance(){assertThat(r.prov().stream().map(CompositionApplicationSemanticsReview.Prov::key).distinct()).containsExactlyElementsOf(CompositionApplicationSemanticsReview.KEYS);}
 @Test void compositionAdjustmentPointIsIdentifiedForEveryKey(){assertThat(r.flows()).allMatch(f->f.adjust()!=null&&!f.adjust().isBlank());}
 @Test void winnerConsumerIsIdentifiedForEveryKey(){assertThat(r.flows()).allMatch(f->f.winner().contains(".")&&f.probability().contains("CombatOutcomeProbabilityEvaluator"));}
 @Test void fightGradeConsumerIsIdentifiedWhenPresent(){assertThat(r.flows().stream().filter(CompositionApplicationSemanticsReview.Flow::grade)).allMatch(f->f.gradeEval().contains("determineFightGrade"));}
 @Test void scoreProvenanceDoesNotUseDisplayTextIdentity(){assertThat(r.prov()).allMatch(p->!p.producer().contains("|GRADE:")&&!p.consumer().contains("|GRADE:"));}
 @Test void decisionStagesUseStructuredTaxonomy(){assertThat(r.uses()).allMatch(u->u.stage()!=null&&u.influence()!=null);}
 @Test void winnerCompositionConsumptionIsDetectedFromCodePath(){assertThat(r.flows()).allMatch(f->f.adjust().contains("adjustedScoreForCandidate"));double p=new CombatOutcomeProbabilityEvaluator().weightedSelectionProbability(6,4);assertThat(p).isEqualTo(.6);}
 @Test void gradeCompositionConsumptionIsDetectedFromCodePath(){assertThat(r.flows().stream().filter(CompositionApplicationSemanticsReview.Flow::grade)).allMatch(f->f.gradeInput().contains("adjustedGap"));}
 @Test void directCompositionStageCountIsComputed(){assertThat(flow(CompositionApplicationSemanticsReview.SK).direct()).isOne();assertThat(r.flows().stream().filter(CompositionApplicationSemanticsReview.Flow::grade)).allMatch(f->f.direct()==2);}
 @Test void winnerGradeDependencyClassificationIsDeterministic(){assertThat(r.flows().stream().filter(CompositionApplicationSemanticsReview.Flow::grade)).allMatch(f->f.dep()==CompositionApplicationSemanticsReview.Dependency.GRADE_REUSES_PRE_WINNER_ADJUSTED_SCORE);}
 @Test void sameAdjustedScoreReuseIsNotAutomaticallyCalledDuplicate(){assertThat(r.flows().stream().filter(CompositionApplicationSemanticsReview.Flow::grade)).noneMatch(f->f.effect()==CompositionApplicationSemanticsReview.Effect.DUPLICATED_COMPOSITION_EFFECT);}
 @Test void duplicateEffectRequiresSemanticEvidence(){assertThat(r.flows().stream().filter(f->f.effect()==CompositionApplicationSemanticsReview.Effect.DUPLICATED_COMPOSITION_EFFECT)).isEmpty();}
 @Test void downstreamPropagationIsNotClassifiedAsDirectDoubleCount(){assertThat(r.uses().stream().filter(u->u.stage()==CompositionApplicationSemanticsReview.Stage.DOWNSTREAM_OBJECTIVE||u.stage()==CompositionApplicationSemanticsReview.Stage.DOWNSTREAM_STRUCTURE)).allMatch(u->u.influence()==CompositionApplicationSemanticsReview.Influence.INDIRECT_VIA_PRIOR_DECISION);}
 @Test void skirmishControlPathIsComparedUsingSameRules(){assertThat(flow(CompositionApplicationSemanticsReview.SK).effect()).isEqualTo(CompositionApplicationSemanticsReview.Effect.SINGLE_STAGE_EFFECT);assertThat(r.uses().stream().filter(u->u.key().equals(CompositionApplicationSemanticsReview.SK))).isNotEmpty();}
 @Test void halfSplitAssessmentIsPerScoreDomain(){assertThat(r.flows().stream().map(CompositionApplicationSemanticsReview.Flow::half)).containsExactly(CompositionApplicationSemanticsReview.Half.HALF_SPLIT_SEMANTICS_VALID,CompositionApplicationSemanticsReview.Half.HALF_SPLIT_SEMANTICS_VALID,CompositionApplicationSemanticsReview.Half.HALF_SPLIT_SEMANTICS_QUESTIONABLE,CompositionApplicationSemanticsReview.Half.HALF_SPLIT_SEMANTICS_QUESTIONABLE);}
 @Test void asymmetricScoreDomainCannotBeDeclaredValidWithoutEvidence(){assertThat(flow(CompositionApplicationSemanticsReview.BD).half()).isEqualTo(CompositionApplicationSemanticsReview.Half.HALF_SPLIT_SEMANTICS_QUESTIONABLE);}
 @Test void halfSplitReviewDoesNotChangeFormula(){assertThat(FrozenCompositionGameplayGainPolicy.ADJUSTMENT_FORMULA).isEqualTo("GAP_MODIFIER_HALF_SPLIT_V1");}
 @Test void gradeRandomAvailabilityIsReported(){assertThat(r.flows().stream().filter(CompositionApplicationSemanticsReview.Flow::grade)).hasSize(3);assertThat(metric("gradeDiagnosticGapKeyCount")).isEqualTo("3");}
 @Test void missingGradeRandomIsNotInvented(){assertThat(r.flows().stream().filter(CompositionApplicationSemanticsReview.Flow::grade)).allMatch(f->f.randomOrder().contains("ACE")||f.randomOrder().contains("grade"));}
 @Test void partiallyObservedGradeBranchRemainsPartial(){assertThat(r.evidence().get(CompositionApplicationSemanticsReview.TF).grade()).isEqualTo(16);assertThat(r.evidence().get(CompositionApplicationSemanticsReview.SI).grade()).isEqualTo(3);assertThat(r.evidence().get(CompositionApplicationSemanticsReview.BD).grade()).isEqualTo(467);}
 @Test void gradeDiagnosticGapCanBlockCandidateDesign(){var f=new ArrayList<>(r.flows());f.set(1,new CompositionApplicationSemanticsReview.Flow(f.get(1).key(),f.get(1).domain(),f.get(1).base(),f.get(1).adjust(),f.get(1).winner(),f.get(1).probability(),true,f.get(1).gradeEval(),f.get(1).gradeInput(),2,f.get(1).dep(),f.get(1).half(),f.get(1).effect(),CompositionApplicationSemanticsReview.Rec.SEMANTICS_REDESIGN_REQUIRES_MORE_DIAGNOSTICS,f.get(1).evidence(),f.get(1).meaning(),f.get(1).unit(),f.get(1).randomOrder()));assertThat(f).anyMatch(x->x.rec()==CompositionApplicationSemanticsReview.Rec.SEMANTICS_REDESIGN_REQUIRES_MORE_DIAGNOSTICS);}
 @Test void recommendationIsComputedPerApplicationKey(){assertThat(r.flows().stream().map(CompositionApplicationSemanticsReview.Flow::rec)).containsExactly(CompositionApplicationSemanticsReview.Rec.KEEP_CURRENT_APPLICATION_SEMANTICS,CompositionApplicationSemanticsReview.Rec.SEPARATE_WINNER_AND_GRADE_COMPOSITION_EFFECT,CompositionApplicationSemanticsReview.Rec.SEPARATE_WINNER_AND_GRADE_COMPOSITION_EFFECT,CompositionApplicationSemanticsReview.Rec.KEY_SPECIFIC_APPLICATION_SEMANTICS);}
 @Test void skirmishIsNotModifiedBecauseOtherKeysFail(){assertThat(flow(CompositionApplicationSemanticsReview.SK).rec()).isEqualTo(CompositionApplicationSemanticsReview.Rec.KEEP_CURRENT_APPLICATION_SEMANTICS);}
 @Test void winnerOnlyRecommendationRequiresWinnerGradeReuseEvidence(){assertThat(r.assess().stream().filter(a->a.candidate()==CompositionApplicationSemanticsReview.Candidate.SEMANTICS_A_WINNER_ONLY&&!a.key().equals(CompositionApplicationSemanticsReview.SK))).allMatch(a->a.concept()!=CompositionApplicationSemanticsReview.Rating.REJECTED);}
 @Test void separatedSignalRecommendationRequiresDistinctSemanticNeed(){assertThat(flow(CompositionApplicationSemanticsReview.TF).evidence()).contains("DISTINCT_WINNER_AND_SEVERITY");}
 @Test void keySpecificRecommendationRequiresCrossKeySemanticDifference(){assertThat(flow(CompositionApplicationSemanticsReview.BD).evidence()).contains("ASYMMETRIC_ATTACKER_DEFENDER_ROLE");}
 @Test void insufficientEvidenceProducesDiagnosticReview(){assertThat(CompositionApplicationSemanticsReview.Rec.SEMANTICS_REDESIGN_REQUIRES_MORE_DIAGNOSTICS.name()).contains("MORE_DIAGNOSTICS");}
 @Test void verdictIsComputedNotHardcoded(){assertThat(r.verdict()).isEqualTo("READY_FOR_PHASE_13D4C4_KEY_SPECIFIC_SEMANTICS_CANDIDATE");assertThat(r.allowed()).isTrue();}
 private CompositionApplicationSemanticsReview.Flow flow(String k){return r.flows().stream().filter(f->f.key().equals(k)).findFirst().orElseThrow();}private String metric(String k){return CompositionApplicationSemanticsReview.summary(r).stream().skip(1).filter(x->x.get(0).equals(k)).findFirst().orElseThrow().get(1);}
}
