package com.lolfm.composition;
import static org.assertj.core.api.Assertions.*;
import com.lolfm.champion.*;import com.lolfm.domain.Position;import com.lolfm.simulator.SimulationOptions;import com.lolfm.testsupport.FrontendTextSourceScanner;import java.nio.file.*;import java.lang.reflect.Modifier;import java.util.*;import org.junit.jupiter.api.Test;
class TeamCompositionFoundationTest{
 @Test void compositionProfileRequiresAllFifteenCapabilities(){var f=f();var k=f.lineup().championsByPosition().get(Position.TOP);assertThatThrownBy(()->new ChampionCompositionProfile(k,Map.of(),new DamageChannelProfile(0,0,0))).isInstanceOf(IllegalArgumentException.class);}
 @Test void compositionProfileRejectsCapabilityBelowZero(){assertBadCapability(-1);}
 @Test void compositionProfileRejectsCapabilityAboveTwenty(){assertBadCapability(21);}
 @Test void compositionProfileIsImmutable(){var f=f();var k=f.lineup().championsByPosition().get(Position.TOP);var m=SyntheticTeamCompositionFixtures.values(10);var p=new ChampionCompositionProfile(k,m,new DamageChannelProfile(1,1,1));m.put(CompositionCapability.ENGAGE,20);assertThat(p.capability(CompositionCapability.ENGAGE)).isEqualTo(10);assertThatThrownBy(()->p.capabilities().put(CompositionCapability.ENGAGE,1)).isInstanceOf(UnsupportedOperationException.class);}
 @Test void damageProfileRejectsInvalidRange(){assertThatThrownBy(()->new DamageChannelProfile(-1,0,0)).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->new DamageChannelProfile(0,21,0)).isInstanceOf(IllegalArgumentException.class);}
 @Test void lineupRequiresExactlyFivePositions(){var f=f();assertThatThrownBy(()->new TeamCompositionLineup(Map.of(Position.TOP,f.lineup().championsByPosition().get(Position.TOP)))).isInstanceOf(IllegalArgumentException.class);}
 @Test void lineupRejectsDuplicateChampion(){var f=f();EnumMap<Position,ChampionRoleKey>m=new EnumMap<>(f.lineup().championsByPosition());var top=m.get(Position.TOP);m.put(Position.MID,new ChampionRoleKey(top.championId(),Position.MID));assertThatThrownBy(()->new TeamCompositionLineup(m)).isInstanceOf(IllegalArgumentException.class);}
 @Test void lineupRejectsRolePositionMismatch(){var f=f();EnumMap<Position,ChampionRoleKey>m=new EnumMap<>(f.lineup().championsByPosition());m.put(Position.TOP,m.get(Position.MID));assertThatThrownBy(()->new TeamCompositionLineup(m)).isInstanceOf(IllegalArgumentException.class);}
 @Test void lineupIsImmutable(){var f=f();EnumMap<Position,ChampionRoleKey>m=new EnumMap<>(f.lineup().championsByPosition());var l=new TeamCompositionLineup(m);m.clear();assertThat(l.championsByPosition()).hasSize(5);assertThatThrownBy(()->l.championsByPosition().clear()).isInstanceOf(UnsupportedOperationException.class);}
 @Test void lineupDoesNotDependOnMapIterationOrder(){var f=f();assertThat(new TeamCompositionLineup(reverse(f.lineup().championsByPosition()))).isEqualTo(f.lineup());}
 @Test void primarySourceAggregationMatchesExactWeights(){assertCoverage(CompositionCapability.ENGAGE,.94);}
 @Test void dualSourceAggregationMatchesExactWeights(){assertCoverage(CompositionCapability.PEEL,.88);}
 @Test void distributedAggregationMatchesExactWeights(){assertCoverage(CompositionCapability.SUSTAINED_DAMAGE,.75);}
 @Test void aggregationIsIndependentOfInputOrder(){var f=ranked();var a=analyze(f);var l=new TeamCompositionLineup(reverse(f.lineup().championsByPosition()));assertThat(new TeamCompositionAnalyzer().analyze(l,f.profiles()).coverage()).isEqualTo(a.coverage());}
 @Test void aggregationIsDeterministic(){var f=ranked();assertThat(analyze(f)).isEqualTo(analyze(f));}
 @Test void aggregationResultRemainsWithinZeroAndOne(){assertThat(analyze(ranked()).coverage().capabilities().values()).allMatch(x->x.coverage()>=0&&x.coverage()<=1);}
 @Test void additionalContributorDoesNotReduceCoverage(){double a=coverage(values(20,0,0,0,0),CompositionCapability.ENGAGE),b=coverage(values(20,10,0,0,0),CompositionCapability.ENGAGE);assertThat(b).isGreaterThanOrEqualTo(a);}
 @Test void singleMaximumContributorDoesNotProduceFullCoverage(){assertThat(coverage(values(20,0,0,0,0),CompositionCapability.ENGAGE)).isEqualTo(.75);}
 @Test void contributorWeightedSumMatchesCoverage(){var c=analyze(ranked()).coverage().capability(CompositionCapability.PEEL);assertThat(c.contributors().stream().mapToDouble(CapabilityContributor::weightedContribution).sum()).isEqualTo(c.coverage());}
 @Test void contributorTieBreakUsesStructuredIdentity(){var c=analyze(f()).coverage().capability(CompositionCapability.ENGAGE);assertThat(c.contributors()).extracting(x->x.championRoleKey().stableId()).isSorted();}
 @Test void allZeroCapabilityProducesPositiveZero(){double v=analyze(zero()).coverage().capability(CompositionCapability.ENGAGE).coverage();assertThat(Double.doubleToRawLongBits(v)).isZero();}
 @Test void engageWithoutFollowUpDoesNotCompleteEngageChain(){assertThat(caseAnalysis("engage-no-follow").patterns().get(CompositionPattern.ENGAGE_CHAIN).readiness()).isZero();}
 @Test void engageChainImprovesWithDistinctFollowUpContributor(){assertThat(caseAnalysis("engage-chain").patterns().get(CompositionPattern.ENGAGE_CHAIN).contributorFactor()).isEqualTo(1);}
 @Test void distinctPreferredAppliesPointSevenFactor(){var x=customSame(CompositionCapability.ENGAGE,CompositionCapability.FOLLOW_UP,CompositionCapability.BACKLINE_ACCESS);assertThat(x.patterns().get(CompositionPattern.ENGAGE_CHAIN).contributorFactor()).isEqualTo(.70);}
 @Test void distinctRequiredProducesZeroWhenUnsatisfied(){assertThat(caseAnalysis("front-concentrated").patterns().get(CompositionPattern.FRONT_TO_BACK).readiness()).isZero();}
 @Test void frontToBackRequiresDistinctFrontlineAndDamageContributor(){assertThat(caseAnalysis("front-to-back").patterns().get(CompositionPattern.FRONT_TO_BACK).readiness()).isGreaterThan(0);}
 @Test void pokeSiegeAllowsSameContributor(){var x=caseAnalysis("poke-siege").patterns().get(CompositionPattern.POKE_SIEGE);assertThat(x.contributorFactor()).isEqualTo(1);assertThat(x.readiness()).isGreaterThan(0);}
 @Test void splitMapPressureRequiresDistinctSideAndWaveContributor(){assertThat(caseAnalysis("split-concentrated").patterns().get(CompositionPattern.SPLIT_MAP_PRESSURE).readiness()).isZero();assertThat(caseAnalysis("split-map").patterns().get(CompositionPattern.SPLIT_MAP_PRESSURE).readiness()).isGreaterThan(0);}
 @Test void patternUsesGeometricMean(){var x=caseAnalysis("engage-chain").patterns().get(CompositionPattern.ENGAGE_CHAIN);double product=x.componentCoverages().values().stream().reduce(1d,(a,b)->a*b);assertThat(x.baseReadiness()).isEqualTo(Math.cbrt(product));}
 @Test void zeroPatternComponentProducesZeroReadiness(){assertThat(caseAnalysis("engage-no-follow").patterns().get(CompositionPattern.ENGAGE_CHAIN).baseReadiness()).isZero();}
 @Test void patternExplanationMatchesEvaluation(){var a=caseAnalysis("engage-chain");var e=a.explanation().patterns().stream().filter(x->x.pattern()==CompositionPattern.ENGAGE_CHAIN).findFirst().orElseThrow();assertThat(e.readiness()).isEqualTo(a.patterns().get(CompositionPattern.ENGAGE_CHAIN).readiness());}
 @Test void lowEngageDeficiencyIsDetected(){assertPresent("no-engage",CompositionDeficiency.NO_RELIABLE_ENGAGE);}
 @Test void lowFrontlineDeficiencyIsDetected(){assertPresent("low-frontline",CompositionDeficiency.LOW_FRONTLINE);}
 @Test void sideLaneAnswerRequiresSidePressureOrWaveClearCoverage(){assertThat(analyze(zero()).deficiencies().get(CompositionDeficiency.NO_SIDE_LANE_ANSWER).present()).isTrue();assertThat(caseAnalysis("split-map").deficiencies().get(CompositionDeficiency.NO_SIDE_LANE_ANSWER).present()).isFalse();}
 @Test void physicalDamageSkewIsDetected(){assertPresent("physical-skew",CompositionDeficiency.DAMAGE_CHANNEL_SKEW);}
 @Test void magicDamageSkewIsDetected(){assertPresent("magic-skew",CompositionDeficiency.DAMAGE_CHANNEL_SKEW);}
 @Test void balancedDamageHasNoSkew(){assertThat(caseAnalysis("balanced-damage").deficiencies().get(CompositionDeficiency.DAMAGE_CHANNEL_SKEW).present()).isFalse();}
 @Test void zeroDamageThreatProducesNotApplicableShares(){var d=caseAnalysis("zero-damage").coverage().damageChannels();assertThat(d.shareApplicable()).isFalse();assertThat(d.physicalShare()).isZero();assertThat(d.magicShare()).isZero();assertThat(d.trueDamageShare()).isZero();}
 @Test void deficiencySeverityRemainsWithinZeroAndOne(){assertThat(analyze(zero()).deficiencies().values()).allMatch(x->x.severity()>=0&&x.severity()<=1);}
 @Test void deficiencyExplanationMatchesEvaluation(){var a=analyze(zero());for(var e:a.explanation().deficiencies())assertThat(e.severity()).isEqualTo(a.deficiencies().get(e.deficiency()).severity());}
 @Test void analyzerConsumesNoRandom(){assertThat(Arrays.stream(TeamCompositionAnalyzer.class.getDeclaredFields())).noneMatch(f->java.util.Random.class.isAssignableFrom(f.getType()));}
 @Test void analyzerDoesNotMutateInputProfiles(){var f=f();var m=new LinkedHashMap<>(f.profiles());var before=Map.copyOf(m);analyze(new SyntheticTeamCompositionFixtures.FixtureCase("x","x",f.lineup(),m));assertThat(m).isEqualTo(before);}
 @Test void analyzerDoesNotMutateLineup(){var f=f();var before=f.lineup();analyze(f);assertThat(f.lineup()).isEqualTo(before);}
 @Test void analyzerHasNoStaticMutableState(){assertThat(Arrays.stream(TeamCompositionAnalyzer.class.getDeclaredFields())).noneMatch(x->Modifier.isStatic(x.getModifiers())&&!Modifier.isFinal(x.getModifiers()));}
 @Test void analysisIsExactForSameInput(){var f=ranked();assertThat(analyze(f)).isEqualTo(analyze(f));}
 @Test void permutationOfLineupMapProducesExactAnalysis(){var f=ranked();var a=analyze(f);var b=new TeamCompositionAnalyzer().analyze(new TeamCompositionLineup(reverse(f.lineup().championsByPosition())),f.profiles());assertThat(b).isEqualTo(a);}
 @Test void compositionRuntimeHasExplicitModeBoundary()throws Exception{String s=Files.readString(Path.of("src/main/java/com/lolfm/simulator/MatchSimulator.java"));assertThat(s).contains("CompositionRuntimeState").contains("teamCompositionGameplayMode").contains("validateCompositionModeBeforeMatch");}
 @Test void compositionFoundationDoesNotChangeCombatScore()throws Exception{assertNoComposition("src/main/java/com/lolfm/champion/DynamicCombatScoreEvaluator.java");}
 @Test void compositionFoundationDoesNotChangeObjectiveScore()throws Exception{for(Path p:Files.walk(Path.of("src/main/java/com/lolfm/simulator")).filter(x->x.getFileName().toString().startsWith("Objective")&&x.toString().endsWith(".java")).toList())assertThat(Files.readString(p)).doesNotContain("TeamComposition");}
 @Test void compositionFoundationDoesNotChangePushScore()throws Exception{for(Path p:Files.walk(Path.of("src/main/java/com/lolfm/simulator")).filter(x->x.getFileName().toString().startsWith("Push")&&x.toString().endsWith(".java")).toList())assertThat(Files.readString(p)).doesNotContain("TeamComposition");}
 @Test void productionMatchupDefaultRemainsGeometricV2(){assertThat(SimulationOptions.productionDefaults().championMatchupMode()).isEqualTo(ChampionMatchupMode.GEOMETRIC_V2);}
 @Test void explicitMatchupOffRollbackStillWorks(){var e=new ChampionMatchupEvaluator(ChampionRoleMatchupProfileCatalog.production());var k=new ChampionRoleKey(new ChampionId("unsupported"),Position.TOP);assertThat(e.evaluate(k,k,com.lolfm.simulator.ProgressionCombatContext.LANE_COMBAT,ChampionMatchupMode.OFF).finalEdge()).isZero();}
 @Test void apiSchemaIsUnchanged()throws Exception{for(Path p:Files.walk(Path.of("src/main/java/com/lolfm/dto")).filter(Files::isRegularFile).toList())assertThat(Files.readString(p)).doesNotContain("TeamComposition");}
 @Test void frontendFilesAreUnchanged()throws Exception{assertThat(FrontendTextSourceScanner.filesContaining(Path.of("../frontend/src"),"TeamComposition")).isEmpty();}
 @Test void auditRunsNoMatchSimulation()throws Exception{String s=Files.readString(Path.of("src/test/java/com/lolfm/composition/TeamCompositionFoundationAudit.java"));assertThat(s).doesNotContain("MatchSimulator","simulate(");}
 @Test void verdictIsComputedNotHardcoded()throws Exception{String s=Files.readString(Path.of("src/test/java/com/lolfm/composition/TeamCompositionFoundationAudit.java"));assertThat(s).doesNotContain("summary.put(\"verdict\",\"READY_FOR_PHASE_13D2\")");}
 private void assertBadCapability(int v){var f=f();var k=f.lineup().championsByPosition().get(Position.TOP);var m=SyntheticTeamCompositionFixtures.values(10);m.put(CompositionCapability.ENGAGE,v);assertThatThrownBy(()->new ChampionCompositionProfile(k,m,new DamageChannelProfile(0,0,0))).isInstanceOf(IllegalArgumentException.class);}
 private void assertCoverage(CompositionCapability c,double expected){assertThat(coverage(values(20,16,12,8,4),c)).isCloseTo(expected,within(1e-12));}
 private double coverage(int[]raw,CompositionCapability c){return analyze(make(raw,c)).coverage().capability(c).coverage();}
 private SyntheticTeamCompositionFixtures.FixtureCase make(int[]raw,CompositionCapability c){var f=f();LinkedHashMap<ChampionRoleKey,ChampionCompositionProfile>p=new LinkedHashMap<>();int i=0;for(var k:f.lineup().championsByPosition().values()){var m=SyntheticTeamCompositionFixtures.values(0);m.put(c,raw[i++]);p.put(k,new ChampionCompositionProfile(k,m,new DamageChannelProfile(0,0,0)));}return new SyntheticTeamCompositionFixtures.FixtureCase("made","made",f.lineup(),Map.copyOf(p));}
 private int[]values(int...v){return v;}
 private SyntheticTeamCompositionFixtures.FixtureCase f(){return SyntheticTeamCompositionFixtures.cases().stream().filter(x->x.caseId().equals("neutral")).findFirst().orElseThrow();}
 private SyntheticTeamCompositionFixtures.FixtureCase zero(){return SyntheticTeamCompositionFixtures.build("zero-test","zero",0,Map.of(),new DamageChannelProfile(0,0,0));}
 private SyntheticTeamCompositionFixtures.FixtureCase ranked(){var f=f();LinkedHashMap<ChampionRoleKey,ChampionCompositionProfile>p=new LinkedHashMap<>();int[]r={20,16,12,8,4};int i=0;for(var k:f.lineup().championsByPosition().values()){var m=SyntheticTeamCompositionFixtures.values(r[i++]);p.put(k,new ChampionCompositionProfile(k,m,new DamageChannelProfile(1,1,0)));}return new SyntheticTeamCompositionFixtures.FixtureCase("ranked","ranked",f.lineup(),Map.copyOf(p));}
 private TeamCompositionAnalysis customSame(CompositionCapability...cs){EnumMap<Position,Map<CompositionCapability,Integer>>o=new EnumMap<>(Position.class);Map<CompositionCapability,Integer>m=new EnumMap<>(CompositionCapability.class);for(var c:cs)m.put(c,20);o.put(Position.TOP,m);return analyze(SyntheticTeamCompositionFixtures.build("same","same",0,o,new DamageChannelProfile(0,0,0)));}
 private TeamCompositionAnalysis caseAnalysis(String id){return analyze(SyntheticTeamCompositionFixtures.cases().stream().filter(x->x.caseId().equals(id)).findFirst().orElseThrow());}
 private TeamCompositionAnalysis analyze(SyntheticTeamCompositionFixtures.FixtureCase f){return new TeamCompositionAnalyzer().analyze(f.lineup(),f.profiles());}
 private void assertPresent(String id,CompositionDeficiency d){assertThat(caseAnalysis(id).deficiencies().get(d).present()).isTrue();}
 private Map<Position,ChampionRoleKey>reverse(Map<Position,ChampionRoleKey>m){List<Map.Entry<Position,ChampionRoleKey>>x=new ArrayList<>(m.entrySet());Collections.reverse(x);LinkedHashMap<Position,ChampionRoleKey>r=new LinkedHashMap<>();x.forEach(e->r.put(e.getKey(),e.getValue()));return r;}
 private void assertNoComposition(String p)throws Exception{assertThat(Files.readString(Path.of(p))).doesNotContain("TeamComposition");}
}
