import type { ChampionViewModel, Position } from './realMatch.types';

const DDRAGON_VERSION = '16.15.1';

// backend champion-pool-full-173-2026-08-v1.json의 읽기 전용 프런트 fixture.
// API 연결 전까지 같은 챔피언 ID/한글명/주 포지션/에셋 ID를 유지한다.
const championSeed: readonly [string, string, Position, string][] = [
  ['renekton', '레넥톤', 'TOP', 'Renekton'],
  ['ornn', '오른', 'TOP', 'Ornn'],
  ['jax', '잭스', 'TOP', 'Jax'],
  ['gwen', '그웬', 'TOP', 'Gwen'],
  ['kennen', '케넨', 'TOP', 'Kennen'],
  ['ksante', '크산테', 'TOP', 'KSante'],
  ['lee-sin', '리 신', 'JUNGLE', 'LeeSin'],
  ['sejuani', '세주아니', 'JUNGLE', 'Sejuani'],
  ['vi', '바이', 'JUNGLE', 'Vi'],
  ['nidalee', '니달리', 'JUNGLE', 'Nidalee'],
  ['viego', '비에고', 'JUNGLE', 'Viego'],
  ['maokai', '마오카이', 'JUNGLE', 'Maokai'],
  ['azir', '아지르', 'MID', 'Azir'],
  ['orianna', '오리아나', 'MID', 'Orianna'],
  ['ahri', '아리', 'MID', 'Ahri'],
  ['leblanc', '르블랑', 'MID', 'Leblanc'],
  ['sylas', '사일러스', 'MID', 'Sylas'],
  ['viktor', '빅토르', 'MID', 'Viktor'],
  ['jinx', '징크스', 'ADC', 'Jinx'],
  ['lucian', '루시안', 'ADC', 'Lucian'],
  ['ezreal', '이즈리얼', 'ADC', 'Ezreal'],
  ['kaisa', '카이사', 'ADC', 'Kaisa'],
  ['aphelios', '아펠리오스', 'ADC', 'Aphelios'],
  ['varus', '바루스', 'ADC', 'Varus'],
  ['nautilus', '노틸러스', 'SUPPORT', 'Nautilus'],
  ['rakan', '라칸', 'SUPPORT', 'Rakan'],
  ['lulu', '룰루', 'SUPPORT', 'Lulu'],
  ['braum', '브라움', 'SUPPORT', 'Braum'],
  ['renata-glasc', '레나타 글라스크', 'SUPPORT', 'Renata'],
  ['bard', '바드', 'SUPPORT', 'Bard'],
  ['aatrox', '아트록스', 'TOP', 'Aatrox'],
  ['akali', '아칼리', 'MID', 'Akali'],
  ['akshan', '아크샨', 'MID', 'Akshan'],
  ['alistar', '알리스타', 'SUPPORT', 'Alistar'],
  ['ambessa', '암베사', 'TOP', 'Ambessa'],
  ['amumu', '아무무', 'JUNGLE', 'Amumu'],
  ['anivia', '애니비아', 'MID', 'Anivia'],
  ['annie', '애니', 'MID', 'Annie'],
  ['ashe', '애쉬', 'ADC', 'Ashe'],
  ['aurelion-sol', '아우렐리온 솔', 'MID', 'AurelionSol'],
  ['aurora', '오로라', 'MID', 'Aurora'],
  ['belveth', '벨베스', 'JUNGLE', 'Belveth'],
  ['blitzcrank', '블리츠크랭크', 'SUPPORT', 'Blitzcrank'],
  ['brand', '브랜드', 'JUNGLE', 'Brand'],
  ['briar', '브라이어', 'JUNGLE', 'Briar'],
  ['caitlyn', '케이틀린', 'ADC', 'Caitlyn'],
  ['camille', '카밀', 'SUPPORT', 'Camille'],
  ['cassiopeia', '카시오페아', 'MID', 'Cassiopeia'],
  ['chogath', '초가스', 'TOP', 'Chogath'],
  ['corki', '코르키', 'ADC', 'Corki'],
  ['darius', '다리우스', 'TOP', 'Darius'],
  ['diana', '다이애나', 'JUNGLE', 'Diana'],
  ['dr-mundo', '문도 박사', 'TOP', 'DrMundo'],
  ['draven', '드레이븐', 'ADC', 'Draven'],
  ['ekko', '에코', 'MID', 'Ekko'],
  ['elise', '엘리스', 'JUNGLE', 'Elise'],
  ['evelynn', '이블린', 'JUNGLE', 'Evelynn'],
  ['fiddlesticks', '피들스틱', 'JUNGLE', 'Fiddlesticks'],
  ['fiora', '피오라', 'TOP', 'Fiora'],
  ['fizz', '피즈', 'MID', 'Fizz'],
  ['galio', '갈리오', 'MID', 'Galio'],
  ['gangplank', '갱플랭크', 'TOP', 'Gangplank'],
  ['garen', '가렌', 'TOP', 'Garen'],
  ['gnar', '나르', 'TOP', 'Gnar'],
  ['gragas', '그라가스', 'TOP', 'Gragas'],
  ['graves', '그레이브즈', 'JUNGLE', 'Graves'],
  ['hecarim', '헤카림', 'JUNGLE', 'Hecarim'],
  ['heimerdinger', '하이머딩거', 'SUPPORT', 'Heimerdinger'],
  ['hwei', '흐웨이', 'MID', 'Hwei'],
  ['illaoi', '일라오이', 'TOP', 'Illaoi'],
  ['irelia', '이렐리아', 'TOP', 'Irelia'],
  ['ivern', '아이번', 'JUNGLE', 'Ivern'],
  ['janna', '잔나', 'SUPPORT', 'Janna'],
  ['jarvan-iv', '자르반 4세', 'JUNGLE', 'JarvanIV'],
  ['jayce', '제이스', 'TOP', 'Jayce'],
  ['jhin', '진', 'ADC', 'Jhin'],
  ['kalista', '칼리스타', 'ADC', 'Kalista'],
  ['karma', '카르마', 'SUPPORT', 'Karma'],
  ['karthus', '카서스', 'JUNGLE', 'Karthus'],
  ['kassadin', '카사딘', 'MID', 'Kassadin'],
  ['katarina', '카타리나', 'MID', 'Katarina'],
  ['kayle', '케일', 'TOP', 'Kayle'],
  ['kayn', '케인', 'JUNGLE', 'Kayn'],
  ['khazix', '카직스', 'JUNGLE', 'Khazix'],
  ['kindred', '킨드레드', 'JUNGLE', 'Kindred'],
  ['kled', '클레드', 'TOP', 'Kled'],
  ['kogmaw', '코그모', 'ADC', 'KogMaw'],
  ['leona', '레오나', 'SUPPORT', 'Leona'],
  ['lillia', '릴리아', 'JUNGLE', 'Lillia'],
  ['lissandra', '리산드라', 'MID', 'Lissandra'],
  ['locke', '로크', 'MID', 'Locke'],
  ['lux', '럭스', 'SUPPORT', 'Lux'],
  ['malphite', '말파이트', 'TOP', 'Malphite'],
  ['malzahar', '말자하', 'MID', 'Malzahar'],
  ['master-yi', '마스터 이', 'JUNGLE', 'MasterYi'],
  ['mel', '멜', 'MID', 'Mel'],
  ['milio', '밀리오', 'SUPPORT', 'Milio'],
  ['miss-fortune', '미스 포츈', 'ADC', 'MissFortune'],
  ['mordekaiser', '모데카이저', 'TOP', 'Mordekaiser'],
  ['morgana', '모르가나', 'MID', 'Morgana'],
  ['naafiri', '나피리', 'JUNGLE', 'Naafiri'],
  ['nami', '나미', 'SUPPORT', 'Nami'],
  ['nasus', '나서스', 'TOP', 'Nasus'],
  ['neeko', '니코', 'SUPPORT', 'Neeko'],
  ['nilah', '닐라', 'ADC', 'Nilah'],
  ['nocturne', '녹턴', 'JUNGLE', 'Nocturne'],
  ['nunu-willump', '누누와 윌럼프', 'JUNGLE', 'Nunu'],
  ['olaf', '올라프', 'TOP', 'Olaf'],
  ['pantheon', '판테온', 'JUNGLE', 'Pantheon'],
  ['poppy', '뽀삐', 'SUPPORT', 'Poppy'],
  ['pyke', '파이크', 'SUPPORT', 'Pyke'],
  ['qiyana', '키아나', 'JUNGLE', 'Qiyana'],
  ['quinn', '퀸', 'TOP', 'Quinn'],
  ['rammus', '람머스', 'JUNGLE', 'Rammus'],
  ['reksai', '렉사이', 'JUNGLE', 'RekSai'],
  ['rell', '렐', 'SUPPORT', 'Rell'],
  ['rengar', '렝가', 'JUNGLE', 'Rengar'],
  ['riven', '리븐', 'TOP', 'Riven'],
  ['rumble', '럼블', 'TOP', 'Rumble'],
  ['ryze', '라이즈', 'MID', 'Ryze'],
  ['samira', '사미라', 'ADC', 'Samira'],
  ['senna', '세나', 'ADC', 'Senna'],
  ['seraphine', '세라핀', 'SUPPORT', 'Seraphine'],
  ['sett', '세트', 'TOP', 'Sett'],
  ['shaco', '샤코', 'JUNGLE', 'Shaco'],
  ['shen', '쉔', 'TOP', 'Shen'],
  ['shyvana', '쉬바나', 'JUNGLE', 'Shyvana'],
  ['singed', '신지드', 'TOP', 'Singed'],
  ['sion', '사이온', 'TOP', 'Sion'],
  ['sivir', '시비르', 'ADC', 'Sivir'],
  ['skarner', '스카너', 'JUNGLE', 'Skarner'],
  ['smolder', '스몰더', 'ADC', 'Smolder'],
  ['sona', '소나', 'SUPPORT', 'Sona'],
  ['soraka', '소라카', 'SUPPORT', 'Soraka'],
  ['swain', '스웨인', 'MID', 'Swain'],
  ['syndra', '신드라', 'MID', 'Syndra'],
  ['tahm-kench', '탐 켄치', 'SUPPORT', 'TahmKench'],
  ['taliyah', '탈리야', 'MID', 'Taliyah'],
  ['talon', '탈론', 'JUNGLE', 'Talon'],
  ['taric', '타릭', 'SUPPORT', 'Taric'],
  ['teemo', '티모', 'TOP', 'Teemo'],
  ['thresh', '쓰레쉬', 'SUPPORT', 'Thresh'],
  ['tristana', '트리스타나', 'ADC', 'Tristana'],
  ['trundle', '트런들', 'JUNGLE', 'Trundle'],
  ['tryndamere', '트린다미어', 'TOP', 'Tryndamere'],
  ['twisted-fate', '트위스티드 페이트', 'MID', 'TwistedFate'],
  ['twitch', '트위치', 'ADC', 'Twitch'],
  ['udyr', '우디르', 'TOP', 'Udyr'],
  ['urgot', '우르곳', 'TOP', 'Urgot'],
  ['vayne', '베인', 'TOP', 'Vayne'],
  ['veigar', '베이가', 'MID', 'Veigar'],
  ['velkoz', '벨코즈', 'MID', 'Velkoz'],
  ['vex', '벡스', 'MID', 'Vex'],
  ['vladimir', '블라디미르', 'TOP', 'Vladimir'],
  ['volibear', '볼리베어', 'TOP', 'Volibear'],
  ['warwick', '워윅', 'JUNGLE', 'Warwick'],
  ['wukong', '오공', 'JUNGLE', 'MonkeyKing'],
  ['xayah', '자야', 'ADC', 'Xayah'],
  ['xerath', '제라스', 'MID', 'Xerath'],
  ['xin-zhao', '신 짜오', 'JUNGLE', 'XinZhao'],
  ['yasuo', '야스오', 'MID', 'Yasuo'],
  ['yone', '요네', 'MID', 'Yone'],
  ['yorick', '요릭', 'TOP', 'Yorick'],
  ['yunara', '유나라', 'ADC', 'Yunara'],
  ['yuumi', '유미', 'SUPPORT', 'Yuumi'],
  ['zaahen', '자헨', 'TOP', 'Zaahen'],
  ['zac', '자크', 'JUNGLE', 'Zac'],
  ['zed', '제드', 'MID', 'Zed'],
  ['zeri', '제리', 'ADC', 'Zeri'],
  ['ziggs', '직스', 'ADC', 'Ziggs'],
  ['zilean', '질리언', 'SUPPORT', 'Zilean'],
  ['zoe', '조이', 'MID', 'Zoe'],
  ['zyra', '자이라', 'JUNGLE', 'Zyra'],
];

export const realMatchChampions: readonly ChampionViewModel[] = championSeed.map(
  ([id, name, position, assetName]) => ({
    id,
    name,
    position,
    portraitUrl: `https://ddragon.leagueoflegends.com/cdn/${DDRAGON_VERSION}/img/champion/${assetName}.png`,
  }),
);
