package com.lolfm.champion;
import static org.assertj.core.api.Assertions.*;
import com.fasterxml.jackson.databind.ObjectMapper;import com.lolfm.composition.*;import com.lolfm.domain.Position;import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;import org.junit.jupiter.api.Test;
class ChampionResourceArchitectureTest{
 private final ObjectMapper mapper=new ObjectMapper();
 @Test void currentThirtyMatchupAndCompositionMigrateExactly(){var matchup=ChampionRoleMatchupProfileCatalog.production();for(var old:ThirtyChampionRoleProfiles.entries())assertThat(matchup.find(old.profile().roleKey()).orElseThrow()).isEqualTo(old.profile());var composition=ChampionCompositionProfileCatalog.loadDefault();assertThat(composition.profiles()).isEqualTo(ThirtyChampionCompositionProfiles.all());assertThat(composition.canonicalSerialization()).isEqualTo(ThirtyChampionCompositionProfiles.canonicalSerialization());assertThat(composition.profileHash()).isEqualTo("fbf58dc5be12f2b07c5dff7ded9e182d7829999d2255e65dbbd073ccde2688d1");}
 @Test void productionSourcesNoLongerReferenceHardcodedThirtyData()throws Exception{assertThat(Files.readString(Path.of("src/main/java/com/lolfm/champion/ChampionRoleMatchupProfileCatalog.java"))).doesNotContain("ThirtyChampionRoleProfiles.entries().stream()\n                .map");assertThat(Files.readString(Path.of("src/main/java/com/lolfm/composition/CompositionRuntimeState.java"))).doesNotContain("ThirtyChampionCompositionProfiles");}
 @Test void flexBaseAndRoleOverridesMaterializeIndependentCompleteProfiles()throws Exception{ChampionCatalog champions=new ChampionCatalog(mapper,bytes(catalog()));Map<String,Integer> traits=new LinkedHashMap<>();for(var t:ChampionMatchupTrait.values())traits.put(t.name(),10);Map<String,Integer> top=Map.of("BURST",20),jungle=Map.of("MOBILITY",19),support=Map.of("DISENGAGE",18);String matchup=mapper.writeValueAsString(Map.of("profileVersion","flex-candidate-v1","requiredChampionPoolVersion","flex-v1","championProfiles",List.of(Map.of("championId","flex","baseTraits",traits,"roleOverrides",List.of(Map.of("position","TOP","traits",top),Map.of("position","JUNGLE","traits",jungle),Map.of("position","SUPPORT","traits",support))))));var mc=ChampionMatchupProfileResourceLoader.load(mapper,champions,bytes(matchup),true);assertThat(mc.profiles()).hasSize(3);assertThat(mc.find(key(Position.TOP)).orElseThrow().trait(ChampionMatchupTrait.BURST)).isEqualTo(20);assertThat(mc.find(key(Position.JUNGLE)).orElseThrow().trait(ChampionMatchupTrait.BURST)).isEqualTo(10);Map<String,Integer> caps=new LinkedHashMap<>();for(var c:CompositionCapability.values())caps.put(c.name(),10);String composition=mapper.writeValueAsString(Map.of("profileVersion","flex-composition-v1","requiredChampionPoolVersion","flex-v1","championProfiles",List.of(Map.of("championId","flex","baseCapabilities",caps,"damageProfile",Map.of("physicalThreat",10,"magicThreat",10,"trueDamageThreat",0),"roleOverrides",List.of(Map.of("position","TOP","capabilities",Map.of("ENGAGE",20)),Map.of("position","JUNGLE","capabilities",Map.of("PICK",19)),Map.of("position","SUPPORT","capabilities",Map.of("PEEL",18)))))));var cc=ChampionCompositionProfileCatalog.load(mapper,champions,bytes(composition));assertThat(cc.profiles()).hasSize(3);assertThat(cc.profiles().get(key(Position.TOP)).capability(CompositionCapability.ENGAGE)).isEqualTo(20);assertThat(cc.profiles().get(key(Position.JUNGLE)).capability(CompositionCapability.ENGAGE)).isEqualTo(10);}
 @Test void unsupportedRoleOverrideIsRejected(){ChampionCatalog champions=new ChampionCatalog(mapper,bytes(catalog()));Map<String,Integer> traits=new LinkedHashMap<>();for(var t:ChampionMatchupTrait.values())traits.put(t.name(),10);String json;try{json=mapper.writeValueAsString(Map.of("profileVersion","flex-candidate-v1","requiredChampionPoolVersion","flex-v1","championProfiles",List.of(Map.of("championId","flex","baseTraits",traits,"roleOverrides",List.of(Map.of("position","MID","traits",Map.of("BURST",20)))))));}catch(Exception e){throw new RuntimeException(e);}assertThatThrownBy(()->ChampionMatchupProfileResourceLoader.load(mapper,champions,bytes(json),true)).hasMessageContaining("Unsupported matchup override");}
 @Test void explicitPowerAnchorsMaterializeWithoutChangingOldSchema()throws Exception{ChampionCatalog champions=new ChampionCatalog(mapper,bytes(catalog()));Map<String,Double> levels=new LinkedHashMap<>();for(int x:new int[]{1,6,11,16,18})levels.put(Integer.toString(x),0.0);Map<String,Double> items=new LinkedHashMap<>();for(var x:com.lolfm.simulator.ItemProgressStage.values())items.put(x.name(),0.0);Map<String,Double> contexts=new LinkedHashMap<>();for(var x:com.lolfm.simulator.ProgressionCombatContext.values())contexts.put(x.name(),0.0);Map<String,Object> profile=new LinkedHashMap<>();profile.put("championId","flex");profile.put("levelCurveId","BASE");profile.put("itemCurveId","BASE");profile.put("contexts",contexts);profile.put("tags",List.of());profile.put("levelAnchors",Map.of("1",0.5));profile.put("itemAnchors",Map.of("FULL_BUILD",0.4));String json=mapper.writeValueAsString(Map.of("profileVersion","power-v1","requiredChampionPoolVersion","flex-v1","levelCurves",Map.of("BASE",levels),"itemCurves",Map.of("BASE",items),"championProfiles",List.of(profile)));var power=new ChampionPowerProfileCatalog(mapper,champions,bytes(json)).get(new ChampionId("flex"));assertThat(power.levelCurve().valueAt(1)).isEqualTo(0.5);assertThat(power.itemModifiers().get(com.lolfm.simulator.ItemProgressStage.FULL_BUILD)).isEqualTo(0.4);}
 @Test void jungleClearFoundationIsCompleteDeterministicAndNeutral(){var catalog=ChampionJungleClearProfileCatalog.loadDefault();assertThat(catalog.profiles()).hasSize(6);var evaluator=new ChampionJungleClearEvaluator();for(var profile:catalog.profiles().values()){assertThat(profile.gameplayEnabled()).isFalse();assertThat(evaluator.evaluate(profile,0)).isEqualTo(1.0);assertThat(evaluator.evaluate(profile,3600)).isEqualTo(1.0);}}
 private ChampionRoleKey key(Position p){return new ChampionRoleKey(new ChampionId("flex"),p);}private InputStream bytes(String s){return new ByteArrayInputStream(s.getBytes(StandardCharsets.UTF_8));}private String catalog(){return "{\"championPoolVersion\":\"flex-v1\",\"championBalanceVersion\":\"flex-b1\",\"riotDataVersion\":\"test\",\"champions\":[{\"id\":\"flex\",\"displayNameKo\":\"플렉스\",\"displayNameEn\":\"Flex\",\"riotAssetId\":\"Flex\",\"primaryPosition\":\"TOP\",\"supportedPositions\":[\"TOP\",\"JUNGLE\",\"SUPPORT\"]}]}";}
}
