package com.lolfm.champion;

import static org.assertj.core.api.Assertions.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.lolfm.domain.*;
import com.lolfm.simulator.*;
import java.util.*;
import org.junit.jupiter.api.Test;

class DynamicStateOverrideAuditTest {
 private final ChampionCatalog champions=new ChampionCatalog(new ObjectMapper());
 private final ChampionPowerProfileCatalog profiles=new ChampionPowerProfileCatalog(new ObjectMapper(),champions);
 private final DynamicCombatScoreEvaluator scores=new DynamicCombatScoreEvaluator(profiles);
 private record Fixture(GameState state,PlayerState leblanc,PlayerState viktor,TeamState blue,TeamState red){}

 @Test void equalStateEarlyLeBlancHasChampionEdgeOverViktor(){Fixture f=fixture(attrs(15,15,15,15),attrs(15,15,15,15));grow(f.leblanc,1720,3500,f.blue);grow(f.viktor,1720,3500,f.red);var l=score(f.leblanc,"leblanc",ProgressionCombatContext.LANE_COMBAT);var v=score(f.viktor,"viktor",ProgressionCombatContext.LANE_COMBAT);assertThat(champion(l)).isGreaterThan(champion(v));}
 @Test void fedViktorCanOvertakeEarlyLeBlanc(){Fixture f=fixture(attrs(15,15,15,15),attrs(15,15,15,15));grow(f.leblanc,1720,1200,f.blue);grow(f.viktor,1720,1200,f.red);feedViktor(f);assertThat(f.viktor.getKills()).isPositive();assertThat(f.viktor.getAssists()).isPositive();assertThat(f.viktor.getGold()).isGreaterThan(f.leblanc.getGold());assertThat(f.viktor.getProgressionState().getProgressionEarnedGold()).isGreaterThan(f.leblanc.getProgressionState().getProgressionEarnedGold());assertThat(score(f.viktor,"viktor",ProgressionCombatContext.LANE_COMBAT).finalCombatScore()).isGreaterThan(score(f.leblanc,"leblanc",ProgressionCombatContext.LANE_COMBAT).finalCombatScore());}
 @Test void strongerPlayerViktorCanBeatWeakerPlayerLeBlancAtEqualState(){Fixture f=fixture(attrs(9,10,10,9),attrs(19,16,15,19));grow(f.leblanc,1720,3500,f.blue);grow(f.viktor,1720,3500,f.red);assertThat(score(f.viktor,"viktor",ProgressionCombatContext.LANE_COMBAT).finalCombatScore()).isGreaterThan(score(f.leblanc,"leblanc",ProgressionCombatContext.LANE_COMBAT).finalCombatScore());}
 @Test void championProfileDoesNotOverrideLargePlayerSkillGap(){Fixture f=fixture(attrs(5,5,5,5),attrs(20,20,20,20));grow(f.leblanc,1720,3500,f.blue);grow(f.viktor,1720,3500,f.red);assertThat(score(f.viktor,"viktor",ProgressionCombatContext.ROAM).finalCombatScore()).isGreaterThan(score(f.leblanc,"leblanc",ProgressionCombatContext.ROAM).finalCombatScore());}
 @Test void championProfileDoesNotOverrideLargeGoldGap(){Fixture f=fixture(attrs(15,15,15,15),attrs(15,15,15,15));grow(f.leblanc,1720,3500,f.blue);grow(f.viktor,1720,10500,f.red);assertThat(score(f.viktor,"viktor",ProgressionCombatContext.ROAM).finalCombatScore()).isGreaterThan(score(f.leblanc,"leblanc",ProgressionCombatContext.ROAM).finalCombatScore());}
 @Test void currentStateIsReevaluatedEveryCombat(){Fixture f=fixture(attrs(15,15,15,15),attrs(15,15,15,15));grow(f.viktor,1720,1200,f.red);var before=score(f.viktor,"viktor",ProgressionCombatContext.TEAMFIGHT);feedViktor(f);var after=score(f.viktor,"viktor",ProgressionCombatContext.TEAMFIGHT);assertThat(after.championBreakdown().level()).isGreaterThan(before.championBreakdown().level());assertThat(after.championBreakdown().itemStage().ordinal()).isGreaterThan(before.championBreakdown().itemStage().ordinal());assertThat(after.championLevelContribution()).isNotEqualTo(before.championLevelContribution());}
 @Test void contextSpecificStrengthCanRemainDespiteOverallLead(){Fixture f=fixture(attrs(15,15,15,15),attrs(15,15,15,15));grow(f.leblanc,1720,1200,f.blue);grow(f.viktor,1720,1200,f.red);feedViktor(f);var vt=score(f.viktor,"viktor",ProgressionCombatContext.TEAMFIGHT);var lt=score(f.leblanc,"leblanc",ProgressionCombatContext.TEAMFIGHT);var vr=score(f.viktor,"viktor",ProgressionCombatContext.ROAM);var lr=score(f.leblanc,"leblanc",ProgressionCombatContext.ROAM);assertThat(vt.finalCombatScore()).isGreaterThan(lt.finalCombatScore());assertThat(lr.championContextContribution()).isGreaterThan(vr.championContextContribution());}
 @Test void scoreBreakdownPrintsEveryIndependentContribution(){Fixture f=fixture(attrs(15,14,13,16),attrs(15,14,13,16));grow(f.leblanc,1720,3500,f.blue);var x=score(f.leblanc,"leblanc",ProgressionCombatContext.ROAM);assertThat(x.finalCombatScore()).isEqualTo(x.playerAttributeContribution()+x.currentGoldContribution()+x.commonLevelContribution()+x.commonItemContribution()+x.championLevelContribution()+x.championItemContribution()+x.championContextContribution());System.out.printf(Locale.ROOT,"DYNAMIC_BREAKDOWN attributes=%.3f currentGold=%.3f commonLevel=%.3f commonItem=%.3f championLevel=%.3f championItem=%.3f championContext=%.3f final=%.3f%n",x.playerAttributeContribution(),x.currentGoldContribution(),x.commonLevelContribution(),x.commonItemContribution(),x.championLevelContribution(),x.championItemContribution(),x.championContextContribution(),x.finalCombatScore());}

 private DynamicCombatScoreBreakdown score(PlayerState p,String id,ProgressionCombatContext c){return scores.evaluate(p,new ChampionId(id),c);}private double champion(DynamicCombatScoreBreakdown x){return x.championLevelContribution()+x.championItemContribution()+x.championContextContribution();}
 private Fixture fixture(PlayerAttributes blueMid,PlayerAttributes redMid){TeamState b=team("B",TeamSide.BLUE,blueMid),r=team("R",TeamSide.RED,redMid);var request=new ChampionSelectionRequest(new ChampionLineupRequest("ornn","vi","leblanc","lucian","lulu"),new ChampionLineupRequest("ksante","maokai","viktor","varus","bard"));var assignments=new ChampionSelectionValidator(champions).resolve(request);GameState s=new GameState(b,r,true,true,true,true,true,true,assignments);s.configureChampionPower(profiles,true);s.configureProgression(true,true);return new Fixture(s,b.playerAt(Position.MID),r.playerAt(Position.MID),b,r);}
 private TeamState team(String name,TeamSide side,PlayerAttributes mid){List<PlayerState>p=new ArrayList<>();for(Position position:Position.values())p.add(new PlayerState(side+"-"+position,position,position==Position.MID?mid:attrs(15,15,15,15),500));return new TeamState(name,p);}
 private static PlayerAttributes attrs(int m,int a,int f,int t){return new PlayerAttributes(m,a,f,t);}
 private static void grow(PlayerState p,int xp,int gold,TeamState team){p.getProgressionState().awardExperience(ExperienceSource.KILL,xp,1);new GoldAwardService().awardGold(team,p,gold,GoldSource.FARM,false,1);}
 private static void feedViktor(Fixture f){KillRewardResolver rewards=new KillRewardResolver();List<com.lolfm.domain.MatchEvent>events=new ArrayList<>();PlayerState victim=f.blue.playerAt(Position.TOP);for(int i=0;i<8;i++){victim.respawn();rewards.award(10+i,f.red,f.viktor,f.blue,victim,List.of(),1,false,0,events);}victim.respawn();PlayerState ally=f.red.playerAt(Position.TOP);rewards.award(30,f.red,ally,f.blue,victim,List.of(f.viktor),1,false,0,events);}
}
