package com.lolfm.draft;
public enum BanScoreComponent {
    OPPONENT_EXPECTED_PICK_VALUE, THREAT_TO_OUR_PLAN_PORTFOLIO, META_PRIORITY,
    OPPONENT_FLEX_VALUE, ROLE_POOL_COMPRESSION, PROTECTION_VALUE, OUR_LOST_PICK_OPPORTUNITY, OPPONENT_AVAILABLE_VALUE, OPPONENT_REPLACEMENT_VALUE, OPPONENT_PICK_PROBABILITY, OUR_NEXT_PICK_DISTANCE, OPPONENT_NEXT_PICK_DISTANCE
}
