package com.lolfm.draft;
public enum PickScoreComponent {
    META_PRIORITY, PLAYER_FIT, MATCHUP, COMPOSITION_FIT, COMPOSITION_RESPONSE,
    FLEXIBILITY, DENIAL, FUTURE_FEASIBILITY, EARLY_POWER, MID_POWER, LATE_POWER, JUNGLE_CLEAR, RESOURCE_RISK
}
