import { useMemo, useState } from 'react';
import type { LeagueFixtureViewDto, LeagueJobViewDto, LeagueSeasonViewDto } from './api/leagueApi.types';
import { FIXTURE_STATUS_COPY, LEAGUE_TEAMS, SEASON_STATUS_COPY } from './league.adapter';
import { LeagueFixturePanel } from './LeagueFixturePanel';
import { LeagueScheduleTable } from './LeagueScheduleTable';
import { LeagueStandingsTable } from './LeagueStandingsTable';

export function LeagueDashboard({ season, fixtures, jobs, pending, error, onRunRound, onPause, onResume, onCancel, onRefresh, onNewSeason, onBackToCareer, onPlayerSeries }: {
  season: LeagueSeasonViewDto; fixtures: readonly LeagueFixtureViewDto[]; jobs: ReadonlyMap<string, LeagueJobViewDto>; pending: string | null; error: string | null;
  onRunRound: () => void; onPause: () => void; onResume: () => void; onCancel: (target: HTMLElement) => void; onRefresh: () => void; onNewSeason: () => void; onPlayerSeries: (fixture: LeagueFixtureViewDto) => void;
  onBackToCareer?: () => void;
}) {
  const [view, setView] = useState<'OVERVIEW' | 'SCHEDULE'>('OVERVIEW'); const [round, setRound] = useState('CURRENT'); const [team, setTeam] = useState('ALL'); const [mode, setMode] = useState('ALL'); const [status, setStatus] = useState('ALL');
  const currentFixtures = fixtures.filter((fixture) => fixture.roundNumber === season.currentRound);
  const filtered = useMemo(() => fixtures.filter((fixture) => (round === 'ALL' || (round === 'CURRENT' ? fixture.roundNumber === season.currentRound : fixture.roundNumber === Number(round))) && (team === 'ALL' || fixture.firstTeamCode === team || fixture.secondTeamCode === team) && (mode === 'ALL' || fixture.executionMode === mode) && (status === 'ALL' || fixture.lifecycleStatus === status)), [fixtures, mode, round, season.currentRound, status, team]);
  const [selectedId, setSelectedId] = useState<string | null>(season.playableManagedFixture?.fixtureId ?? currentFixtures[0]?.fixtureId ?? null);
  const selected = fixtures.find((fixture) => fixture.fixtureId === selectedId) ?? filtered[0] ?? null; const selectedJob = selected?.jobId ? jobs.get(selected.jobId) ?? null : null;
  const commands = new Set(season.allowedCommands); const activeJobs = [...jobs.values()].filter((job) => !['COMPLETED', 'BLOCKED', 'CANCELLED'].includes(job.lifecycleStatus));
  const completedInRound = currentFixtures.filter((fixture) => fixture.lifecycleStatus === 'COMPLETED').length;
  return <main className="lg-dashboard" aria-labelledby="lg-season-title" aria-busy={pending !== null}>
    <header className="lg-page-head lg-season-head"><div><span>{onBackToCareer ? 'CAREER / AI 리그' : 'AI 리그 / 정규 시즌'}</span><h1 id="lg-season-title">{season.managedTeamCode ? `${season.managedTeamCode} 감독 시즌` : '전체 관전 시즌'}</h1></div><div className="lg-season-head__meta"><span className={`lg-season-state is-${season.lifecycleStatus.toLowerCase()}`}>{SEASON_STATUS_COPY[season.lifecycleStatus]}</span><b>ROUND {season.currentRound} / 18</b><small>{season.seasonMode === 'HYBRID_MANAGER' ? 'HYBRID · 18 PLAYER / 72 AUTO' : 'SPECTATOR · 90 AUTO'}</small></div><div className="lg-head-actions">{onBackToCareer ? <button type="button" className="lg-career-return" onClick={onBackToCareer}>Career로 돌아가기</button> : null}<button type="button" onClick={onRefresh} disabled={pending !== null}>새로고침</button>{commands.has('PAUSE_SEASON') ? <button type="button" onClick={onPause} disabled={pending !== null}>일시 정지</button> : null}{commands.has('RESUME_SEASON') ? <button type="button" onClick={onResume} disabled={pending !== null}>시즌 재개</button> : null}{commands.has('CANCEL_SEASON') ? <button type="button" className="is-danger" disabled={pending !== null} onClick={(event) => onCancel(event.currentTarget)}>시즌 취소</button> : null}{!onBackToCareer && ['COMPLETED', 'CANCELLED', 'BLOCKED'].includes(season.lifecycleStatus) ? <button type="button" onClick={onNewSeason}>새 시즌</button> : null}</div></header>
    <nav className="lg-view-tabs" aria-label="AI 리그 화면"><button type="button" aria-current={view === 'OVERVIEW' ? 'page' : undefined} onClick={() => setView('OVERVIEW')}>시즌 개요</button><button type="button" aria-current={view === 'SCHEDULE' ? 'page' : undefined} onClick={() => setView('SCHEDULE')}>전체 일정 <span>90</span></button><div><code>{season.seasonId.slice(0, 22)}…</code></div></nav>
    {error ? <div className="lg-error-banner" role="alert"><strong>요청을 완료하지 못했습니다</strong><span>{error}</span></div> : null}
    {activeJobs.length > 0 ? <section className="lg-job-progress" role="status" aria-live="polite"><span className="lg-spinner" aria-hidden="true" /><div><strong>Round {season.currentRound} 자동 경기 계산 중</strong><p>{completedInRound} / {currentFixtures.length} 경기 완료 · {activeJobs.length}개 작업 확인 중</p></div><div className="lg-progress-track"><i style={{ width: `${Math.round((completedInRound / Math.max(1, currentFixtures.length)) * 100)}%` }} /></div></section> : null}
    {view === 'OVERVIEW' ? <div className="lg-overview-grid">
      <section className="lg-round-control"><header><div><span>CURRENT ROUND</span><h2>Round {season.currentRound}</h2></div><strong>{completedInRound}<i>/</i>{currentFixtures.length}</strong></header><div className="lg-round-fixtures">{currentFixtures.map((fixture) => <button type="button" key={fixture.fixtureId} className={selected?.fixtureId === fixture.fixtureId ? 'is-selected' : ''} onClick={() => setSelectedId(fixture.fixtureId)}><span>{fixture.executionMode === 'PLAYER_CONTROLLED' ? 'PLAYER' : 'AUTO'}</span><b>{fixture.firstTeamCode}<i>vs</i>{fixture.secondTeamCode}</b><small><span className={`lg-status-dot is-${fixture.lifecycleStatus.toLowerCase()}`} />{FIXTURE_STATUS_COPY[fixture.lifecycleStatus]}</small></button>)}</div>{commands.has('RUN_CURRENT_ROUND_AUTO_FIXTURES') ? <button className="lg-primary lg-round-action" type="button" onClick={onRunRound} disabled={pending !== null}>{pending === 'RUN_ROUND' ? <><span className="lg-spinner" aria-hidden="true" />작업 상태 확인 중</> : '현재 라운드 Auto 경기 실행'}</button> : null}{season.playableManagedFixture ? <p className="lg-player-callout"><b>{season.playableManagedFixture.firstTeamCode} vs {season.playableManagedFixture.secondTeamCode}</b><span>관리 팀 Player Series가 준비되어 있습니다.</span><button type="button" onClick={() => onPlayerSeries(season.playableManagedFixture!)} disabled={pending !== null}>Series 열기</button></p> : null}</section>
      <LeagueStandingsTable rows={season.standings} managedTeamCode={season.managedTeamCode} />
      <LeagueFixturePanel fixture={selected} job={selectedJob} pending={pending !== null} playerActionable={selected?.fixtureId === season.playableManagedFixture?.fixtureId} onPlayerSeries={onPlayerSeries} />
    </div> : <div className="lg-schedule-view"><section className="lg-schedule-main"><div className="lg-filters"><label><span>라운드</span><select value={round} onChange={(event) => setRound(event.target.value)}><option value="CURRENT">현재 Round {season.currentRound}</option><option value="ALL">전체 라운드</option>{Array.from({ length: 18 }, (_, index) => <option value={index + 1} key={index + 1}>Round {index + 1}</option>)}</select></label><label><span>팀</span><select value={team} onChange={(event) => setTeam(event.target.value)}><option value="ALL">전체 팀</option>{LEAGUE_TEAMS.map((item) => <option key={item.code} value={item.code}>{item.code}</option>)}</select></label><label><span>모드</span><select value={mode} onChange={(event) => setMode(event.target.value)}><option value="ALL">전체 모드</option><option value="FULL_AUTO">AUTO</option><option value="PLAYER_CONTROLLED">PLAYER</option></select></label><label><span>상태</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">전체 상태</option>{Object.entries(FIXTURE_STATUS_COPY).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><p><b>{filtered.length}</b>개 경기</p></div><LeagueScheduleTable fixtures={filtered} selectedId={selected?.fixtureId ?? null} onSelect={(fixture) => setSelectedId(fixture.fixtureId)} /></section><LeagueFixturePanel fixture={selected} job={selectedJob} pending={pending !== null} playerActionable={selected?.fixtureId === season.playableManagedFixture?.fixtureId} onPlayerSeries={onPlayerSeries} /></div>}
  </main>;
}
