import type { InboxMessage } from './inbox.types';

export const inboxMessages: readonly InboxMessage[] = [
  {
    id: 'tactics-report',
    tab: 'team',
    date: '2026년 8월 24일',
    sender: 'Han 코치',
    initials: 'HC',
    role: '수석 코치',
    department: 'Northvale 코칭스태프',
    subject: '코치의 다음 경기 전술 보고서',
    time: '오전 9:10',
    category: '전술',
    tone: 'violet',
    important: true,
    initiallyUnread: false,
    preview: 'Coastline전 초반 오브젝트 운영과 바텀 우선순위',
    summary: 'Coastline전 준비를 위해 초반 오브젝트 운영과 바텀 라인 우선순위를 정리했습니다.',
    body: [
      { text: '감독님, 최근 5경기 데이터를 기준으로 Coastline의 초반 운영을 분석했습니다. 상대는 ', emphasis: '첫 드래곤 전 바텀 주도권', suffix: '을 확보했을 때 승률이 크게 올라갑니다.' },
      { text: '우리 팀은 Lumen의 3레벨 동선을 바텀 쪽으로 조정하고, Cipher가 첫 귀환 전 미드 웨이브를 빠르게 정리하는 구성이 가장 안정적입니다. Anchor의 컨디션을 고려해 교전 콜은 짧고 명확하게 유지하는 편이 좋습니다.' },
    ],
    metrics: [
      { label: '상대 첫 드래곤', value: '71%' },
      { label: '10분 골드 차이', value: '+420' },
      { label: '로스터 준비도', value: '82%' },
      { label: '예상 경기 시간', value: '31분' },
    ],
    contextTitle: '전술 포인트',
    rows: [
      { label: '바텀 주도권', current: '중간', recommendation: '높음', note: '첫 드래곤 연결' },
      { label: '정글 동선', current: '상체 시작', recommendation: '바텀 전환', note: '3레벨 갱킹 대비' },
      { label: '전령 타이밍', current: '오전 9:20', recommendation: '오전 8:45', note: '미드 우선권 필요' },
      { label: '밴 우선순위', current: '2순위', recommendation: '1순위', note: '원거리 이니시에이터' },
    ],
    attachment: { name: 'Coastline_전술_브리핑', meta: '분석 보고서 · 8쪽 · 코칭스태프 공유' },
    actions: ['보고서 보기', '전술 화면으로 이동', '확인 완료'],
  },
  {
    id: 'playtime-request',
    tab: 'team',
    date: '2026년 8월 24일',
    sender: 'Rook',
    initials: 'RK',
    role: '탑 라이너',
    department: 'Northvale 선수단',
    subject: '선수의 출전 시간 관련 요청',
    time: '오전 8:34',
    category: '선수단',
    tone: 'teal',
    important: true,
    initiallyUnread: true,
    preview: '최근 로테이션과 다음 경기 출전 계획 상담 요청',
    summary: 'Rook이 최근 로테이션과 다음 경기 출전 계획에 대해 면담을 요청했습니다.',
    body: [
      { text: '감독님, 최근 두 경기에서 교체 출전한 이유와 다음 주 라인업 계획을 알고 싶습니다. 현재 컨디션은 좋고 추가 훈련도 가능합니다.' },
      { text: '선수단 사기와 역할 만족도에 영향을 줄 수 있으므로 ', emphasis: '오늘 훈련 전 짧은 면담', suffix: '을 권장합니다.' },
    ],
    metrics: [
      { label: '최근 출전', value: '2 / 5' },
      { label: '폼', value: '82' },
      { label: '사기', value: '보통' },
      { label: '계약 잔여', value: '18주' },
    ],
    contextTitle: '선수 상태',
    rows: [
      { label: '훈련 참여', current: '정상', recommendation: '유지', note: '피로 18' },
      { label: '역할 만족도', current: '낮음', recommendation: '보통', note: '면담 권장' },
      { label: '라인 단계', current: '+3.1 CS', recommendation: '유지', note: '안정적' },
      { label: '팀 기여', current: '74', recommendation: '78', note: '콜 참여 확대' },
    ],
    attachment: { name: 'Rook_출전_기록', meta: '선수 관리 기록 · 최근 5경기' },
    actions: ['선수와 대화', '일정 확인', '확인 완료'],
  },
  {
    id: 'prospect-report',
    tab: 'transfer',
    date: '2026년 8월 24일',
    sender: 'Park 스카우터',
    initials: 'PS',
    role: '수석 스카우터',
    department: 'Northvale 스카우팅팀',
    subject: '스카우터의 유망주 보고서',
    time: '오전 7:50',
    category: '스카우팅',
    tone: 'violet',
    important: false,
    initiallyUnread: true,
    preview: '챌린저스 정글 유망주 3명 최종 관찰 결과',
    summary: '챌린저스 정글 유망주 3명의 최종 관찰 결과와 영입 우선순위가 정리되었습니다.',
    body: [
      { text: '6주간의 관찰을 마쳤습니다. 세 선수 모두 성장 여지가 있지만 즉시 전력감은 한 명입니다.' },
      { text: '예산과 로스터 슬롯을 고려하면 ', emphasis: 'Juno', suffix: '를 우선 협상 대상으로 추천합니다.' },
    ],
    metrics: [
      { label: '관찰 선수', value: '3명' },
      { label: '즉시 전력', value: '1명' },
      { label: '예상 비용', value: '4.8만' },
      { label: '보고 신뢰도', value: '높음' },
    ],
    contextTitle: '후보 비교',
    rows: [
      { label: 'Juno', current: '78', recommendation: '83', note: '교전 설계 강점' },
      { label: 'Marl', current: '72', recommendation: '80', note: '성장형 정글러' },
      { label: 'Peak', current: '74', recommendation: '77', note: '안정적 운영' },
      { label: '평균 나이', current: '19.3', recommendation: '—', note: '개발 계약 가능' },
    ],
    attachment: { name: '정글_유망주_최종보고', meta: '스카우팅 보고서 · 12쪽' },
    actions: ['보고서 보기', '이적 시장 확인', '확인 완료'],
  },
  {
    id: 'injury-alert',
    tab: 'team',
    date: '2026년 8월 24일',
    sender: '의무팀',
    initials: 'MD',
    role: '퍼포먼스 매니저',
    department: 'Northvale 의무팀',
    subject: '선수 부상 및 컨디션 알림',
    time: '오전 7:18',
    category: '컨디션',
    tone: 'red',
    important: true,
    initiallyUnread: true,
    preview: 'Anchor 손목 피로 누적, 훈련 강도 조정 필요',
    summary: 'Anchor의 손목 피로가 누적되어 오늘 훈련 강도 조정과 상태 확인이 필요합니다.',
    body: [
      { text: '오전 검사에서 오른쪽 손목 피로 지표가 기준치를 넘었습니다. 통증은 경미하지만 반복 입력 훈련을 줄여야 합니다.' },
      { text: '경기 출전은 가능하나 ', emphasis: '스크림 2세트 제한', suffix: '과 경기 전 재검사를 권장합니다.' },
    ],
    metrics: [
      { label: '통증 지수', value: '3 / 10' },
      { label: '피로 위험', value: '중간' },
      { label: '출전 가능', value: '가능' },
      { label: '재검사', value: '오후 4:30' },
    ],
    contextTitle: '컨디션 계획',
    rows: [
      { label: '개인 훈련', current: '60분', recommendation: '20분', note: '반복 입력 제한' },
      { label: '스크림', current: '4세트', recommendation: '2세트', note: '세트 간 휴식' },
      { label: '회복 세션', current: '없음', recommendation: '30분', note: '손목 안정화' },
      { label: '경기 전 검사', current: '미정', recommendation: '오후 4:30', note: '출전 최종 확인' },
    ],
    attachment: { name: 'Anchor_컨디션_기록', meta: '의무 기록 · 제한 열람' },
    actions: ['선수와 대화', '일정 확인', '확인 완료'],
  },
  {
    id: 'contract-expiry',
    tab: 'transfer',
    date: '2026년 8월 23일',
    sender: '운영팀',
    initials: 'OP',
    role: '선수 운영 매니저',
    department: 'Northvale 운영팀',
    subject: '계약 만료 예정 선수',
    time: '오후 6:20',
    category: '계약',
    tone: 'amber',
    important: true,
    initiallyUnread: false,
    preview: '30일 이내 계약 만료 선수 2명 협상 필요',
    summary: '30일 이내 계약이 만료되는 선수 2명의 재계약 방향을 결정해야 합니다.',
    body: [
      { text: 'Cipher와 연습생 Nova의 계약 종료일이 다가옵니다. Cipher 측은 주전 보장 조항을 포함한 협상을 원합니다.' },
      { text: '이적 시장 개장 전 ', emphasis: '우선 협상 범위', suffix: '를 정해 주시면 에이전트와 일정을 잡겠습니다.' },
    ],
    metrics: [
      { label: '대상 선수', value: '2명' },
      { label: '남은 기간', value: '28일' },
      { label: '예상 인상률', value: '12%' },
      { label: '협상 마감', value: '2026년 9월 3일' },
    ],
    contextTitle: '계약 현황',
    rows: [
      { label: 'Cipher', current: '주전', recommendation: '재계약', note: '역할 조항 요청' },
      { label: 'Nova', current: '연습생', recommendation: '연장 검토', note: '육성 슬롯' },
      { label: '연봉 여유', current: '8.4만', recommendation: '6.9만', note: '보너스 제외' },
      { label: '협상 우선도', current: '높음', recommendation: '즉시', note: '이적 시장 전' },
    ],
    attachment: { name: '계약_만료_대상', meta: '계약 목록 · 2명' },
    actions: ['보고서 보기', '이적 시장 확인', '확인 완료'],
  },
  {
    id: 'league-notice',
    tab: 'league',
    date: '2026년 8월 23일',
    sender: '리그 사무국',
    initials: 'LG',
    role: '경기 운영 담당',
    department: 'Spring Split 사무국',
    subject: '리그 사무국 공지',
    time: '오후 3:05',
    category: '리그',
    tone: 'violet',
    important: false,
    initiallyUnread: false,
    preview: '26.16 패치 적용 및 경기 서버 점검 안내',
    summary: '이번 주 경기부터 26.16 패치가 적용되며 경기 서버 점검 시간이 확정되었습니다.',
    body: [
      { text: '2026년 8월 24일 경기부터 26.16 패치를 적용합니다. 로스터 및 장비 확인 절차는 기존과 동일합니다.' },
      { text: '경기 서버는 ', emphasis: '오후 5:30부터 오후 6:00까지', suffix: ' 점검 예정입니다.' },
    ],
    metrics: [
      { label: '적용 패치', value: '26.16' },
      { label: '점검 시작', value: '오후 5:30' },
      { label: '점검 종료', value: '오후 6:00' },
      { label: '응답 필요', value: '없음' },
    ],
    contextTitle: '운영 일정',
    rows: [
      { label: '서버 점검', current: '오후 5:30', recommendation: '확인', note: '30분 예정' },
      { label: '로비 개방', current: '오후 6:20', recommendation: '접속', note: '스태프 우선' },
      { label: '로스터 확인', current: '오후 6:35', recommendation: '제출', note: '변경 불가' },
      { label: '경기 시작', current: '오후 7:00', recommendation: '준비', note: 'BO3' },
    ],
    attachment: { name: '26.16_경기운영_공지', meta: '리그 공문 · 3쪽' },
    actions: ['보고서 보기', '일정 확인', '확인 완료'],
  },
  {
    id: 'opponent-analysis',
    tab: 'team',
    date: '2026년 8월 23일',
    sender: '분석팀',
    initials: 'AN',
    role: '게임 분석관',
    department: 'Northvale 분석팀',
    subject: '다음 상대 분석 완료',
    time: '오전 11:42',
    category: '분석',
    tone: 'teal',
    important: false,
    initiallyUnread: false,
    preview: 'Coastline 최근 10경기 픽·밴 및 오브젝트 패턴',
    summary: 'Coastline의 최근 10경기 픽·밴과 주요 오브젝트 패턴 분석이 완료되었습니다.',
    body: [
      { text: '상대는 블루 진영에서 1픽 원거리 딜러 선호도가 높고, 레드 진영에서는 마지막 픽을 탑에 사용합니다.' },
      { text: '세부 챔피언 우선순위는 첨부 보고서에서 확인할 수 있습니다.' },
    ],
    metrics: [
      { label: '분석 경기', value: '10' },
      { label: '블루 승률', value: '60%' },
      { label: '첫 전령', value: '70%' },
      { label: '평균 밴 중복', value: '2.4' },
    ],
    contextTitle: '상대 경향',
    rows: [
      { label: '1픽', current: '원거리 딜러', recommendation: '대응 밴', note: '선호도 70%' },
      { label: '마지막 픽', current: '탑', recommendation: '미드 압박', note: '레드 진영' },
      { label: '첫 전령', current: '적극적', recommendation: '교환 준비', note: '오전 8:45 집결' },
      { label: '바론 시도', current: '빠름', recommendation: '시야 유지', note: '23분 이후' },
    ],
    attachment: { name: 'Coastline_상대분석', meta: '데이터 보고서 · 최근 10경기' },
    actions: ['보고서 보기', '전술 화면으로 이동', '확인 완료'],
  },
  {
    id: 'roster-deadline',
    tab: 'league',
    date: '2026년 8월 22일',
    sender: '리그 사무국',
    initials: 'LG',
    role: '로스터 담당',
    department: 'Spring Split 사무국',
    subject: '로스터 등록 마감 안내',
    time: '오후 4:00',
    category: '리그',
    tone: 'amber',
    important: true,
    initiallyUnread: true,
    preview: '7주 차 로스터 등록 마감은 2026년 8월 26일 오후 6:00',
    summary: '7주 차 로스터 등록 마감이 2026년 8월 26일 오후 6:00로 확정되었습니다.',
    body: [
      { text: '마감 이후에는 부상 대체를 제외한 로스터 변경이 불가능합니다. 선수 정보와 계약 상태를 미리 확인해 주세요.' },
      { text: '현재 Northvale 선수단은 등록 요건을 충족하고 있습니다.' },
    ],
    metrics: [
      { label: '등록 선수', value: '7명' },
      { label: '최소 인원', value: '6명' },
      { label: '마감', value: '2026년 8월 26일' },
      { label: '상태', value: '충족' },
    ],
    contextTitle: '등록 점검',
    rows: [
      { label: '선발 로스터', current: '5명', recommendation: '확인', note: '요건 충족' },
      { label: '교체 선수', current: '2명', recommendation: '확인', note: '요건 충족' },
      { label: '계약 서류', current: '7건', recommendation: '완료', note: '누락 없음' },
      { label: '마감 시각', current: '오후 6:00', recommendation: '일정 등록', note: '2026년 8월 26일' },
    ],
    attachment: { name: '7주차_로스터_안내', meta: '리그 공문 · 등록 요건' },
    actions: ['보고서 보기', '일정 확인', '확인 완료'],
  },
  {
    id: 'media-request',
    tab: 'social',
    date: '2026년 8월 22일',
    sender: '미디어팀',
    initials: 'PR',
    role: '커뮤니케이션 매니저',
    department: 'Northvale 미디어팀',
    subject: '미디어 인터뷰 요청',
    time: '오전 10:25',
    category: '미디어',
    tone: 'violet',
    important: false,
    initiallyUnread: false,
    preview: 'Coastline전 프리뷰 인터뷰 참석자 지정 요청',
    summary: 'Coastline전 프리뷰 인터뷰에 참석할 선수와 코칭스태프를 지정해 주세요.',
    body: [
      { text: '리그 공식 채널에서 경기 전 프리뷰 인터뷰를 요청했습니다. 촬영은 15분 이내이며 훈련 일정과 겹치지 않습니다.' },
      { text: '후보로 Cipher와 Han 코치를 제안합니다.' },
    ],
    metrics: [
      { label: '촬영 시간', value: '오후 3:40' },
      { label: '소요 시간', value: '15분' },
      { label: '참석 인원', value: '2명' },
      { label: '응답 마감', value: '오후 2:30' },
    ],
    contextTitle: '인터뷰 계획',
    rows: [
      { label: '선수 후보', current: 'Cipher', recommendation: '지정', note: '최근 폼 우수' },
      { label: '스태프 후보', current: 'Han 코치', recommendation: '지정', note: '전술 질문 대응' },
      { label: '촬영 위치', current: '미디어룸', recommendation: '확인', note: '훈련장 인접' },
      { label: '검토 요청', current: '없음', recommendation: '유지', note: '사전 질문 제공' },
    ],
    attachment: { name: 'Coastline전_인터뷰_요청', meta: '미디어 요청서 · 질문 6개' },
    actions: ['보고서 보기', '일정 확인', '확인 완료'],
  },
] as const;
