package com.lolfm.career;

import static com.lolfm.career.CareerRosterStore.*;
import java.time.LocalDate;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.*;
import org.springframework.transaction.support.TransactionTemplate;

@Service
public final class CareerOpponentService {
    private final JdbcTemplate db;private final TransactionTemplate tx;private final CareerApplicationService careers;private final CareerCalendarApplicationService calendar;private final CareerCalendarLeaguePort leagues;
    public CareerOpponentService(JdbcTemplate db,PlatformTransactionManager manager,CareerApplicationService careers,CareerCalendarApplicationService calendar,CareerCalendarLeaguePort leagues){this.db=db;this.careers=careers;this.calendar=calendar;this.leagues=leagues;tx=new TransactionTemplate(manager);tx.setReadOnly(true);tx.setIsolationLevel(TransactionDefinition.ISOLATION_REPEATABLE_READ);}
    public record Target(String fixtureId,int year,String competition,LocalDate date,String first,String second,String opponent,String state,CareerInboxStore.Link link) {}
    public record Sample(String recordId,LocalDate date,String competition,String against,int gameNumber,int seconds,boolean won,CareerDraftEvidence.Evidence draft,List<CareerRecordsStore.PlayerGame> performances) {}
    public record Analysis(String careerId,int activeYear,LocalDate currentDate,int year,String competition,String team,long asOf,Target next,List<String> currentStarters,List<String> registered,List<String> frozen,Map<String,String> names,List<Sample> games,int series,int seriesWins,int sets,int wins,int draftSets,int blueSets,Map<String,Integer> picks,Map<String,Integer> bansBy,Map<String,Integer> bansAgainst,Map<String,Integer> combinations) {}
    Target target(String career){var row=careers.get(career).career();var view=calendar.view(row);int year=view.state().seasonYear();String managed="LCK:"+row.managedTeamCode();var targets=new ArrayList<Target>();
        db.query("SELECT f.fixture_id,f.competition_id,f.scheduled_date,f.first_team_code,f.second_team_code,f.series_id,b.binding_hash FROM career_competition_fixture f LEFT JOIN career_competition_series_binding b ON b.series_id=f.series_id WHERE f.career_id=? AND f.calendar_season_year=? AND f.execution_mode='PLAYER_CONTROLLED' AND f.lifecycle_status<>'COMPLETED'",(org.springframework.jdbc.core.RowCallbackHandler)r->{String a=CareerRecordsStore.team(r.getString(4),r.getString(2)),b=CareerRecordsStore.team(r.getString(5),r.getString(2)),state=r.getString(7)==null?"UNSTARTED":"IN_PROGRESS";targets.add(new Target(r.getString(1),year,r.getString(2),r.getObject(3,LocalDate.class),a,b,Objects.equals(a,managed)||Objects.equals(a,managed+":CL")?b:a,state,new CareerInboxStore.Link("MATCH",null,r.getString(1),r.getString(2),year,r.getString(6),List.of(),state)));},career,year);
        var provenance=view.fixtureOverlay().provenanceV2();var dates=new HashMap<String,LocalDate>();view.fixtureOverlay().fixtures().forEach(f->dates.put(f.fixtureId(),f.date()));
        for(var f:leagues.load(provenance.leagueId(),provenance.seasonId()).fixtures())if(f.executionMode().equals("PLAYER_CONTROLLED")&&!f.fixtureStatus().equals("COMPLETED")&&dates.containsKey(f.fixtureId())){String a=CareerRecordsStore.team(f.firstTeamCode(),"LCK_REGULAR_R1_R2"),b=CareerRecordsStore.team(f.secondTeamCode(),"LCK_REGULAR_R1_R2"),state=f.boundSeriesId()==null?"UNSTARTED":"IN_PROGRESS";targets.add(new Target(f.fixtureId(),year,"LCK_REGULAR_R1_R2",dates.get(f.fixtureId()),a,b,a.equals(managed)?b:a,state,new CareerInboxStore.Link("MATCH",null,f.fixtureId(),"LCK_REGULAR_R1_R2",year,f.boundSeriesId(),List.of(),state)));}
        return targets.stream().sorted(Comparator.comparing(Target::date).thenComparing(Target::fixtureId)).findFirst().orElse(null);
    }
    public Analysis analyze(String career,Integer selectedYear,String selectedTeam,String competition,int limit){return tx.execute(transaction->{
        if(limit!=5&&limit!=10)throw CareerException.invalid("limit","최근 5개 또는 10개 Series를 선택하세요.");var next=target(career);int active=activeYear(db,career),year=selectedYear==null?active:selectedYear;String team=selectedTeam==null||selectedTeam.isBlank()?next==null?null:next.opponent():selectedTeam;String scope=competition==null?next==null?"":next.competition():competition;
        var directory=directory(db,career);var names=new TreeMap<String,String>();directory.players().values().forEach(p->names.put(p.playerId(),p.nickname()));var roster=saved(db,career,active).state();
        var starters=team==null?List.<String>of():team.endsWith(":CL")?(CareerClStore.active(db,career,active)?CareerClStore.load(db,career,active).lineups().getOrDefault(team.replace(":CL",""),List.of()):List.<String>of()):roster.lineups().getOrDefault(team,List.of());
        var registered=new TreeSet<String>();if(team!=null){db.query("SELECT pool_json,pool_hash FROM career_registered_player_pool WHERE career_id=? AND season_year=? AND competition_id=?",(org.springframework.jdbc.core.RowCallbackHandler)r->registered.addAll(pool(r.getString(1),r.getString(2)).getOrDefault(team,List.of())),career,year,scope);
            if(registered.isEmpty())db.query("SELECT state_json,state_hash FROM career_international_state WHERE career_id=? AND calendar_season_year=? AND competition_id=?",(org.springframework.jdbc.core.RowCallbackHandler)r->{if(!hash(r.getString(1)).equals(r.getString(2)))throw new IllegalStateException("INTERNATIONAL_STATE_INTEGRITY");var st=read(r.getString(1),CareerInternationalState.class);st.rosters().teams().values().stream().filter(t->CompetitionRosterSnapshot.token(t.team()).equals(team)).forEach(t->t.players().forEach(p->registered.add(p.playerId())));},career,year,scope);
            db.query("SELECT player_id FROM career_registration_supplement WHERE career_id=? AND season_year=? AND competition_id=? AND team=?",(org.springframework.jdbc.core.RowCallbackHandler)r->registered.add(r.getString(1)),career,year,scope,team);}
        if(team!=null&&team.endsWith(":CL")&&CareerClStore.active(db,career,year))registered.addAll(CareerClStore.load(db,career,year).registered().getOrDefault(team.replace(":CL",""),List.of()));
        var frozen=new ArrayList<String>();if(next!=null&&next.state().equals("IN_PROGRESS")&&Objects.equals(team,next.opponent())){
            db.query("SELECT binding_canonical FROM career_competition_series_binding WHERE career_id=? AND series_id=?",(org.springframework.jdbc.core.RowCallbackHandler)r->{var snapshot=CareerCompetitionSeriesBindingV1.restoreCanonical(r.getString(1)).frozenRosters();if(snapshot!=null)snapshot.teams().values().stream().filter(t->CompetitionRosterSnapshot.token(t.team()).equals(team.replace(":CL",""))).forEach(t->t.players().forEach(p->frozen.add(p.playerId())));},career,next.link().seriesId());
            db.query("SELECT r.roster_json FROM career_league_fixture_roster r JOIN career_season s ON s.season_id=r.season_id WHERE s.career_id=? AND r.fixture_id=?",(org.springframework.jdbc.core.RowCallbackHandler)r->CompetitionRosterSnapshot.decode(r.getString(1)).teams().values().stream().filter(t->CompetitionRosterSnapshot.token(t.team()).equals(team)).forEach(t->t.players().forEach(p->frozen.add(p.playerId()))),career,next.fixtureId());
        }
        var args=new ArrayList<Object>();args.add(career);args.add(year);args.add(team);args.add(team);String filter="career_id=? AND season_year=? AND (first_team=? OR second_team=?)";if(!scope.isBlank()){filter+=" AND competition_id=?";args.add(scope);}
        var series=db.query("SELECT record_json,record_hash FROM career_record_series WHERE "+filter+" ORDER BY played_date DESC,record_revision DESC LIMIT "+limit,(r,n)->CareerRecordsStore.readSeries(r.getString(1),r.getString(2)),args.toArray());
        var samples=new ArrayList<Sample>();for(var s:series){var evidence=new TreeMap<Integer,CareerDraftEvidence.Evidence>();db.query("SELECT evidence_json,evidence_hash FROM career_record_draft WHERE record_id=?",(org.springframework.jdbc.core.RowCallbackHandler)r->{var e=CareerDraftEvidence.readEvidence(r.getString(1),r.getString(2));evidence.put(e.gameNumber(),e);},s.recordId());for(var g:s.games())samples.add(new Sample(s.recordId(),s.date(),s.competition(),s.firstTeam().equals(team)?s.secondTeam():s.firstTeam(),g.gameNumber(),g.seconds(),g.winner().equals(team),evidence.get(g.gameNumber()),g.players().stream().filter(p->p.team().equals(team)).toList()));}
        return summarize(career,active,CareerMarketStore.date(db,career),year,scope,team,CareerRecordsStore.revision(db,career),next,starters,List.copyOf(registered),List.copyOf(frozen),names,samples,series.size(),(int)series.stream().filter(s->s.winner().equals(team)).count());
    });}
    static Analysis summarize(String career,int active,LocalDate date,int year,String scope,String team,long asOf,Target next,List<String> starters,List<String> registered,List<String> frozen,Map<String,String> names,List<Sample> games,int series,int seriesWins){
        var picks=new TreeMap<String,Integer>();var by=new TreeMap<String,Integer>();var against=new TreeMap<String,Integer>();var combinations=new TreeMap<String,Integer>();int observed=0,blue=0;
        for(var g:games){var d=g.draft();if(d==null)continue;observed++;boolean isBlue=d.blue().equals(team);if(isBlue)blue++;(isBlue?d.blueBans():d.redBans()).forEach(c->by.merge(c,1,Integer::sum));(isBlue?d.redBans():d.blueBans()).forEach(c->against.merge(c,1,Integer::sum));var own=d.picks().stream().filter(p->p.team().equals(team)).toList();own.forEach(p->picks.merge(p.position()+" · "+p.championId(),1,Integer::sum));combinations.merge(String.join(" / ",own.stream().sorted(Comparator.comparing(CareerDraftEvidence.Pick::position)).map(p->p.position()+":"+p.championId()).toList()),1,Integer::sum);}
        return new Analysis(career,active,date,year,scope,team,asOf,next,starters,registered,frozen,names,games,series,seriesWins,games.size(),(int)games.stream().filter(Sample::won).count(),observed,blue,picks,by,against,combinations);
    }
}
